import type { WorldBlueprint } from '../types/index.js';

export const ALL_BLUEPRINTS: WorldBlueprint[] = [
  // --- Fantasy ---
  {
    id: 'high_fantasy',
    name: 'High Fantasy Realm',
    description: 'A classic high-magic world of diverse peoples, ancient forests, feudal kingdoms, and dragons. Elves and dwarves rub shoulders with human empires, and magic permeates every layer of society.',
    icon: 'crown',
    color: '#e8c547',
    tags: ['fantasy', 'classic', 'magic'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'habitable_planet', priority: 'essential', note: 'The material world where the story takes place' },
      { domain: 'geology', archetypeId: 'continental_mountain_range', priority: 'recommended', note: 'Mountain ranges divide kingdoms and hide ancient secrets' },
      { domain: 'biomes', archetypeId: 'temperate_forest', priority: 'recommended', note: 'Ancient forests are the heartland of elven civilizations' },
      { domain: 'flora', archetypeId: 'ancient_hardwood', priority: 'optional', note: 'Millennial trees form the backbone of old-growth forests' },
      { domain: 'fauna', archetypeId: 'apex_predator', priority: 'optional', note: 'Great beasts roam the wild places between kingdoms' },
      { domain: 'fauna', archetypeId: 'beast_of_burden', priority: 'optional', note: 'Horses, oxen, or their equivalents power civilization' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Humans form the most numerous and adaptable species' },
      { domain: 'sentient_species', archetypeId: 'long_lived_elven', priority: 'recommended', note: 'Long-lived elves bring ancient perspective' },
      { domain: 'sentient_species', archetypeId: 'hardy_mountain_folk', priority: 'recommended', note: 'Dwarves anchor the mountains and underground' },
      { domain: 'civilizations', archetypeId: 'feudal_kingdom', priority: 'essential', note: 'The dominant political structure of the realm' },
      { domain: 'cultures', archetypeId: 'warrior_honor', priority: 'recommended', note: 'Knightly honor codes shape the ruling class' },
      { domain: 'magic_systems', archetypeId: 'elemental_taxonomy', priority: 'essential', note: 'Magic organized into classical elemental schools' },
      { domain: 'magic_systems', archetypeId: 'apprentice_to_archmage', priority: 'recommended', note: 'Structured magical education and progression' },
      { domain: 'history', archetypeId: 'great_war', priority: 'optional', note: 'A defining conflict that shaped the current political map' },
    ],
  },
  {
    id: 'dark_fantasy',
    name: 'Dark Fantasy',
    description: 'A grim world where magic comes at terrible cost, the dead don\'t rest easy, and corruption seeps from the planes. Hope is precious because it\'s so rare.',
    icon: 'skull',
    color: '#6b21a8',
    tags: ['fantasy', 'horror', 'grim'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'dying_god_star', priority: 'recommended', note: 'Even the stars are dying — sets the tone' },
      { domain: 'climate', archetypeId: 'polar_tundra', priority: 'optional', note: 'Harsh, unforgiving climate matches the mood' },
      { domain: 'biomes', archetypeId: 'deep_cavern', priority: 'optional', note: 'Darkness below mirrors darkness above' },
      { domain: 'flora', archetypeId: 'corpse_bloom', priority: 'optional', note: 'Beauty growing from death' },
      { domain: 'fauna', archetypeId: 'deep_sea_leviathan', priority: 'optional', note: 'Ancient terrors lurking in the deep' },
      { domain: 'ecosystems', archetypeId: 'war_scarred', priority: 'recommended', note: 'Landscapes still recovering from past horrors' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Fragile humans struggling to survive' },
      { domain: 'civilizations', archetypeId: 'necrocracy', priority: 'recommended', note: 'The dead rule — the ultimate dark authority' },
      { domain: 'cultures', archetypeId: 'death_celebrants', priority: 'optional', note: 'A culture shaped by the omnipresence of death' },
      { domain: 'magic_systems', archetypeId: 'soul_cost', priority: 'essential', note: 'Magic eats the caster alive' },
      { domain: 'magic_systems', archetypeId: 'forbidden_spell', priority: 'recommended', note: 'Forbidden workings tempt the desperate' },
      { domain: 'planar_systems', archetypeId: 'shadow_realm', priority: 'recommended', note: 'A shadow plane bleeds into reality' },
      { domain: 'history', archetypeId: 'the_sundering', priority: 'optional', note: 'A cataclysm that broke the world' },
    ],
  },
  {
    id: 'oceanic_world',
    name: 'Oceanic World',
    description: 'A world dominated by vast oceans with scattered island chains, reef civilizations, and mysteries in the deep. Land is precious, and the sea is everything.',
    icon: 'waves',
    color: '#0891b2',
    tags: ['fantasy', 'exploration', 'maritime'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'habitable_planet', priority: 'essential', note: 'A water-heavy world with minimal landmass' },
      { domain: 'geology', archetypeId: 'shield_volcano', priority: 'recommended', note: 'Volcanic islands are the primary land' },
      { domain: 'hydrology', archetypeId: 'major_ocean', priority: 'essential', note: 'The defining feature of this world' },
      { domain: 'hydrology', archetypeId: 'coastal_wetlands', priority: 'optional', note: 'Precious coastal ecosystems where land meets sea' },
      { domain: 'climate', archetypeId: 'tropical_monsoon', priority: 'recommended', note: 'Tropical maritime climate shapes life' },
      { domain: 'biomes', archetypeId: 'coral_reef_biome', priority: 'essential', note: 'Coral reefs are the forests of this world' },
      { domain: 'flora', archetypeId: 'dreaming_lotus', priority: 'optional', note: 'Mystical aquatic plants' },
      { domain: 'fauna', archetypeId: 'deep_sea_leviathan', priority: 'recommended', note: 'Leviathans rule the deep ocean' },
      { domain: 'ecosystems', archetypeId: 'coral_reef_ecosystem', priority: 'essential', note: 'Reef ecosystems drive biodiversity' },
      { domain: 'sentient_species', archetypeId: 'aquatic_people', priority: 'essential', note: 'Aquatic species dominate this world' },
      { domain: 'civilizations', archetypeId: 'trading_republic', priority: 'recommended', note: 'Maritime trade republics thrive' },
      { domain: 'cultures', archetypeId: 'maritime_voyagers', priority: 'essential', note: 'Seafaring culture is the default' },
      { domain: 'geography', archetypeId: 'harbor_city', priority: 'recommended', note: 'Port cities are the hubs of civilization' },
    ],
  },
  {
    id: 'desert_realm',
    name: 'Desert Realm',
    description: 'A harsh, arid world where water is currency, shade is shelter, and ancient ruins hide beneath the sands. Civilizations cluster around oases and underground rivers.',
    icon: 'sun',
    color: '#d97706',
    tags: ['fantasy', 'survival', 'ancient'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'rift_valley', priority: 'optional', note: 'Rift valleys provide water and shelter in the wastes' },
      { domain: 'geology', archetypeId: 'glass_desert', priority: 'recommended', note: 'A glassed wasteland hints at ancient catastrophe' },
      { domain: 'hydrology', archetypeId: 'alpine_lake', priority: 'optional', note: 'Rare oasis lakes are the basis of civilization' },
      { domain: 'atmosphere', archetypeId: 'earth_like', priority: 'essential', note: 'Breathable but brutally hot and dry' },
      { domain: 'climate', archetypeId: 'arid_desert', priority: 'essential', note: 'The defining climate of the realm' },
      { domain: 'biomes', archetypeId: 'arid_desert_biome', priority: 'essential', note: 'Desert biomes cover most of the world' },
      { domain: 'flora', archetypeId: 'medicinal_herb', priority: 'optional', note: 'Desert herbs are rare and valuable' },
      { domain: 'fauna', archetypeId: 'migratory_herder', priority: 'optional', note: 'Herds follow seasonal water sources' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Hardy desert peoples' },
      { domain: 'civilizations', archetypeId: 'nomadic_confederation', priority: 'essential', note: 'Nomadic peoples follow water and trade' },
      { domain: 'civilizations', archetypeId: 'theocratic_empire', priority: 'recommended', note: 'Oasis cities grow into theocratic powers' },
      { domain: 'geography', archetypeId: 'crossroads_town', priority: 'recommended', note: 'Trade crossroads between oases' },
      { domain: 'history', archetypeId: 'great_war', priority: 'optional', note: 'Water wars shaped the current order' },
    ],
  },
  {
    id: 'underground_world',
    name: 'Underground World',
    description: 'Life beneath the surface — vast cavern cities, fungal forests, underground seas, and civilizations that have never seen the sky. Darkness is home.',
    icon: 'mountain',
    color: '#78716c',
    tags: ['fantasy', 'subterranean', 'alien'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'limestone_cave_network', priority: 'essential', note: 'Vast cave systems form the living space' },
      { domain: 'hydrology', archetypeId: 'underground_ocean', priority: 'essential', note: 'Underground oceans provide water and transport' },
      { domain: 'biomes', archetypeId: 'deep_cavern', priority: 'essential', note: 'Cavern biomes sustained by chemosynthesis' },
      { domain: 'biomes', archetypeId: 'inverted_canopy', priority: 'recommended', note: 'Forests growing from cavern ceilings' },
      { domain: 'flora', archetypeId: 'cave_fungus', priority: 'essential', note: 'Bioluminescent fungi provide light and food' },
      { domain: 'fauna', archetypeId: 'colonial_insect', priority: 'recommended', note: 'Eusocial insects thrive in the dark' },
      { domain: 'ecosystems', archetypeId: 'hydrothermal_vent', priority: 'recommended', note: 'Geothermal vents power deep ecosystems' },
      { domain: 'sentient_species', archetypeId: 'hardy_mountain_folk', priority: 'essential', note: 'Species adapted to darkness and stone' },
      { domain: 'sentient_species', archetypeId: 'fungal_collective', priority: 'optional', note: 'Fungal intelligence thrives underground' },
      { domain: 'civilizations', archetypeId: 'underground_empire', priority: 'essential', note: 'Great cities carved from living rock' },
      { domain: 'geography', archetypeId: 'ancient_ruin', priority: 'optional', note: 'Ruins of deeper, older civilizations below' },
      { domain: 'magic_systems', archetypeId: 'mana_crystal', priority: 'recommended', note: 'Crystal deposits fuel underground magic' },
    ],
  },
  // --- Environmental Extremes ---
  {
    id: 'frozen_wastes',
    name: 'Frozen Wastes',
    description: 'An ice-bound world where glaciers grind, blizzards howl, and warmth is the most precious resource. Civilizations huddle around geothermal vents and hot springs.',
    icon: 'snowflake',
    color: '#7dd3fc',
    tags: ['survival', 'harsh', 'arctic'],
    magic: true,
    suggestions: [
      { domain: 'hydrology', archetypeId: 'frozen_highway', priority: 'recommended', note: 'Frozen rivers serve as highways' },
      { domain: 'climate', archetypeId: 'polar_tundra', priority: 'essential', note: 'Polar climate dominates' },
      { domain: 'biomes', archetypeId: 'arid_desert_biome', priority: 'optional', note: 'Cold deserts of ice and rock' },
      { domain: 'flora', archetypeId: 'medicinal_herb', priority: 'optional', note: 'Hardy arctic plants with potent properties' },
      { domain: 'fauna', archetypeId: 'apex_predator', priority: 'recommended', note: 'Ice predators are apex survivors' },
      { domain: 'fauna', archetypeId: 'migratory_herder', priority: 'recommended', note: 'Herds migrate with the brief summer' },
      { domain: 'sentient_species', archetypeId: 'hardy_mountain_folk', priority: 'essential', note: 'Stocky, cold-adapted peoples' },
      { domain: 'civilizations', archetypeId: 'nomadic_confederation', priority: 'recommended', note: 'Nomadic peoples follow game and warmth' },
      { domain: 'cultures', archetypeId: 'nomadic_storytellers', priority: 'optional', note: 'Oral traditions survive the long dark' },
      { domain: 'geography', archetypeId: 'forbidden_zone', priority: 'optional', note: 'The deep ice is too deadly to enter' },
    ],
  },
  {
    id: 'sky_realm',
    name: 'Sky Realm',
    description: 'A world of floating islands, cloud forests, and bottomless sky. Civilizations build on drifting rock, and falling is the ultimate fear.',
    icon: 'cloud',
    color: '#38bdf8',
    tags: ['fantasy', 'aerial', 'vertical'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'floating_islands', priority: 'essential', note: 'Floating rock masses are the only land' },
      { domain: 'atmosphere', archetypeId: 'layered_breathability', priority: 'recommended', note: 'Breathable only at certain altitudes' },
      { domain: 'atmosphere', archetypeId: 'singing_winds', priority: 'optional', note: 'Winds sing through crystal formations' },
      { domain: 'biomes', archetypeId: 'floating_reef', priority: 'essential', note: 'Sky reef ecosystems on floating debris' },
      { domain: 'fauna', archetypeId: 'sky_whale', priority: 'essential', note: 'Sky whales drift between islands' },
      { domain: 'ecosystems', archetypeId: 'parasitic_network', priority: 'optional', note: 'Aerial parasitic networks connect drifting life' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Sky-adapted peoples' },
      { domain: 'civilizations', archetypeId: 'isolated_city_state', priority: 'recommended', note: 'Each island is its own city-state' },
      { domain: 'geography', archetypeId: 'sky_port', priority: 'essential', note: 'Sky ports connect the floating world' },
      { domain: 'magic_systems', archetypeId: 'ambient_field', priority: 'recommended', note: 'Ambient mana keeps the islands aloft' },
    ],
  },
  {
    id: 'volcanic_world',
    name: 'Primordial World',
    description: 'A young, raw world of active volcanoes, lava rivers, and violent geology. Life is tough, new, and evolving fast. The ground itself is still being born.',
    icon: 'flame',
    color: '#ef4444',
    tags: ['primal', 'dangerous', 'young'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'shield_volcano', priority: 'essential', note: 'Active volcanoes shape the landscape' },
      { domain: 'geology', archetypeId: 'rift_valley', priority: 'recommended', note: 'Rifts tear the young crust apart' },
      { domain: 'hydrology', archetypeId: 'major_ocean', priority: 'recommended', note: 'Steaming primordial oceans' },
      { domain: 'atmosphere', archetypeId: 'thick_greenhouse', priority: 'optional', note: 'Dense, volcanic atmosphere' },
      { domain: 'biomes', archetypeId: 'crystalline_waste', priority: 'optional', note: 'Mineral biomes in extreme heat' },
      { domain: 'flora', archetypeId: 'iron_root', priority: 'optional', note: 'Metal-extracting plants thrive on mineral-rich soil' },
      { domain: 'ecosystems', archetypeId: 'hydrothermal_vent', priority: 'essential', note: 'Vent ecosystems are the cradle of life' },
      { domain: 'sentient_species', archetypeId: 'living_statues', priority: 'optional', note: 'Silicon-based life in extreme heat' },
      { domain: 'civilizations', archetypeId: 'nomadic_confederation', priority: 'recommended', note: 'Nomadic peoples avoid eruption zones' },
      { domain: 'magic_ecology', archetypeId: 'geological_mana', priority: 'optional', note: 'Mana wells up through volcanic processes' },
    ],
  },
  // --- Conceptual/Strange ---
  {
    id: 'dying_world',
    name: 'Dying World',
    description: 'A world in ecological and magical collapse. Resources are dwindling, magic is fading, and every civilization is desperate. The end is coming — but when?',
    icon: 'hourglass',
    color: '#a3a3a3',
    tags: ['grim', 'decline', 'survival'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'dying_god_star', priority: 'recommended', note: 'Even the star is failing' },
      { domain: 'climate', archetypeId: 'arid_desert', priority: 'recommended', note: 'Climate shifting toward arid death' },
      { domain: 'ecosystems', archetypeId: 'war_scarred', priority: 'essential', note: 'Ecosystems collapsing everywhere' },
      { domain: 'fauna', archetypeId: 'living_fossil', priority: 'optional', note: 'Ancient survivors from better times' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Desperate peoples clinging to survival' },
      { domain: 'civilizations', archetypeId: 'isolated_city_state', priority: 'recommended', note: 'Isolated cities hoarding last resources' },
      { domain: 'magic_systems', archetypeId: 'soul_cost', priority: 'recommended', note: 'Magic exacts ever-steeper costs' },
      { domain: 'magic_ecology', archetypeId: 'mana_desert', priority: 'essential', note: 'Mana dead zones spreading across the world' },
      { domain: 'magic_economy', archetypeId: 'mana_debt', priority: 'optional', note: 'Magical debts coming due all at once' },
      { domain: 'history', archetypeId: 'the_sundering', priority: 'recommended', note: 'The cataclysm that started the decline' },
      { domain: 'geography', archetypeId: 'forbidden_zone', priority: 'optional', note: 'Dead zones where nothing survives' },
    ],
  },
  {
    id: 'planar_crossroads',
    name: 'Planar Crossroads',
    description: 'A world where the barriers between planes are thin. Extraplanar creatures walk the streets, portals open without warning, and reality is negotiable.',
    icon: 'git-branch',
    color: '#a855f7',
    tags: ['fantasy', 'planar', 'chaotic'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'habitable_planet', priority: 'essential', note: 'The material plane — thin-skinned and leaking' },
      { domain: 'planar_systems', archetypeId: 'material_plane', priority: 'essential', note: 'The anchor plane, but weakened' },
      { domain: 'planar_systems', archetypeId: 'elemental_bastion', priority: 'recommended', note: 'Elemental planes bleeding through' },
      { domain: 'planar_systems', archetypeId: 'fey_wild', priority: 'recommended', note: 'The Fey realm overlaps with forests' },
      { domain: 'planar_systems', archetypeId: 'shadow_realm', priority: 'recommended', note: 'Shadow plane visible at night' },
      { domain: 'planar_systems', archetypeId: 'bleeding_wound', priority: 'essential', note: 'Planar wounds where realities merge' },
      { domain: 'magic_systems', archetypeId: 'wild_surge', priority: 'essential', note: 'Wild magic surges from planar interference' },
      { domain: 'magic_ecology', archetypeId: 'ley_line_nexus', priority: 'recommended', note: 'Ley line nexuses mark thin spots' },
      { domain: 'sentient_species', archetypeId: 'phase_beings', priority: 'optional', note: 'Phase beings slip between planes' },
      { domain: 'fauna', archetypeId: 'mimic_predator', priority: 'optional', note: 'Extraplanar predators disguise as terrain' },
      { domain: 'geography', archetypeId: 'crossroads_town', priority: 'recommended', note: 'Trade towns at stable portal sites' },
    ],
  },
  {
    id: 'archipelago',
    name: 'Archipelago',
    description: 'A world of island chains — each island its own culture, ecosystem, and mystery. Navigation is survival, and the spaces between islands are as important as the land.',
    icon: 'compass',
    color: '#14b8a6',
    tags: ['exploration', 'maritime', 'diverse'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'shield_volcano', priority: 'recommended', note: 'Volcanic islands form the archipelago' },
      { domain: 'hydrology', archetypeId: 'major_ocean', priority: 'essential', note: 'Ocean dominates between islands' },
      { domain: 'hydrology', archetypeId: 'coastal_wetlands', priority: 'optional', note: 'Mangroves and tidal flats ring the islands' },
      { domain: 'climate', archetypeId: 'tropical_monsoon', priority: 'recommended', note: 'Tropical climate across the chain' },
      { domain: 'biomes', archetypeId: 'tropical_rainforest', priority: 'recommended', note: 'Dense tropical forests on larger islands' },
      { domain: 'biomes', archetypeId: 'coral_reef_biome', priority: 'essential', note: 'Reefs connect the islands underwater' },
      { domain: 'ecosystems', archetypeId: 'coral_reef_ecosystem', priority: 'recommended', note: 'Rich reef ecosystems' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Island peoples' },
      { domain: 'civilizations', archetypeId: 'isolated_city_state', priority: 'essential', note: 'Each island is self-governing' },
      { domain: 'civilizations', archetypeId: 'pirate_republic', priority: 'optional', note: 'Pirate havens among the outer islands' },
      { domain: 'cultures', archetypeId: 'maritime_voyagers', priority: 'essential', note: 'Seafaring is the core cultural skill' },
      { domain: 'geography', archetypeId: 'harbor_city', priority: 'recommended', note: 'Every major settlement is a port' },
    ],
  },
  {
    id: 'magical_industrial',
    name: 'Magical Industrial',
    description: 'A world where magic and technology have merged into magitech industry. Enchanted factories, spell-powered transit, and the social upheaval of a magical industrial revolution.',
    icon: 'cog',
    color: '#f59e0b',
    tags: ['magitech', 'urban', 'progress'],
    magic: true,
    suggestions: [
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'The innovating species' },
      { domain: 'civilizations', archetypeId: 'trading_republic', priority: 'essential', note: 'Merchant power drives innovation' },
      { domain: 'cultures', archetypeId: 'scholarly_tradition', priority: 'recommended', note: 'Academic traditions fuel research' },
      { domain: 'geography', archetypeId: 'capital_city', priority: 'essential', note: 'Great cities are the engines of progress' },
      { domain: 'magic_systems', archetypeId: 'mana_crystal', priority: 'essential', note: 'Mana crystals fuel the industrial machine' },
      { domain: 'magic_systems', archetypeId: 'runic_system', priority: 'recommended', note: 'Runic inscriptions power enchanted devices' },
      { domain: 'arcane_sciences', archetypeId: 'communication_crystal', priority: 'recommended', note: 'Magical communication networks' },
      { domain: 'arcane_sciences', archetypeId: 'golem_workforce', priority: 'essential', note: 'Golem labor replaces human workers' },
      { domain: 'arcane_sciences', archetypeId: 'spell_telegraph', priority: 'recommended', note: 'Instant communication across distances' },
      { domain: 'magic_economy', archetypeId: 'enchanter_guild', priority: 'essential', note: 'Guilds control the magical economy' },
      { domain: 'magic_economy', archetypeId: 'mana_currency', priority: 'optional', note: 'Mana becomes the medium of exchange' },
      { domain: 'magic_ecology', archetypeId: 'ley_line_nexus', priority: 'optional', note: 'Cities built on ley line nexuses for power' },
    ],
  },
  {
    id: 'mythic_world',
    name: 'Mythic World',
    description: 'Gods walk the earth, mythical beasts are real, and mortal deeds echo in the divine realm. This is a world of legends being written in real time.',
    icon: 'zap',
    color: '#eab308',
    tags: ['mythic', 'divine', 'epic'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'dying_god_star', priority: 'optional', note: 'Stars as divine corpses or eyes' },
      { domain: 'fauna', archetypeId: 'deep_sea_leviathan', priority: 'recommended', note: 'Titanic beasts of legend' },
      { domain: 'fauna', archetypeId: 'sky_whale', priority: 'optional', note: 'Sky whales as divine messengers' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Mortals caught between gods' },
      { domain: 'civilizations', archetypeId: 'theocratic_empire', priority: 'essential', note: 'Theocracies serve the gods directly' },
      { domain: 'cultures', archetypeId: 'death_celebrants', priority: 'optional', note: 'Death rites connect to the divine' },
      { domain: 'magic_systems', archetypeId: 'divine_gift', priority: 'essential', note: 'All magic comes from the gods' },
      { domain: 'planar_systems', archetypeId: 'divine_domain', priority: 'essential', note: 'Gods reside in their own planes' },
      { domain: 'history', archetypeId: 'great_war', priority: 'recommended', note: 'Divine wars shaped the world' },
      { domain: 'history', archetypeId: 'founding_nation', priority: 'recommended', note: 'Nations founded by divine mandate' },
      { domain: 'geography', archetypeId: 'sacred_site', priority: 'essential', note: 'Temples and holy sites dot the land' },
    ],
  },
  {
    id: 'pastoral',
    name: 'Pastoral',
    description: 'A peaceful, gentle world of rolling farmland, cozy villages, and kind folk. Conflict is personal, not apocalyptic. The beauty is in the everyday.',
    icon: 'flower-2',
    color: '#22c55e',
    tags: ['peaceful', 'rural', 'cozy'],
    magic: false,
    suggestions: [
      { domain: 'climate', archetypeId: 'temperate_maritime', priority: 'essential', note: 'Mild, pleasant climate' },
      { domain: 'biomes', archetypeId: 'temperate_forest', priority: 'recommended', note: 'Gentle forests and meadows' },
      { domain: 'flora', archetypeId: 'staple_grain', priority: 'essential', note: 'Agriculture is the foundation of life' },
      { domain: 'flora', archetypeId: 'ancient_hardwood', priority: 'optional', note: 'Ancient trees shade village greens' },
      { domain: 'fauna', archetypeId: 'beast_of_burden', priority: 'essential', note: 'Farm animals and companions' },
      { domain: 'ecosystems', archetypeId: 'old_growth_forest', priority: 'optional', note: 'Undisturbed old-growth woodlands' },
      { domain: 'ecosystems', archetypeId: 'freshwater_wetland', priority: 'optional', note: 'Ponds and marshes teeming with life' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Simple, good folk' },
      { domain: 'civilizations', archetypeId: 'feudal_kingdom', priority: 'recommended', note: 'A benevolent monarchy' },
      { domain: 'cultures', archetypeId: 'agrarian_folk', priority: 'essential', note: 'Farming communities with harvest festivals' },
      { domain: 'geography', archetypeId: 'crossroads_town', priority: 'recommended', note: 'Bustling market towns' },
    ],
  },
  // --- Weird/Unique ---
  {
    id: 'hollow_interior',
    name: 'Hollow World',
    description: 'Life on the inside of a hollow sphere — the horizon curves up, not down. The inner sun never sets, and distant lands hang overhead like painted ceiling.',
    icon: 'circle',
    color: '#8b5cf6',
    tags: ['alien', 'unique', 'exploration'],
    magic: true,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'hollow_world', priority: 'essential', note: 'The hollow planet itself' },
      { domain: 'geology', archetypeId: 'continental_mountain_range', priority: 'recommended', note: 'Mountains on the inner surface reach toward the core' },
      { domain: 'atmosphere', archetypeId: 'layered_breathability', priority: 'optional', note: 'Atmosphere thickens toward the core' },
      { domain: 'climate', archetypeId: 'eternal_twilight', priority: 'optional', note: 'The inner sun never sets — eternal day' },
      { domain: 'biomes', archetypeId: 'tropical_rainforest', priority: 'recommended', note: 'Lush growth under constant warm light' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Interior peoples unaware of the outside' },
      { domain: 'civilizations', archetypeId: 'isolated_city_state', priority: 'recommended', note: 'Isolated communities on the inner surface' },
      { domain: 'cultures', archetypeId: 'silence_keepers', priority: 'optional', note: 'A culture of mystery in the hollow' },
      { domain: 'magic_systems', archetypeId: 'ambient_field', priority: 'optional', note: 'Mana concentrated inside the shell' },
    ],
  },
  {
    id: 'dual_world',
    name: 'Dual World',
    description: 'A tidally locked planet — one side faces the star in eternal day, the other in eternal night. The habitable twilight band between them is everything.',
    icon: 'contrast',
    color: '#6366f1',
    tags: ['sci-fi', 'unique', 'divided'],
    magic: false,
    suggestions: [
      { domain: 'cosmology', archetypeId: 'red_dwarf_star', priority: 'essential', note: 'Red dwarfs commonly tidally lock their planets' },
      { domain: 'cosmology', archetypeId: 'habitable_planet', priority: 'essential', note: 'A tidally locked world' },
      { domain: 'climate', archetypeId: 'eternal_twilight', priority: 'essential', note: 'The habitable twilight zone' },
      { domain: 'climate', archetypeId: 'storm_belt', priority: 'recommended', note: 'Permanent storm systems at the terminator' },
      { domain: 'biomes', archetypeId: 'arid_desert_biome', priority: 'recommended', note: 'The day side is a scorching desert' },
      { domain: 'flora', archetypeId: 'singing_tree', priority: 'optional', note: 'Wind-adapted flora in the storm belt' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Peoples adapted to twilight living' },
      { domain: 'civilizations', archetypeId: 'isolated_city_state', priority: 'recommended', note: 'Cities along the narrow habitable band' },
      { domain: 'geography', archetypeId: 'crossroads_town', priority: 'recommended', note: 'Towns where day-side and night-side trade' },
    ],
  },
  {
    id: 'living_world',
    name: 'Living World',
    description: 'The planet itself is a living organism. Mountains breathe, rivers are veins, earthquakes are heartbeats. Civilizations are parasites, symbionts, or children of the world-body.',
    icon: 'heart',
    color: '#10b981',
    tags: ['alien', 'organic', 'mythic'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'living_mountain', priority: 'essential', note: 'Mountains that breathe and shift' },
      { domain: 'hydrology', archetypeId: 'great_river', priority: 'recommended', note: 'Rivers as the world\'s circulatory system' },
      { domain: 'biomes', archetypeId: 'fungal_jungle', priority: 'recommended', note: 'Fungal networks as the world\'s neural tissue' },
      { domain: 'flora', archetypeId: 'iron_root', priority: 'optional', note: 'Plants interfacing with the living geology' },
      { domain: 'fauna', archetypeId: 'symbiotic_pair', priority: 'recommended', note: 'All life is symbiotic with the world-organism' },
      { domain: 'ecosystems', archetypeId: 'symbiotic_megaorganism', priority: 'essential', note: 'The entire world is one superorganism' },
      { domain: 'sentient_species', archetypeId: 'fungal_collective', priority: 'recommended', note: 'Fungal minds connected to the world\'s consciousness' },
      { domain: 'magic_systems', archetypeId: 'innate_biological', priority: 'essential', note: 'Magic is the world\'s life force' },
      { domain: 'magic_ecology', archetypeId: 'biological_mana', priority: 'recommended', note: 'Living mana cycles through organisms' },
      { domain: 'planar_systems', archetypeId: 'living_realm', priority: 'optional', note: 'The plane IS a living being' },
    ],
  },
  {
    id: 'ancient_ruins',
    name: 'Ancient Ruins',
    description: 'A world built on the bones of a prior civilization. Ruins everywhere, lost technology underground, and modern peoples living among monuments they don\'t understand.',
    icon: 'landmark',
    color: '#b45309',
    tags: ['mystery', 'archaeological', 'ancient'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'glass_desert', priority: 'optional', note: 'Glassed wastelands from ancient weapons' },
      { domain: 'ecosystems', archetypeId: 'war_scarred', priority: 'recommended', note: 'Ecosystems recovering from ancient devastation' },
      { domain: 'sentient_species', archetypeId: 'baseline_humanoid', priority: 'essential', note: 'Modern peoples in the ruins' },
      { domain: 'sentient_species', archetypeId: 'constructed_people', priority: 'optional', note: 'Ancient constructs still wandering' },
      { domain: 'civilizations', archetypeId: 'feudal_kingdom', priority: 'recommended', note: 'Medieval civilizations in ancient shells' },
      { domain: 'cultures', archetypeId: 'scholarly_tradition', priority: 'recommended', note: 'Scholars trying to decode the ancients' },
      { domain: 'geography', archetypeId: 'ancient_ruin', priority: 'essential', note: 'Ruins are the defining feature of the landscape' },
      { domain: 'geography', archetypeId: 'forbidden_zone', priority: 'recommended', note: 'Some ruins are too dangerous to enter' },
      { domain: 'arcane_sciences', archetypeId: 'golem_workforce', priority: 'optional', note: 'Ancient golems still performing obsolete tasks' },
      { domain: 'history', archetypeId: 'the_sundering', priority: 'essential', note: 'The fall of the ancients' },
      { domain: 'history', archetypeId: 'forbidden_knowledge_event', priority: 'recommended', note: 'Knowledge of what destroyed them — suppressed' },
    ],
  },
  {
    id: 'elemental_chaos',
    name: 'Elemental Chaos',
    description: 'Raw elemental forces run rampant. Fire storms, stone waves, water that flows upward. The world is beautiful, deadly, and never still.',
    icon: 'zap',
    color: '#f43f5e',
    tags: ['chaotic', 'elemental', 'dangerous'],
    magic: true,
    suggestions: [
      { domain: 'geology', archetypeId: 'living_mountain', priority: 'recommended', note: 'Earth elementals shape the land in real time' },
      { domain: 'hydrology', archetypeId: 'blood_sea', priority: 'optional', note: 'Seas infused with elemental fire minerals' },
      { domain: 'atmosphere', archetypeId: 'singing_winds', priority: 'recommended', note: 'Air elementals manifest as singing winds' },
      { domain: 'climate', archetypeId: 'mana_seasons', priority: 'essential', note: 'Seasons driven by elemental tides' },
      { domain: 'biomes', archetypeId: 'crystalline_waste', priority: 'recommended', note: 'Crystal formations of solidified mana' },
      { domain: 'ecosystems', archetypeId: 'parasitic_network', priority: 'optional', note: 'Elemental parasites drain energy' },
      { domain: 'magic_systems', archetypeId: 'elemental_taxonomy', priority: 'essential', note: 'Magic organized by element — the only framework that works' },
      { domain: 'magic_systems', archetypeId: 'wild_surge', priority: 'essential', note: 'Wild surges are constant here' },
      { domain: 'planar_systems', archetypeId: 'elemental_bastion', priority: 'essential', note: 'Elemental planes bleeding through everywhere' },
      { domain: 'planar_systems', archetypeId: 'bleeding_wound', priority: 'recommended', note: 'Planar wounds letting elemental chaos in' },
      { domain: 'magic_ecology', archetypeId: 'ley_line_nexus', priority: 'recommended', note: 'Ley line nexuses are nexuses of elemental power' },
    ],
  },
];

export const BLUEPRINT_MAP = new Map<string, WorldBlueprint>(
  ALL_BLUEPRINTS.map(b => [b.id, b])
);

export function getBlueprint(id: string): WorldBlueprint | undefined {
  return BLUEPRINT_MAP.get(id);
}

export function getBlueprintsByTag(tag: string): WorldBlueprint[] {
  return ALL_BLUEPRINTS.filter(b => b.tags.includes(tag));
}

export const BLUEPRINT_TAGS = [...new Set(ALL_BLUEPRINTS.flatMap(b => b.tags))].sort();
