import type { DomainConfig } from '../types/domains.js';

export const arcaneSciencesConfig: DomainConfig = {
  id: 'arcane_sciences',
  name: 'Arcane Science',
  namePlural: 'Arcane Sciences',
  icon: 'cog',
  color: '#16a085',
  description: 'Design the magitech devices, engineering principles, and technological infrastructure that emerge when magic and science converge. From enchanted steam engines to mana-powered communication networks, this domain covers the applied magical arts.',
  tableName: 'magitech_devices',
  category: 'magic',
  fields: [
    {
      name: 'device_category',
      label: 'Device Category',
      type: 'select',
      required: true,
      options: ['weapon', 'armor', 'transport', 'communication', 'construction', 'medical', 'agricultural', 'industrial', 'domestic', 'surveillance', 'entertainment', 'research', 'infrastructure', 'custom'],
      helpText: 'The functional category of this magitech device or principle.',
    },
    {
      name: 'engineering_principle_ids',
      label: 'Engineering Principles',
      type: 'json',
      placeholder: '["mana_circulation_id", "rune_logic_id"]',
      helpText: 'The underlying magitech engineering principles this device relies on.',
    },
    {
      name: 'era_id',
      label: 'Era of Invention',
      type: 'text',
      placeholder: 'ID of the historical era when this was invented',
      helpText: 'The period in which this device or principle was first developed.',
    },
    {
      name: 'power_source',
      label: 'Power Source',
      type: 'text',
      placeholder: 'e.g. mana crystal, bound elemental, ambient mana, hybrid',
      helpText: 'What provides energy to this device.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type consumed',
      helpText: 'The specific type of magical energy this device uses.',
    },
    {
      name: 'materials_required',
      label: 'Materials Required',
      type: 'json',
      placeholder: '["mithril", "dragon bone", "enchanted glass"]',
      helpText: 'Key materials needed to construct this device.',
    },
    {
      name: 'complexity',
      label: 'Complexity',
      type: 'select',
      options: ['trivial', 'simple', 'moderate', 'complex', 'masterwork', 'legendary'],
      helpText: 'How difficult this device is to design, build, and maintain.',
    },
    {
      name: 'reliability',
      label: 'Reliability',
      type: 'select',
      options: ['experimental', 'unreliable', 'functional', 'reliable', 'robust', 'flawless'],
      helpText: 'How consistently this device performs under normal conditions.',
    },
    {
      name: 'availability',
      label: 'Availability',
      type: 'select',
      options: ['unique', 'prototype', 'rare', 'limited', 'common', 'ubiquitous'],
      helpText: 'How widely available this device is in the world.',
    },
    {
      name: 'cost_level',
      label: 'Cost Level',
      type: 'select',
      options: ['trivial', 'affordable', 'expensive', 'luxury', 'national_investment', 'incalculable'],
      helpText: 'The relative cost to produce or acquire this device.',
    },
    {
      name: 'operator_requirements',
      label: 'Operator Requirements',
      type: 'textarea',
      placeholder: 'e.g. trained mage, any literate person, no operator needed',
      helpText: 'What skills, training, or magical ability is needed to operate this device.',
    },
    {
      name: 'failure_modes',
      label: 'Failure Modes',
      type: 'textarea',
      placeholder: 'What happens when it breaks or malfunctions?',
      helpText: 'How this device fails and what the consequences are—mana explosion, gradual decay, wild magic leak.',
    },
    {
      name: 'societal_impact',
      label: 'Societal Impact',
      type: 'textarea',
      placeholder: 'How has this device changed society?',
      helpText: 'The broader social, economic, or political effects of this technology.',
    },
    {
      name: 'predecessor_device_id',
      label: 'Predecessor Device',
      type: 'text',
      placeholder: 'ID of the device this evolved from',
      helpText: 'The earlier device or principle that this technology builds upon.',
    },
    {
      name: 'research_methodology',
      label: 'Research Methodology',
      type: 'textarea',
      placeholder: 'Describe how R&D works — empirical testing, intuitive discovery, divine revelation...',
      helpText: 'How this technology was developed — empirical experimentation, magical intuition, reverse-engineering, or divine inspiration.',
    },
    {
      name: 'safety_standards',
      label: 'Safety Standards',
      type: 'textarea',
      placeholder: 'Describe testing requirements, certifications, known risks...',
      helpText: 'Regulations, testing standards, and safety protocols governing this technology.',
    },
  ],
  elementTypes: ['device', 'principle', 'infrastructure', 'research_node', 'failure', 'era'],
  prompts: [
    'What was the breakthrough moment when magic and technology first merged in your world? Was it deliberate research, an accident, or a gift from another plane?',
    'How does magitech affect social inequality? Does it democratize power or concentrate it further in the hands of those who control magical resources?',
    'What are the environmental consequences of magitech industry? Does mana extraction pollute, and are there movements against it?',
    'What magitech devices exist that would be immediately recognizable analogs to real-world technology (communication, transport, medicine), and which have no real-world equivalent at all?',
    'What happens when magitech fails catastrophically? Are there historical disasters that shaped safety regulations or public fear?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'communication_crystal',
      name: 'Communication Crystal',
      description: 'A paired set of enchanted crystals that transmit voice or text over vast distances.',
      element_type: 'device',
      summary: 'Enchanted crystals enabling instant long-distance communication',
      fields: {
        device_category: 'communication',
        power_source: 'Ambient mana absorption with manual charging backup',
        complexity: 'moderate',
        reliability: 'reliable',
        availability: 'limited',
        cost_level: 'expensive',
        operator_requirements: 'Minimal training required — speak clearly while touching the crystal. Tuning to a specific paired crystal requires a trained arcanist.',
        failure_modes: 'Mana-dead zones cause total blackout. Interference from magical storms garbles messages. Crystals crack if overcharged.',
        societal_impact: 'Revolutionized long-distance governance and trade. Military applications make them strategically vital. Commoners rarely have access.',
      },
    },
    {
      id: 'healing_ward',
      name: 'Healing Ward',
      description: 'A medical enchantment that accelerates natural healing within a defined area.',
      element_type: 'device',
      summary: 'A magical field that accelerates natural healing',
      fields: {
        device_category: 'medical',
        power_source: 'Inscribed mana-gathering rune array, requires periodic recharging',
        complexity: 'complex',
        reliability: 'reliable',
        availability: 'rare',
        cost_level: 'luxury',
        operator_requirements: 'Must be installed and calibrated by a trained healer-arcanist. Ongoing use requires no special skill — patients simply rest within the ward.',
        failure_modes: 'Overloaded wards can accelerate harmful growths alongside healing. Power failure during critical healing causes dangerous rebound shock.',
        societal_impact: 'Hospitals and temples with healing wards attract pilgrims and the desperate. Access is a major marker of wealth and privilege.',
      },
    },
    {
      id: 'mana_powered_transport',
      name: 'Mana-Powered Transport',
      description: 'A vehicle or conveyance propelled by magical energy instead of animal or wind power.',
      element_type: 'device',
      summary: 'A magitech vehicle that travels without beast or wind',
      fields: {
        device_category: 'transport',
        power_source: 'Crystallized mana fuel cells or ley line siphoning',
        complexity: 'masterwork',
        reliability: 'functional',
        availability: 'rare',
        cost_level: 'luxury',
        operator_requirements: 'Trained pilot with basic arcane sensitivity to monitor mana flow. Emergency manual controls exist but are crude.',
        failure_modes: 'Mana depletion mid-transit leaves the vehicle stranded. Ley line disruptions can cause violent course deviations. Older models are prone to mana leaks.',
        societal_impact: 'Wealthy merchants and nobles use these for fast overland travel. Military applications are being explored. Common folk view them with awe and suspicion.',
      },
    },
    {
      id: 'emotion_engine',
      name: 'Emotion Engine',
      description: 'A device powered by captured emotions — joy, grief, rage — condensed into fuel. Effective, efficient, and ethically nightmarish.',
      element_type: 'device',
      summary: 'A machine that runs on bottled feelings — the question is whose',
      fields: {
        device_category: 'industrial',
        power_source: 'Distilled emotional energy captured via empathic resonance chambers',
        complexity: 'masterwork',
        reliability: 'unreliable',
        availability: 'prototype',
        cost_level: 'national_investment',
        operator_requirements: 'Requires an empath to calibrate and monitor emotional fuel purity. Operators report mood contamination — prolonged exposure to grief-fuel causes depression, rage-fuel causes aggression.',
        failure_modes: 'Emotional resonance cascade — if the containment fails, everyone within range experiences the stored emotion at full intensity simultaneously. A grief-engine rupture once caused a city-wide depression lasting weeks.',
        societal_impact: 'Banned in most civilized nations. Black market demand is enormous. Orphanages and prisons are targeted for emotion harvesting. Abolition movements call it "soul-mining." Proponents argue it\'s no worse than any other energy extraction.',
      },
    },
  ],
  defaultSortField: 'device_category',
};
