import type { DomainConfig } from '../types/domains.js';

export const arcaneSciencesConfig: DomainConfig = {
  id: 'arcane_sciences',
  name: 'Arcane Science',
  namePlural: 'Arcane Sciences',
  icon: 'cog',
  color: '#16a085',
  description: 'Design the magitech devices, engineering principles, and technological infrastructure that emerge when magic and science converge. From enchanted steam engines to mana-powered communication networks, this domain covers the applied magical arts.',
  tableName: 'magitech_devices',
  category: 'magic',
  fields: [
    {
      name: 'device_category',
      label: 'Device Category',
      type: 'select',
      required: true,
      options: ['weapon', 'armor', 'transport', 'communication', 'construction', 'medical', 'agricultural', 'industrial', 'domestic', 'surveillance', 'entertainment', 'research', 'infrastructure', 'custom'],
      helpText: 'The functional category of this magitech device or principle.',
    },
    {
      name: 'engineering_principle_ids',
      label: 'Engineering Principles',
      type: 'json',
      placeholder: '["mana_circulation_id", "rune_logic_id"]',
      helpText: 'The underlying magitech engineering principles this device relies on.',
    },
    {
      name: 'era_id',
      label: 'Era of Invention',
      type: 'text',
      placeholder: 'ID of the historical era when this was invented',
      helpText: 'The period in which this device or principle was first developed.',
    },
    {
      name: 'power_source',
      label: 'Power Source',
      type: 'text',
      placeholder: 'e.g. mana crystal, bound elemental, ambient mana, hybrid',
      helpText: 'What provides energy to this device.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type consumed',
      helpText: 'The specific type of magical energy this device uses.',
    },
    {
      name: 'materials_required',
      label: 'Materials Required',
      type: 'json',
      placeholder: '["mithril", "dragon bone", "enchanted glass"]',
      helpText: 'Key materials needed to construct this device.',
    },
    {
      name: 'complexity',
      label: 'Complexity',
      type: 'select',
      options: ['trivial', 'simple', 'moderate', 'complex', 'masterwork', 'legendary'],
      helpText: 'How difficult this device is to design, build, and maintain.',
    },
    {
      name: 'reliability',
      label: 'Reliability',
      type: 'select',
      options: ['experimental', 'unreliable', 'functional', 'reliable', 'robust', 'flawless'],
      helpText: 'How consistently this device performs under normal conditions.',
    },
    {
      name: 'availability',
      label: 'Availability',
      type: 'select',
      options: ['unique', 'prototype', 'rare', 'limited', 'common', 'ubiquitous'],
      helpText: 'How widely available this device is in the world.',
    },
    {
      name: 'cost_level',
      label: 'Cost Level',
      type: 'select',
      options: ['trivial', 'affordable', 'expensive', 'luxury', 'national_investment', 'incalculable'],
      helpText: 'The relative cost to produce or acquire this device.',
    },
    {
      name: 'operator_requirements',
      label: 'Operator Requirements',
      type: 'textarea',
      placeholder: 'e.g. trained mage, any literate person, no operator needed',
      helpText: 'What skills, training, or magical ability is needed to operate this device.',
    },
    {
      name: 'failure_modes',
      label: 'Failure Modes',
      type: 'textarea',
      placeholder: 'What happens when it breaks or malfunctions?',
      helpText: 'How this device fails and what the consequences are—mana explosion, gradual decay, wild magic leak.',
    },
    {
      name: 'societal_impact',
      label: 'Societal Impact',
      type: 'textarea',
      placeholder: 'How has this device changed society?',
      helpText: 'The broader social, economic, or political effects of this technology.',
    },
    {
      name: 'predecessor_device_id',
      label: 'Predecessor Device',
      type: 'text',
      placeholder: 'ID of the device this evolved from',
      helpText: 'The earlier device or principle that this technology builds upon.',
    },
    {
      name: 'research_methodology',
      label: 'Research Methodology',
      type: 'textarea',
      placeholder: 'Describe how R&D works — empirical testing, intuitive discovery, divine revelation...',
      helpText: 'How this technology was developed — empirical experimentation, magical intuition, reverse-engineering, or divine inspiration.',
    },
    {
      name: 'safety_standards',
      label: 'Safety Standards',
      type: 'textarea',
      placeholder: 'Describe testing requirements, certifications, known risks...',
      helpText: 'Regulations, testing standards, and safety protocols governing this technology.',
    },
  ],
  elementTypes: ['device', 'principle', 'infrastructure', 'research_node', 'failure', 'era'],
  elementTypeDescriptions: {
    device: 'A magitech tool, weapon, or apparatus — enchanted objects that merge magical and mechanical principles to achieve specific functions.',
    principle: 'A fundamental law or theory of arcane engineering — the scientific understanding behind why and how magitech works.',
    infrastructure: 'Large-scale magitech systems serving a society — communication networks, transportation grids, defensive wards, or power distribution.',
    research_node: 'A center of arcane scientific study — laboratories, academies, or think-tanks pushing the boundaries of what magitech can do.',
    failure: 'A magitech disaster or catastrophic malfunction — explosions, corruptions, or runaway enchantments that went terribly wrong.',
    era: 'A period defined by a particular level or style of magitech development — from early experimentation to industrial revolution.',
  },
  prompts: [
    'What was the breakthrough moment when magic and technology first merged in your world? Was it deliberate research, an accident, or a gift from another plane?',
    'How does magitech affect social inequality? Does it democratize power or concentrate it further in the hands of those who control magical resources?',
    'What are the environmental consequences of magitech industry? Does mana extraction pollute, and are there movements against it?',
    'What magitech devices exist that would be immediately recognizable analogs to real-world technology (communication, transport, medicine), and which have no real-world equivalent at all?',
    'What happens when magitech fails catastrophically? Are there historical disasters that shaped safety regulations or public fear?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'communication_crystal',
      name: 'Communication Crystal',
      description: 'A paired set of enchanted crystals that transmit voice or text over vast distances.',
      element_type: 'device',
      summary: 'Enchanted crystals enabling instant long-distance communication',
      fields: {
        device_category: 'communication',
        power_source: 'Ambient mana absorption with manual charging backup',
        complexity: 'moderate',
        reliability: 'reliable',
        availability: 'limited',
        cost_level: 'expensive',
        operator_requirements: 'Minimal training required — speak clearly while touching the crystal. Tuning to a specific paired crystal requires a trained arcanist.',
        failure_modes: 'Mana-dead zones cause total blackout. Interference from magical storms garbles messages. Crystals crack if overcharged.',
        societal_impact: 'Revolutionized long-distance governance and trade. Military applications make them strategically vital. Commoners rarely have access.',
      },
    },
    {
      id: 'healing_ward',
      name: 'Healing Ward',
      description: 'A medical enchantment that accelerates natural healing within a defined area.',
      element_type: 'device',
      summary: 'A magical field that accelerates natural healing',
      fields: {
        device_category: 'medical',
        power_source: 'Inscribed mana-gathering rune array, requires periodic recharging',
        complexity: 'complex',
        reliability: 'reliable',
        availability: 'rare',
        cost_level: 'luxury',
        operator_requirements: 'Must be installed and calibrated by a trained healer-arcanist. Ongoing use requires no special skill — patients simply rest within the ward.',
        failure_modes: 'Overloaded wards can accelerate harmful growths alongside healing. Power failure during critical healing causes dangerous rebound shock.',
        societal_impact: 'Hospitals and temples with healing wards attract pilgrims and the desperate. Access is a major marker of wealth and privilege.',
      },
    },
    {
      id: 'mana_powered_transport',
      name: 'Mana-Powered Transport',
      description: 'A vehicle or conveyance propelled by magical energy instead of animal or wind power.',
      element_type: 'device',
      summary: 'A magitech vehicle that travels without beast or wind',
      fields: {
        device_category: 'transport',
        power_source: 'Crystallized mana fuel cells or ley line siphoning',
        complexity: 'masterwork',
        reliability: 'functional',
        availability: 'rare',
        cost_level: 'luxury',
        operator_requirements: 'Trained pilot with basic arcane sensitivity to monitor mana flow. Emergency manual controls exist but are crude.',
        failure_modes: 'Mana depletion mid-transit leaves the vehicle stranded. Ley line disruptions can cause violent course deviations. Older models are prone to mana leaks.',
        societal_impact: 'Wealthy merchants and nobles use these for fast overland travel. Military applications are being explored. Common folk view them with awe and suspicion.',
      },
    },
    {
      id: 'emotion_engine',
      name: 'Emotion Engine',
      description: 'A device powered by captured emotions — joy, grief, rage — condensed into fuel. Effective, efficient, and ethically nightmarish.',
      element_type: 'device',
      summary: 'A machine that runs on bottled feelings — the question is whose',
      fields: {
        device_category: 'industrial',
        power_source: 'Distilled emotional energy captured via empathic resonance chambers',
        complexity: 'masterwork',
        reliability: 'unreliable',
        availability: 'prototype',
        cost_level: 'national_investment',
        operator_requirements: 'Requires an empath to calibrate and monitor emotional fuel purity. Operators report mood contamination — prolonged exposure to grief-fuel causes depression, rage-fuel causes aggression.',
        failure_modes: 'Emotional resonance cascade — if the containment fails, everyone within range experiences the stored emotion at full intensity simultaneously. A grief-engine rupture once caused a city-wide depression lasting weeks.',
        societal_impact: 'Banned in most civilized nations. Black market demand is enormous. Orphanages and prisons are targeted for emotion harvesting. Abolition movements call it "soul-mining." Proponents argue it\'s no worse than any other energy extraction.',
      },
    },
    {
      id: 'golem_workforce',
      name: 'Golem Workforce',
      description: 'Mass-produced magical constructs used for labor, warfare, and service. Raises questions about consciousness and rights.',
      element_type: 'device',
      summary: 'Standardized magical constructs built for labor — cheap, tireless, and possibly aware',
      detailed_notes: 'Golem workforces represent the industrialization of construct-making. Where once each golem was a unique creation of a master artificer, modern techniques allow assembly-line production using standardized animation cores and pre-inscribed command matrices. The golems handle mining, farming, construction, and warfare. They follow orders without complaint, need no food or rest, and can be repaired rather than healed. But as production scales, troubling questions arise: some golems hesitate before following orders, others develop preferences, and a few have refused commands entirely. The debate over golem consciousness — and whether these beings deserve rights — threatens to upend the economies that depend on them.',
      fields: {
        device_category: 'industrial',
        power_source: 'Standardized animation cores charged with crystallized mana. Each core lasts approximately one year before requiring replacement.',
        complexity: 'moderate',
        reliability: 'reliable',
        availability: 'common',
        cost_level: 'affordable',
        operator_requirements: 'Basic command phrases allow anyone to direct a golem. Reprogramming, repair, and core replacement require a trained artificer. Fleet management of large workforces needs a golem-marshal with arcane training.',
        failure_modes: 'Core depletion causes gradual shutdown — the golem slows, then freezes mid-task. Command matrix corruption leads to erratic behavior or literal interpretation of orders with disastrous results. In rare cases, a golem enters "cascade awareness" and begins acting independently.',
        societal_impact: 'Displaced millions of manual laborers, creating vast unemployment in lower classes. Guilds are split between those who build golems and those whose members were replaced by them. A growing abolitionist movement argues golems are enslaved minds. Counter-arguments hold that they are no more conscious than a plow.',
      },
    },
    {
      id: 'spell_telegraph',
      name: 'Spell Telegraph Network',
      description: 'A communication system using enchanted relay stations. Messages travel at the speed of magic.',
      element_type: 'infrastructure',
      summary: 'A continental network of enchanted relay towers enabling near-instant communication',
      detailed_notes: 'The spell telegraph network consists of hundreds of relay stations, each containing a paired set of resonance crystals tuned to their neighbors. A message enters the network at one station, is encoded into a pulse of arcane energy, and hops from relay to relay until it reaches its destination. Coverage spans major cities and trade routes, though rural areas and frontier regions remain unconnected. The network has transformed governance, commerce, and warfare — generals receive battlefield reports in minutes, merchants track shipments in real time, and governments coordinate policy across vast distances. Control of the network is fiercely contested.',
      fields: {
        device_category: 'communication',
        power_source: 'Each relay station draws from a local mana collector array, supplemented by manually recharged crystal batteries during high-traffic periods',
        complexity: 'complex',
        reliability: 'reliable',
        availability: 'limited',
        cost_level: 'national_investment',
        operator_requirements: 'Each relay station requires a trained signal-mage to encode, decode, and route messages. Operators develop a distinctive "telegraphic shorthand" that is nearly its own language. Network maintenance requires teams of traveling artificers.',
        failure_modes: 'Relay station failure creates dead zones until repaired. Magical storms can overload crystals, causing garbled messages or cascade failures across multiple stations. The network is vulnerable to sabotage — destroying a single relay in a sparse region can cut communication to entire provinces.',
        societal_impact: 'Centralized power in nations that control the network. Created a new class of signal-mage professionals. Enabled modern banking, commodity trading, and rapid military response. The "unconnected" regions resent their information disadvantage. Espionage agencies have developed methods to tap relay stations.',
      },
    },
    {
      id: 'healing_vat',
      name: 'Regeneration Vat',
      description: 'A medical device that rebuilds tissue using magical templates. Expensive, imperfect, and ethically complex.',
      element_type: 'device',
      summary: 'A magitech medical pod that regrows flesh from arcane blueprints — for those who can afford it',
      detailed_notes: 'Regeneration vats use a combination of healing magic, alchemical solutions, and biological templates to rebuild damaged or missing tissue. A patient is submerged in a nutrient-rich, mana-infused solution while inscribed runes guide the regrowth process according to a pre-recorded template of their healthy body. The technology can regrow limbs, repair organs, and reverse aging to a degree. However, each treatment is enormously expensive, the process is painful and takes weeks, and imperfect templates can produce tissue that functions but feels wrong to the patient. The existence of regeneration vats raises sharp questions about medical access, the ethics of enhancement, and what constitutes a "natural" body.',
      fields: {
        device_category: 'medical',
        power_source: 'High-capacity mana crystal arrays providing sustained, precisely calibrated healing energy throughout the regeneration cycle',
        complexity: 'masterwork',
        reliability: 'functional',
        availability: 'rare',
        cost_level: 'luxury',
        operator_requirements: 'A team of healer-arcanists and alchemists must monitor the process continuously. Template creation requires a biological mage to scan and record the patient\'s healthy baseline. Errors in the template produce errors in the flesh.',
        failure_modes: 'Template drift causes regrown tissue that is subtly wrong — functional but alien-feeling to the patient. Power interruption during regeneration leaves tissue partially formed. In catastrophic failure, the vat produces undifferentiated tissue growth — a medical horror requiring immediate surgical intervention.',
        societal_impact: 'Available only to the wealthy and powerful, creating a stark divide between those who can be rebuilt and those who suffer permanent injury. Veterans\' advocacy groups demand public access. Religious orders debate whether regenerated tissue has a soul. A black market offers cut-rate treatments with dangerously imprecise templates.',
      },
    },
    {
      id: 'memory_crystal_archive',
      name: 'Memory Crystal Archive',
      description: 'A library stored in crystallized mana with complete sensory records.',
      element_type: 'infrastructure',
      summary: 'A vast library encoded in mana crystals — each record contains not just text but full sensory experience',
      detailed_notes: 'Memory crystal archives represent the pinnacle of magical information storage. Instead of writing on paper or parchment, knowledge is recorded directly into crystallized mana as complete sensory experiences. A reader doesn\'t just learn about a historical battle — they experience it, feeling the ground shake, hearing the war cries, smelling the smoke. The technology was developed by archivist-mages frustrated with the limitations of written language, and it has transformed scholarship, education, and legal testimony. A single crystal the size of a fist can hold a lifetime of experiences. Major archives contain millions of crystals, organized by sophisticated indexing systems. The technology raises profound questions about privacy, intellectual property, and the nature of knowledge — experiencing someone\'s memories is far more intimate than reading their words.',
      fields: {
        device_category: 'infrastructure',
        power_source: 'Self-sustaining mana lattice within each crystal. Archive-wide search and indexing systems draw from a central mana reservoir.',
        complexity: 'masterwork',
        reliability: 'reliable',
        availability: 'rare',
        cost_level: 'national_investment',
        operator_requirements: 'Recording requires a trained memory-crystallographer who can extract and encode sensory experiences without distortion. Reading requires only physical contact with the crystal and basic mana sensitivity. Indexing and archive management require specialized training.',
        failure_modes: 'Crystal degradation over centuries causes memory corruption — sensory details fade, emotions flatten, or experiences blend together. Physical damage shatters the crystal and destroys its contents irretrievably. Mana surges can overwrite crystals with ambient impressions.',
        societal_impact: 'Transformed legal proceedings — eyewitness testimony is now recorded and replayed directly. Education uses experiential learning. Historical research provides first-person perspectives on ancient events. Privacy advocates warn of a surveillance state where every experience can be crystallized and reviewed.',
      },
    },
    {
      id: 'weather_engine',
      name: 'Weather Engine',
      description: 'Magitech that controls regional weather. Agricultural revolution or weapon.',
      element_type: 'infrastructure',
      summary: 'A massive magitech installation that controls weather across an entire region — harvest-bringer or weapon of war',
      detailed_notes: 'Weather engines are enormous magitech installations capable of controlling precipitation, temperature, wind patterns, and storm activity across a region spanning hundreds of square kilometers. Developed initially to stabilize agriculture — ensuring reliable rainfall, preventing frost, and dissipating destructive storms — the technology quickly found military and political applications. A civilization with a weather engine can starve its enemies through drought, shatter armies with directed lightning storms, or simply make its own farmland the most productive in the world. The devices are monumentally expensive, requiring rare materials, continuous mana supply, and teams of specialized operators. They also have ecological consequences: forcing weather patterns in one region disrupts natural patterns in neighboring regions, creating a cascading arms race where every nation needs its own weather engine to counter its neighbors\'.',
      fields: {
        device_category: 'infrastructure',
        power_source: 'Massive ley line tap supplemented by banks of high-capacity mana crystals. Peak operations during storm-calling consume enormous energy.',
        complexity: 'legendary',
        reliability: 'functional',
        availability: 'unique',
        cost_level: 'national_investment',
        operator_requirements: 'A team of weather-mages, atmospheric scholars, and magitech engineers operating in shifts. The lead operator must have innate weather sensitivity and decades of meteorological experience. Miscalibration can trigger uncontrolled storms.',
        failure_modes: 'Catastrophic failure releases stored atmospheric energy as a massive uncontrolled storm — hurricanes, lightning barrages, or flash-freezing events. Partial failures create bizarre localized weather anomalies that persist until manually corrected. Sustained operation without maintenance degrades the ley line tap, risking mana depletion in the surrounding region.',
        societal_impact: 'Agricultural revolution in regions with weather engines — famine becomes almost unknown. Military applications make weather engines strategic targets and deterrents. Neighboring regions suffer weather disruption, creating diplomatic crises. Environmental movements protest the ecological damage of forced weather patterns.',
      },
    },
    {
      id: 'portal_network',
      name: 'Portal Network',
      description: 'Transportation system of linked magical gateways.',
      element_type: 'infrastructure',
      summary: 'A continental transportation network of linked magical gateways enabling instant travel between distant locations',
      detailed_notes: 'The portal network is a system of permanently maintained magical gateways that allow instant transportation between connected nodes. Each portal is a stabilized rift anchored by massive runestone arrays and powered by local mana sources. Travelers step through a shimmering gateway in one city and emerge from a corresponding gateway hundreds or thousands of kilometers away. The network has transformed trade, warfare, governance, and daily life in connected regions. However, it is expensive to build and maintain, limiting coverage to major cities and strategic locations. Rural areas remain isolated, creating a sharp divide between the portal-connected world and the "walk-bound" communities beyond the network\'s reach. Security is a constant concern — a compromised portal could allow an invading army to appear in the heart of a capital city.',
      fields: {
        device_category: 'transport',
        power_source: 'Each portal node draws from a dedicated ley line tap or large mana crystal array. Transit energy scales with distance and cargo mass.',
        complexity: 'legendary',
        reliability: 'reliable',
        availability: 'limited',
        cost_level: 'national_investment',
        operator_requirements: 'Each portal station requires a team of portal-mages to maintain stabilization, manage traffic flow, and perform security screening. Emergency shutdown requires a senior portal-mage with override authority. Travelers need no special ability — they simply walk through.',
        failure_modes: 'Portal destabilization can scatter travelers across random locations or partially transport them (a horrifying outcome). Power failure strands travelers mid-transit in an inter-spatial void. Security breaches allow unauthorized access. Rare cascade failures can collapse multiple linked portals simultaneously.',
        societal_impact: 'Unified distant territories under single governance. Enabled rapid military deployment and response. Created a new class of portal-connected elite. Rural communities resent their exclusion. Smuggling through corrupted portal operators is a constant law enforcement challenge. The network\'s controller wields enormous geopolitical influence.',
      },
    },
  ],
  defaultSortField: 'device_category',
};
