import type { DomainConfig } from '../types/domains.js';

export const arcaneSciencesConfig: DomainConfig = {
  id: 'arcane_sciences',
  name: 'Arcane Science',
  namePlural: 'Arcane Sciences',
  icon: 'cog',
  color: '#16a085',
  description: 'Design the magitech devices, engineering principles, and technological infrastructure that emerge when magic and science converge. From enchanted steam engines to mana-powered communication networks, this domain covers the applied magical arts.',
  tableName: 'magitech_devices',
  category: 'magic',
  fields: [
    {
      name: 'device_category',
      label: 'Device Category',
      type: 'select',
      required: true,
      options: ['weapon', 'armor', 'transport', 'communication', 'construction', 'medical', 'agricultural', 'industrial', 'domestic', 'surveillance', 'entertainment', 'research', 'infrastructure', 'custom'],
      helpText: 'The functional category of this magitech device or principle.',
    },
    {
      name: 'engineering_principle_ids',
      label: 'Engineering Principles',
      type: 'json',
      placeholder: '["mana_circulation_id", "rune_logic_id"]',
      helpText: 'The underlying magitech engineering principles this device relies on.',
    },
    {
      name: 'era_id',
      label: 'Era of Invention',
      type: 'text',
      placeholder: 'ID of the historical era when this was invented',
      helpText: 'The period in which this device or principle was first developed.',
    },
    {
      name: 'power_source',
      label: 'Power Source',
      type: 'text',
      placeholder: 'e.g. mana crystal, bound elemental, ambient mana, hybrid',
      helpText: 'What provides energy to this device.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type consumed',
      helpText: 'The specific type of magical energy this device uses.',
    },
    {
      name: 'materials_required',
      label: 'Materials Required',
      type: 'json',
      placeholder: '["mithril", "dragon bone", "enchanted glass"]',
      helpText: 'Key materials needed to construct this device.',
    },
    {
      name: 'complexity',
      label: 'Complexity',
      type: 'select',
      options: ['trivial', 'simple', 'moderate', 'complex', 'masterwork', 'legendary'],
      helpText: 'How difficult this device is to design, build, and maintain.',
    },
    {
      name: 'reliability',
      label: 'Reliability',
      type: 'select',
      options: ['experimental', 'unreliable', 'functional', 'reliable', 'robust', 'flawless'],
      helpText: 'How consistently this device performs under normal conditions.',
    },
    {
      name: 'availability',
      label: 'Availability',
      type: 'select',
      options: ['unique', 'prototype', 'rare', 'limited', 'common', 'ubiquitous'],
      helpText: 'How widely available this device is in the world.',
    },
    {
      name: 'cost_level',
      label: 'Cost Level',
      type: 'select',
      options: ['trivial', 'affordable', 'expensive', 'luxury', 'national_investment', 'incalculable'],
      helpText: 'The relative cost to produce or acquire this device.',
    },
    {
      name: 'operator_requirements',
      label: 'Operator Requirements',
      type: 'textarea',
      placeholder: 'e.g. trained mage, any literate person, no operator needed',
      helpText: 'What skills, training, or magical ability is needed to operate this device.',
    },
    {
      name: 'failure_modes',
      label: 'Failure Modes',
      type: 'textarea',
      placeholder: 'What happens when it breaks or malfunctions?',
      helpText: 'How this device fails and what the consequences are—mana explosion, gradual decay, wild magic leak.',
    },
    {
      name: 'societal_impact',
      label: 'Societal Impact',
      type: 'textarea',
      placeholder: 'How has this device changed society?',
      helpText: 'The broader social, economic, or political effects of this technology.',
    },
    {
      name: 'predecessor_device_id',
      label: 'Predecessor Device',
      type: 'text',
      placeholder: 'ID of the device this evolved from',
      helpText: 'The earlier device or principle that this technology builds upon.',
    },
    {
      name: 'research_methodology',
      label: 'Research Methodology',
      type: 'textarea',
      placeholder: 'Describe how R&D works — empirical testing, intuitive discovery, divine revelation...',
      helpText: 'How this technology was developed — empirical experimentation, magical intuition, reverse-engineering, or divine inspiration.',
    },
    {
      name: 'safety_standards',
      label: 'Safety Standards',
      type: 'textarea',
      placeholder: 'Describe testing requirements, certifications, known risks...',
      helpText: 'Regulations, testing standards, and safety protocols governing this technology.',
    },
  ],
  elementTypes: ['device', 'principle', 'infrastructure', 'research_node', 'failure', 'era'],
  prompts: [
    'What was the breakthrough moment when magic and technology first merged in your world? Was it deliberate research, an accident, or a gift from another plane?',
    'How does magitech affect social inequality? Does it democratize power or concentrate it further in the hands of those who control magical resources?',
    'What are the environmental consequences of magitech industry? Does mana extraction pollute, and are there movements against it?',
    'What magitech devices exist that would be immediately recognizable analogs to real-world technology (communication, transport, medicine), and which have no real-world equivalent at all?',
    'What happens when magitech fails catastrophically? Are there historical disasters that shaped safety regulations or public fear?',
  ],
  magicPermeation: null,
  defaultSortField: 'device_category',
};
