import type { DomainConfig } from '../types/domains.js';

export const atmosphereConfig: DomainConfig = {
  id: 'atmosphere',
  name: 'Atmosphere',
  namePlural: 'Atmospheres',
  icon: 'wind',
  color: '#7ec8e3',
  description: 'Define the gaseous envelopes surrounding your world\'s celestial bodies. Atmospheric composition, pressure, and phenomena determine what can breathe, what burns, and what flies.',
  tableName: 'atmospheres',
  category: 'natural',
  fields: [
    {
      name: 'composition',
      label: 'Atmospheric Composition',
      type: 'json',
      placeholder: '{"nitrogen": 78, "oxygen": 21, "argon": 0.9}',
      helpText: 'Gas composition as percentages or a descriptive list.',
    },
    {
      name: 'pressure',
      label: 'Surface Pressure',
      type: 'text',
      placeholder: 'e.g. 1.0 atm, 101.3 kPa',
      helpText: 'Atmospheric pressure at the surface.',
    },
    {
      name: 'breathable',
      label: 'Breathable',
      type: 'boolean',
      helpText: 'Whether the atmosphere can sustain common life forms without aid.',
    },
    {
      name: 'color',
      label: 'Sky Color',
      type: 'text',
      placeholder: 'e.g. pale blue, amber, violet',
      helpText: 'The dominant color of the sky as seen from the surface.',
    },
    {
      name: 'layers',
      label: 'Atmospheric Layers',
      type: 'json',
      placeholder: '[{"name": "lower", "altitude": "0-10km", "traits": "breathable"}, ...]',
      helpText: 'The distinct layers of the atmosphere and their characteristics.',
    },
    {
      name: 'wind_systems',
      label: 'Wind Systems',
      type: 'textarea',
      placeholder: 'Describe prevailing winds, jet streams, trade winds...',
      helpText: 'Major wind patterns including prevailing winds, jet streams, and seasonal wind shifts.',
    },
    {
      name: 'weather_patterns',
      label: 'Weather Patterns',
      type: 'textarea',
      placeholder: 'Describe recurring weather systems, storm tracks, monsoons...',
      helpText: 'Recurring weather systems and patterns distinct from one-off phenomena.',
    },
    {
      name: 'phenomena',
      label: 'Atmospheric Phenomena',
      type: 'json',
      placeholder: '["aurora", "perpetual storms", "floating dust layers"]',
      helpText: 'Unusual or notable atmospheric events and features.',
    },
  ],
  elementTypes: ['atmospheric_layer', 'weather_system', 'wind_pattern', 'atmospheric_phenomenon'],
  prompts: [
    'What gases make up the atmosphere? Are there unusual components that create exotic sky colors or chemical reactions?',
    'How does atmospheric pressure vary with altitude? Are there floating islands or organisms at high altitude?',
    'What persistent weather systems define regions—eternal storms, calm doldrums, or walls of wind?',
    'How do wind patterns drive ocean currents, rainfall, and the spread of seeds, spores, or airborne creatures?',
  ],
  magicPermeation: {
    companionTable: 'atmosphere_magic_aspects',
    fields: [
      {
        name: 'mana_density_in_air',
        label: 'Mana Density in Air',
        type: 'textarea',
        helpText: 'How much ambient mana is suspended in the atmosphere.',
      },
      {
        name: 'atmospheric_mana_layers',
        label: 'Atmospheric Mana Layers',
        type: 'textarea',
        helpText: 'Stratified layers where mana concentrates or thins at different altitudes.',
      },
      {
        name: 'arcane_aurora',
        label: 'Arcane Aurora',
        type: 'textarea',
        helpText: 'Visible magical phenomena in the upper atmosphere—mana auroras, spell echoes, etc.',
      },
      {
        name: 'magical_weather_patterns',
        label: 'Magical Weather Patterns',
        type: 'textarea',
        helpText: 'Weather systems created or influenced by magical energy.',
      },
      {
        name: 'air_magic_conductivity',
        label: 'Air-Magic Conductivity',
        type: 'textarea',
        helpText: 'How well the atmosphere conducts, disperses, or blocks magical energy.',
      },
      {
        name: 'atmospheric_magic_filtering',
        label: 'Atmospheric Magic Filtering',
        type: 'textarea',
        helpText: 'Whether the atmosphere filters incoming cosmic magical radiation.',
      },
      {
        name: 'high_altitude_magic_effects',
        label: 'High Altitude Magic Effects',
        type: 'textarea',
        helpText: 'How magic behaves differently at extreme altitudes.',
      },
      {
        name: 'windborne_magic',
        label: 'Windborne Magic',
        type: 'textarea',
        helpText: 'Magical energy carried by winds—mana breezes, spell-carrying gales, etc.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this atmosphere.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Does mana concentrate at certain altitudes, creating layers where spellcasting is stronger or weaker?',
      'Can winds carry magical energy across continents, spreading enchantments or curses far from their source?',
      'Are there visible magical phenomena in the sky—arcane auroras, mana storms, or luminous spell-trails?',
    ],
  },
  defaultSortField: 'pressure',
};
