import type { DomainConfig } from '../types/domains.js';

export const atmosphereConfig: DomainConfig = {
  id: 'atmosphere',
  name: 'Atmosphere',
  namePlural: 'Atmospheres',
  icon: 'wind',
  color: '#7ec8e3',
  description: 'Define the gaseous envelopes surrounding your world\'s celestial bodies. Atmospheric composition, pressure, and phenomena determine what can breathe, what burns, and what flies.',
  tableName: 'atmospheres',
  category: 'natural',
  fields: [
    {
      name: 'composition',
      label: 'Atmospheric Composition',
      type: 'json',
      placeholder: '{"nitrogen": 78, "oxygen": 21, "argon": 0.9}',
      helpText: 'Gas composition as percentages or a descriptive list.',
    },
    {
      name: 'pressure',
      label: 'Surface Pressure',
      type: 'text',
      placeholder: 'e.g. 1.0 atm, 101.3 kPa',
      helpText: 'Atmospheric pressure at the surface.',
    },
    {
      name: 'breathable',
      label: 'Breathable',
      type: 'boolean',
      helpText: 'Whether the atmosphere can sustain common life forms without aid.',
    },
    {
      name: 'color',
      label: 'Sky Color',
      type: 'text',
      placeholder: 'e.g. pale blue, amber, violet',
      helpText: 'The dominant color of the sky as seen from the surface.',
    },
    {
      name: 'layers',
      label: 'Atmospheric Layers',
      type: 'json',
      placeholder: '[{"name": "lower", "altitude": "0-10km", "traits": "breathable"}, ...]',
      helpText: 'The distinct layers of the atmosphere and their characteristics.',
    },
    {
      name: 'wind_systems',
      label: 'Wind Systems',
      type: 'textarea',
      placeholder: 'Describe prevailing winds, jet streams, trade winds...',
      helpText: 'Major wind patterns including prevailing winds, jet streams, and seasonal wind shifts.',
    },
    {
      name: 'weather_patterns',
      label: 'Weather Patterns',
      type: 'textarea',
      placeholder: 'Describe recurring weather systems, storm tracks, monsoons...',
      helpText: 'Recurring weather systems and patterns distinct from one-off phenomena.',
    },
    {
      name: 'phenomena',
      label: 'Atmospheric Phenomena',
      type: 'json',
      placeholder: '["aurora", "perpetual storms", "floating dust layers"]',
      helpText: 'Unusual or notable atmospheric events and features.',
    },
  ],
  elementTypes: ['atmospheric_layer', 'weather_system', 'wind_pattern', 'atmospheric_phenomenon'],
  elementTypeDescriptions: {
    atmospheric_layer: 'A distinct horizontal zone of the atmosphere defined by temperature, composition, or pressure. Each layer has unique properties.',
    weather_system: 'A large-scale pattern of atmospheric conditions — fronts, pressure systems, or persistent storms that drive regional weather.',
    wind_pattern: 'A recurring directional airflow caused by pressure differentials, planetary rotation, or geography. Shapes climate and navigation.',
    atmospheric_phenomenon: 'An unusual or notable atmospheric event — auroras, perpetual storms, luminous clouds, or other spectacles in the sky.',
  },
  prompts: [
    'What gases make up the atmosphere? Are there unusual components that create exotic sky colors or chemical reactions?',
    'How does atmospheric pressure vary with altitude? Are there floating islands or organisms at high altitude?',
    'What persistent weather systems define regions—eternal storms, calm doldrums, or walls of wind?',
    'How do wind patterns drive ocean currents, rainfall, and the spread of seeds, spores, or airborne creatures?',
  ],
  magicPermeation: {
    companionTable: 'atmosphere_magic_aspects',
    fields: [
      {
        name: 'mana_density_in_air',
        label: 'Mana Density in Air',
        type: 'textarea',
        helpText: 'How much ambient mana is suspended in the atmosphere.',
      },
      {
        name: 'atmospheric_mana_layers',
        label: 'Atmospheric Mana Layers',
        type: 'textarea',
        helpText: 'Stratified layers where mana concentrates or thins at different altitudes.',
      },
      {
        name: 'arcane_aurora',
        label: 'Arcane Aurora',
        type: 'textarea',
        helpText: 'Visible magical phenomena in the upper atmosphere—mana auroras, spell echoes, etc.',
      },
      {
        name: 'magical_weather_patterns',
        label: 'Magical Weather Patterns',
        type: 'textarea',
        helpText: 'Weather systems created or influenced by magical energy.',
      },
      {
        name: 'air_magic_conductivity',
        label: 'Air-Magic Conductivity',
        type: 'textarea',
        helpText: 'How well the atmosphere conducts, disperses, or blocks magical energy.',
      },
      {
        name: 'atmospheric_magic_filtering',
        label: 'Atmospheric Magic Filtering',
        type: 'textarea',
        helpText: 'Whether the atmosphere filters incoming cosmic magical radiation.',
      },
      {
        name: 'high_altitude_magic_effects',
        label: 'High Altitude Magic Effects',
        type: 'textarea',
        helpText: 'How magic behaves differently at extreme altitudes.',
      },
      {
        name: 'windborne_magic',
        label: 'Windborne Magic',
        type: 'textarea',
        helpText: 'Magical energy carried by winds—mana breezes, spell-carrying gales, etc.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this atmosphere.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Does mana concentrate at certain altitudes, creating layers where spellcasting is stronger or weaker?',
      'Can winds carry magical energy across continents, spreading enchantments or curses far from their source?',
      'Are there visible magical phenomena in the sky—arcane auroras, mana storms, or luminous spell-trails?',
    ],
  },
  archetypes: [
    {
      id: 'earth_like',
      name: 'Earth-like Atmosphere',
      description: 'A nitrogen-oxygen atmosphere suitable for carbon-based life, with active weather.',
      element_type: 'atmospheric_layer',
      summary: 'A breathable nitrogen-oxygen atmosphere with familiar weather patterns',
      fields: {
        breathable: true,
        pressure: '1.0 atm at sea level',
        color: 'Blue, with white cloud formations',
        wind_systems: 'Global circulation with trade winds, westerlies, and polar easterlies. Seasonal monsoons in tropical regions.',
        weather_patterns: 'Regular precipitation cycles, thunderstorms in warm seasons, frontal systems in temperate zones. Hurricanes form over warm oceans.',
      },
    },
    {
      id: 'thick_greenhouse',
      name: 'Thick Greenhouse Atmosphere',
      description: 'A dense, hot atmosphere with a runaway greenhouse effect — hostile to most life.',
      element_type: 'atmospheric_layer',
      summary: 'A crushing, superheated atmosphere with acid clouds',
      fields: {
        breathable: false,
        pressure: '90+ atm at surface',
        color: 'Yellowish-orange haze',
        wind_systems: 'Superrotation of upper atmosphere. Extreme surface winds are slow due to density but carry tremendous force.',
        weather_patterns: 'Sulfuric acid rain that evaporates before reaching the surface. Permanent cloud cover blocks direct sunlight.',
      },
    },
    {
      id: 'thin_highland',
      name: 'Thin Highland Atmosphere',
      description: 'A sparse atmosphere with low pressure — breathable at lower elevations but dangerously thin at altitude.',
      element_type: 'atmospheric_layer',
      summary: 'A thin atmosphere where the sky shades to black at high elevations',
      fields: {
        breathable: true,
        pressure: '0.4-0.7 atm at lowland level',
        color: 'Deep indigo, stars visible during the day at high altitudes',
        wind_systems: 'Fierce katabatic winds descend from highlands. Dust storms common in dry seasons due to low atmospheric moisture.',
        weather_patterns: 'Rapid temperature swings between day and night. Precipitation is rare and localized. Frost forms year-round at higher elevations.',
      },
    },
    {
      id: 'spore_sea',
      name: 'Spore Sea Atmosphere',
      description: 'An atmosphere so thick with fungal spores that it behaves like a living medium — the air itself is an ecosystem.',
      element_type: 'atmospheric_phenomenon',
      summary: 'An atmosphere saturated with living spores, blurring the line between air and organism',
      fields: {
        breathable: false,
        pressure: '1.2 atm — slightly heavier due to suspended biomass',
        color: 'Golden-green haze with seasonal shifts to deep amber. Visibility rarely exceeds 200 meters.',
        wind_systems: 'Spore currents follow thermal patterns but also respond to biological signals — colonies can redirect airflow by coordinated spore release, creating local weather.',
        weather_patterns: 'Spore storms replace rainstorms. Germination events cause localized temperature spikes as billions of spores activate simultaneously. Clear days are rare and considered ominous.',
      },
    },
    {
      id: 'layered_breathability',
      name: 'Stratified Atmosphere',
      description: 'An atmosphere breathable only at certain altitudes, forcing civilizations to stratify by height.',
      element_type: 'atmospheric_layer',
      summary: 'An atmosphere with breathable and toxic bands, forcing life to cluster at specific altitudes',
      detailed_notes: 'This atmosphere is not uniformly hospitable. Dense, toxic gases — heavier than breathable air — pool in the lowlands, creating a permanent poison layer below approximately 800 meters elevation. Above 4,000 meters, the air thins to the point of uselessness. Between these extremes lies the habitable band: a ribbon of breathable atmosphere where all surface civilization exists. Lowland regions are visible but unreachable without protective equipment, their ruins and resources tantalizingly close but deadly. Highland peaks pierce above the breathable zone into thin, frigid air. Civilizations build along mountain slopes and plateau edges, and elevation is the primary axis of social organization — the higher you live, the thinner but purer your air, and the greater your status.',
      fields: {
        composition: '{"nitrogen": 65, "oxygen": 18, "carbon_dioxide": 8, "sulfur_compounds": 5, "argon": 3, "other": 1}',
        pressure: '1.4 atm at sea level (toxic zone), 0.9 atm in habitable band, 0.3 atm at high altitude',
        breathable: false,
        color: 'Yellowish-brown below the habitable zone, pale blue in the breathable band, deep violet above',
        layers: '[{"name": "Poison Floor", "altitude": "0-800m", "traits": "Dense toxic gases, unbreathable, visibility 50m"}, {"name": "Habitable Band", "altitude": "800-4000m", "traits": "Breathable nitrogen-oxygen mix, temperate"}, {"name": "Thin Crown", "altitude": "4000m+", "traits": "Insufficient oxygen, extreme cold, stars visible by day"}]',
      },
    },
    {
      id: 'singing_winds',
      name: 'Singing Winds',
      description: 'Winds that produce harmonic tones when passing through certain geological or crystalline formations.',
      element_type: 'atmospheric_phenomenon',
      summary: 'Winds that generate audible music as they interact with the landscape',
      detailed_notes: 'Across certain regions, the wind does not merely blow — it sings. The phenomenon occurs where prevailing winds encounter specific geological formations: narrow canyon slots, crystalline rock spires, hollow basalt columns, or forests of resonant stone. The resulting tones range from deep, subsonic rumbles felt in the chest to high, clear notes audible for miles. The "music" follows patterns tied to wind speed, direction, and temperature, creating compositions that shift with the weather and seasons. Some formations produce simple drones; others generate complex harmonics that listeners describe as choral or orchestral. Civilizations in these regions have built their musical traditions around the wind-songs, and some have learned to carve stone to create new instruments for the wind to play. On rare occasions when atmospheric conditions align perfectly, the singing reaches a crescendo audible across entire continents — an event called the Grand Resonance.',
      fields: {
        phenomena: '["harmonic wind tones", "subsonic geological resonance", "Grand Resonance events", "wind-carved tuning formations"]',
        wind_systems: 'Prevailing easterlies drive the primary singing through canyon systems. Seasonal shifts in wind direction activate different formation sets, changing the dominant key. Thermal updrafts create descant harmonics in crystalline spire fields.',
        color: 'Standard blue sky, but during Grand Resonance events, standing waves in the atmosphere create visible ripple patterns — shimmering bands of refracted light that pulse in time with the deepest tones.',
      },
    },
    {
      id: 'luminous_sky',
      name: 'Luminous Night Sky',
      description: 'An atmosphere that glows at night from bioluminescent particles, auroral activity, or suspended mana.',
      element_type: 'atmospheric_phenomenon',
      summary: 'A sky that never truly darkens, glowing with its own soft light after sunset',
      detailed_notes: 'On this world, night is never dark. After sunset, the atmosphere itself begins to glow — a soft, diffuse luminescence that ranges from pale green to deep blue depending on the season and latitude. The light comes from multiple sources: bioluminescent microorganisms that drift in the upper atmosphere, feeding on solar radiation during the day and releasing stored energy as light at night; persistent auroral activity driven by the world\'s unusually strong magnetic field; and, some scholars argue, trace amounts of ambient mana that fluoresce when no longer drowned out by sunlight. The effect is beautiful but has profound consequences. True darkness is unknown — there are no pitch-black nights, and the concept of "darkness" is philosophical rather than literal. Astronomy is limited, as only the brightest stars and celestial bodies are visible through the glow. Nocturnal species have adapted to the perpetual twilight, and the circadian rhythms of all life are shifted compared to dark-night worlds.',
      fields: {
        color: 'Pale green to cerulean blue at night, shifting to violet near the poles. Standard blue during the day, with a faint residual glow visible at dawn and dusk.',
        phenomena: '["atmospheric bioluminescence", "persistent aurora", "mana fluorescence", "lunar halos amplified by luminous particles", "dark spots — rare zones where the glow fails, considered omens"]',
        breathable: true,
      },
    },
    {
      id: 'memory_fog',
      name: 'Memory Fog',
      description: 'A fog that causes confusion and lost memories in those who breathe it.',
      element_type: 'atmospheric_phenomenon',
      summary: 'A sinister fog that erases memories and sows confusion in those who wander into it',
      detailed_notes: 'Memory Fog is an atmospheric phenomenon of unknown origin that manifests as a dense, low-lying mist with a faintly iridescent quality. It appears without meteorological warning, often in valleys, marshlands, or near sites of historical trauma. Those who breathe the fog experience progressive memory loss beginning with recent memories and working backward — first forgetting why they entered the fog, then where they were going, then who they are. Short exposures cause temporary amnesia lasting hours to days. Prolonged exposure results in permanent memory erasure. Victims found wandering in the fog are often in a state of childlike bewilderment, unable to recognize their own companions. The fog seems to have a predatory quality: it thickens around those who panic and thins around those who remain calm, as though feeding on distress. Some scholars theorize it is not a weather phenomenon at all but a colonial organism or a psychic residue of mass-casualty events. Settlements near fog-prone areas maintain bell towers and rope lines to guide the lost home.',
      fields: {
        phenomena: '["progressive memory erasure", "iridescent mist", "psychic disruption", "predatory thickening around panicked victims", "residual amnesia lasting hours to weeks"]',
        breathable: false,
        color: 'Pearlescent white with faint rainbow iridescence, thicker and more opaque than natural fog. Glows faintly from within at night.',
      },
    },
    {
      id: 'crystalline_rain',
      name: 'Crystalline Rain',
      description: 'Precipitation of tiny crystals instead of water drops.',
      element_type: 'atmospheric_phenomenon',
      summary: 'A precipitation event where the sky rains tiny, tinkling crystals instead of water',
      detailed_notes: 'Crystalline Rain occurs in regions where atmospheric mineral content is unusually high — often near volcanic fields, mana-saturated zones, or areas where industrial alchemical processes have altered the air. Instead of water droplets condensing in clouds, dissolved minerals nucleate around atmospheric dust, forming tiny crystals that grow as they fall. The result is a rain of glittering, tinkling fragments that accumulate on the ground like snow but do not melt. The crystals vary in composition depending on local atmospheric chemistry: silicate crystals in volcanic regions produce a harsh, sharp rain that can lacerate exposed skin, while mana-crystallized precipitation in magical zones produces soft, luminous fragments that dissolve slowly and release stored energy. The sound of crystalline rain is distinctive — a continuous, musical tinkling quite unlike the white noise of water rain. Heavy crystal storms can accumulate to dangerous depths, burying roads and collapsing roofs under the weight of mineral deposits.',
      fields: {
        phenomena: '["mineral crystal precipitation", "tinkling rainfall", "accumulation deposits", "variable crystal composition", "laceration hazard in silicate storms"]',
        color: 'Sky turns a pale metallic silver during crystal rain events. The falling crystals catch light, creating a shimmering curtain effect visible for miles.',
        weather_patterns: 'Crystal rain events follow volcanic eruptions or mana surges by 2-5 days, as mineral-laden air masses cool and precipitate. Seasonal patterns emerge in volcanically active regions, with crystal rain most common in cool months when atmospheric temperatures drop below mineral condensation thresholds.',
      },
    },
    {
      id: 'void_layer',
      name: 'Void Ceiling',
      description: 'An altitude where the atmosphere simply stops — a hard ceiling on the world.',
      element_type: 'atmospheric_layer',
      summary: 'An absolute atmospheric boundary — a hard ceiling beyond which there is nothing',
      detailed_notes: 'The Void Ceiling is an atmospheric anomaly with no natural analogue: at a specific altitude, the atmosphere does not thin gradually into space but terminates abruptly. One moment there is breathable air at reasonable pressure; the next, there is absolute void — no air, no pressure, no sound, no heat transfer. The boundary is sharp enough to touch: climbers who reach it describe pressing their hands against an invisible wall of nothing. Objects pushed through the boundary freeze instantly and hang motionless in the void, neither falling nor floating. The Void Ceiling imposes an absolute limit on the world — there is no "space" above it, no stars visible through it (the sky simply goes black), and no way to reach other celestial bodies that may or may not exist above the boundary. The philosophical and theological implications are profound: is the world a sealed container? What lies above the void? Some civilizations accept the ceiling as the edge of reality; others mount desperate expeditions to breach it.',
      fields: {
        layers: '[{"name": "Breathable Zone", "altitude": "0-12km", "traits": "Normal breathable atmosphere with standard weather"}, {"name": "Thinning Band", "altitude": "12-14.8km", "traits": "Rapidly decreasing pressure and temperature"}, {"name": "Void Boundary", "altitude": "14.8km", "traits": "Absolute termination of atmosphere — hard vacuum beyond"}]',
        pressure: '1.0 atm at sea level, decreasing normally until 14.8 km, then instantaneous drop to 0.0 atm',
        breathable: true,
        color: 'Standard blue at low altitudes, darkening to black above 10 km. No gradual transition to space — the sky simply ends in featureless black at the Void Ceiling.',
      },
    },
  ],
  defaultSortField: 'pressure',
};
