import type { DomainConfig } from '../types/domains.js';

export const biomesConfig: DomainConfig = {
  id: 'biomes',
  name: 'Biome',
  namePlural: 'Biomes',
  icon: 'trees',
  color: '#2ecc71',
  description: 'Define the major ecological regions of your world—forests, deserts, tundra, and realms that have no earthly equivalent. Biomes tie together climate, terrain, and the living things that inhabit them.',
  tableName: 'biomes',
  category: 'natural',
  fields: [
    {
      name: 'biome_type',
      label: 'Biome Type',
      type: 'select',
      required: true,
      options: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean', 'cave', 'sky', 'volcanic', 'custom'],
      helpText: 'The broad ecological classification of this biome.',
    },
    {
      name: 'temperature_range',
      label: 'Temperature Range',
      type: 'text',
      placeholder: 'e.g. -10°C to 25°C',
      helpText: 'Typical temperature range experienced in this biome.',
    },
    {
      name: 'moisture_level',
      label: 'Moisture Level',
      type: 'text',
      placeholder: 'e.g. arid, moderate, saturated',
      helpText: 'General moisture availability in this biome.',
    },
    {
      name: 'elevation_range',
      label: 'Elevation Range',
      type: 'text',
      placeholder: 'e.g. 0-500m, 2000-4000m',
      helpText: 'Typical elevation range where this biome occurs.',
    },
    {
      name: 'dominant_terrain',
      label: 'Dominant Terrain',
      type: 'text',
      placeholder: 'e.g. rolling hills, flat plains, rocky crags',
      helpText: 'The primary terrain type that characterizes this biome.',
    },
    {
      name: 'climate_zone_id',
      label: 'Climate Zone',
      type: 'text',
      placeholder: 'ID of the associated climate zone',
      helpText: 'The climate zone that governs this biome\'s weather patterns.',
    },
    {
      name: 'carrying_capacity',
      label: 'Carrying Capacity',
      type: 'text',
      placeholder: 'e.g. high, moderate, low, overstressed',
      helpText: 'The maximum population and activity level this biome can sustainably support.',
    },
  ],
  elementTypes: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean_zone', 'cave_system', 'sky_realm', 'volcanic', 'custom'],
  prompts: [
    'What biomes exist in your world that have no real-world equivalent? A crystal forest, a living desert, floating sky-islands?',
    'How do biome boundaries work—are transitions gradual or sharp? Are there contested borderlands between ecosystems?',
    'What is the most dangerous biome in your world, and what makes it lethal to the unprepared?',
    'How have sentient species altered biomes through agriculture, urbanization, or magical terraforming?',
    'Are there biomes that are expanding or shrinking? What forces drive those changes?',
  ],
  magicPermeation: {
    companionTable: 'biomes_magic_aspects',
    fields: [
      {
        name: 'mana_saturation_level',
        label: 'Mana Saturation Level',
        type: 'textarea',
        helpText: 'How much ambient magical energy permeates this biome.',
      },
      {
        name: 'wild_magic_presence',
        label: 'Wild Magic Present',
        type: 'boolean',
        helpText: 'Whether uncontrolled wild magic manifests in this biome.',
      },
      {
        name: 'wild_magic_description',
        label: 'Wild Magic Description',
        type: 'textarea',
        helpText: 'How wild magic manifests—random effects, chaotic surges, reality warping.',
      },
      {
        name: 'enchanted_biome_features',
        label: 'Enchanted Biome Features',
        type: 'textarea',
        helpText: 'Magical features unique to this biome—glowing flora, floating stones, singing rivers.',
      },
      {
        name: 'dominant_magic_type',
        label: 'Dominant Magic Type',
        type: 'text',
        helpText: 'The school, element, or type of magic most naturally occurring here.',
      },
      {
        name: 'magical_hazards',
        label: 'Magical Hazards',
        type: 'textarea',
        helpText: 'Dangers arising from the magical nature of the biome.',
      },
      {
        name: 'magic_effect_on_biodiversity',
        label: 'Magic Effect on Biodiversity',
        type: 'textarea',
        helpText: 'How ambient magic increases, decreases, or warps species diversity.',
      },
      {
        name: 'biome_magic_source_id',
        label: 'Biome Magic Source',
        type: 'text',
        helpText: 'The primary source of magical energy sustaining this biome.',
      },
      {
        name: 'transition_zone_magic',
        label: 'Transition Zone Magic',
        type: 'textarea',
        helpText: 'Magical phenomena occurring at the boundaries between biomes.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this biome\'s existence and ecology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Are there biomes that exist only because of magic—regions where ambient mana sustains impossible ecosystems?',
      'How does wild magic affect a biome? Do random surges mutate creatures, shift terrain, or create pockets of altered reality?',
      'At the edges where high-magic and low-magic biomes meet, what unusual phenomena occur in the transition zones?',
    ],
  },
  defaultSortField: 'biome_type',
};
