import type { DomainConfig } from '../types/domains.js';

export const biomesConfig: DomainConfig = {
  id: 'biomes',
  name: 'Biome',
  namePlural: 'Biomes',
  icon: 'trees',
  color: '#2ecc71',
  description: 'Define the major ecological regions of your world—forests, deserts, tundra, and realms that have no earthly equivalent. Biomes tie together climate, terrain, and the living things that inhabit them.',
  tableName: 'biomes',
  category: 'natural',
  fields: [
    {
      name: 'biome_type',
      label: 'Biome Type',
      type: 'select',
      required: true,
      options: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean', 'cave', 'sky', 'volcanic', 'custom'],
      helpText: 'The broad ecological classification of this biome.',
    },
    {
      name: 'temperature_range',
      label: 'Temperature Range',
      type: 'text',
      placeholder: 'e.g. -10°C to 25°C',
      helpText: 'Typical temperature range experienced in this biome.',
    },
    {
      name: 'moisture_level',
      label: 'Moisture Level',
      type: 'text',
      placeholder: 'e.g. arid, moderate, saturated',
      helpText: 'General moisture availability in this biome.',
    },
    {
      name: 'elevation_range',
      label: 'Elevation Range',
      type: 'text',
      placeholder: 'e.g. 0-500m, 2000-4000m',
      helpText: 'Typical elevation range where this biome occurs.',
    },
    {
      name: 'dominant_terrain',
      label: 'Dominant Terrain',
      type: 'text',
      placeholder: 'e.g. rolling hills, flat plains, rocky crags',
      helpText: 'The primary terrain type that characterizes this biome.',
    },
    {
      name: 'climate_zone_id',
      label: 'Climate Zone',
      type: 'text',
      placeholder: 'ID of the associated climate zone',
      helpText: 'The climate zone that governs this biome\'s weather patterns.',
    },
    {
      name: 'carrying_capacity',
      label: 'Carrying Capacity',
      type: 'text',
      placeholder: 'e.g. high, moderate, low, overstressed',
      helpText: 'The maximum population and activity level this biome can sustainably support.',
    },
  ],
  elementTypes: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean_zone', 'cave_system', 'sky_realm', 'volcanic', 'custom'],
  prompts: [
    'What biomes exist in your world that have no real-world equivalent? A crystal forest, a living desert, floating sky-islands?',
    'How do biome boundaries work—are transitions gradual or sharp? Are there contested borderlands between ecosystems?',
    'What is the most dangerous biome in your world, and what makes it lethal to the unprepared?',
    'How have sentient species altered biomes through agriculture, urbanization, or magical terraforming?',
    'Are there biomes that are expanding or shrinking? What forces drive those changes?',
  ],
  magicPermeation: {
    companionTable: 'biomes_magic_aspects',
    fields: [
      {
        name: 'mana_saturation_level',
        label: 'Mana Saturation Level',
        type: 'textarea',
        helpText: 'How much ambient magical energy permeates this biome.',
      },
      {
        name: 'wild_magic_presence',
        label: 'Wild Magic Present',
        type: 'boolean',
        helpText: 'Whether uncontrolled wild magic manifests in this biome.',
      },
      {
        name: 'wild_magic_description',
        label: 'Wild Magic Description',
        type: 'textarea',
        helpText: 'How wild magic manifests—random effects, chaotic surges, reality warping.',
      },
      {
        name: 'enchanted_biome_features',
        label: 'Enchanted Biome Features',
        type: 'textarea',
        helpText: 'Magical features unique to this biome—glowing flora, floating stones, singing rivers.',
      },
      {
        name: 'dominant_magic_type',
        label: 'Dominant Magic Type',
        type: 'text',
        helpText: 'The school, element, or type of magic most naturally occurring here.',
      },
      {
        name: 'magical_hazards',
        label: 'Magical Hazards',
        type: 'textarea',
        helpText: 'Dangers arising from the magical nature of the biome.',
      },
      {
        name: 'magic_effect_on_biodiversity',
        label: 'Magic Effect on Biodiversity',
        type: 'textarea',
        helpText: 'How ambient magic increases, decreases, or warps species diversity.',
      },
      {
        name: 'biome_magic_source_id',
        label: 'Biome Magic Source',
        type: 'text',
        helpText: 'The primary source of magical energy sustaining this biome.',
      },
      {
        name: 'transition_zone_magic',
        label: 'Transition Zone Magic',
        type: 'textarea',
        helpText: 'Magical phenomena occurring at the boundaries between biomes.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this biome\'s existence and ecology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Are there biomes that exist only because of magic—regions where ambient mana sustains impossible ecosystems?',
      'How does wild magic affect a biome? Do random surges mutate creatures, shift terrain, or create pockets of altered reality?',
      'At the edges where high-magic and low-magic biomes meet, what unusual phenomena occur in the transition zones?',
    ],
  },
  archetypes: [
    {
      id: 'temperate_forest',
      name: 'Temperate Forest',
      description: 'A deciduous or mixed forest with four seasons, rich soil, and layered canopy structure.',
      element_type: 'forest',
      summary: 'A four-season forest with dense canopy and rich undergrowth',
      fields: {
        biome_type: 'forest',
        temperature_range: '-5°C to 30°C across seasons',
        moisture_level: 'Moderate to high, 750-1500mm annual precipitation',
        elevation_range: '0-2000m',
        dominant_terrain: 'Rolling hills with deep loam soils, crisscrossed by streams',
        carrying_capacity: 'High — dense canopy supports complex food webs',
      },
    },
    {
      id: 'tropical_rainforest',
      name: 'Tropical Rainforest',
      description: 'A hot, humid biome with extraordinary biodiversity and a multi-layered canopy.',
      element_type: 'forest',
      summary: 'A lush equatorial rainforest teeming with life',
      fields: {
        biome_type: 'forest',
        temperature_range: '24°C to 32°C year-round',
        moisture_level: 'Very high, 2000-4000mm annual precipitation',
        elevation_range: '0-1000m',
        dominant_terrain: 'Flat to gently undulating terrain with thin, nutrient-poor soil beneath thick leaf litter',
        carrying_capacity: 'Extremely high — the most species-dense biome',
      },
    },
    {
      id: 'arid_desert_biome',
      name: 'Arid Desert',
      description: 'A harsh, sun-baked biome where life clings to scarce water sources.',
      element_type: 'desert',
      summary: 'A vast desert where survival demands adaptation',
      fields: {
        biome_type: 'desert',
        temperature_range: '-5°C at night to 50°C by day',
        moisture_level: 'Extremely low, under 250mm annual precipitation',
        elevation_range: '0-1500m',
        dominant_terrain: 'Sandy dunes, gravel plains, and rocky outcrops with dry washes',
        carrying_capacity: 'Very low — life concentrated around oases and seasonal water',
      },
    },
    {
      id: 'coral_reef_biome',
      name: 'Coral Reef',
      description: 'A shallow marine biome built by coral organisms, forming an underwater oasis of biodiversity.',
      element_type: 'ocean_zone',
      summary: 'A vibrant coral reef ecosystem in warm, shallow seas',
      fields: {
        biome_type: 'ocean',
        temperature_range: '20°C to 29°C',
        moisture_level: 'N/A (fully submerged)',
        elevation_range: '0 to -60m depth',
        dominant_terrain: 'Calcium carbonate reef structures built by coral polyps, with sandy channels and reef walls',
        carrying_capacity: 'Very high — rivals rainforests in species density',
      },
    },
    {
      id: 'deep_cavern',
      name: 'Deep Cavern Biome',
      description: 'A lightless underground biome sustained by chemosynthesis and geological energy.',
      element_type: 'cave_system',
      summary: 'A sunless underground world with alien-like adapted life',
      fields: {
        biome_type: 'cave',
        temperature_range: '10°C to 18°C (stable year-round)',
        moisture_level: 'High humidity (90-100%) with dripping water and underground pools',
        elevation_range: '-50m to -2000m below surface',
        dominant_terrain: 'Limestone chambers, lava tubes, and subterranean rivers in perpetual darkness',
        carrying_capacity: 'Low — food webs based on chemosynthesis and detritus from the surface',
      },
    },
    {
      id: 'crystalline_waste',
      name: 'Crystalline Waste',
      description: 'A biome of living crystals that grow, compete for light, and shatter to reproduce — geology behaving like biology.',
      element_type: 'custom',
      summary: 'A landscape where mineral formations grow, compete, and evolve like living things',
      fields: {
        biome_type: 'custom',
        temperature_range: '40°C at the crystal surface (absorbed solar heat), -10°C in the shade between formations',
        moisture_level: 'Near zero — crystals absorb all available moisture',
        elevation_range: '500-2000m (crystal spires reach 30m+)',
        dominant_terrain: 'Fields of translucent crystalline spires, some razor-sharp, others smooth and singing in the wind. The ground is a crust of shattered crystal fragments that crunch underfoot.',
        carrying_capacity: 'Extremely low for organic life — a few silicate-eating extremophiles. The crystals themselves may count as a biomass.',
      },
    },
    {
      id: 'inverted_canopy',
      name: 'Inverted Canopy',
      description: 'A forest that grows downward from the ceiling of a vast underground cavern, roots in stone and canopy hanging into the abyss.',
      element_type: 'cave_system',
      summary: 'A subterranean forest dangling from a cavern roof, lit by bioluminescence',
      fields: {
        biome_type: 'cave',
        temperature_range: '14°C to 20°C (geothermally stable)',
        moisture_level: 'Very high — condensation drips constantly from the canopy above into the chasm below',
        elevation_range: 'Cavern ceiling at -200m, canopy tips at -350m, chasm floor at -600m',
        dominant_terrain: 'Massive tree-like organisms grow downward from the cavern roof, their bioluminescent leaves forming a ghostly inverted canopy. Bridges of root and vine connect the hanging groves.',
        carrying_capacity: 'Moderate — rich invertebrate and amphibian fauna adapted to vertical life. Many species are found nowhere else.',
      },
    },
  ],
  defaultSortField: 'biome_type',
};
