import type { DomainConfig } from '../types/domains.js';

export const biomesConfig: DomainConfig = {
  id: 'biomes',
  name: 'Biome',
  namePlural: 'Biomes',
  icon: 'trees',
  color: '#2ecc71',
  description: 'Define the major ecological regions of your world—forests, deserts, tundra, and realms that have no earthly equivalent. Biomes tie together climate, terrain, and the living things that inhabit them.',
  tableName: 'biomes',
  category: 'natural',
  fields: [
    {
      name: 'biome_type',
      label: 'Biome Type',
      type: 'select',
      required: true,
      options: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean', 'cave', 'sky', 'volcanic', 'custom'],
      helpText: 'The broad ecological classification of this biome.',
    },
    {
      name: 'temperature_range',
      label: 'Temperature Range',
      type: 'text',
      placeholder: 'e.g. -10°C to 25°C',
      helpText: 'Typical temperature range experienced in this biome.',
    },
    {
      name: 'moisture_level',
      label: 'Moisture Level',
      type: 'text',
      placeholder: 'e.g. arid, moderate, saturated',
      helpText: 'General moisture availability in this biome.',
    },
    {
      name: 'elevation_range',
      label: 'Elevation Range',
      type: 'text',
      placeholder: 'e.g. 0-500m, 2000-4000m',
      helpText: 'Typical elevation range where this biome occurs.',
    },
    {
      name: 'dominant_terrain',
      label: 'Dominant Terrain',
      type: 'text',
      placeholder: 'e.g. rolling hills, flat plains, rocky crags',
      helpText: 'The primary terrain type that characterizes this biome.',
    },
    {
      name: 'climate_zone_id',
      label: 'Climate Zone',
      type: 'text',
      placeholder: 'ID of the associated climate zone',
      helpText: 'The climate zone that governs this biome\'s weather patterns.',
    },
    {
      name: 'carrying_capacity',
      label: 'Carrying Capacity',
      type: 'text',
      placeholder: 'e.g. high, moderate, low, overstressed',
      helpText: 'The maximum population and activity level this biome can sustainably support.',
    },
  ],
  elementTypes: ['forest', 'desert', 'tundra', 'grassland', 'wetland', 'ocean_zone', 'cave_system', 'sky_realm', 'volcanic', 'custom'],
  elementTypeDescriptions: {
    forest: 'A biome dominated by trees, with a layered canopy structure. Ranges from temperate deciduous to tropical rainforest.',
    desert: 'A biome defined by extreme aridity — hot or cold, sandy or rocky. Life here is specialized for water conservation.',
    tundra: 'A cold, treeless biome with permafrost, short growing seasons, and hardy low vegetation. Found at high latitudes or altitudes.',
    grassland: 'An open biome of grasses and wildflowers with few trees. Supports large herds and is often converted to farmland.',
    wetland: 'A biome where the land is saturated or submerged for part or all of the year. Incredibly biodiverse and ecologically vital.',
    ocean_zone: 'A marine biome defined by depth, light, and temperature — from sunlit shallows to the lightless abyss.',
    cave_system: 'An underground biome sustained by chemosynthesis, drip-water nutrients, or magical energy rather than sunlight.',
    sky_realm: 'A biome that exists in the upper atmosphere — floating islands, cloud forests, or aerial ecosystems with no ground.',
    volcanic: 'A biome shaped by active volcanism — lava fields, geothermal vents, ash plains, and extremophile communities.',
    custom: 'A biome that doesn\'t fit standard categories — something unique to your world.',
  },
  prompts: [
    'What biomes exist in your world that have no real-world equivalent? A crystal forest, a living desert, floating sky-islands?',
    'How do biome boundaries work—are transitions gradual or sharp? Are there contested borderlands between ecosystems?',
    'What is the most dangerous biome in your world, and what makes it lethal to the unprepared?',
    'How have sentient species altered biomes through agriculture, urbanization, or magical terraforming?',
    'Are there biomes that are expanding or shrinking? What forces drive those changes?',
  ],
  magicPermeation: {
    companionTable: 'biomes_magic_aspects',
    fields: [
      {
        name: 'mana_saturation_level',
        label: 'Mana Saturation Level',
        type: 'textarea',
        helpText: 'How much ambient magical energy permeates this biome.',
      },
      {
        name: 'wild_magic_presence',
        label: 'Wild Magic Present',
        type: 'boolean',
        helpText: 'Whether uncontrolled wild magic manifests in this biome.',
      },
      {
        name: 'wild_magic_description',
        label: 'Wild Magic Description',
        type: 'textarea',
        helpText: 'How wild magic manifests—random effects, chaotic surges, reality warping.',
      },
      {
        name: 'enchanted_biome_features',
        label: 'Enchanted Biome Features',
        type: 'textarea',
        helpText: 'Magical features unique to this biome—glowing flora, floating stones, singing rivers.',
      },
      {
        name: 'dominant_magic_type',
        label: 'Dominant Magic Type',
        type: 'text',
        helpText: 'The school, element, or type of magic most naturally occurring here.',
      },
      {
        name: 'magical_hazards',
        label: 'Magical Hazards',
        type: 'textarea',
        helpText: 'Dangers arising from the magical nature of the biome.',
      },
      {
        name: 'magic_effect_on_biodiversity',
        label: 'Magic Effect on Biodiversity',
        type: 'textarea',
        helpText: 'How ambient magic increases, decreases, or warps species diversity.',
      },
      {
        name: 'biome_magic_source_id',
        label: 'Biome Magic Source',
        type: 'text',
        helpText: 'The primary source of magical energy sustaining this biome.',
      },
      {
        name: 'transition_zone_magic',
        label: 'Transition Zone Magic',
        type: 'textarea',
        helpText: 'Magical phenomena occurring at the boundaries between biomes.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this biome\'s existence and ecology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Are there biomes that exist only because of magic—regions where ambient mana sustains impossible ecosystems?',
      'How does wild magic affect a biome? Do random surges mutate creatures, shift terrain, or create pockets of altered reality?',
      'At the edges where high-magic and low-magic biomes meet, what unusual phenomena occur in the transition zones?',
    ],
  },
  archetypes: [
    {
      id: 'temperate_forest',
      name: 'Temperate Forest',
      description: 'A deciduous or mixed forest with four seasons, rich soil, and layered canopy structure.',
      element_type: 'forest',
      summary: 'A four-season forest with dense canopy and rich undergrowth',
      fields: {
        biome_type: 'forest',
        temperature_range: '-5°C to 30°C across seasons',
        moisture_level: 'Moderate to high, 750-1500mm annual precipitation',
        elevation_range: '0-2000m',
        dominant_terrain: 'Rolling hills with deep loam soils, crisscrossed by streams',
        carrying_capacity: 'High — dense canopy supports complex food webs',
      },
    },
    {
      id: 'tropical_rainforest',
      name: 'Tropical Rainforest',
      description: 'A hot, humid biome with extraordinary biodiversity and a multi-layered canopy.',
      element_type: 'forest',
      summary: 'A lush equatorial rainforest teeming with life',
      fields: {
        biome_type: 'forest',
        temperature_range: '24°C to 32°C year-round',
        moisture_level: 'Very high, 2000-4000mm annual precipitation',
        elevation_range: '0-1000m',
        dominant_terrain: 'Flat to gently undulating terrain with thin, nutrient-poor soil beneath thick leaf litter',
        carrying_capacity: 'Extremely high — the most species-dense biome',
      },
    },
    {
      id: 'arid_desert_biome',
      name: 'Arid Desert',
      description: 'A harsh, sun-baked biome where life clings to scarce water sources.',
      element_type: 'desert',
      summary: 'A vast desert where survival demands adaptation',
      fields: {
        biome_type: 'desert',
        temperature_range: '-5°C at night to 50°C by day',
        moisture_level: 'Extremely low, under 250mm annual precipitation',
        elevation_range: '0-1500m',
        dominant_terrain: 'Sandy dunes, gravel plains, and rocky outcrops with dry washes',
        carrying_capacity: 'Very low — life concentrated around oases and seasonal water',
      },
    },
    {
      id: 'coral_reef_biome',
      name: 'Coral Reef',
      description: 'A shallow marine biome built by coral organisms, forming an underwater oasis of biodiversity.',
      element_type: 'ocean_zone',
      summary: 'A vibrant coral reef ecosystem in warm, shallow seas',
      fields: {
        biome_type: 'ocean',
        temperature_range: '20°C to 29°C',
        moisture_level: 'N/A (fully submerged)',
        elevation_range: '0 to -60m depth',
        dominant_terrain: 'Calcium carbonate reef structures built by coral polyps, with sandy channels and reef walls',
        carrying_capacity: 'Very high — rivals rainforests in species density',
      },
    },
    {
      id: 'deep_cavern',
      name: 'Deep Cavern Biome',
      description: 'A lightless underground biome sustained by chemosynthesis and geological energy.',
      element_type: 'cave_system',
      summary: 'A sunless underground world with alien-like adapted life',
      fields: {
        biome_type: 'cave',
        temperature_range: '10°C to 18°C (stable year-round)',
        moisture_level: 'High humidity (90-100%) with dripping water and underground pools',
        elevation_range: '-50m to -2000m below surface',
        dominant_terrain: 'Limestone chambers, lava tubes, and subterranean rivers in perpetual darkness',
        carrying_capacity: 'Low — food webs based on chemosynthesis and detritus from the surface',
      },
    },
    {
      id: 'crystalline_waste',
      name: 'Crystalline Waste',
      description: 'A biome of living crystals that grow, compete for light, and shatter to reproduce — geology behaving like biology.',
      element_type: 'custom',
      summary: 'A landscape where mineral formations grow, compete, and evolve like living things',
      fields: {
        biome_type: 'custom',
        temperature_range: '40°C at the crystal surface (absorbed solar heat), -10°C in the shade between formations',
        moisture_level: 'Near zero — crystals absorb all available moisture',
        elevation_range: '500-2000m (crystal spires reach 30m+)',
        dominant_terrain: 'Fields of translucent crystalline spires, some razor-sharp, others smooth and singing in the wind. The ground is a crust of shattered crystal fragments that crunch underfoot.',
        carrying_capacity: 'Extremely low for organic life — a few silicate-eating extremophiles. The crystals themselves may count as a biomass.',
      },
    },
    {
      id: 'inverted_canopy',
      name: 'Inverted Canopy',
      description: 'A forest that grows downward from the ceiling of a vast underground cavern, roots in stone and canopy hanging into the abyss.',
      element_type: 'cave_system',
      summary: 'A subterranean forest dangling from a cavern roof, lit by bioluminescence',
      fields: {
        biome_type: 'cave',
        temperature_range: '14°C to 20°C (geothermally stable)',
        moisture_level: 'Very high — condensation drips constantly from the canopy above into the chasm below',
        elevation_range: 'Cavern ceiling at -200m, canopy tips at -350m, chasm floor at -600m',
        dominant_terrain: 'Massive tree-like organisms grow downward from the cavern roof, their bioluminescent leaves forming a ghostly inverted canopy. Bridges of root and vine connect the hanging groves.',
        carrying_capacity: 'Moderate — rich invertebrate and amphibian fauna adapted to vertical life. Many species are found nowhere else.',
      },
    },
    {
      id: 'fungal_jungle',
      name: 'Fungal Jungle',
      description: 'A biome dominated by giant fungi instead of trees — towering mushrooms, bioluminescent caps, and spore-thick air.',
      element_type: 'forest',
      summary: 'A dense jungle of colossal fungi where spore clouds replace canopy shade',
      detailed_notes: 'The fungal jungle is a forest without a single tree. Instead, towering mushroom stalks rise 30 to 60 meters, their broad caps interlocking to form a canopy that blocks most light. Beneath the caps, bioluminescent gills cast the understory in shifting blues and greens. The air is thick with spores — visible as a permanent haze that gives the jungle a dreamlike quality. The ground is a spongy mat of mycelium that connects every organism in a vast underground network, allowing the jungle to function as a single superorganism. Nutrients, chemical signals, and even rudimentary information pass through the mycelial web. Fauna has adapted to the fungal diet: insects with chitin-dissolving enzymes, mammals that graze on mushroom caps, and predators that use the spore haze for ambush cover. The air is technically breathable but irritates lungs over prolonged exposure, and many visitors develop "spore cough" — a persistent condition that clears only after leaving the biome.',
      fields: {
        biome_type: 'forest',
        temperature_range: '18°C to 28°C — stable due to the insulating spore canopy',
        moisture_level: 'Very high — 90-100% humidity, with condensation dripping constantly from cap undersides',
        elevation_range: '0-800m',
        dominant_terrain: 'Spongy mycelial floor punctuated by massive mushroom trunks. Bracket fungi form natural shelves and platforms at various heights. Pools of collected condensation dot the floor.',
        carrying_capacity: 'High — the mycelial network recycles nutrients with extreme efficiency, supporting dense populations of adapted fauna',
      },
    },
    {
      id: 'salt_flat_biome',
      name: 'Salt Flat',
      description: 'A vast, blinding expanse of crystallized salt — beautiful, hostile, and hiding life in the crust below.',
      element_type: 'desert',
      summary: 'An endless plain of crystallized salt, blindingly white and deceptively alive beneath the crust',
      detailed_notes: 'The salt flat stretches to the horizon in every direction — a perfectly level plane of white crystal that reflects the sky so completely it appears to merge with it. The effect is disorienting: without landmarks, travelers lose all sense of distance and direction. Mirages are constant and vivid. The surface is a hard crust of halite and gypsum crystals, some forming geometric patterns of stunning beauty. Beneath this crust, however, lies a thin but persistent brine layer — and within it, extremophile organisms thrive. Brine shrimp, salt-tolerant algae, and halophilic bacteria form a hidden ecosystem invisible from the surface. During rare rain events, the flat transforms into a shallow mirror lake centimeters deep, creating the famous "sky mirror" effect where the ground perfectly reflects clouds and stars. These brief wet periods trigger explosive reproduction in the subsurface organisms, staining patches of the flat pink, orange, and red before the water evaporates and the white silence returns.',
      fields: {
        biome_type: 'desert',
        temperature_range: '-8°C at night to 52°C by day — the white surface reflects heat upward but the ground stores it',
        moisture_level: 'Extremely low on the surface, moderate in subsurface brine layer',
        elevation_range: '1200-1300m (remarkably flat, less than 1m variation over hundreds of km)',
        dominant_terrain: 'Perfectly flat crystalline salt crust with polygonal fracture patterns. Occasional salt pillars where mineral-laden water has evaporated over centuries.',
        carrying_capacity: 'Near zero on the surface — moderate in the subsurface brine ecosystem. Migratory birds use the flat as a waypoint during rare wet periods.',
      },
    },
    {
      id: 'floating_reef',
      name: 'Floating Sky Reef',
      description: 'A biome of organisms growing on airborne debris and floating rock — a reef in the clouds.',
      element_type: 'sky_realm',
      summary: 'A living reef suspended in the atmosphere, built by organisms that never touch the ground',
      detailed_notes: 'High in the atmosphere, where updrafts from volcanic fields meet moisture-laden trade winds, a reef grows in the sky. It began with floating mineral fragments — pumice, levitite-laced rock, volcanic glass — caught in a stable atmospheric vortex. Over millennia, airborne organisms colonized these fragments: lichens first, then mosses, then increasingly complex life forms that evolved to never need solid ground. Today the sky reef is a sprawling three-dimensional ecosystem of interconnected floating masses, some as small as a fist and others the size of city blocks. Vine-like organisms bridge the gaps between fragments, and the reef\'s own accumulated biomass generates updrafts that help sustain its altitude. Birds nest in its crevices, insects swarm around its flowering surfaces, and at least one species of small mammal has been observed living its entire life cycle within the reef, leaping between fragments with adapted gliding membranes. The reef migrates slowly with the seasons, following wind patterns, and the shadow it casts on the ground below moves like a vast, living cloud.',
      fields: {
        biome_type: 'sky',
        temperature_range: '-5°C to 15°C — cooler than the surface due to altitude',
        moisture_level: 'High — the reef captures and retains cloud moisture, creating its own micro-rain cycle',
        elevation_range: '3000-5000m above the surface, shifting with atmospheric conditions',
        dominant_terrain: 'Interconnected floating rock fragments covered in layered growth — lichen crusts, moss beds, aerial root networks, and flowering vines. Open sky between major reef masses.',
        carrying_capacity: 'Moderate — limited by available surface area and nutrient input from atmospheric dust and captured precipitation',
      },
    },
    {
      id: 'bone_forest',
      name: 'Bone Forest',
      description: 'Trees made of calcite growing from fossil-rich soil. White, brittle, and eerily beautiful.',
      element_type: 'forest',
      summary: 'A forest of pale, mineral trees growing from ancient bone deposits — hauntingly beautiful and eerily silent',
      detailed_notes: 'The Bone Forest is a biome where the boundary between geology and biology has blurred beyond recognition. The "trees" are columnar formations of living calcite — mineral structures that grow from the fossil-rich substrate by drawing dissolved calcium carbonate upward through capillary action and precipitating it into trunk-like pillars and branch-like formations. They are not alive in the biological sense, yet they grow, respond to moisture, and even "reproduce" by shedding mineral fragments that seed new formations. The forest is blindingly white, the calcite reflecting sunlight with a bone-like pallor. The formations are brittle — a strong wind can snap smaller "branches," sending them crashing to the ground with a sound like breaking porcelain. The forest floor is a carpet of calcite fragments, and walking through it produces a continuous crunching. Despite the lack of biological trees, an ecosystem has developed: lichens colonize the calcite surfaces, insects bore into softer mineral deposits, and small mammals shelter in the hollow cores of older formations. The silence is notable — with no leaves to rustle and no wood to creak, the Bone Forest is one of the quietest places on the planet.',
      fields: {
        biome_type: 'forest',
        temperature_range: '5°C to 35°C — the white calcite reflects heat, keeping the interior cooler than surrounding terrain',
        moisture_level: 'Low to moderate — the calcite formations draw moisture from the soil, leaving the air relatively dry',
        elevation_range: '200-800m',
        terrain_description: 'Dense clusters of white calcite columns ranging from 2 to 30 meters tall, with branching mineral formations creating a canopy-like structure. The ground is a thick layer of calcite fragments over fossil-rich sediment.',
      },
    },
    {
      id: 'mirror_lake_biome',
      name: 'Mirror Lake Biome',
      description: 'A biome around a lake so reflective it perfectly doubles the sky — disorienting and sacred.',
      element_type: 'wetland',
      summary: 'A disorienting wetland surrounding a perfectly reflective lake that doubles the sky',
      detailed_notes: 'The Mirror Lake Biome is centered on a body of water so still and so reflective that it creates a perfect duplicate of the sky on its surface. The effect is profoundly disorienting: at the lake\'s edge, it becomes impossible to distinguish up from down, and the horizon dissolves into a seamless sphere of sky. Birds have been observed diving into the lake\'s surface, mistaking it for open air. The reflectivity is caused by an unusual combination of factors: the lake is extraordinarily shallow (rarely exceeding one meter), its bed is composed of a white clay that acts as a perfect backing, and a film of mineral oils from surrounding geological seeps creates a surface tension that eliminates all ripples. The surrounding wetland has adapted to the lake\'s presence — vegetation grows low and outward rather than upward, as though the biome itself is trying to minimize its disruption of the mirror effect. The biome is sacred to many cultures, who see the doubled sky as a gateway to a spirit realm or a reflection of the divine.',
      fields: {
        biome_type: 'wetland',
        temperature_range: '8°C to 28°C — moderated by the lake\'s thermal mass',
        moisture_level: 'High — saturated ground surrounds the lake, supporting dense low vegetation',
        elevation_range: '50-200m (the lake occupies a broad, shallow depression)',
        dominant_terrain: 'A vast, shallow lake surrounded by concentric rings of low marsh vegetation, mineral mudflats, and sedge meadows. The transition from water to land is gradual and ambiguous.',
        carrying_capacity: 'Moderate — rich in waterbirds, amphibians, and aquatic invertebrates, but the shallow water limits fish diversity',
      },
    },
    {
      id: 'rust_waste',
      name: 'Rust Waste',
      description: 'Oxidized metal landscape, remnant of ancient industrial civilization.',
      element_type: 'desert',
      summary: 'A barren expanse of oxidized metal — the corroded remains of a fallen industrial civilization',
      detailed_notes: 'The Rust Waste is what remains when a technologically advanced civilization collapses and its infrastructure decays over millennia. The landscape is dominated by oxidized metal: the ground is a crust of iron oxide giving everything a deep red-orange hue, punctuated by the skeletal remains of structures too massive to fully corrode — collapsed frameworks, half-buried machinery, and columns of an unidentifiable alloy that still resist the rust. The soil is toxic with heavy metals, and groundwater is contaminated with dissolved iron, copper, and more exotic industrial byproducts. Despite the toxicity, life has adapted. Rust-tolerant lichens and iron-metabolizing bacteria form the base of a sparse food chain, and a few hardy arthropod species have evolved to extract nutrients from the corroded metal. The Waste serves as a cautionary landscape — a reminder of what unchecked industry leaves behind. Scavengers and archaeologists pick through the ruins seeking salvageable technology, but the toxic environment limits expeditions to days at most.',
      fields: {
        biome_type: 'desert',
        temperature_range: '-10°C to 55°C — the dark metal surfaces absorb and radiate heat intensely',
        moisture_level: 'Extremely low — toxic runoff has poisoned most natural water sources',
        elevation_range: '100-600m (relatively flat, with occasional mounds of collapsed superstructures)',
        dominant_terrain: 'Flat expanses of iron oxide crust broken by jutting remnants of ancient metal structures. Shallow pools of rust-colored, acidic water collect in depressions. Wind-sculpted dunes of metal flakes accumulate against the larger ruins.',
        carrying_capacity: 'Very low — heavy metal toxicity limits all biological activity. Only extremophile organisms persist.',
      },
    },
  ],
  defaultSortField: 'biome_type',
};
