import type { DomainConfig } from '../types/domains.js';

export const civilizationsConfig: DomainConfig = {
  id: 'civilizations',
  name: 'Civilization',
  namePlural: 'Civilizations',
  icon: 'landmark',
  color: '#8e44ad',
  description: 'Define the organized societies of your world—their governments, economies, militaries, and territorial ambitions. Civilizations are the political and institutional frameworks within which cultures, technologies, and conflicts emerge.',
  tableName: 'civilizations',
  category: 'sentient',
  fields: [
    {
      name: 'government_type',
      label: 'Government Type',
      type: 'select',
      required: true,
      options: ['monarchy', 'republic', 'democracy', 'oligarchy', 'theocracy', 'magocracy', 'military_junta', 'tribal_council', 'feudal', 'imperial', 'anarchist', 'hive_mind', 'custom'],
      helpText: 'The primary form of governance in this civilization.',
    },
    {
      name: 'tech_level',
      label: 'Technology Level',
      type: 'select',
      required: true,
      options: ['stone_age', 'bronze_age', 'iron_age', 'medieval', 'renaissance', 'industrial', 'modern', 'post_modern', 'magitech', 'custom'],
      helpText: 'The general level of technological development.',
    },
    {
      name: 'magic_integration',
      label: 'Magic Integration',
      type: 'select',
      options: ['none', 'forbidden', 'rare_elite', 'regulated', 'widespread', 'fundamental', 'declining'],
      helpText: 'How deeply magic is integrated into the functioning of this civilization.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 5 million, several hundred thousand, unknown',
      helpText: 'Current estimated total population.',
    },
    {
      name: 'territory_description',
      label: 'Territory Description',
      type: 'textarea',
      placeholder: 'Describe the lands claimed or controlled by this civilization...',
      helpText: 'Geographic extent, borders, and key territorial features.',
    },
    {
      name: 'founded_era_id',
      label: 'Founded Era',
      type: 'text',
      placeholder: 'ID of the founding era or event',
      helpText: 'The historical era or event in which this civilization was founded.',
    },
    {
      name: 'species_id',
      label: 'Primary Species',
      type: 'text',
      placeholder: 'ID of the dominant or founding species',
      helpText: 'The sentient species that founded or primarily comprises this civilization.',
    },
    {
      name: 'economic_system',
      label: 'Economic System',
      type: 'select',
      options: ['barter', 'mercantile', 'feudal', 'capitalist', 'socialist', 'command', 'gift_economy', 'mana_based', 'mixed', 'custom'],
      helpText: 'The dominant economic model.',
    },
    {
      name: 'military_strength',
      label: 'Military Strength',
      type: 'select',
      options: ['none', 'militia_only', 'moderate', 'strong', 'dominant', 'legendary'],
      helpText: 'Overall military power relative to neighboring civilizations.',
    },
    {
      name: 'capital_id',
      label: 'Capital',
      type: 'text',
      placeholder: 'ID of the capital city or seat of power',
      helpText: 'The geographic place serving as the capital or seat of government.',
    },
    {
      name: 'growth_status',
      label: 'Growth Status',
      type: 'select',
      options: ['nascent', 'growing', 'stable', 'stagnant', 'declining', 'collapsed', 'resurgent'],
      helpText: 'Whether this civilization is expanding, stable, or in decline.',
    },
    {
      name: 'diplomatic_stance',
      label: 'Diplomatic Stance',
      type: 'select',
      options: ['expansionist', 'aggressive', 'defensive', 'isolationist', 'mercantile', 'diplomatic', 'tributary', 'hegemonic'],
      helpText: 'The general approach this civilization takes toward foreign relations.',
    },
  ],
  elementTypes: ['empire', 'kingdom', 'republic', 'tribal_confederation', 'city_state', 'nomadic', 'theocracy', 'magocracy', 'custom'],
  elementTypeDescriptions: {
    empire: 'A vast, multi-ethnic state ruled by a central authority — an emperor, council, or dynasty. Expands through conquest or diplomacy.',
    kingdom: 'A state ruled by a hereditary monarch, with a nobility, feudal obligations, and defined territorial borders.',
    republic: 'A state governed by elected representatives or appointed officials rather than a monarch. Power derives from civic participation.',
    tribal_confederation: 'A loose alliance of clans or tribes united by kinship, treaty, or a shared threat. Flexible but potentially fragile.',
    city_state: 'A single sovereign city and its surrounding territory. Self-governing, often wealthy, and fiercely independent.',
    nomadic: 'A mobile civilization that follows herds, trade routes, or seasonal resources rather than settling permanently.',
    theocracy: 'A state ruled by religious authority — priests, prophets, or divine mandate. Faith and law are one.',
    magocracy: 'A state ruled by magic users — wizards, sorcerers, or those with innate magical talent hold political power.',
    custom: 'A civilization type that doesn\'t fit standard categories — something unique to your world.',
  },
  prompts: [
    'What tensions exist between the ruling class and the governed? Is power held by birthright, magical talent, wealth, or popular mandate?',
    'How does this civilization interact with its neighbors—through diplomacy, trade, conquest, or isolation?',
    'What are the civilization\'s greatest achievements and deepest failures? What do they celebrate and what do they try to forget?',
    'How does the economic system distribute resources? Are there stark inequalities, and if so, what justifies them in the eyes of the powerful?',
    'What existential threats does this civilization face—internal decay, external invasion, resource depletion, or magical catastrophe?',
  ],
  magicPermeation: {
    companionTable: 'civilizations_magic_aspects',
    fields: [
      {
        name: 'magic_governance',
        label: 'Magic Governance',
        type: 'textarea',
        helpText: 'How the government regulates, controls, or promotes the use of magic—licensing, academies, prohibitions.',
      },
      {
        name: 'magical_economy',
        label: 'Magical Economy',
        type: 'textarea',
        helpText: 'The role of magic in commerce, industry, and wealth generation—enchanted goods, mana trade, spell services.',
      },
      {
        name: 'spell_infrastructure',
        label: 'Spell Infrastructure',
        type: 'textarea',
        helpText: 'Magical infrastructure supporting the civilization—warded walls, teleportation networks, scrying systems, weather control.',
      },
      {
        name: 'magical_military',
        label: 'Magical Military',
        type: 'textarea',
        helpText: 'Military applications of magic—battle mages, enchanted weapons, magical siege engines, ward defenses.',
      },
      {
        name: 'magical_education',
        label: 'Magical Education',
        type: 'textarea',
        helpText: 'How magic is taught—academies, apprenticeships, temples, state programs, or suppressed entirely.',
      },
      {
        name: 'magic_social_hierarchy',
        label: 'Magic & Social Hierarchy',
        type: 'textarea',
        helpText: 'How magical ability affects social standing—are mages revered, feared, enslaved, or treated as ordinary citizens?',
      },
      {
        name: 'magical_law_enforcement',
        label: 'Magical Law Enforcement',
        type: 'textarea',
        helpText: 'How magic is used to enforce laws or how magical crimes are policed and punished.',
      },
      {
        name: 'magical_healthcare',
        label: 'Magical Healthcare',
        type: 'textarea',
        helpText: 'The role of healing magic in public health—who has access, how is it regulated, what are its limits?',
      },
      {
        name: 'magic_tech_relationship',
        label: 'Magic-Technology Relationship',
        type: 'textarea',
        helpText: 'How magic and mundane technology interact—do they complement, compete, or merge into magitech?',
      },
      {
        name: 'attitude_toward_magic',
        label: 'Attitude Toward Magic',
        type: 'select',
        options: ['reverent', 'pragmatic', 'fearful', 'hostile', 'indifferent', 'divided', 'dependent'],
        helpText: 'The prevailing cultural attitude toward magic within this civilization.',
      },
      {
        name: 'magitech_era_id',
        label: 'Magitech Era',
        type: 'text',
        placeholder: 'ID of the era when magitech emerged',
        helpText: 'The historical period when this civilization began integrating magic and technology.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the identity and functioning of this civilization.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Does this civilization regulate magic like a weapon, a profession, or a natural right? What happens to those who practice forbidden magic?',
      'How has the availability (or scarcity) of magic shaped the civilization\'s architecture, warfare, and daily life?',
      'Is there a tension between magical elites and the non-magical majority? Has this ever sparked revolutions or reforms?',
    ],
  },
  archetypes: [
    {
      id: 'feudal_kingdom',
      name: 'Feudal Kingdom',
      description: 'A medieval kingdom ruled by a hereditary monarch, with lords, vassals, and a peasant majority.',
      element_type: 'kingdom',
      summary: 'A hereditary kingdom held together by oaths of fealty and tradition',
      fields: {
        government_type: 'feudal',
        tech_level: 'medieval',
        magic_integration: 'rare_elite',
        economic_system: 'feudal',
        military_strength: 'moderate',
        growth_status: 'stable',
        diplomatic_stance: 'defensive',
        territory_description: 'A contiguous realm centered on a fertile river valley, with outlying provinces held by vassal lords. Borders defined by natural features — mountains, rivers, and dense forests.',
      },
    },
    {
      id: 'trading_republic',
      name: 'Trading Republic',
      description: 'A wealthy merchant republic where political power follows economic power.',
      element_type: 'republic',
      summary: 'A prosperous republic where merchant princes wield political power',
      fields: {
        government_type: 'oligarchy',
        tech_level: 'renaissance',
        magic_integration: 'regulated',
        economic_system: 'mercantile',
        military_strength: 'moderate',
        growth_status: 'growing',
        diplomatic_stance: 'mercantile',
        territory_description: 'A coastal city-state with a modest hinterland but extensive overseas trading posts, colonies, and treaty ports. Power projects outward via its merchant fleet.',
      },
    },
    {
      id: 'nomadic_confederation',
      name: 'Nomadic Confederation',
      description: 'A loose alliance of mobile clans united under a great leader, following herds and seasonal routes.',
      element_type: 'nomadic',
      summary: 'A powerful horse-borne confederation of steppe clans',
      fields: {
        government_type: 'tribal_council',
        tech_level: 'iron_age',
        magic_integration: 'none',
        economic_system: 'barter',
        military_strength: 'strong',
        growth_status: 'growing',
        diplomatic_stance: 'expansionist',
        territory_description: 'No fixed borders — the confederation claims vast open steppes and grasslands through which its clans roam. Seasonal camps at traditional gathering sites.',
      },
    },
    {
      id: 'theocratic_empire',
      name: 'Theocratic Empire',
      description: 'A vast empire ruled by a divine sovereign or priestly caste, where faith and law are one.',
      element_type: 'empire',
      summary: 'A divine empire where the priesthood rules in the name of the gods',
      fields: {
        government_type: 'theocracy',
        tech_level: 'iron_age',
        magic_integration: 'fundamental',
        economic_system: 'command',
        military_strength: 'dominant',
        growth_status: 'stable',
        diplomatic_stance: 'hegemonic',
        territory_description: 'A sprawling empire radiating from a sacred capital. Temple complexes serve as administrative centers in each province. Holy roads connect the faithful.',
      },
    },
    {
      id: 'isolated_city_state',
      name: 'Isolated City-State',
      description: 'A single fortified city governing itself independently, relying on strong walls and clever diplomacy.',
      element_type: 'city_state',
      summary: 'A self-governing city surviving by wit among greater powers',
      fields: {
        government_type: 'republic',
        tech_level: 'medieval',
        magic_integration: 'regulated',
        economic_system: 'mixed',
        military_strength: 'militia_only',
        growth_status: 'stable',
        diplomatic_stance: 'isolationist',
        territory_description: 'The city and its immediate farmlands within a day\'s ride. Surrounded by larger, more powerful neighbors, surviving through neutrality and strategic value.',
      },
    },
    {
      id: 'necrocracy',
      name: 'Undead Bureaucracy',
      description: 'A civilization where the dead continue to govern — ancestor spirits or preserved liches hold every office, and the living are merely the junior workforce.',
      element_type: 'custom',
      summary: 'A realm where death is a promotion — the undead govern, and the living serve their time',
      fields: {
        government_type: 'oligarchy',
        tech_level: 'magitech',
        magic_integration: 'fundamental',
        economic_system: 'command',
        military_strength: 'dominant',
        growth_status: 'stagnant',
        diplomatic_stance: 'isolationist',
        territory_description: 'A grey, orderly realm where cities are immaculately maintained by tireless undead labor. The living occupy the sunlit districts; the dead govern from the underground administrative complexes. Borders are warded against uninvited life and death alike.',
      },
    },
    {
      id: 'underground_empire',
      name: 'Underground Empire',
      description: 'A civilization built entirely beneath the surface. Deep cities, fungal agriculture, bioluminescent lighting, no sky.',
      element_type: 'empire',
      summary: 'A vast subterranean empire that has never seen the sun and does not miss it',
      detailed_notes: 'The Underground Empire has existed beneath the surface for so long that its people consider the sky a myth — or worse, a dangerous void. Their cities are carved from living rock, illuminated by cultivated bioluminescent fungi and mineral phosphorescence. Agriculture is based on fungal farms, subterranean lakes stocked with blind fish, and insect husbandry. Water comes from underground rivers; heat from geothermal vents. The civilization is vertically stratified: the deepest levels, closest to geothermal heat, are the domain of the powerful. The upper tunnels, closer to the dangerous surface, are for the poor and the military. Expansion means digging — and the empire\'s engineers and miners are the most honored profession, equivalent to admirals in a surface navy.',
      fields: {
        government_type: 'imperial',
        tech_level: 'iron_age',
        magic_integration: 'regulated',
        economic_system: 'feudal',
        military_strength: 'strong',
        population_size: 'Several million spread across hundreds of interconnected cavern-cities',
        growth_status: 'growing',
        diplomatic_stance: 'isolationist',
        territory_description: 'A vast network of interconnected caverns, tunnels, and excavated chambers spanning hundreds of kilometers beneath a mountain range. The deepest cities reach several kilometers below the surface. Surface access points are heavily fortified and rarely used.',
      },
    },
    {
      id: 'pirate_republic',
      name: 'Pirate Republic',
      description: 'A lawless maritime state governed by codes of conduct among equals. Freedom above all, but survival requires cooperation.',
      element_type: 'republic',
      summary: 'A chaotic maritime democracy where freedom is law and every captain has a vote',
      detailed_notes: 'The Pirate Republic began as a haven for outcasts — mutineers, escaped slaves, exiled nobles, and wanted criminals who discovered that the only law they could agree on was the right to be free. Over generations, this anti-civilization developed its own complex governance: a council of captains where every ship commander has an equal vote, articles of conduct that protect crew rights, and a shared defense pact against naval powers that would destroy them. The Republic has no fixed capital — it moves with its fleet, though certain harbors and hidden coves serve as traditional gathering points. Its economy runs on piracy, smuggling, salvage, and increasingly legitimate trade as the Republic gains grudging recognition from its neighbors. Internal politics are volatile: alliances shift with the tides, and a charismatic captain can reshape policy overnight.',
      fields: {
        government_type: 'republic',
        tech_level: 'renaissance',
        magic_integration: 'rare_elite',
        economic_system: 'mixed',
        military_strength: 'moderate',
        population_size: 'Fifty to a hundred thousand, fluctuating with the season and the latest war',
        growth_status: 'growing',
        diplomatic_stance: 'aggressive',
        territory_description: 'No contiguous territory — the Republic controls a shifting constellation of island harbors, hidden coves, and floating anchorages. Its true territory is the open sea itself, where its fleet is sovereign.',
      },
    },
    {
      id: 'living_city_civ',
      name: 'Living City Civilization',
      description: 'A civilization that IS its city — the settlement is a single vast organism its people live within.',
      element_type: 'custom',
      summary: 'A people who dwell inside their city because their city is alive — a symbiosis of organism and society',
      detailed_notes: 'The Living City is not a metaphor. The city is a single colossal organism — part coral, part tree, part something with no natural analog — and its people live inside it like beneficial bacteria in a gut. The city grows walls, floors, and roofs from its own tissue. It circulates fresh air through breathing pores and clean water through vascular channels. It heals damage, seals breaches, and slowly expands to accommodate population growth. In return, the inhabitants feed it, tend to parasites and infections, and defend it from external threats. The relationship is deeply symbiotic: the people cannot survive without the city\'s shelter and infrastructure, and the city cannot survive without the people\'s care and nourishment. Governance is shaped by this relationship — the city\'s health is the supreme political concern, and those who can communicate with the organism (sensing its needs through vibrations in its walls) hold enormous influence.',
      fields: {
        government_type: 'custom',
        tech_level: 'custom',
        magic_integration: 'fundamental',
        economic_system: 'gift_economy',
        military_strength: 'strong',
        population_size: 'Hundreds of thousands living within the organism, which spans several square kilometers',
        growth_status: 'stable',
        diplomatic_stance: 'defensive',
        territory_description: 'The civilization occupies exactly the area of the living organism — a single vast biological structure several kilometers across. There is no territory beyond the city-organism itself. External land is unclaimed and irrelevant; the city is their world.',
      },
    },
    {
      id: 'merchant_armada',
      name: 'Merchant Armada',
      description: 'A civilization of perpetually moving ships with no homeland, only fleet.',
      element_type: 'nomadic',
      summary: 'A floating nation of ships that has never known land — the sea is their country',
      detailed_notes: 'The Merchant Armada is a civilization without territory in the conventional sense. Hundreds of ships — from massive cargo galleons to nimble scout vessels — form a perpetually moving fleet that trades between coastal civilizations. The fleet is their city: ships are lashed together in shifting configurations to form floating marketplaces, shipboard farms grow food in salt-resistant planters, and children are born, raised, and buried at sea. Political power belongs to the Fleet Admiral, elected by a council of ship captains, but real influence follows trade wealth. The Armada has no standing army — every merchant is armed, and the fleet can concentrate its firepower with devastating effect. Coastal nations tolerate and need them, as the Armada controls trade routes no single nation can dominate alone.',
      fields: {
        government_type: 'oligarchy',
        tech_level: 'renaissance',
        magic_integration: 'regulated',
        economic_system: 'mercantile',
        military_strength: 'moderate',
        population_size: 'Approximately 200,000 souls spread across a fleet of several hundred vessels',
        growth_status: 'growing',
        diplomatic_stance: 'mercantile',
        territory_description: 'No land territory. The fleet itself is sovereign territory — a floating nation that follows trade winds and seasonal markets. Harbor agreements with coastal cities grant temporary docking rights but never permanent settlement.',
      },
    },
    {
      id: 'library_state',
      name: 'Library State',
      description: 'A civilization organized around knowledge preservation. Archivists rule.',
      element_type: 'republic',
      summary: 'A nation where knowledge is power — literally, as archivists govern by controlling access to information',
      detailed_notes: 'The Library State was founded on a simple principle: whoever controls information controls everything. The entire civilization is organized around the collection, preservation, and controlled distribution of knowledge. Archivists — scholar-bureaucrats who have memorized vast catalogs and passed rigorous examinations — form the ruling class. Laws are written as cross-referenced documents, disputes are settled by precedent research, and social status is determined by one\'s access level within the great archives. The civilization is peaceful but not passive: it wages information warfare with devastating effectiveness, trading secrets and withholding knowledge as other nations use armies. Its greatest fear is not invasion but data loss — and its most severe crime is the destruction of records.',
      fields: {
        government_type: 'republic',
        tech_level: 'renaissance',
        magic_integration: 'regulated',
        economic_system: 'mixed',
        military_strength: 'militia_only',
        population_size: 'Roughly 2 million, concentrated in archive-cities',
        growth_status: 'stable',
        diplomatic_stance: 'diplomatic',
        territory_description: 'A compact realm centered on the Great Archive — a city-sized complex of libraries, scriptoria, and vaults. Surrounding territories are organized as resource-producing provinces that support the archive\'s operation. Borders are precisely documented and aggressively defended through diplomacy rather than force.',
      },
    },
    {
      id: 'beast_riders',
      name: 'Beast Riders',
      description: 'A civilization built on bonded relationships with massive creatures.',
      element_type: 'tribal_confederation',
      summary: 'A confederation of clans, each bonded to a species of great beast that shapes their culture and warfare',
      detailed_notes: 'The Beast Riders are a confederation of clans, each defined by its bonded creature. The Thunderhoof clan rides massive armored herbivores across open plains. The Skytalon clan soars on great raptors. The Deepscale clan navigates rivers and swamps on the backs of enormous reptiles. The bond between rider and beast is forged in youth through a dangerous ritual and lasts a lifetime — the death of one partner often kills the other through psychic shock. This bond is the foundation of their social structure: clan identity follows beast species, marriage between clans requires complex negotiation over which beast-bond the children will inherit, and political power belongs to those whose beasts are strongest. The confederation holds together because no single clan\'s beasts can dominate all terrains — cooperation is survival.',
      fields: {
        government_type: 'tribal_council',
        tech_level: 'iron_age',
        magic_integration: 'rare_elite',
        economic_system: 'barter',
        military_strength: 'strong',
        population_size: 'Several hundred thousand across all clans, with beast populations roughly a tenth of that',
        growth_status: 'stable',
        diplomatic_stance: 'defensive',
        territory_description: 'Vast, varied territories matching the habitats of bonded beasts — open plains, mountain ranges, river deltas, and deep forests. Each clan controls the terrain its beasts are adapted to. Territorial boundaries follow ecological zones rather than political lines.',
      },
    },
  ],
  defaultSortField: 'government_type',
};
