import type { DomainConfig } from '../types/domains.js';

export const civilizationsConfig: DomainConfig = {
  id: 'civilizations',
  name: 'Civilization',
  namePlural: 'Civilizations',
  icon: 'landmark',
  color: '#8e44ad',
  description: 'Define the organized societies of your world—their governments, economies, militaries, and territorial ambitions. Civilizations are the political and institutional frameworks within which cultures, technologies, and conflicts emerge.',
  tableName: 'civilizations',
  category: 'sentient',
  fields: [
    {
      name: 'government_type',
      label: 'Government Type',
      type: 'select',
      required: true,
      options: ['monarchy', 'republic', 'democracy', 'oligarchy', 'theocracy', 'magocracy', 'military_junta', 'tribal_council', 'feudal', 'imperial', 'anarchist', 'hive_mind', 'custom'],
      helpText: 'The primary form of governance in this civilization.',
    },
    {
      name: 'tech_level',
      label: 'Technology Level',
      type: 'select',
      required: true,
      options: ['stone_age', 'bronze_age', 'iron_age', 'medieval', 'renaissance', 'industrial', 'modern', 'post_modern', 'magitech', 'custom'],
      helpText: 'The general level of technological development.',
    },
    {
      name: 'magic_integration',
      label: 'Magic Integration',
      type: 'select',
      options: ['none', 'forbidden', 'rare_elite', 'regulated', 'widespread', 'fundamental', 'declining'],
      helpText: 'How deeply magic is integrated into the functioning of this civilization.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 5 million, several hundred thousand, unknown',
      helpText: 'Current estimated total population.',
    },
    {
      name: 'territory_description',
      label: 'Territory Description',
      type: 'textarea',
      placeholder: 'Describe the lands claimed or controlled by this civilization...',
      helpText: 'Geographic extent, borders, and key territorial features.',
    },
    {
      name: 'founded_era_id',
      label: 'Founded Era',
      type: 'text',
      placeholder: 'ID of the founding era or event',
      helpText: 'The historical era or event in which this civilization was founded.',
    },
    {
      name: 'species_id',
      label: 'Primary Species',
      type: 'text',
      placeholder: 'ID of the dominant or founding species',
      helpText: 'The sentient species that founded or primarily comprises this civilization.',
    },
    {
      name: 'economic_system',
      label: 'Economic System',
      type: 'select',
      options: ['barter', 'mercantile', 'feudal', 'capitalist', 'socialist', 'command', 'gift_economy', 'mana_based', 'mixed', 'custom'],
      helpText: 'The dominant economic model.',
    },
    {
      name: 'military_strength',
      label: 'Military Strength',
      type: 'select',
      options: ['none', 'militia_only', 'moderate', 'strong', 'dominant', 'legendary'],
      helpText: 'Overall military power relative to neighboring civilizations.',
    },
    {
      name: 'capital_id',
      label: 'Capital',
      type: 'text',
      placeholder: 'ID of the capital city or seat of power',
      helpText: 'The geographic place serving as the capital or seat of government.',
    },
    {
      name: 'growth_status',
      label: 'Growth Status',
      type: 'select',
      options: ['nascent', 'growing', 'stable', 'stagnant', 'declining', 'collapsed', 'resurgent'],
      helpText: 'Whether this civilization is expanding, stable, or in decline.',
    },
    {
      name: 'diplomatic_stance',
      label: 'Diplomatic Stance',
      type: 'select',
      options: ['expansionist', 'aggressive', 'defensive', 'isolationist', 'mercantile', 'diplomatic', 'tributary', 'hegemonic'],
      helpText: 'The general approach this civilization takes toward foreign relations.',
    },
  ],
  elementTypes: ['empire', 'kingdom', 'republic', 'tribal_confederation', 'city_state', 'nomadic', 'theocracy', 'magocracy', 'custom'],
  prompts: [
    'What tensions exist between the ruling class and the governed? Is power held by birthright, magical talent, wealth, or popular mandate?',
    'How does this civilization interact with its neighbors—through diplomacy, trade, conquest, or isolation?',
    'What are the civilization\'s greatest achievements and deepest failures? What do they celebrate and what do they try to forget?',
    'How does the economic system distribute resources? Are there stark inequalities, and if so, what justifies them in the eyes of the powerful?',
    'What existential threats does this civilization face—internal decay, external invasion, resource depletion, or magical catastrophe?',
  ],
  magicPermeation: {
    companionTable: 'civilizations_magic_aspects',
    fields: [
      {
        name: 'magic_governance',
        label: 'Magic Governance',
        type: 'textarea',
        helpText: 'How the government regulates, controls, or promotes the use of magic—licensing, academies, prohibitions.',
      },
      {
        name: 'magical_economy',
        label: 'Magical Economy',
        type: 'textarea',
        helpText: 'The role of magic in commerce, industry, and wealth generation—enchanted goods, mana trade, spell services.',
      },
      {
        name: 'spell_infrastructure',
        label: 'Spell Infrastructure',
        type: 'textarea',
        helpText: 'Magical infrastructure supporting the civilization—warded walls, teleportation networks, scrying systems, weather control.',
      },
      {
        name: 'magical_military',
        label: 'Magical Military',
        type: 'textarea',
        helpText: 'Military applications of magic—battle mages, enchanted weapons, magical siege engines, ward defenses.',
      },
      {
        name: 'magical_education',
        label: 'Magical Education',
        type: 'textarea',
        helpText: 'How magic is taught—academies, apprenticeships, temples, state programs, or suppressed entirely.',
      },
      {
        name: 'magic_social_hierarchy',
        label: 'Magic & Social Hierarchy',
        type: 'textarea',
        helpText: 'How magical ability affects social standing—are mages revered, feared, enslaved, or treated as ordinary citizens?',
      },
      {
        name: 'magical_law_enforcement',
        label: 'Magical Law Enforcement',
        type: 'textarea',
        helpText: 'How magic is used to enforce laws or how magical crimes are policed and punished.',
      },
      {
        name: 'magical_healthcare',
        label: 'Magical Healthcare',
        type: 'textarea',
        helpText: 'The role of healing magic in public health—who has access, how is it regulated, what are its limits?',
      },
      {
        name: 'magic_tech_relationship',
        label: 'Magic-Technology Relationship',
        type: 'textarea',
        helpText: 'How magic and mundane technology interact—do they complement, compete, or merge into magitech?',
      },
      {
        name: 'attitude_toward_magic',
        label: 'Attitude Toward Magic',
        type: 'select',
        options: ['reverent', 'pragmatic', 'fearful', 'hostile', 'indifferent', 'divided', 'dependent'],
        helpText: 'The prevailing cultural attitude toward magic within this civilization.',
      },
      {
        name: 'magitech_era_id',
        label: 'Magitech Era',
        type: 'text',
        placeholder: 'ID of the era when magitech emerged',
        helpText: 'The historical period when this civilization began integrating magic and technology.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the identity and functioning of this civilization.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Does this civilization regulate magic like a weapon, a profession, or a natural right? What happens to those who practice forbidden magic?',
      'How has the availability (or scarcity) of magic shaped the civilization\'s architecture, warfare, and daily life?',
      'Is there a tension between magical elites and the non-magical majority? Has this ever sparked revolutions or reforms?',
    ],
  },
  archetypes: [
    {
      id: 'feudal_kingdom',
      name: 'Feudal Kingdom',
      description: 'A medieval kingdom ruled by a hereditary monarch, with lords, vassals, and a peasant majority.',
      element_type: 'kingdom',
      summary: 'A hereditary kingdom held together by oaths of fealty and tradition',
      fields: {
        government_type: 'feudal',
        tech_level: 'medieval',
        magic_integration: 'rare_elite',
        economic_system: 'feudal',
        military_strength: 'moderate',
        growth_status: 'stable',
        diplomatic_stance: 'defensive',
        territory_description: 'A contiguous realm centered on a fertile river valley, with outlying provinces held by vassal lords. Borders defined by natural features — mountains, rivers, and dense forests.',
      },
    },
    {
      id: 'trading_republic',
      name: 'Trading Republic',
      description: 'A wealthy merchant republic where political power follows economic power.',
      element_type: 'republic',
      summary: 'A prosperous republic where merchant princes wield political power',
      fields: {
        government_type: 'oligarchy',
        tech_level: 'renaissance',
        magic_integration: 'regulated',
        economic_system: 'mercantile',
        military_strength: 'moderate',
        growth_status: 'growing',
        diplomatic_stance: 'mercantile',
        territory_description: 'A coastal city-state with a modest hinterland but extensive overseas trading posts, colonies, and treaty ports. Power projects outward via its merchant fleet.',
      },
    },
    {
      id: 'nomadic_confederation',
      name: 'Nomadic Confederation',
      description: 'A loose alliance of mobile clans united under a great leader, following herds and seasonal routes.',
      element_type: 'nomadic',
      summary: 'A powerful horse-borne confederation of steppe clans',
      fields: {
        government_type: 'tribal_council',
        tech_level: 'iron_age',
        magic_integration: 'none',
        economic_system: 'barter',
        military_strength: 'strong',
        growth_status: 'growing',
        diplomatic_stance: 'expansionist',
        territory_description: 'No fixed borders — the confederation claims vast open steppes and grasslands through which its clans roam. Seasonal camps at traditional gathering sites.',
      },
    },
    {
      id: 'theocratic_empire',
      name: 'Theocratic Empire',
      description: 'A vast empire ruled by a divine sovereign or priestly caste, where faith and law are one.',
      element_type: 'empire',
      summary: 'A divine empire where the priesthood rules in the name of the gods',
      fields: {
        government_type: 'theocracy',
        tech_level: 'iron_age',
        magic_integration: 'fundamental',
        economic_system: 'command',
        military_strength: 'dominant',
        growth_status: 'stable',
        diplomatic_stance: 'hegemonic',
        territory_description: 'A sprawling empire radiating from a sacred capital. Temple complexes serve as administrative centers in each province. Holy roads connect the faithful.',
      },
    },
    {
      id: 'isolated_city_state',
      name: 'Isolated City-State',
      description: 'A single fortified city governing itself independently, relying on strong walls and clever diplomacy.',
      element_type: 'city_state',
      summary: 'A self-governing city surviving by wit among greater powers',
      fields: {
        government_type: 'republic',
        tech_level: 'medieval',
        magic_integration: 'regulated',
        economic_system: 'mixed',
        military_strength: 'militia_only',
        growth_status: 'stable',
        diplomatic_stance: 'isolationist',
        territory_description: 'The city and its immediate farmlands within a day\'s ride. Surrounded by larger, more powerful neighbors, surviving through neutrality and strategic value.',
      },
    },
    {
      id: 'necrocracy',
      name: 'Undead Bureaucracy',
      description: 'A civilization where the dead continue to govern — ancestor spirits or preserved liches hold every office, and the living are merely the junior workforce.',
      element_type: 'custom',
      summary: 'A realm where death is a promotion — the undead govern, and the living serve their time',
      fields: {
        government_type: 'oligarchy',
        tech_level: 'magitech',
        magic_integration: 'fundamental',
        economic_system: 'command',
        military_strength: 'dominant',
        growth_status: 'stagnant',
        diplomatic_stance: 'isolationist',
        territory_description: 'A grey, orderly realm where cities are immaculately maintained by tireless undead labor. The living occupy the sunlit districts; the dead govern from the underground administrative complexes. Borders are warded against uninvited life and death alike.',
      },
    },
  ],
  defaultSortField: 'government_type',
};
