import type { DomainConfig } from '../types/domains.js';

export const climateConfig: DomainConfig = {
  id: 'climate',
  name: 'Climate',
  namePlural: 'Climate Zones',
  icon: 'thermometer',
  color: '#ff9f43',
  description: 'Establish the long-term weather patterns, seasonal cycles, and climate zones that govern temperature, precipitation, and habitability across your world.',
  tableName: 'climate_zones',
  category: 'natural',
  fields: [
    {
      name: 'zone_type',
      label: 'Zone Type',
      type: 'select',
      required: true,
      options: ['tropical', 'arid', 'temperate', 'continental', 'polar', 'custom'],
      helpText: 'The broad climate classification for this zone.',
    },
    {
      name: 'avg_temp_high',
      label: 'Average High Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical high temperature during the warmest period.',
    },
    {
      name: 'avg_temp_low',
      label: 'Average Low Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical low temperature during the coldest period.',
    },
    {
      name: 'annual_precipitation',
      label: 'Annual Precipitation',
      type: 'text',
      placeholder: 'e.g. 800 mm/year',
      helpText: 'Total yearly precipitation (rain, snow, etc.).',
    },
    {
      name: 'dominant_wind',
      label: 'Dominant Wind',
      type: 'text',
      placeholder: 'e.g. Westerlies, Trade winds',
      helpText: 'The prevailing wind pattern in this climate zone.',
    },
    {
      name: 'season_count',
      label: 'Number of Seasons',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      helpText: 'How many distinct seasons this zone experiences.',
    },
    {
      name: 'humidity',
      label: 'Humidity',
      type: 'text',
      placeholder: 'e.g. arid, semi-arid, moderate, humid, saturated',
      helpText: 'Typical humidity level for this climate zone.',
    },
    {
      name: 'weather_extremes',
      label: 'Weather Extremes',
      type: 'json',
      placeholder: '["hurricanes", "blizzards", "flash floods", "dust storms"]',
      helpText: 'Extreme weather events that can occur in this climate zone.',
    },
    {
      name: 'historical_shifts',
      label: 'Historical Climate Shifts',
      type: 'textarea',
      placeholder: 'Describe long-term climate changes — ice ages, warming periods, desertification...',
      helpText: 'How this climate zone has changed over geological or historical time.',
    },
    {
      name: 'season_descriptions',
      label: 'Season Descriptions',
      type: 'json',
      placeholder: '[{"name": "Verdance", "months": "1-4", "desc": "warm rains"}]',
      helpText: 'Details for each season: name, timing, and characteristics.',
    },
  ],
  elementTypes: ['climate_zone', 'season', 'weather_pattern', 'climate_event'],
  prompts: [
    'Does your world have familiar seasons, or something entirely different—perhaps a long winter, dual summers, or a mana-tide season?',
    'How do axial tilt, orbital mechanics, and atmospheric composition combine to create your climate zones?',
    'Are there regions with extreme or paradoxical climates—a frozen desert, a tropical pole, or a storm that never ends?',
    'How has climate changed over historical time? Were there ice ages, warming periods, or sudden shifts?',
    'What role does precipitation play in agriculture, settlement patterns, and conflict?',
  ],
  magicPermeation: {
    companionTable: 'climate_magic_aspects',
    fields: [
      {
        name: 'magic_influenced_seasons',
        label: 'Magic-Influenced Seasons',
        type: 'textarea',
        helpText: 'Seasons that exist because of or are modified by magical forces.',
      },
      {
        name: 'mana_tides',
        label: 'Mana Tides',
        type: 'textarea',
        helpText: 'Cyclical fluctuations in ambient mana that follow seasonal or longer patterns.',
      },
      {
        name: 'climate_zones_magical_character',
        label: 'Magical Character of Climate Zones',
        type: 'textarea',
        helpText: 'How the magical nature of each climate zone differs—mana-rich tropics vs. mana-sparse tundra, etc.',
      },
      {
        name: 'weather_magic_interaction',
        label: 'Weather-Magic Interaction',
        type: 'textarea',
        helpText: 'How weather events interact with magic—do storms amplify spells? Does drought starve enchantments?',
      },
      {
        name: 'seasonal_magic_rituals',
        label: 'Seasonal Magic Rituals',
        type: 'textarea',
        helpText: 'Rituals or traditions tied to seasonal shifts in magical energy.',
      },
      {
        name: 'long_term_magical_climate_change',
        label: 'Long-Term Magical Climate Change',
        type: 'textarea',
        helpText: 'How magical events or practices have altered climate over centuries.',
      },
      {
        name: 'magical_precipitation',
        label: 'Magical Precipitation',
        type: 'textarea',
        helpText: 'Rain, snow, or other precipitation infused with magical properties.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this climate zone.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Do mana levels rise and fall with the seasons? Is there a "mana spring" when magical energy surges, or a "dead winter" when it fades?',
      'Has large-scale spellcasting or magical industry altered the climate irreversibly—magical global warming or ice-age induction?',
      'Does magical precipitation—mana rain, enchanted snow—have lasting effects on the land and creatures it touches?',
    ],
  },
  defaultSortField: 'zone_type',
};
