import type { DomainConfig } from '../types/domains.js';

export const climateConfig: DomainConfig = {
  id: 'climate',
  name: 'Climate',
  namePlural: 'Climate Zones',
  icon: 'thermometer',
  color: '#ff9f43',
  description: 'Establish the long-term weather patterns, seasonal cycles, and climate zones that govern temperature, precipitation, and habitability across your world.',
  tableName: 'climate_zones',
  category: 'natural',
  fields: [
    {
      name: 'zone_type',
      label: 'Zone Type',
      type: 'select',
      required: true,
      options: ['tropical', 'arid', 'temperate', 'continental', 'polar', 'custom'],
      helpText: 'The broad climate classification for this zone.',
    },
    {
      name: 'avg_temp_high',
      label: 'Average High Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical high temperature during the warmest period.',
    },
    {
      name: 'avg_temp_low',
      label: 'Average Low Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical low temperature during the coldest period.',
    },
    {
      name: 'annual_precipitation',
      label: 'Annual Precipitation',
      type: 'text',
      placeholder: 'e.g. 800 mm/year',
      helpText: 'Total yearly precipitation (rain, snow, etc.).',
    },
    {
      name: 'dominant_wind',
      label: 'Dominant Wind',
      type: 'text',
      placeholder: 'e.g. Westerlies, Trade winds',
      helpText: 'The prevailing wind pattern in this climate zone.',
    },
    {
      name: 'season_count',
      label: 'Number of Seasons',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      helpText: 'How many distinct seasons this zone experiences.',
    },
    {
      name: 'humidity',
      label: 'Humidity',
      type: 'text',
      placeholder: 'e.g. arid, semi-arid, moderate, humid, saturated',
      helpText: 'Typical humidity level for this climate zone.',
    },
    {
      name: 'weather_extremes',
      label: 'Weather Extremes',
      type: 'json',
      placeholder: '["hurricanes", "blizzards", "flash floods", "dust storms"]',
      helpText: 'Extreme weather events that can occur in this climate zone.',
    },
    {
      name: 'historical_shifts',
      label: 'Historical Climate Shifts',
      type: 'textarea',
      placeholder: 'Describe long-term climate changes — ice ages, warming periods, desertification...',
      helpText: 'How this climate zone has changed over geological or historical time.',
    },
    {
      name: 'season_descriptions',
      label: 'Season Descriptions',
      type: 'json',
      placeholder: '[{"name": "Verdance", "months": "1-4", "desc": "warm rains"}]',
      helpText: 'Details for each season: name, timing, and characteristics.',
    },
  ],
  elementTypes: ['climate_zone', 'season', 'weather_pattern', 'climate_event'],
  elementTypeDescriptions: {
    climate_zone: 'A region with consistent long-term weather characteristics — temperature range, precipitation, and humidity that define what can live there.',
    season: 'A recurring period within a year defined by predictable weather changes. Driven by axial tilt, orbital position, or magical cycles.',
    weather_pattern: 'A recurring atmospheric condition tied to geography or season — monsoons, dry spells, fog banks, or perpetual drizzle.',
    climate_event: 'A significant, often disruptive climatic occurrence — ice ages, droughts, super-storms, or sudden shifts in global temperature.',
  },
  prompts: [
    'Does your world have familiar seasons, or something entirely different—perhaps a long winter, dual summers, or a mana-tide season?',
    'How do axial tilt, orbital mechanics, and atmospheric composition combine to create your climate zones?',
    'Are there regions with extreme or paradoxical climates—a frozen desert, a tropical pole, or a storm that never ends?',
    'How has climate changed over historical time? Were there ice ages, warming periods, or sudden shifts?',
    'What role does precipitation play in agriculture, settlement patterns, and conflict?',
  ],
  magicPermeation: {
    companionTable: 'climate_magic_aspects',
    fields: [
      {
        name: 'magic_influenced_seasons',
        label: 'Magic-Influenced Seasons',
        type: 'textarea',
        helpText: 'Seasons that exist because of or are modified by magical forces.',
      },
      {
        name: 'mana_tides',
        label: 'Mana Tides',
        type: 'textarea',
        helpText: 'Cyclical fluctuations in ambient mana that follow seasonal or longer patterns.',
      },
      {
        name: 'climate_zones_magical_character',
        label: 'Magical Character of Climate Zones',
        type: 'textarea',
        helpText: 'How the magical nature of each climate zone differs—mana-rich tropics vs. mana-sparse tundra, etc.',
      },
      {
        name: 'weather_magic_interaction',
        label: 'Weather-Magic Interaction',
        type: 'textarea',
        helpText: 'How weather events interact with magic—do storms amplify spells? Does drought starve enchantments?',
      },
      {
        name: 'seasonal_magic_rituals',
        label: 'Seasonal Magic Rituals',
        type: 'textarea',
        helpText: 'Rituals or traditions tied to seasonal shifts in magical energy.',
      },
      {
        name: 'long_term_magical_climate_change',
        label: 'Long-Term Magical Climate Change',
        type: 'textarea',
        helpText: 'How magical events or practices have altered climate over centuries.',
      },
      {
        name: 'magical_precipitation',
        label: 'Magical Precipitation',
        type: 'textarea',
        helpText: 'Rain, snow, or other precipitation infused with magical properties.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this climate zone.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Do mana levels rise and fall with the seasons? Is there a "mana spring" when magical energy surges, or a "dead winter" when it fades?',
      'Has large-scale spellcasting or magical industry altered the climate irreversibly—magical global warming or ice-age induction?',
      'Does magical precipitation—mana rain, enchanted snow—have lasting effects on the land and creatures it touches?',
    ],
  },
  archetypes: [
    {
      id: 'temperate_maritime',
      name: 'Temperate Maritime',
      description: 'A mild, rainy climate moderated by nearby ocean currents — think western coastlines.',
      element_type: 'climate_zone',
      summary: 'A mild oceanic climate with cool winters and warm summers',
      fields: {
        zone_type: 'temperate',
        avg_temp_high: 22,
        avg_temp_low: 2,
        annual_precipitation: '800-1200 mm annually',
        dominant_wind: 'Prevailing westerlies from the ocean',
        season_count: 4,
        humidity: 'Moderate to high year-round (65-85%)',
      },
    },
    {
      id: 'tropical_monsoon',
      name: 'Tropical Monsoon',
      description: 'A hot climate with dramatic wet and dry seasons driven by shifting wind patterns.',
      element_type: 'climate_zone',
      summary: 'A hot tropical climate with intense monsoon rains',
      fields: {
        zone_type: 'tropical',
        avg_temp_high: 35,
        avg_temp_low: 22,
        annual_precipitation: '1500-3000 mm, concentrated in the wet season',
        dominant_wind: 'Seasonal reversal — onshore in wet season, offshore in dry',
        season_count: 2,
        humidity: 'Very high in wet season (85-100%), moderate in dry (40-60%)',
      },
    },
    {
      id: 'polar_tundra',
      name: 'Polar Tundra',
      description: 'A frigid climate with permafrost, brief summers, and months of continuous darkness or light.',
      element_type: 'climate_zone',
      summary: 'A frozen tundra with extreme seasonal light variation',
      fields: {
        zone_type: 'polar',
        avg_temp_high: 8,
        avg_temp_low: -40,
        annual_precipitation: '150-300 mm (mostly snow)',
        dominant_wind: 'Polar easterlies with frequent blizzards',
        season_count: 2,
        humidity: 'Low (20-40%), but feels damp due to permafrost moisture',
      },
    },
    {
      id: 'arid_desert',
      name: 'Arid Desert',
      description: 'An extremely dry climate with scorching days, cold nights, and almost no rainfall.',
      element_type: 'climate_zone',
      summary: 'A harsh desert climate with extreme temperature swings',
      fields: {
        zone_type: 'arid',
        avg_temp_high: 45,
        avg_temp_low: -5,
        annual_precipitation: 'Under 100 mm annually',
        dominant_wind: 'Hot, dry winds carrying fine sand and dust',
        season_count: 2,
        humidity: 'Extremely low (5-20%)',
      },
    },
    {
      id: 'magical_inversion',
      name: 'Magical Inversion Zone',
      description: 'A climate zone where magical saturation overrides normal weather — mana storms, crystal snow, and seasons that change based on celestial alignment rather than axial tilt.',
      element_type: 'climate_event',
      summary: 'A region where magic has hijacked the weather cycle entirely',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 35,
        avg_temp_low: -20,
        annual_precipitation: 'Variable — includes mana rain, crystal sleet, and liquid starlight depending on planar conditions',
        dominant_wind: 'Mana currents that shift with ley line activity, not pressure systems',
        season_count: 7,
        humidity: 'Fluctuates wildly — can shift from bone-dry to saturated in hours during mana surges',
      },
    },
    {
      id: 'eternal_twilight',
      name: 'Eternal Twilight Zone',
      description: 'A climate region in permanent dim light — between a tidally locked day and night side.',
      element_type: 'climate_zone',
      summary: 'A narrow band of perpetual dusk between a scorched dayside and a frozen nightside',
      detailed_notes: 'On a tidally locked world, one hemisphere faces the star in permanent day while the other faces away in permanent night. Between them lies the twilight zone — a narrow ring of perpetual dim light where the sun sits forever on the horizon. This band is the only habitable region, and all civilization clusters here. Temperatures are moderate but vary sharply over short distances: a few miles toward the dayside brings searing heat, while a few miles toward the nightside brings lethal cold. Winds are constant and fierce, driven by the extreme temperature differential between the hemispheres. The eternal sunset casts everything in amber and rose, and shadows are always long. Crops grow in the dim light but slowly, and the psychological effects of never seeing full daylight or true darkness shape the culture profoundly.',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 28,
        avg_temp_low: -5,
        annual_precipitation: '600-900 mm, primarily from moisture carried by winds from the dayside',
        dominant_wind: 'Constant gales blowing from the hot dayside toward the cold nightside, moderated by Coriolis effect',
        season_count: 1,
        humidity: 'Moderate (50-70%), with fog banks common where warm and cold air masses meet',
        weather_extremes: '["thermal gradient storms", "dayside heat surges", "nightside cold snaps", "perpetual fog banks"]',
      },
    },
    {
      id: 'storm_belt',
      name: 'Permanent Storm Belt',
      description: 'A band of continuous storms that divides the world into hemispheres, passable only by the desperate or the mad.',
      element_type: 'climate_event',
      summary: 'An unbroken wall of storms encircling the planet, dividing the world in two',
      detailed_notes: 'The storm belt is a continuous band of violent weather that wraps around the planet like a ribbon, roughly following the equator but shifting north and south with a slow, unpredictable oscillation. Within the belt, conditions are apocalyptic: winds exceed 300 km/h, lightning strikes are nearly continuous, rain falls in horizontal sheets, and visibility drops to zero. The belt is approximately 200 km wide at its narrowest and 500 km at its widest. No permanent settlement exists within it, and crossing it is one of the most dangerous undertakings in the world. The few successful crossings are legendary — most who attempt it are never seen again. The storm belt effectively divides the world into two hemispheres with separate civilizations, languages, and histories. Trade and communication between the hemispheres is rare, expensive, and heroic. Scholars debate whether the belt is a natural meteorological phenomenon, a remnant of an ancient magical war, or a deliberate barrier placed by the gods.',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 18,
        avg_temp_low: 5,
        annual_precipitation: 'Unmeasurable — continuous precipitation exceeding 15,000 mm equivalent',
        dominant_wind: 'Chaotic and violent, averaging 200+ km/h with gusts exceeding 400 km/h',
        season_count: 1,
        humidity: 'Saturated (100%) at all times',
        weather_extremes: '["continuous lightning", "horizontal rain", "waterspouts", "hail bombardment", "wind shear fatal to aircraft"]',
      },
    },
    {
      id: 'mana_seasons',
      name: 'Mana Tide Seasons',
      description: 'Seasons driven by magical tides rather than axial tilt — when mana surges, everything blooms and burns.',
      element_type: 'season',
      summary: 'A seasonal cycle driven by the ebb and flow of magical energy rather than solar geometry',
      detailed_notes: 'In this world, seasons are not caused by the tilt of the planet\'s axis but by cyclical fluctuations in ambient magical energy — the mana tides. When mana surges (the Bloom), temperatures rise, plants grow explosively, animals become hyperactive, and the air itself crackles with potential. When mana ebbs (the Fade), temperatures drop, growth slows to nothing, and a profound stillness settles over the land. The transition periods — the Kindling and the Dimming — bring their own weather: mana storms during the Kindling as energy floods back into the system, and mana fog during the Dimming as residual energy condenses and dissipates. The mana tide cycle does not follow solar geometry, so it can be summer by temperature during a Bloom while the sun is in its winter position. This creates deeply counterintuitive weather — warm winters, cold summers — that confounds visitors from non-magical worlds.',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 38,
        avg_temp_low: -15,
        annual_precipitation: '1000-2000 mm, concentrated during the Kindling as mana-charged rain',
        dominant_wind: 'Shifts with mana tide phase — inward toward high-mana zones during Bloom, outward during Fade',
        season_count: 4,
        humidity: 'High during Bloom (80-100%), very low during Fade (10-25%)',
        season_descriptions: '[{"name": "The Bloom", "months": "1-3", "desc": "Mana surges. Explosive growth, rising temperatures, hyperactive fauna. Magic is easy and wild."}, {"name": "The Kindling", "months": "4-6", "desc": "Mana floods back. Violent mana storms, unpredictable weather, charged precipitation."}, {"name": "The Fade", "months": "7-9", "desc": "Mana ebbs. Cold, stillness, dormancy. Magic is difficult and costly."}, {"name": "The Dimming", "months": "10-12", "desc": "Residual mana condenses. Mana fog, gentle cooling, reflective calm."}]',
      },
    },
    {
      id: 'color_seasons',
      name: 'Color Seasons',
      description: 'Seasons defined by the color the sky and foliage turns rather than temperature changes.',
      element_type: 'season',
      summary: 'A seasonal cycle defined by dramatic shifts in the color of sky and vegetation rather than temperature',
      detailed_notes: 'In this climate, the traditional markers of seasonal change — temperature, precipitation, day length — remain relatively constant year-round. Instead, the seasons are defined by sweeping changes in color that affect the sky, foliage, water, and even the soil. During the Azure Season, the sky deepens to an intense cobalt and plants shift to blue-green hues. The Crimson Season brings a blood-red sky and scarlet-leafed forests. The Gold Season bathes everything in amber, and the Pale Season bleaches the world to ghostly whites and silvers. The color shifts are caused by seasonal changes in atmospheric particle composition — different mineral dusts, biological spores, and chemical compounds dominate the air at different times, filtering sunlight into distinct spectra. The effect is not merely visual: each color season brings different photosynthetic conditions, favoring different plant species and triggering distinct animal behaviors. Civilizations mark time by color, not temperature, and their art, clothing, and festivals reflect the dominant hue.',
      fields: {
        zone_type: 'custom',
        season_count: 4,
        avg_temp_high: 25,
        avg_temp_low: 18,
      },
    },
    {
      id: 'whisper_winter',
      name: 'Whisper Winter',
      description: 'A season of unnatural silence where even sound is dampened.',
      element_type: 'season',
      summary: 'A chilling season where sound itself is suppressed, wrapping the world in eerie silence',
      detailed_notes: 'Whisper Winter is not merely cold — it is quiet. As the season descends, an atmospheric phenomenon causes progressive sound dampening across the affected region. Snow falls in absolute silence. Shouts carry only a few meters. Footsteps in snow make no crunch. Conversations become whispered by necessity, as raising one\'s voice produces only a muffled murmur. The mechanism is debated: some scholars attribute it to a temperature-dependent change in atmospheric density that absorbs acoustic energy, while others point to the crystalline structure of the winter precipitation, which forms sound-absorbing lattices on every surface. The psychological effects are profound. The unnatural silence induces paranoia, depression, and a condition called "whisper-madness" in those who cannot adapt. Predators thrive, as prey cannot hear them approach. Communication over distance becomes impossible without visual signals. Communities develop elaborate sign languages and light-based communication systems that are used only during Whisper Winter and forgotten by spring.',
      fields: {
        zone_type: 'polar',
        avg_temp_high: -5,
        avg_temp_low: -35,
        humidity: 'Very low (10-20%) — the cold air holds almost no moisture, contributing to the sound-dampening effect',
      },
    },
    {
      id: 'hunger_season',
      name: 'Hunger Season',
      description: 'A brutal annual period where magic or natural resources become scarce.',
      element_type: 'climate_event',
      summary: 'A dreaded annual period of absolute scarcity when both natural and magical resources fail',
      detailed_notes: 'The Hunger Season is the most feared time of year — a period of weeks to months when the world\'s generosity simply stops. Crops wither regardless of water and soil quality. Game animals vanish into hiding places that defy tracking. Fish abandon coastal waters for the unreachable deep. Fruit rots on the branch before ripening. In magical regions, the deprivation extends to mana itself: spells fail, enchanted items go dormant, and healers find their powers useless precisely when they are most needed. The cause is cyclical but not fully understood — some scholars link it to a celestial alignment that disrupts the flow of life energy, while others attribute it to the world\'s ecosystem entering a periodic dormancy analogous to a heartbeat\'s pause between beats. Civilizations survive the Hunger Season through stockpiling, rationing, and communal solidarity — but every year, the vulnerable perish. The end of the Hunger Season is celebrated with the most important festival in the calendar, a release of pent-up desperation into wild relief.',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 15,
        season_count: 2,
      },
    },
  ],
  defaultSortField: 'zone_type',
};
