import type { DomainConfig } from '../types/domains.js';

export const climateConfig: DomainConfig = {
  id: 'climate',
  name: 'Climate',
  namePlural: 'Climate Zones',
  icon: 'thermometer',
  color: '#ff9f43',
  description: 'Establish the long-term weather patterns, seasonal cycles, and climate zones that govern temperature, precipitation, and habitability across your world.',
  tableName: 'climate_zones',
  category: 'natural',
  fields: [
    {
      name: 'zone_type',
      label: 'Zone Type',
      type: 'select',
      required: true,
      options: ['tropical', 'arid', 'temperate', 'continental', 'polar', 'custom'],
      helpText: 'The broad climate classification for this zone.',
    },
    {
      name: 'avg_temp_high',
      label: 'Average High Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical high temperature during the warmest period.',
    },
    {
      name: 'avg_temp_low',
      label: 'Average Low Temperature',
      type: 'number',
      placeholder: '°C',
      helpText: 'Typical low temperature during the coldest period.',
    },
    {
      name: 'annual_precipitation',
      label: 'Annual Precipitation',
      type: 'text',
      placeholder: 'e.g. 800 mm/year',
      helpText: 'Total yearly precipitation (rain, snow, etc.).',
    },
    {
      name: 'dominant_wind',
      label: 'Dominant Wind',
      type: 'text',
      placeholder: 'e.g. Westerlies, Trade winds',
      helpText: 'The prevailing wind pattern in this climate zone.',
    },
    {
      name: 'season_count',
      label: 'Number of Seasons',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      helpText: 'How many distinct seasons this zone experiences.',
    },
    {
      name: 'humidity',
      label: 'Humidity',
      type: 'text',
      placeholder: 'e.g. arid, semi-arid, moderate, humid, saturated',
      helpText: 'Typical humidity level for this climate zone.',
    },
    {
      name: 'weather_extremes',
      label: 'Weather Extremes',
      type: 'json',
      placeholder: '["hurricanes", "blizzards", "flash floods", "dust storms"]',
      helpText: 'Extreme weather events that can occur in this climate zone.',
    },
    {
      name: 'historical_shifts',
      label: 'Historical Climate Shifts',
      type: 'textarea',
      placeholder: 'Describe long-term climate changes — ice ages, warming periods, desertification...',
      helpText: 'How this climate zone has changed over geological or historical time.',
    },
    {
      name: 'season_descriptions',
      label: 'Season Descriptions',
      type: 'json',
      placeholder: '[{"name": "Verdance", "months": "1-4", "desc": "warm rains"}]',
      helpText: 'Details for each season: name, timing, and characteristics.',
    },
  ],
  elementTypes: ['climate_zone', 'season', 'weather_pattern', 'climate_event'],
  prompts: [
    'Does your world have familiar seasons, or something entirely different—perhaps a long winter, dual summers, or a mana-tide season?',
    'How do axial tilt, orbital mechanics, and atmospheric composition combine to create your climate zones?',
    'Are there regions with extreme or paradoxical climates—a frozen desert, a tropical pole, or a storm that never ends?',
    'How has climate changed over historical time? Were there ice ages, warming periods, or sudden shifts?',
    'What role does precipitation play in agriculture, settlement patterns, and conflict?',
  ],
  magicPermeation: {
    companionTable: 'climate_magic_aspects',
    fields: [
      {
        name: 'magic_influenced_seasons',
        label: 'Magic-Influenced Seasons',
        type: 'textarea',
        helpText: 'Seasons that exist because of or are modified by magical forces.',
      },
      {
        name: 'mana_tides',
        label: 'Mana Tides',
        type: 'textarea',
        helpText: 'Cyclical fluctuations in ambient mana that follow seasonal or longer patterns.',
      },
      {
        name: 'climate_zones_magical_character',
        label: 'Magical Character of Climate Zones',
        type: 'textarea',
        helpText: 'How the magical nature of each climate zone differs—mana-rich tropics vs. mana-sparse tundra, etc.',
      },
      {
        name: 'weather_magic_interaction',
        label: 'Weather-Magic Interaction',
        type: 'textarea',
        helpText: 'How weather events interact with magic—do storms amplify spells? Does drought starve enchantments?',
      },
      {
        name: 'seasonal_magic_rituals',
        label: 'Seasonal Magic Rituals',
        type: 'textarea',
        helpText: 'Rituals or traditions tied to seasonal shifts in magical energy.',
      },
      {
        name: 'long_term_magical_climate_change',
        label: 'Long-Term Magical Climate Change',
        type: 'textarea',
        helpText: 'How magical events or practices have altered climate over centuries.',
      },
      {
        name: 'magical_precipitation',
        label: 'Magical Precipitation',
        type: 'textarea',
        helpText: 'Rain, snow, or other precipitation infused with magical properties.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this climate zone.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Do mana levels rise and fall with the seasons? Is there a "mana spring" when magical energy surges, or a "dead winter" when it fades?',
      'Has large-scale spellcasting or magical industry altered the climate irreversibly—magical global warming or ice-age induction?',
      'Does magical precipitation—mana rain, enchanted snow—have lasting effects on the land and creatures it touches?',
    ],
  },
  archetypes: [
    {
      id: 'temperate_maritime',
      name: 'Temperate Maritime',
      description: 'A mild, rainy climate moderated by nearby ocean currents — think western coastlines.',
      element_type: 'climate_zone',
      summary: 'A mild oceanic climate with cool winters and warm summers',
      fields: {
        zone_type: 'temperate',
        avg_temp_high: 22,
        avg_temp_low: 2,
        annual_precipitation: '800-1200 mm annually',
        dominant_wind: 'Prevailing westerlies from the ocean',
        season_count: 4,
        humidity: 'Moderate to high year-round (65-85%)',
      },
    },
    {
      id: 'tropical_monsoon',
      name: 'Tropical Monsoon',
      description: 'A hot climate with dramatic wet and dry seasons driven by shifting wind patterns.',
      element_type: 'climate_zone',
      summary: 'A hot tropical climate with intense monsoon rains',
      fields: {
        zone_type: 'tropical',
        avg_temp_high: 35,
        avg_temp_low: 22,
        annual_precipitation: '1500-3000 mm, concentrated in the wet season',
        dominant_wind: 'Seasonal reversal — onshore in wet season, offshore in dry',
        season_count: 2,
        humidity: 'Very high in wet season (85-100%), moderate in dry (40-60%)',
      },
    },
    {
      id: 'polar_tundra',
      name: 'Polar Tundra',
      description: 'A frigid climate with permafrost, brief summers, and months of continuous darkness or light.',
      element_type: 'climate_zone',
      summary: 'A frozen tundra with extreme seasonal light variation',
      fields: {
        zone_type: 'polar',
        avg_temp_high: 8,
        avg_temp_low: -40,
        annual_precipitation: '150-300 mm (mostly snow)',
        dominant_wind: 'Polar easterlies with frequent blizzards',
        season_count: 2,
        humidity: 'Low (20-40%), but feels damp due to permafrost moisture',
      },
    },
    {
      id: 'arid_desert',
      name: 'Arid Desert',
      description: 'An extremely dry climate with scorching days, cold nights, and almost no rainfall.',
      element_type: 'climate_zone',
      summary: 'A harsh desert climate with extreme temperature swings',
      fields: {
        zone_type: 'arid',
        avg_temp_high: 45,
        avg_temp_low: -5,
        annual_precipitation: 'Under 100 mm annually',
        dominant_wind: 'Hot, dry winds carrying fine sand and dust',
        season_count: 2,
        humidity: 'Extremely low (5-20%)',
      },
    },
    {
      id: 'magical_inversion',
      name: 'Magical Inversion Zone',
      description: 'A climate zone where magical saturation overrides normal weather — mana storms, crystal snow, and seasons that change based on celestial alignment rather than axial tilt.',
      element_type: 'climate_event',
      summary: 'A region where magic has hijacked the weather cycle entirely',
      fields: {
        zone_type: 'custom',
        avg_temp_high: 35,
        avg_temp_low: -20,
        annual_precipitation: 'Variable — includes mana rain, crystal sleet, and liquid starlight depending on planar conditions',
        dominant_wind: 'Mana currents that shift with ley line activity, not pressure systems',
        season_count: 7,
        humidity: 'Fluctuates wildly — can shift from bone-dry to saturated in hours during mana surges',
      },
    },
  ],
  defaultSortField: 'zone_type',
};
