import type { DomainConfig } from '../types/domains.js';

export const cosmologyConfig: DomainConfig = {
  id: 'cosmology',
  name: 'Cosmology',
  namePlural: 'Celestial Bodies',
  icon: 'star',
  color: '#e8c547',
  description: 'Define the stars, planets, moons, and other celestial bodies that make up your world\'s universe. Establish orbital mechanics, creation myths, and the structure of the cosmos.',
  tableName: 'celestial_bodies',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'select',
      required: true,
      options: ['star', 'planet', 'moon', 'asteroid', 'ring', 'comet', 'nebula'],
      helpText: 'The classification of this celestial body.',
    },
    {
      name: 'composition',
      label: 'Composition',
      type: 'select',
      options: ['rocky', 'gas_giant', 'ice_giant', 'metallic', 'plasma', 'mixed', 'energy', 'unknown'],
      helpText: 'The primary material composition of this celestial body.',
    },
    {
      name: 'mass',
      label: 'Mass',
      type: 'text',
      placeholder: 'e.g. 1.0 solar masses, 5.97e24 kg',
      helpText: 'Mass of the body in your preferred units.',
    },
    {
      name: 'radius',
      label: 'Radius',
      type: 'text',
      placeholder: 'e.g. 6,371 km',
      helpText: 'Mean radius of the body.',
    },
    {
      name: 'orbital_period',
      label: 'Orbital Period',
      type: 'text',
      placeholder: 'e.g. 365.25 days',
      helpText: 'Time to complete one orbit around its parent body.',
    },
    {
      name: 'orbital_parent_id',
      label: 'Orbital Parent',
      type: 'text',
      placeholder: 'ID of the body this orbits',
      helpText: 'The celestial body this object orbits around.',
    },
    {
      name: 'axial_tilt',
      label: 'Axial Tilt',
      type: 'text',
      placeholder: 'e.g. 23.4°',
      helpText: 'Tilt of the rotational axis, which affects seasons.',
    },
    {
      name: 'day_length',
      label: 'Day Length',
      type: 'text',
      placeholder: 'e.g. 24 hours',
      helpText: 'Duration of one full rotation.',
    },
    {
      name: 'surface_gravity',
      label: 'Surface Gravity',
      type: 'text',
      placeholder: 'e.g. 9.8 m/s²',
      helpText: 'Gravitational pull at the surface.',
    },
    {
      name: 'luminosity',
      label: 'Luminosity',
      type: 'text',
      placeholder: 'e.g. 1.0 solar luminosities',
      helpText: 'Total energy output (primarily for stars).',
    },
    {
      name: 'atmosphere_description',
      label: 'Atmosphere Description',
      type: 'textarea',
      placeholder: 'Describe the atmosphere, if any...',
      helpText: 'A brief description of the atmospheric composition and conditions.',
    },
  ],
  elementTypes: ['star', 'planet', 'moon', 'asteroid', 'comet', 'ring_system', 'nebula'],
  elementTypeDescriptions: {
    star: 'A luminous sphere of plasma held together by gravity, generating light and heat through nuclear fusion. The anchor of a planetary system.',
    planet: 'A large body orbiting a star, massive enough for gravity to shape it into a sphere. May be rocky, gaseous, or something stranger.',
    moon: 'A natural satellite orbiting a planet. Moons influence tides, stabilize axial tilt, and may harbor life of their own.',
    asteroid: 'A small, irregular rocky or metallic body orbiting a star. Often found in belts, and a source of rare minerals.',
    comet: 'An icy body that develops a glowing tail of gas and dust when it approaches a star. Often carries mythological significance.',
    ring_system: 'A disc of particles — ice, rock, or dust — orbiting a planet. Visible from the surface as luminous arcs across the sky.',
    nebula: 'A vast cloud of gas and dust in interstellar space, often a stellar nursery where new stars are born.',
  },
  prompts: [
    'How many suns does your world orbit? Does the star system have unusual properties that affect life?',
    'What do the night skies look like? Are there multiple moons, visible planets, or permanent celestial features?',
    'How do the orbital mechanics of your world create seasons, tides, and day/night cycles?',
    'What creation myths do the inhabitants tell about the origin of the cosmos?',
    'Are there any celestial events (eclipses, conjunctions, comet passages) that hold cultural or practical significance?',
  ],
  magicPermeation: {
    companionTable: 'cosmology_magic_aspects',
    fields: [
      {
        name: 'magical_celestial_bodies',
        label: 'Magical Celestial Bodies',
        type: 'textarea',
        helpText: 'Celestial bodies with inherent magical properties or significance.',
      },
      {
        name: 'astral_plane_relationship',
        label: 'Astral Plane Relationship',
        type: 'textarea',
        helpText: 'How this body relates to or overlaps with the astral plane.',
      },
      {
        name: 'dimensional_cosmology',
        label: 'Dimensional Cosmology',
        type: 'textarea',
        helpText: 'The dimensional structure of the cosmos and how planes layer or intersect.',
      },
      {
        name: 'cosmic_magic_sources',
        label: 'Cosmic Magic Sources',
        type: 'textarea',
        helpText: 'Sources of magical energy at the cosmic scale (stellar mana, void energy, etc.).',
      },
      {
        name: 'celestial_alignments_effects',
        label: 'Celestial Alignment Effects',
        type: 'textarea',
        helpText: 'How alignments of celestial bodies affect magic in the world.',
      },
      {
        name: 'creation_myth_magical',
        label: 'Magical Creation Myth',
        type: 'textarea',
        helpText: 'The role of magic in the creation of the cosmos.',
      },
      {
        name: 'cosmic_entities',
        label: 'Cosmic Entities',
        type: 'textarea',
        helpText: 'Beings of cosmic scale that inhabit or influence the celestial realm.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the cosmological nature of this body.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'Do celestial alignments amplify or dampen magical energy? Are there cosmic ley lines between stars?',
      'Is the cosmos itself a magical construct, or did magic arise within it naturally?',
      'Are there cosmic entities—star gods, void beings—whose movements affect the magical tides of your world?',
    ],
  },
  archetypes: [
    {
      id: 'habitable_planet',
      name: 'Habitable Planet',
      description: 'A rocky world in the habitable zone with liquid water and a breathable atmosphere.',
      element_type: 'planet',
      summary: "A terrestrial world orbiting within its star's habitable zone",
      fields: {
        body_type: 'planet',
        composition: 'rocky',
        surface_gravity: '9.8 m/s²',
        axial_tilt: '20-25°',
        day_length: '20-28 hours',
        atmosphere_description: 'Nitrogen-oxygen atmosphere capable of supporting complex life. Moderate greenhouse effect maintains stable surface temperatures.',
      },
    },
    {
      id: 'gas_giant',
      name: 'Gas Giant',
      description: 'A massive planet with no solid surface, surrounded by swirling bands of cloud.',
      element_type: 'planet',
      summary: 'A massive gas giant with swirling cloud bands and numerous moons',
      fields: {
        body_type: 'planet',
        composition: 'gas_giant',
        mass: '~300 Earth masses',
        radius: '~70,000 km',
        day_length: '10-14 hours',
        atmosphere_description: 'Thick layers of hydrogen and helium with bands of ammonia and methane clouds. Violent storms rage across the surface.',
      },
    },
    {
      id: 'red_dwarf_star',
      name: 'Red Dwarf Star',
      description: 'A small, cool, long-lived star — the most common type in many universes.',
      element_type: 'star',
      summary: 'A dim, long-lived red dwarf star',
      fields: {
        body_type: 'star',
        composition: 'plasma',
        luminosity: '0.01-0.08 solar luminosities',
        mass: '0.1-0.5 solar masses',
        radius: '~200,000 km',
      },
    },
    {
      id: 'major_moon',
      name: 'Major Moon',
      description: 'A large natural satellite, potentially tidally locked and geologically active.',
      element_type: 'moon',
      summary: 'A large natural satellite with its own geological character',
      fields: {
        body_type: 'moon',
        composition: 'rocky',
        surface_gravity: '1.6-3.0 m/s²',
        atmosphere_description: 'Thin or absent atmosphere, possibly with volcanic outgassing creating temporary local haze.',
      },
    },
    {
      id: 'dying_god_star',
      name: 'Dying God-Star',
      description: 'A star that is the smoldering corpse of a dead deity — still radiating divine energy as it slowly fades.',
      element_type: 'star',
      summary: 'The remains of a fallen god, burning with fading divine light',
      fields: {
        body_type: 'star',
        composition: 'energy',
        luminosity: 'Erratic — pulses with divine resonance, brighter during prayer',
        mass: 'Impossible to measure; gravitational pull fluctuates with faith',
        atmosphere_description: 'The corona is not plasma but luminous ichor — the divine blood of the dead god. Ships passing through report visions, prophecies, and madness.',
      },
    },
    {
      id: 'wandering_world',
      name: 'Wandering Rogue Planet',
      description: 'A planet cast out of its star system, drifting through interstellar void with a frozen surface hiding a warm interior.',
      element_type: 'planet',
      summary: 'A starless world drifting through the void, warmed only from within',
      fields: {
        body_type: 'planet',
        composition: 'rocky',
        surface_gravity: '12.5 m/s²',
        luminosity: 'None — no parent star, perpetual darkness on the surface',
        atmosphere_description: 'A thick nitrogen atmosphere frozen into surface ice. Geothermal vents create pockets of warmth and breathable air in deep valleys, where eyeless ecosystems thrive.',
      },
    },
    {
      id: 'binary_stars',
      name: 'Binary Star System',
      description: 'Two stars orbiting each other, creating complex seasons, double shadows, and competing gravitational fields.',
      element_type: 'star',
      summary: 'A pair of stars locked in mutual orbit, bathing their worlds in shifting double light',
      detailed_notes: 'Binary star systems produce extraordinary environmental complexity. Planets in such systems experience variable day lengths, overlapping light spectra, and seasons driven by the relative positions of both stars. Shadows are always doubled, and twilight can last for hours as one star sets while the other remains. Civilizations here develop dual calendars, and the interplay of gravitational fields creates unusual tidal forces on any orbiting worlds.',
      fields: {
        body_type: 'star',
        composition: 'plasma',
        mass: 'Primary: 1.1 solar masses, Secondary: 0.8 solar masses',
        luminosity: 'Combined: 2.4 solar luminosities, shifting as orbital distance varies',
        orbital_period: '80 years mutual orbit; inner planets experience complex multi-year light cycles',
      },
    },
    {
      id: 'hollow_world',
      name: 'Hollow World',
      description: 'A planet that is hollow inside, with an interior surface, inner sun, and inverted horizon.',
      element_type: 'planet',
      summary: 'A world with a habitable interior surface curving upward in every direction',
      detailed_notes: 'The hollow world defies conventional physics — its inner surface is habitable, lit by a small, perpetual light source at the core. Gravity pulls toward the shell from both sides, allowing life on the outer and inner surfaces. The interior sky is the land itself, curving upward until it vanishes in atmospheric haze. There is no true horizon; instead, distant lands arc overhead. Navigation relies on the inner sun\'s position, and weather systems spiral in inverted patterns. Civilizations on the interior may be entirely unaware of the exterior world, and vice versa.',
      fields: {
        body_type: 'planet',
        composition: 'rocky',
        surface_gravity: '7.2 m/s² on outer surface, 6.8 m/s² on inner surface',
        atmosphere_description: 'The interior atmosphere is denser and warmer than the exterior, trapped by the shell. Clouds form at the midpoint between the inner surface and the core sun, creating a permanent band of weather. Light diffuses evenly, so the interior knows no night — only dimming when the core sun pulses.',
      },
    },
    {
      id: 'crystal_sphere',
      name: 'Crystal Sphere',
      description: 'The cosmos enclosed in a literal crystalline shell — the stars are imperfections in the crystal, and the edge of the universe is a wall you can touch.',
      element_type: 'nebula',
      summary: 'A finite universe bounded by a crystalline firmament, with stars as flaws in the shell',
      detailed_notes: 'In this cosmology, the universe is not infinite but enclosed within an immense sphere of translucent crystal. What appear to be stars are actually cracks, inclusions, and imperfections in the crystal that allow light from whatever lies beyond to leak through. The sphere rotates slowly, which is why the stars appear to move. Expeditions to reach the edge have returned with fragments of the crystal — a material harder than diamond that hums with residual energy. Theologians debate whether the sphere is a prison, a womb, or a lens. The largest crack in the sphere is visible as a nebula-like smear of light, and it appears to be growing.',
      fields: {
        composition: 'unknown',
        atmosphere_description: 'Near the crystal boundary, the atmosphere thins to nothing — but the crystal itself radiates a faint warmth. Explorers report a low harmonic vibration audible in the silence of near-vacuum, as though the sphere is resonating. Dust and debris accumulate against the inner surface, forming a shell of dead comets and lost ships.',
      },
    },
    {
      id: 'dyson_sphere',
      name: 'Dyson Shell',
      description: 'A star enclosed in an artificial shell — civilizations live on the inner surface. Sci-fi cosmology.',
      element_type: 'planet',
      summary: 'An artificial megastructure enclosing a star, with civilizations inhabiting the inner surface',
      detailed_notes: 'The Dyson Shell is the ultimate expression of a civilization\'s mastery over stellar engineering. An entire star has been enclosed within a rigid artificial sphere, capturing all of its radiant energy. The inner surface — incomprehensibly vast — is habitable, lit by the captive sun at the center. Gravity is simulated through rotation or technological means. Entire continents, oceans, and mountain ranges have been constructed on the interior, and populations numbering in the trillions live their lives unaware that their "sky" is a sun and their "ground" curves upward in every direction. The shell\'s exterior is dark and cold, visible from outside only as a void where a star used to be. The engineering challenges are staggering: structural integrity, heat dissipation, and the sheer material required suggest a civilization that dismantled every planet in the system to build their shell.',
      fields: {
        body_type: 'planet',
        composition: 'metallic',
        surface_gravity: '9.8 m/s² (artificially maintained)',
        atmosphere_description: 'Engineered nitrogen-oxygen atmosphere contained by the shell. Weather systems are partially artificial, managed by climate engines embedded in the shell structure. The sky is dominated by the enclosed star, which never sets — day and night are simulated by massive orbiting shades.',
      },
    },
    {
      id: 'dream_sun',
      name: 'Dream Sun',
      description: 'A star that exists only while a god sleeps. If the god wakes, the star vanishes and the world goes dark.',
      element_type: 'star',
      summary: 'A star sustained by the slumber of a dreaming deity — fragile, sacred, and terrifying in its impermanence',
      detailed_notes: 'The Dream Sun is not a ball of plasma held together by gravity and fusion. It is a thought — a radiant dream burning in the mind of a sleeping god. As long as the god slumbers, the sun blazes in the sky, warming the worlds that orbit it and sustaining all life in the system. But the sun flickers. Sometimes it dims for hours or days, and scholars have correlated these episodes with disturbances near the god\'s resting place. Entire religions are built around keeping the god asleep: monks chant lullabies that resonate through the divine frequency, assassins eliminate anyone who might cause a disturbance, and heretics who seek to wake the god are hunted with fanatical urgency. The existential terror is absolute — if the god wakes, the sun winks out, and everything dies. Some philosophers wonder what the god dreams of, and whether the world itself is part of that dream.',
      fields: {
        body_type: 'star',
        composition: 'energy',
        luminosity: 'Variable — dims during the god\'s restless episodes, brightens during deep sleep. Average output approximately 1.0 solar luminosities.',
      },
    },
    {
      id: 'shattered_moon',
      name: 'Shattered Moon',
      description: 'A moon broken into orbiting fragments. The debris ring creates spectacular night skies and periodic meteor showers.',
      element_type: 'moon',
      summary: 'The remnants of a destroyed moon, now a glittering ring of debris producing spectacular meteor showers',
      detailed_notes: 'Something destroyed the moon. Whether it was a cosmic impact, a weapons test by a forgotten civilization, or the wrath of a deity, the result is the same: where a solid moon once orbited, there is now a slowly dispersing cloud of fragments ranging from dust motes to city-sized boulders. The debris has settled into a rough ring around the planet, creating a luminous arc across the night sky that is hauntingly beautiful. Periodically, fragments descend through the atmosphere as meteor showers — some predictable and celebrated as festivals, others chaotic and destructive. The largest fragments retain enough gravity to be miniature worlds of their own, and some civilizations have established outposts on them. Tidal patterns on the planet below have been permanently disrupted, and coastlines are still adjusting centuries after the shattering.',
      fields: {
        body_type: 'moon',
        composition: 'rocky',
        orbital_period: 'Fragments orbit at varying speeds — inner debris completes an orbit in 12 days, outer fragments in 45 days. The original moon had a 28-day period.',
      },
    },
  ],
  defaultSortField: 'body_type',
};
