import type { DomainConfig } from '../types/domains.js';

export const cosmologyConfig: DomainConfig = {
  id: 'cosmology',
  name: 'Cosmology',
  namePlural: 'Celestial Bodies',
  icon: 'star',
  color: '#e8c547',
  description: 'Define the stars, planets, moons, and other celestial bodies that make up your world\'s universe. Establish orbital mechanics, creation myths, and the structure of the cosmos.',
  tableName: 'celestial_bodies',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'select',
      required: true,
      options: ['star', 'planet', 'moon', 'asteroid', 'ring', 'comet', 'nebula'],
      helpText: 'The classification of this celestial body.',
    },
    {
      name: 'composition',
      label: 'Composition',
      type: 'select',
      options: ['rocky', 'gas_giant', 'ice_giant', 'metallic', 'plasma', 'mixed', 'energy', 'unknown'],
      helpText: 'The primary material composition of this celestial body.',
    },
    {
      name: 'mass',
      label: 'Mass',
      type: 'text',
      placeholder: 'e.g. 1.0 solar masses, 5.97e24 kg',
      helpText: 'Mass of the body in your preferred units.',
    },
    {
      name: 'radius',
      label: 'Radius',
      type: 'text',
      placeholder: 'e.g. 6,371 km',
      helpText: 'Mean radius of the body.',
    },
    {
      name: 'orbital_period',
      label: 'Orbital Period',
      type: 'text',
      placeholder: 'e.g. 365.25 days',
      helpText: 'Time to complete one orbit around its parent body.',
    },
    {
      name: 'orbital_parent_id',
      label: 'Orbital Parent',
      type: 'text',
      placeholder: 'ID of the body this orbits',
      helpText: 'The celestial body this object orbits around.',
    },
    {
      name: 'axial_tilt',
      label: 'Axial Tilt',
      type: 'text',
      placeholder: 'e.g. 23.4°',
      helpText: 'Tilt of the rotational axis, which affects seasons.',
    },
    {
      name: 'day_length',
      label: 'Day Length',
      type: 'text',
      placeholder: 'e.g. 24 hours',
      helpText: 'Duration of one full rotation.',
    },
    {
      name: 'surface_gravity',
      label: 'Surface Gravity',
      type: 'text',
      placeholder: 'e.g. 9.8 m/s²',
      helpText: 'Gravitational pull at the surface.',
    },
    {
      name: 'luminosity',
      label: 'Luminosity',
      type: 'text',
      placeholder: 'e.g. 1.0 solar luminosities',
      helpText: 'Total energy output (primarily for stars).',
    },
    {
      name: 'atmosphere_description',
      label: 'Atmosphere Description',
      type: 'textarea',
      placeholder: 'Describe the atmosphere, if any...',
      helpText: 'A brief description of the atmospheric composition and conditions.',
    },
  ],
  elementTypes: ['star', 'planet', 'moon', 'asteroid', 'comet', 'ring_system', 'nebula'],
  prompts: [
    'How many suns does your world orbit? Does the star system have unusual properties that affect life?',
    'What do the night skies look like? Are there multiple moons, visible planets, or permanent celestial features?',
    'How do the orbital mechanics of your world create seasons, tides, and day/night cycles?',
    'What creation myths do the inhabitants tell about the origin of the cosmos?',
    'Are there any celestial events (eclipses, conjunctions, comet passages) that hold cultural or practical significance?',
  ],
  magicPermeation: {
    companionTable: 'cosmology_magic_aspects',
    fields: [
      {
        name: 'magical_celestial_bodies',
        label: 'Magical Celestial Bodies',
        type: 'textarea',
        helpText: 'Celestial bodies with inherent magical properties or significance.',
      },
      {
        name: 'astral_plane_relationship',
        label: 'Astral Plane Relationship',
        type: 'textarea',
        helpText: 'How this body relates to or overlaps with the astral plane.',
      },
      {
        name: 'dimensional_cosmology',
        label: 'Dimensional Cosmology',
        type: 'textarea',
        helpText: 'The dimensional structure of the cosmos and how planes layer or intersect.',
      },
      {
        name: 'cosmic_magic_sources',
        label: 'Cosmic Magic Sources',
        type: 'textarea',
        helpText: 'Sources of magical energy at the cosmic scale (stellar mana, void energy, etc.).',
      },
      {
        name: 'celestial_alignments_effects',
        label: 'Celestial Alignment Effects',
        type: 'textarea',
        helpText: 'How alignments of celestial bodies affect magic in the world.',
      },
      {
        name: 'creation_myth_magical',
        label: 'Magical Creation Myth',
        type: 'textarea',
        helpText: 'The role of magic in the creation of the cosmos.',
      },
      {
        name: 'cosmic_entities',
        label: 'Cosmic Entities',
        type: 'textarea',
        helpText: 'Beings of cosmic scale that inhabit or influence the celestial realm.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the cosmological nature of this body.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'Do celestial alignments amplify or dampen magical energy? Are there cosmic ley lines between stars?',
      'Is the cosmos itself a magical construct, or did magic arise within it naturally?',
      'Are there cosmic entities—star gods, void beings—whose movements affect the magical tides of your world?',
    ],
  },
  archetypes: [
    {
      id: 'habitable_planet',
      name: 'Habitable Planet',
      description: 'A rocky world in the habitable zone with liquid water and a breathable atmosphere.',
      element_type: 'planet',
      summary: "A terrestrial world orbiting within its star's habitable zone",
      fields: {
        body_type: 'planet',
        composition: 'rocky',
        surface_gravity: '9.8 m/s²',
        axial_tilt: '20-25°',
        day_length: '20-28 hours',
        atmosphere_description: 'Nitrogen-oxygen atmosphere capable of supporting complex life. Moderate greenhouse effect maintains stable surface temperatures.',
      },
    },
    {
      id: 'gas_giant',
      name: 'Gas Giant',
      description: 'A massive planet with no solid surface, surrounded by swirling bands of cloud.',
      element_type: 'planet',
      summary: 'A massive gas giant with swirling cloud bands and numerous moons',
      fields: {
        body_type: 'planet',
        composition: 'gas_giant',
        mass: '~300 Earth masses',
        radius: '~70,000 km',
        day_length: '10-14 hours',
        atmosphere_description: 'Thick layers of hydrogen and helium with bands of ammonia and methane clouds. Violent storms rage across the surface.',
      },
    },
    {
      id: 'red_dwarf_star',
      name: 'Red Dwarf Star',
      description: 'A small, cool, long-lived star — the most common type in many universes.',
      element_type: 'star',
      summary: 'A dim, long-lived red dwarf star',
      fields: {
        body_type: 'star',
        composition: 'plasma',
        luminosity: '0.01-0.08 solar luminosities',
        mass: '0.1-0.5 solar masses',
        radius: '~200,000 km',
      },
    },
    {
      id: 'major_moon',
      name: 'Major Moon',
      description: 'A large natural satellite, potentially tidally locked and geologically active.',
      element_type: 'moon',
      summary: 'A large natural satellite with its own geological character',
      fields: {
        body_type: 'moon',
        composition: 'rocky',
        surface_gravity: '1.6-3.0 m/s²',
        atmosphere_description: 'Thin or absent atmosphere, possibly with volcanic outgassing creating temporary local haze.',
      },
    },
    {
      id: 'dying_god_star',
      name: 'Dying God-Star',
      description: 'A star that is the smoldering corpse of a dead deity — still radiating divine energy as it slowly fades.',
      element_type: 'star',
      summary: 'The remains of a fallen god, burning with fading divine light',
      fields: {
        body_type: 'star',
        composition: 'energy',
        luminosity: 'Erratic — pulses with divine resonance, brighter during prayer',
        mass: 'Impossible to measure; gravitational pull fluctuates with faith',
        atmosphere_description: 'The corona is not plasma but luminous ichor — the divine blood of the dead god. Ships passing through report visions, prophecies, and madness.',
      },
    },
    {
      id: 'wandering_world',
      name: 'Wandering Rogue Planet',
      description: 'A planet cast out of its star system, drifting through interstellar void with a frozen surface hiding a warm interior.',
      element_type: 'planet',
      summary: 'A starless world drifting through the void, warmed only from within',
      fields: {
        body_type: 'planet',
        composition: 'rocky',
        surface_gravity: '12.5 m/s²',
        luminosity: 'None — no parent star, perpetual darkness on the surface',
        atmosphere_description: 'A thick nitrogen atmosphere frozen into surface ice. Geothermal vents create pockets of warmth and breathable air in deep valleys, where eyeless ecosystems thrive.',
      },
    },
  ],
  defaultSortField: 'body_type',
};
