import type { DomainConfig } from '../types/domains.js';

export const cosmologyConfig: DomainConfig = {
  id: 'cosmology',
  name: 'Cosmology',
  namePlural: 'Celestial Bodies',
  icon: 'star',
  color: '#e8c547',
  description: 'Define the stars, planets, moons, and other celestial bodies that make up your world\'s universe. Establish orbital mechanics, creation myths, and the structure of the cosmos.',
  tableName: 'celestial_bodies',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'select',
      required: true,
      options: ['star', 'planet', 'moon', 'asteroid', 'ring', 'comet', 'nebula'],
      helpText: 'The classification of this celestial body.',
    },
    {
      name: 'mass',
      label: 'Mass',
      type: 'text',
      placeholder: 'e.g. 1.0 solar masses, 5.97e24 kg',
      helpText: 'Mass of the body in your preferred units.',
    },
    {
      name: 'radius',
      label: 'Radius',
      type: 'text',
      placeholder: 'e.g. 6,371 km',
      helpText: 'Mean radius of the body.',
    },
    {
      name: 'orbital_period',
      label: 'Orbital Period',
      type: 'text',
      placeholder: 'e.g. 365.25 days',
      helpText: 'Time to complete one orbit around its parent body.',
    },
    {
      name: 'orbital_parent_id',
      label: 'Orbital Parent',
      type: 'text',
      placeholder: 'ID of the body this orbits',
      helpText: 'The celestial body this object orbits around.',
    },
    {
      name: 'axial_tilt',
      label: 'Axial Tilt',
      type: 'text',
      placeholder: 'e.g. 23.4°',
      helpText: 'Tilt of the rotational axis, which affects seasons.',
    },
    {
      name: 'day_length',
      label: 'Day Length',
      type: 'text',
      placeholder: 'e.g. 24 hours',
      helpText: 'Duration of one full rotation.',
    },
    {
      name: 'surface_gravity',
      label: 'Surface Gravity',
      type: 'text',
      placeholder: 'e.g. 9.8 m/s²',
      helpText: 'Gravitational pull at the surface.',
    },
    {
      name: 'luminosity',
      label: 'Luminosity',
      type: 'text',
      placeholder: 'e.g. 1.0 solar luminosities',
      helpText: 'Total energy output (primarily for stars).',
    },
    {
      name: 'atmosphere_description',
      label: 'Atmosphere Description',
      type: 'textarea',
      placeholder: 'Describe the atmosphere, if any...',
      helpText: 'A brief description of the atmospheric composition and conditions.',
    },
  ],
  elementTypes: ['star', 'planet', 'moon', 'asteroid', 'comet', 'ring_system', 'nebula'],
  prompts: [
    'How many suns does your world orbit? Does the star system have unusual properties that affect life?',
    'What do the night skies look like? Are there multiple moons, visible planets, or permanent celestial features?',
    'How do the orbital mechanics of your world create seasons, tides, and day/night cycles?',
    'What creation myths do the inhabitants tell about the origin of the cosmos?',
    'Are there any celestial events (eclipses, conjunctions, comet passages) that hold cultural or practical significance?',
  ],
  magicPermeation: {
    companionTable: 'cosmology_magic_aspects',
    fields: [
      {
        name: 'magical_celestial_bodies',
        label: 'Magical Celestial Bodies',
        type: 'textarea',
        helpText: 'Celestial bodies with inherent magical properties or significance.',
      },
      {
        name: 'astral_plane_relationship',
        label: 'Astral Plane Relationship',
        type: 'textarea',
        helpText: 'How this body relates to or overlaps with the astral plane.',
      },
      {
        name: 'dimensional_cosmology',
        label: 'Dimensional Cosmology',
        type: 'textarea',
        helpText: 'The dimensional structure of the cosmos and how planes layer or intersect.',
      },
      {
        name: 'cosmic_magic_sources',
        label: 'Cosmic Magic Sources',
        type: 'textarea',
        helpText: 'Sources of magical energy at the cosmic scale (stellar mana, void energy, etc.).',
      },
      {
        name: 'celestial_alignments_effects',
        label: 'Celestial Alignment Effects',
        type: 'textarea',
        helpText: 'How alignments of celestial bodies affect magic in the world.',
      },
      {
        name: 'creation_myth_magical',
        label: 'Magical Creation Myth',
        type: 'textarea',
        helpText: 'The role of magic in the creation of the cosmos.',
      },
      {
        name: 'cosmic_entities',
        label: 'Cosmic Entities',
        type: 'textarea',
        helpText: 'Beings of cosmic scale that inhabit or influence the celestial realm.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the cosmological nature of this body.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'Do celestial alignments amplify or dampen magical energy? Are there cosmic ley lines between stars?',
      'Is the cosmos itself a magical construct, or did magic arise within it naturally?',
      'Are there cosmic entities—star gods, void beings—whose movements affect the magical tides of your world?',
    ],
  },
  defaultSortField: 'body_type',
};
