import type { DomainConfig } from '../types/domains.js';

export const culturesConfig: DomainConfig = {
  id: 'cultures',
  name: 'Culture',
  namePlural: 'Cultures',
  icon: 'palette',
  color: '#e74c3c',
  description: 'Define the living traditions, beliefs, languages, and customs that give your world\'s peoples their identity. Cultures exist within and across civilizations, carried by communities through art, ritual, cuisine, and shared memory.',
  tableName: 'cultures',
  category: 'sentient',
  fields: [
    {
      name: 'civilization_id',
      label: 'Parent Civilization',
      type: 'text',
      placeholder: 'ID of the civilization this culture belongs to',
      helpText: 'The civilization within which this culture primarily exists, if any.',
    },
    {
      name: 'language_name',
      label: 'Language Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. Old Elvish, Trade Common, Deepspeak',
      helpText: 'The primary language spoken by this cultural group.',
    },
    {
      name: 'writing_system',
      label: 'Writing System',
      type: 'text',
      placeholder: 'e.g. runic, logographic, alphabetic, none (oral tradition)',
      helpText: 'The writing system used, if any.',
    },
    {
      name: 'religion_name',
      label: 'Primary Religion',
      type: 'text',
      placeholder: 'e.g. The Path of Embers, Ancestor Worship, secular',
      helpText: 'The dominant religious or spiritual tradition.',
    },
    {
      name: 'values',
      label: 'Core Values',
      type: 'json',
      placeholder: '["honor", "knowledge", "community", "individual freedom"]',
      helpText: 'The fundamental values that guide behavior and judgment in this culture.',
    },
    {
      name: 'customs',
      label: 'Customs & Traditions',
      type: 'json',
      placeholder: '["coming-of-age trials", "harvest festivals", "ancestor shrines"]',
      helpText: 'Key customs, rituals, and social practices.',
    },
    {
      name: 'art_forms',
      label: 'Art Forms',
      type: 'json',
      placeholder: '["tapestry weaving", "bone carving", "throat singing"]',
      helpText: 'Distinctive artistic expressions and creative traditions.',
    },
    {
      name: 'cuisine',
      label: 'Cuisine',
      type: 'textarea',
      placeholder: 'Describe staple foods, cooking methods, dining customs...',
      helpText: 'Distinctive foods, preparation methods, and dining traditions.',
    },
    {
      name: 'architecture_style',
      label: 'Architecture Style',
      type: 'text',
      placeholder: 'e.g. living-wood towers, underground warrens, floating platforms',
      helpText: 'Characteristic architectural forms and building philosophy.',
    },
    {
      name: 'social_hierarchy',
      label: 'Social Hierarchy',
      type: 'textarea',
      placeholder: 'Describe the social classes, mobility, and status markers...',
      helpText: 'How this culture organizes social status—caste, merit, wealth, age, magical ability.',
    },
  ],
  elementTypes: ['ethnic_group', 'subculture', 'religious_order', 'guild', 'academic_tradition', 'artistic_movement', 'custom'],
  prompts: [
    'What do the people of this culture consider a life well lived? What virtues do they teach their children above all else?',
    'How do members of this culture mark the major transitions of life—birth, coming of age, marriage, death?',
    'What foods are considered sacred, celebratory, or taboo? Does cuisine reflect the culture\'s history of abundance, scarcity, or trade?',
    'How does this culture relate to outsiders? Are they welcoming, isolationist, or something more complex?',
    'What stories do they tell about themselves? What is the founding myth, and how does it differ from historical reality?',
  ],
  magicPermeation: {
    companionTable: 'cultures_magic_aspects',
    fields: [
      {
        name: 'magical_traditions',
        label: 'Magical Traditions',
        type: 'textarea',
        helpText: 'Distinct magical practices passed down through this culture—hedge magic, ancestral summoning, dream-walking, etc.',
      },
      {
        name: 'arcane_religions',
        label: 'Arcane Religions',
        type: 'textarea',
        helpText: 'Religions or spiritual practices centered around magical forces, deities of magic, or mana worship.',
      },
      {
        name: 'magical_art',
        label: 'Magical Art',
        type: 'textarea',
        helpText: 'Art forms that incorporate magic—illusion theater, enchanted music, living sculptures, spell-woven tapestries.',
      },
      {
        name: 'magical_festivals',
        label: 'Magical Festivals',
        type: 'textarea',
        helpText: 'Celebrations tied to magical events—mana tides, solstice surges, ley line alignments, summoning days.',
      },
      {
        name: 'magical_rites',
        label: 'Magical Rites of Passage',
        type: 'textarea',
        helpText: 'Life transitions marked by magical rituals—awakening ceremonies, binding oaths, spirit journeys.',
      },
      {
        name: 'attitudes_toward_practitioners',
        label: 'Attitudes Toward Practitioners',
        type: 'textarea',
        helpText: 'How this culture views magic users—as priests, scholars, dangers, servants, or something else entirely.',
      },
      {
        name: 'folk_magic',
        label: 'Folk Magic',
        type: 'textarea',
        helpText: 'Everyday magical practices of common people—ward signs, charm bags, blessing rituals, kitchen witchery.',
      },
      {
        name: 'magical_taboos',
        label: 'Magical Taboos',
        type: 'textarea',
        helpText: 'Types of magic considered forbidden, immoral, or dangerous within this culture—necromancy, blood magic, mind control.',
      },
      {
        name: 'magical_language',
        label: 'Magical Language',
        type: 'textarea',
        helpText: 'How the culture\'s language incorporates magical concepts—spell words, true names, power syllables, arcane grammar.',
      },
      {
        name: 'magical_cuisine',
        label: 'Magical Cuisine',
        type: 'textarea',
        helpText: 'Foods and beverages with magical properties—mana-infused drinks, enchanted feasts, alchemical cooking.',
      },
      {
        name: 'magical_fashion',
        label: 'Magical Fashion',
        type: 'textarea',
        helpText: 'Enchanted clothing, warded jewelry, status-indicating magical accessories, glamour-based fashion.',
      },
      {
        name: 'magical_oral_traditions',
        label: 'Magical Oral Traditions',
        type: 'textarea',
        helpText: 'Stories, songs, and spoken traditions that carry magical power—true histories, prophecy ballads, naming songs.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this culture\'s identity and daily life.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'How does this culture\'s relationship with magic shape its art, music, and storytelling? Are there art forms that literally cannot exist without magic?',
      'What magical practices are considered sacred versus profane? Do folk magic and institutional magic coexist or conflict?',
      'How do magical taboos reflect deeper cultural values? Is necromancy forbidden because of reverence for the dead, or fear of what the dead might say?',
    ],
  },
  defaultSortField: 'language_name',
};
