import type { DomainConfig } from '../types/domains.js';

export const culturesConfig: DomainConfig = {
  id: 'cultures',
  name: 'Culture',
  namePlural: 'Cultures',
  icon: 'palette',
  color: '#e74c3c',
  description: 'Define the living traditions, beliefs, languages, and customs that give your world\'s peoples their identity. Cultures exist within and across civilizations, carried by communities through art, ritual, cuisine, and shared memory.',
  tableName: 'cultures',
  category: 'sentient',
  fields: [
    {
      name: 'civilization_ids',
      label: 'Civilizations',
      type: 'json',
      placeholder: '["civilization_id_1", "civilization_id_2"]',
      helpText: 'The civilizations this culture exists within — cultures can span multiple civilizations or exist independently.',
    },
    {
      name: 'language_name',
      label: 'Language Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. Old Elvish, Trade Common, Deepspeak',
      helpText: 'The primary language spoken by this cultural group.',
    },
    {
      name: 'writing_system',
      label: 'Writing System',
      type: 'text',
      placeholder: 'e.g. runic, logographic, alphabetic, none (oral tradition)',
      helpText: 'The writing system used, if any.',
    },
    {
      name: 'religion_name',
      label: 'Primary Religion',
      type: 'text',
      placeholder: 'e.g. The Path of Embers, Ancestor Worship, secular',
      helpText: 'The dominant religious or spiritual tradition.',
    },
    {
      name: 'values',
      label: 'Core Values',
      type: 'json',
      placeholder: '["honor", "knowledge", "community", "individual freedom"]',
      helpText: 'The fundamental values that guide behavior and judgment in this culture.',
    },
    {
      name: 'customs',
      label: 'Customs & Traditions',
      type: 'json',
      placeholder: '["coming-of-age trials", "harvest festivals", "ancestor shrines"]',
      helpText: 'Key customs, rituals, and social practices.',
    },
    {
      name: 'art_forms',
      label: 'Art Forms',
      type: 'json',
      placeholder: '["tapestry weaving", "bone carving", "throat singing"]',
      helpText: 'Distinctive artistic expressions and creative traditions.',
    },
    {
      name: 'cuisine',
      label: 'Cuisine',
      type: 'textarea',
      placeholder: 'Describe staple foods, cooking methods, dining customs...',
      helpText: 'Distinctive foods, preparation methods, and dining traditions.',
    },
    {
      name: 'architecture_style',
      label: 'Architecture Style',
      type: 'text',
      placeholder: 'e.g. living-wood towers, underground warrens, floating platforms',
      helpText: 'Characteristic architectural forms and building philosophy.',
    },
    {
      name: 'social_hierarchy',
      label: 'Social Hierarchy',
      type: 'textarea',
      placeholder: 'Describe the social classes, mobility, and status markers...',
      helpText: 'How this culture organizes social status—caste, merit, wealth, age, magical ability.',
    },
    {
      name: 'funerary_practices',
      label: 'Funerary Practices',
      type: 'textarea',
      placeholder: 'Describe death rites, burial customs, mourning traditions...',
      helpText: 'How this culture handles death — burial, cremation, sky burial, ancestor rites, mourning periods.',
    },
    {
      name: 'family_structure',
      label: 'Family Structure',
      type: 'textarea',
      placeholder: 'Describe kinship systems, marriage customs, household composition...',
      helpText: 'Kinship systems, marriage customs, household structures, and family obligations.',
    },
    {
      name: 'calendar_system',
      label: 'Calendar System',
      type: 'textarea',
      placeholder: 'Describe how time is measured — months, festivals, eras...',
      helpText: 'How this culture measures and marks time — calendar structure, significant dates, era reckoning.',
    },
  ],
  elementTypes: ['ethnic_group', 'subculture', 'religious_order', 'guild', 'academic_tradition', 'artistic_movement', 'custom'],
  prompts: [
    'What do the people of this culture consider a life well lived? What virtues do they teach their children above all else?',
    'How do members of this culture mark the major transitions of life—birth, coming of age, marriage, death?',
    'What foods are considered sacred, celebratory, or taboo? Does cuisine reflect the culture\'s history of abundance, scarcity, or trade?',
    'How does this culture relate to outsiders? Are they welcoming, isolationist, or something more complex?',
    'What stories do they tell about themselves? What is the founding myth, and how does it differ from historical reality?',
  ],
  magicPermeation: {
    companionTable: 'cultures_magic_aspects',
    fields: [
      {
        name: 'magical_traditions',
        label: 'Magical Traditions',
        type: 'textarea',
        helpText: 'Distinct magical practices passed down through this culture—hedge magic, ancestral summoning, dream-walking, etc.',
      },
      {
        name: 'arcane_religions',
        label: 'Arcane Religions',
        type: 'textarea',
        helpText: 'Religions or spiritual practices centered around magical forces, deities of magic, or mana worship.',
      },
      {
        name: 'magical_art',
        label: 'Magical Art',
        type: 'textarea',
        helpText: 'Art forms that incorporate magic—illusion theater, enchanted music, living sculptures, spell-woven tapestries.',
      },
      {
        name: 'magical_festivals',
        label: 'Magical Festivals',
        type: 'textarea',
        helpText: 'Celebrations tied to magical events—mana tides, solstice surges, ley line alignments, summoning days.',
      },
      {
        name: 'magical_rites',
        label: 'Magical Rites of Passage',
        type: 'textarea',
        helpText: 'Life transitions marked by magical rituals—awakening ceremonies, binding oaths, spirit journeys.',
      },
      {
        name: 'attitudes_toward_practitioners',
        label: 'Attitudes Toward Practitioners',
        type: 'textarea',
        helpText: 'How this culture views magic users—as priests, scholars, dangers, servants, or something else entirely.',
      },
      {
        name: 'folk_magic',
        label: 'Folk Magic',
        type: 'textarea',
        helpText: 'Everyday magical practices of common people—ward signs, charm bags, blessing rituals, kitchen witchery.',
      },
      {
        name: 'magical_taboos',
        label: 'Magical Taboos',
        type: 'textarea',
        helpText: 'Types of magic considered forbidden, immoral, or dangerous within this culture—necromancy, blood magic, mind control.',
      },
      {
        name: 'magical_language',
        label: 'Magical Language',
        type: 'textarea',
        helpText: 'How the culture\'s language incorporates magical concepts—spell words, true names, power syllables, arcane grammar.',
      },
      {
        name: 'magical_cuisine',
        label: 'Magical Cuisine',
        type: 'textarea',
        helpText: 'Foods and beverages with magical properties—mana-infused drinks, enchanted feasts, alchemical cooking.',
      },
      {
        name: 'magical_fashion',
        label: 'Magical Fashion',
        type: 'textarea',
        helpText: 'Enchanted clothing, warded jewelry, status-indicating magical accessories, glamour-based fashion.',
      },
      {
        name: 'magical_oral_traditions',
        label: 'Magical Oral Traditions',
        type: 'textarea',
        helpText: 'Stories, songs, and spoken traditions that carry magical power—true histories, prophecy ballads, naming songs.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this culture\'s identity and daily life.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'How does this culture\'s relationship with magic shape its art, music, and storytelling? Are there art forms that literally cannot exist without magic?',
      'What magical practices are considered sacred versus profane? Do folk magic and institutional magic coexist or conflict?',
      'How do magical taboos reflect deeper cultural values? Is necromancy forbidden because of reverence for the dead, or fear of what the dead might say?',
    ],
  },
  archetypes: [
    {
      id: 'warrior_honor',
      name: 'Warrior Honor Culture',
      description: 'A martial culture built around personal honor, combat prowess, and loyalty to one\'s war-band.',
      element_type: 'ethnic_group',
      summary: 'A proud warrior culture where glory in battle is the highest virtue',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Runic script carved in stone and bone',
        religion_name: 'Ancestor and hero worship',
        architecture_style: 'Timber longhouses and hilltop fortifications',
        cuisine: 'Hearty fare — roasted meats, root vegetables, mead, and fermented dairy. Feasting is a central social ritual with strict seating hierarchy.',
        social_hierarchy: 'Warriors at the top, followed by free landowners, artisans, thralls. Status earned through combat deeds and gift-giving.',
        funerary_practices: 'Honored dead are cremated on pyres with their weapons and treasures. Great heroes receive ship burials.',
        family_structure: 'Extended clan-based households. Blood feuds between clans are common and can span generations.',
      },
    },
    {
      id: 'scholarly_tradition',
      name: 'Scholarly Tradition',
      description: 'A culture that venerates knowledge, debate, and the preservation of learning above all.',
      element_type: 'academic_tradition',
      summary: 'A culture that prizes wisdom, learning, and mastery of the written word',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Elaborate calligraphic script with thousands of characters',
        religion_name: 'Philosophical tradition emphasizing harmony and balance',
        architecture_style: 'Walled academy complexes with libraries, observatories, and meditation gardens',
        cuisine: 'Simple, refined meals emphasizing balance of flavors. Tea ceremonies are a major social institution.',
        social_hierarchy: 'Scholar-officials at the top, selected by rigorous examination. Merchants rank below farmers in social theory, though not in practice.',
        funerary_practices: 'Elaborate ancestor veneration with family shrines. The names and writings of great scholars are preserved for centuries.',
        family_structure: 'Multigenerational households with strong filial obligations. Education of children is the paramount family duty.',
      },
    },
    {
      id: 'maritime_traders',
      name: 'Maritime Traders',
      description: 'A seafaring culture of merchants, navigators, and explorers who call the ocean home.',
      element_type: 'ethnic_group',
      summary: 'A salt-sprayed people whose home is the deck of a ship',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Practical alphabetic script optimized for contracts and navigation logs',
        religion_name: 'Polytheistic — sea gods, wind spirits, and star-guides',
        architecture_style: 'Stilted waterfront buildings and fortified harbors with lighthouse towers',
        cuisine: 'Seafood-heavy diet with preserved foods for long voyages — salted fish, hardtack, citrus fruits. Spice trade influences exotic blends.',
        social_hierarchy: 'Ship captains and successful merchants hold highest status. Navigators are revered as near-priests. Landlocked peoples are viewed with mild pity.',
        funerary_practices: 'The dead are committed to the sea in weighted shrouds. Captains are set adrift in their ships with the tide.',
        family_structure: 'Fluid households — one parent often at sea for months. Extended dockside communities raise children collectively.',
      },
    },
    {
      id: 'agrarian_folk',
      name: 'Agrarian Folk Culture',
      description: 'A rooted, land-loving culture centered on farming, seasonal festivals, and community bonds.',
      element_type: 'ethnic_group',
      summary: 'A warm, rooted people whose lives follow the rhythm of the seasons',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Simple phonetic script, primarily oral tradition',
        religion_name: 'Earth-mother worship and seasonal fertility rites',
        architecture_style: 'Thatched stone cottages, communal barns, and village greens',
        cuisine: 'Seasonal, locally sourced — bread, cheese, preserved vegetables, orchard fruits. Harvest feasts and midsummer cookouts are cultural keystones.',
        social_hierarchy: 'Relatively egalitarian. Village elders and large landowners have authority, but communal decision-making is the norm.',
        funerary_practices: 'Buried in family plots on their own land, with a fruit tree planted over the grave. Annual remembrance at harvest time.',
        family_structure: 'Nuclear families within tight village communities. Barn-raisings and harvest cooperation bind neighbors together.',
      },
    },
    {
      id: 'dream_weavers',
      name: 'Dream Weaver Culture',
      description: 'A culture built around shared dreaming — architecture, law, and art all exist primarily in the dream world.',
      element_type: 'subculture',
      summary: 'A people who live half their lives in a shared dreamscape they shape together',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Dream-glyphs — symbols that trigger specific dream-images when viewed before sleep. Their libraries are pillows.',
        religion_name: 'The Collective Dream — the shared dreamscape is considered sacred, and skilled dreamers are the clergy',
        architecture_style: 'Waking-world structures are simple dormitories optimized for comfortable sleep. The true cities exist only in the shared dream — impossible spires, inverted oceans, and gardens of living light.',
        cuisine: 'Light meals designed not to disrupt sleep. Herbal teas that deepen dreaming are the cultural staple. Feasting happens in the dream world where taste has no caloric limit.',
        social_hierarchy: 'Lucid dreamers — those who can shape the shared dreamscape — hold the highest status. Dream-blind individuals (who cannot enter the shared dream) are a pitied underclass.',
        funerary_practices: 'The dying perform a final dream-walk, leaving an echo of themselves in the shared dreamscape. The greatest dreamers persist as permanent dream-ghosts, becoming landmarks.',
        family_structure: 'Dream-families often matter more than blood families. Children are raised communally in dream-nurseries where they learn to shape reality before they learn to walk.',
      },
    },
  ],
  defaultSortField: 'language_name',
};
