import type { DomainConfig } from '../types/domains.js';

export const culturesConfig: DomainConfig = {
  id: 'cultures',
  name: 'Culture',
  namePlural: 'Cultures',
  icon: 'palette',
  color: '#e74c3c',
  description: 'Define the living traditions, beliefs, languages, and customs that give your world\'s peoples their identity. Cultures exist within and across civilizations, carried by communities through art, ritual, cuisine, and shared memory.',
  tableName: 'cultures',
  category: 'sentient',
  fields: [
    {
      name: 'civilization_ids',
      label: 'Civilizations',
      type: 'json',
      placeholder: '["civilization_id_1", "civilization_id_2"]',
      helpText: 'The civilizations this culture exists within — cultures can span multiple civilizations or exist independently.',
    },
    {
      name: 'language_name',
      label: 'Language Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. Old Elvish, Trade Common, Deepspeak',
      helpText: 'The primary language spoken by this cultural group.',
    },
    {
      name: 'writing_system',
      label: 'Writing System',
      type: 'text',
      placeholder: 'e.g. runic, logographic, alphabetic, none (oral tradition)',
      helpText: 'The writing system used, if any.',
    },
    {
      name: 'religion_name',
      label: 'Primary Religion',
      type: 'text',
      placeholder: 'e.g. The Path of Embers, Ancestor Worship, secular',
      helpText: 'The dominant religious or spiritual tradition.',
    },
    {
      name: 'values',
      label: 'Core Values',
      type: 'json',
      placeholder: '["honor", "knowledge", "community", "individual freedom"]',
      helpText: 'The fundamental values that guide behavior and judgment in this culture.',
    },
    {
      name: 'customs',
      label: 'Customs & Traditions',
      type: 'json',
      placeholder: '["coming-of-age trials", "harvest festivals", "ancestor shrines"]',
      helpText: 'Key customs, rituals, and social practices.',
    },
    {
      name: 'art_forms',
      label: 'Art Forms',
      type: 'json',
      placeholder: '["tapestry weaving", "bone carving", "throat singing"]',
      helpText: 'Distinctive artistic expressions and creative traditions.',
    },
    {
      name: 'cuisine',
      label: 'Cuisine',
      type: 'textarea',
      placeholder: 'Describe staple foods, cooking methods, dining customs...',
      helpText: 'Distinctive foods, preparation methods, and dining traditions.',
    },
    {
      name: 'architecture_style',
      label: 'Architecture Style',
      type: 'text',
      placeholder: 'e.g. living-wood towers, underground warrens, floating platforms',
      helpText: 'Characteristic architectural forms and building philosophy.',
    },
    {
      name: 'social_hierarchy',
      label: 'Social Hierarchy',
      type: 'textarea',
      placeholder: 'Describe the social classes, mobility, and status markers...',
      helpText: 'How this culture organizes social status—caste, merit, wealth, age, magical ability.',
    },
    {
      name: 'funerary_practices',
      label: 'Funerary Practices',
      type: 'textarea',
      placeholder: 'Describe death rites, burial customs, mourning traditions...',
      helpText: 'How this culture handles death — burial, cremation, sky burial, ancestor rites, mourning periods.',
    },
    {
      name: 'family_structure',
      label: 'Family Structure',
      type: 'textarea',
      placeholder: 'Describe kinship systems, marriage customs, household composition...',
      helpText: 'Kinship systems, marriage customs, household structures, and family obligations.',
    },
    {
      name: 'calendar_system',
      label: 'Calendar System',
      type: 'textarea',
      placeholder: 'Describe how time is measured — months, festivals, eras...',
      helpText: 'How this culture measures and marks time — calendar structure, significant dates, era reckoning.',
    },
  ],
  elementTypes: ['ethnic_group', 'subculture', 'religious_order', 'guild', 'academic_tradition', 'artistic_movement', 'custom'],
  elementTypeDescriptions: {
    ethnic_group: 'A people defined by shared ancestry, language, and traditions. The broadest cultural unit, often spanning multiple civilizations.',
    subculture: 'A distinct community within a larger culture, defined by shared interests, practices, or identity that sets them apart.',
    religious_order: 'An organized group united by shared spiritual beliefs, rituals, and hierarchy. May wield significant social or political influence.',
    guild: 'A professional association of craftspeople, merchants, or specialists who regulate their trade and protect shared interests.',
    academic_tradition: 'A school of thought, scholarly institution, or intellectual lineage that preserves and advances knowledge in specific fields.',
    artistic_movement: 'A collective shift in creative expression — new styles, philosophies, or media that reshape how a culture sees itself.',
    custom: 'A cultural grouping that doesn\'t fit standard categories — something unique to your world.',
  },
  prompts: [
    'What do the people of this culture consider a life well lived? What virtues do they teach their children above all else?',
    'How do members of this culture mark the major transitions of life—birth, coming of age, marriage, death?',
    'What foods are considered sacred, celebratory, or taboo? Does cuisine reflect the culture\'s history of abundance, scarcity, or trade?',
    'How does this culture relate to outsiders? Are they welcoming, isolationist, or something more complex?',
    'What stories do they tell about themselves? What is the founding myth, and how does it differ from historical reality?',
  ],
  magicPermeation: {
    companionTable: 'cultures_magic_aspects',
    fields: [
      {
        name: 'magical_traditions',
        label: 'Magical Traditions',
        type: 'textarea',
        helpText: 'Distinct magical practices passed down through this culture—hedge magic, ancestral summoning, dream-walking, etc.',
      },
      {
        name: 'arcane_religions',
        label: 'Arcane Religions',
        type: 'textarea',
        helpText: 'Religions or spiritual practices centered around magical forces, deities of magic, or mana worship.',
      },
      {
        name: 'magical_art',
        label: 'Magical Art',
        type: 'textarea',
        helpText: 'Art forms that incorporate magic—illusion theater, enchanted music, living sculptures, spell-woven tapestries.',
      },
      {
        name: 'magical_festivals',
        label: 'Magical Festivals',
        type: 'textarea',
        helpText: 'Celebrations tied to magical events—mana tides, solstice surges, ley line alignments, summoning days.',
      },
      {
        name: 'magical_rites',
        label: 'Magical Rites of Passage',
        type: 'textarea',
        helpText: 'Life transitions marked by magical rituals—awakening ceremonies, binding oaths, spirit journeys.',
      },
      {
        name: 'attitudes_toward_practitioners',
        label: 'Attitudes Toward Practitioners',
        type: 'textarea',
        helpText: 'How this culture views magic users—as priests, scholars, dangers, servants, or something else entirely.',
      },
      {
        name: 'folk_magic',
        label: 'Folk Magic',
        type: 'textarea',
        helpText: 'Everyday magical practices of common people—ward signs, charm bags, blessing rituals, kitchen witchery.',
      },
      {
        name: 'magical_taboos',
        label: 'Magical Taboos',
        type: 'textarea',
        helpText: 'Types of magic considered forbidden, immoral, or dangerous within this culture—necromancy, blood magic, mind control.',
      },
      {
        name: 'magical_language',
        label: 'Magical Language',
        type: 'textarea',
        helpText: 'How the culture\'s language incorporates magical concepts—spell words, true names, power syllables, arcane grammar.',
      },
      {
        name: 'magical_cuisine',
        label: 'Magical Cuisine',
        type: 'textarea',
        helpText: 'Foods and beverages with magical properties—mana-infused drinks, enchanted feasts, alchemical cooking.',
      },
      {
        name: 'magical_fashion',
        label: 'Magical Fashion',
        type: 'textarea',
        helpText: 'Enchanted clothing, warded jewelry, status-indicating magical accessories, glamour-based fashion.',
      },
      {
        name: 'magical_oral_traditions',
        label: 'Magical Oral Traditions',
        type: 'textarea',
        helpText: 'Stories, songs, and spoken traditions that carry magical power—true histories, prophecy ballads, naming songs.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this culture\'s identity and daily life.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'How does this culture\'s relationship with magic shape its art, music, and storytelling? Are there art forms that literally cannot exist without magic?',
      'What magical practices are considered sacred versus profane? Do folk magic and institutional magic coexist or conflict?',
      'How do magical taboos reflect deeper cultural values? Is necromancy forbidden because of reverence for the dead, or fear of what the dead might say?',
    ],
  },
  archetypes: [
    {
      id: 'warrior_honor',
      name: 'Warrior Honor Culture',
      description: 'A martial culture built around personal honor, combat prowess, and loyalty to one\'s war-band.',
      element_type: 'ethnic_group',
      summary: 'A proud warrior culture where glory in battle is the highest virtue',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Runic script carved in stone and bone',
        religion_name: 'Ancestor and hero worship',
        architecture_style: 'Timber longhouses and hilltop fortifications',
        cuisine: 'Hearty fare — roasted meats, root vegetables, mead, and fermented dairy. Feasting is a central social ritual with strict seating hierarchy.',
        social_hierarchy: 'Warriors at the top, followed by free landowners, artisans, thralls. Status earned through combat deeds and gift-giving.',
        funerary_practices: 'Honored dead are cremated on pyres with their weapons and treasures. Great heroes receive ship burials.',
        family_structure: 'Extended clan-based households. Blood feuds between clans are common and can span generations.',
      },
    },
    {
      id: 'scholarly_tradition',
      name: 'Scholarly Tradition',
      description: 'A culture that venerates knowledge, debate, and the preservation of learning above all.',
      element_type: 'academic_tradition',
      summary: 'A culture that prizes wisdom, learning, and mastery of the written word',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Elaborate calligraphic script with thousands of characters',
        religion_name: 'Philosophical tradition emphasizing harmony and balance',
        architecture_style: 'Walled academy complexes with libraries, observatories, and meditation gardens',
        cuisine: 'Simple, refined meals emphasizing balance of flavors. Tea ceremonies are a major social institution.',
        social_hierarchy: 'Scholar-officials at the top, selected by rigorous examination. Merchants rank below farmers in social theory, though not in practice.',
        funerary_practices: 'Elaborate ancestor veneration with family shrines. The names and writings of great scholars are preserved for centuries.',
        family_structure: 'Multigenerational households with strong filial obligations. Education of children is the paramount family duty.',
      },
    },
    {
      id: 'maritime_traders',
      name: 'Maritime Traders',
      description: 'A seafaring culture of merchants, navigators, and explorers who call the ocean home.',
      element_type: 'ethnic_group',
      summary: 'A salt-sprayed people whose home is the deck of a ship',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Practical alphabetic script optimized for contracts and navigation logs',
        religion_name: 'Polytheistic — sea gods, wind spirits, and star-guides',
        architecture_style: 'Stilted waterfront buildings and fortified harbors with lighthouse towers',
        cuisine: 'Seafood-heavy diet with preserved foods for long voyages — salted fish, hardtack, citrus fruits. Spice trade influences exotic blends.',
        social_hierarchy: 'Ship captains and successful merchants hold highest status. Navigators are revered as near-priests. Landlocked peoples are viewed with mild pity.',
        funerary_practices: 'The dead are committed to the sea in weighted shrouds. Captains are set adrift in their ships with the tide.',
        family_structure: 'Fluid households — one parent often at sea for months. Extended dockside communities raise children collectively.',
      },
    },
    {
      id: 'agrarian_folk',
      name: 'Agrarian Folk Culture',
      description: 'A rooted, land-loving culture centered on farming, seasonal festivals, and community bonds.',
      element_type: 'ethnic_group',
      summary: 'A warm, rooted people whose lives follow the rhythm of the seasons',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Simple phonetic script, primarily oral tradition',
        religion_name: 'Earth-mother worship and seasonal fertility rites',
        architecture_style: 'Thatched stone cottages, communal barns, and village greens',
        cuisine: 'Seasonal, locally sourced — bread, cheese, preserved vegetables, orchard fruits. Harvest feasts and midsummer cookouts are cultural keystones.',
        social_hierarchy: 'Relatively egalitarian. Village elders and large landowners have authority, but communal decision-making is the norm.',
        funerary_practices: 'Buried in family plots on their own land, with a fruit tree planted over the grave. Annual remembrance at harvest time.',
        family_structure: 'Nuclear families within tight village communities. Barn-raisings and harvest cooperation bind neighbors together.',
      },
    },
    {
      id: 'dream_weavers',
      name: 'Dream Weaver Culture',
      description: 'A culture built around shared dreaming — architecture, law, and art all exist primarily in the dream world.',
      element_type: 'subculture',
      summary: 'A people who live half their lives in a shared dreamscape they shape together',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Dream-glyphs — symbols that trigger specific dream-images when viewed before sleep. Their libraries are pillows.',
        religion_name: 'The Collective Dream — the shared dreamscape is considered sacred, and skilled dreamers are the clergy',
        architecture_style: 'Waking-world structures are simple dormitories optimized for comfortable sleep. The true cities exist only in the shared dream — impossible spires, inverted oceans, and gardens of living light.',
        cuisine: 'Light meals designed not to disrupt sleep. Herbal teas that deepen dreaming are the cultural staple. Feasting happens in the dream world where taste has no caloric limit.',
        social_hierarchy: 'Lucid dreamers — those who can shape the shared dreamscape — hold the highest status. Dream-blind individuals (who cannot enter the shared dream) are a pitied underclass.',
        funerary_practices: 'The dying perform a final dream-walk, leaving an echo of themselves in the shared dreamscape. The greatest dreamers persist as permanent dream-ghosts, becoming landmarks.',
        family_structure: 'Dream-families often matter more than blood families. Children are raised communally in dream-nurseries where they learn to shape reality before they learn to walk.',
      },
    },
    {
      id: 'death_celebrants',
      name: 'Death Celebrants',
      description: 'A culture that celebrates death as the greatest transition. Elaborate funerary arts, ancestor veneration, and beautiful memorial traditions.',
      element_type: 'religious_order',
      summary: 'A joyful death-venerating culture that transforms grief into art and celebration',
      detailed_notes: 'The Death Celebrants do not mourn — they celebrate. Death, in their belief, is not an ending but the greatest transition: a graduation, a homecoming, a metamorphosis. Their funerary rites are the most elaborate and beautiful events in their calendar, combining music, dance, feasting, and breathtaking memorial art. The dead are honored with joy, not sorrow, and weeping at a funeral is considered rude — it implies the deceased lived a life not worth celebrating. Ancestor veneration is central: the dead are consulted through rituals, their advice sought on matters of importance, their names woven into daily blessings. The culture produces extraordinary memorial artists — sculptors, composers, and poets whose life\'s work is to distill a person\'s essence into a lasting tribute. Outsiders often find them morbid, but the Death Celebrants consider other cultures\' fear of death to be the true tragedy.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Ornamental script designed for memorial inscriptions — every letter is a small work of art',
        religion_name: 'The Great Transition — death as sacred metamorphosis and reunion with ancestors',
        architecture_style: 'Cathedral-ossuaries — soaring structures built from and decorated with the bones and ashes of honored ancestors. Beautiful, not macabre.',
        cuisine: 'Feast cuisine designed for celebrations of death — elaborate multi-course meals where each dish represents a chapter of the deceased\'s life. Bitter herbs for hardship, sweet fruits for joy, fiery spices for passion.',
        social_hierarchy: 'Memorial artists and death-priests hold the highest status. Age is deeply respected — the closer to the Great Transition, the more wisdom one carries. The young are cherished but considered unfinished.',
        funerary_practices: 'Multi-day celebrations with music, storytelling, feasting, and the creation of a memorial artwork. The body is prepared with aromatic preservatives and displayed in a place of honor before being interred in the community ossuary.',
        family_structure: 'Extended families spanning the living and the dead. Ancestor shrines are the heart of every home. Children are given the names of notable ancestors and expected to honor their namesake\'s legacy.',
        values: ['joyful acceptance of mortality', 'remembrance', 'artistic excellence', 'ancestor reverence', 'living fully'],
        customs: ['death-day celebrations', 'ancestor consultation rituals', 'memorial art commissions', 'naming ceremonies linking newborns to ancestors'],
        art_forms: ['memorial sculpture', 'funeral music', 'life-story poetry', 'bone-carving', 'ash-glass craft'],
      },
    },
    {
      id: 'silence_keepers',
      name: 'Silence Keepers',
      description: 'A culture that communicates through sign, writing, or telepathy. Speech is forbidden or sacred — silence holds power.',
      element_type: 'subculture',
      summary: 'A culture of profound silence where unspoken communication carries deeper meaning than words ever could',
      detailed_notes: 'The Silence Keepers believe that spoken language is inherently imprecise, corrupting, or sacred — depending on the sect. Some hold that the voice carries a fragment of the soul, and to speak frivolously is to scatter oneself. Others believe that silence is the natural state of wisdom, and that speech is a crutch for minds too undisciplined for deeper communication. In practice, they communicate through an extraordinarily expressive sign language, written notes, facial expression, and — among the gifted — limited telepathy. Their communities are eerily quiet to outsiders: markets bustling with activity but no sound, children playing in perfect silence, councils debating through rapid hand-signs. The Silence Keepers are not mute — they can speak, and some rituals require the sacred act of breaking silence. But casual speech is considered vulgar, and a person who speaks without necessity loses social standing.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'A highly developed ideographic script used for all formal communication. Quick shorthand variants exist for casual written conversation.',
        religion_name: 'The Still Voice — a meditative tradition teaching that truth is found in silence and that the divine speaks only to those who stop talking',
        architecture_style: 'Sound-dampening construction — thick walls, heavy curtains, soft floors. Public spaces are designed for sight-lines rather than acoustics. Bell towers exist but ring only for emergencies.',
        cuisine: 'Communal silent meals are a bonding ritual. Food is simple and eaten mindfully. Crunchy or noisy foods are avoided in polite company. Tea is the social beverage — poured silently, shared in contemplation.',
        social_hierarchy: 'Those who have maintained unbroken silence for years or decades hold the highest status. Telepaths are respected but also slightly feared. The "loud" — those who speak too readily — occupy the lowest social tier.',
        funerary_practices: 'The dead are mourned in absolute silence for three days. A single word — the deceased\'s true name — is spoken once at the burial by their closest companion. This is considered the most sacred utterance possible.',
        family_structure: 'Families communicate through a private family sign-dialect that outsiders cannot fully understand. Parent-child bonds are expressed through touch and presence rather than verbal affection.',
        values: ['silence as power', 'mindful communication', 'inner discipline', 'contemplation', 'precision of expression'],
        customs: ['the Unspeaking (vow of extended silence)', 'hand-sign debates', 'silent market trading', 'the Sacred Word ritual'],
        art_forms: ['visual storytelling', 'sign-language poetry', 'sand mandala', 'silent theater', 'calligraphy'],
      },
    },
    {
      id: 'nomadic_storytellers',
      name: 'Oral Tradition Keepers',
      description: 'A culture whose entire history and law exists only in spoken word. The living memory, never written down.',
      element_type: 'ethnic_group',
      summary: 'A wandering people whose spoken stories ARE their civilization — destroy the stories, destroy the people',
      detailed_notes: 'The Oral Tradition Keepers have no written language — by choice, not ignorance. They believe that writing kills knowledge by fixing it in place, making it rigid and dead. True knowledge, they hold, must live in a mind, be shaped by a voice, and breathe through retelling. Their entire legal code, history, genealogy, scientific knowledge, and spiritual tradition exists only in the memories of trained storytellers called Keepers. A Keeper begins training in childhood and spends decades memorizing thousands of stories, songs, and recitations with word-perfect accuracy. The loss of a Keeper before they can pass on their stories is a cultural catastrophe equivalent to the burning of a library. The culture is nomadic, traveling in small bands between seasonal camps, and the stories serve as their portable civilization — carrying everything they need to know in the minds of their people.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'None — deliberately and philosophically rejected. Memory aids such as knotted cords and carved tokens exist but do not encode language.',
        religion_name: 'The Living Word — the belief that spoken stories carry spiritual power and that the first story ever told created the world',
        architecture_style: 'Portable camps — hide tents, woven shelters, and story-circles (cleared ground around a central fire where stories are told). No permanent structures.',
        cuisine: 'Trail food and foraged meals that vary with the season and region. Cooking is accompanied by storytelling — recipes are themselves stories. Feast-stories are elaborate performances where food and narrative are served in courses together.',
        social_hierarchy: 'Keepers (master storytellers) hold the highest status — they are the living repositories of the people\'s identity. Elders are revered for the stories they carry. Children are treasured as future vessels for knowledge.',
        funerary_practices: 'When a person dies, their life is told as a story by those who knew them. If the story is compelling enough, it enters the collective tradition and the person achieves immortality. If not, they are mourned and released.',
        family_structure: 'Extended family bands of 20-50 people who travel together. A Keeper belongs to the whole band, not to any single family. Marriage involves the interweaving of two families\' stories into a shared narrative.',
        values: ['memory as sacred duty', 'the spoken word as living truth', 'community over individual', 'the journey over the destination'],
        customs: ['nightly story-circles', 'the Keeper\'s apprenticeship', 'the Story-Walk (pilgrimage to retell stories at their origin sites)', 'the Forgetting (ritual erasure of shamed events)'],
        art_forms: ['epic oral poetry', 'call-and-response chanting', 'rhythmic drumming', 'story-dance', 'knotwork memory aids'],
      },
    },
    {
      id: 'mask_wearers',
      name: 'Mask Wearers',
      description: 'Everyone wears masks. Identity is the mask, not the face beneath.',
      element_type: 'subculture',
      summary: 'A culture where the mask IS the person — to remove it is to become no one',
      detailed_notes: 'Among the Mask Wearers, a person\'s face is private in the same way other cultures consider nudity private — more so, in fact. Children receive their first mask at naming, and from that moment, they are never seen unmasked in public. The mask is not a disguise; it IS the identity. Changing masks means changing who you are — different masks for different social roles, with each mask carrying its own reputation, obligations, and relationships. A merchant mask conducts business; a parent mask raises children; a lover mask courts. The face beneath is considered sacred and unknowable, shared only in the most intimate moments. The culture\'s art, politics, and crime all revolve around masks: master mask-makers are the most revered artisans, stealing someone\'s mask is equivalent to murder, and the greatest philosophical question is whether there is a true self beneath all the masks or whether the masks are all there is.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Pictographic script where each character is a stylized mask representing a concept',
        religion_name: 'The Faceless Divine — gods who have no true face, only infinite masks representing their aspects',
        architecture_style: 'Buildings with masked facades — every structure has a decorative face. Interiors are plain and private.',
        cuisine: 'Eaten in private or through specially designed mask-ports. Public dining is considered vulgar. Tea is sipped through mask-straws at social gatherings.',
        social_hierarchy: 'Status is determined by the number and quality of masks one owns. Master mask-makers sit at the apex. The maskless are outcasts — either by punishment or poverty.',
        values: ['identity as performance', 'privacy of the true self', 'craftsmanship', 'social fluidity', 'the sacred unknowable'],
        customs: ['mask-naming ceremonies', 'the Unmasking (intimate trust ritual)', 'mask funerals (burying the mask, not the body)', 'the Festival of New Faces'],
        art_forms: ['mask-making', 'masked theater', 'identity poetry', 'face-painting (private, meditative art)', 'mask-dance'],
      },
    },
    {
      id: 'dream_architects',
      name: 'Dream Architects',
      description: 'A culture that builds primarily in shared dreams. Physical structures are secondary.',
      element_type: 'artistic_movement',
      summary: 'Visionary builders whose greatest works exist only in the shared dreamscape',
      detailed_notes: 'The Dream Architects are an artistic and cultural movement that emerged when practitioners discovered how to create permanent structures in the shared dream plane. Their waking-world settlements are deliberately minimal — functional shelters for sleeping bodies — because their true creative energy goes into dream-construction. In the shared dreamscape, they build impossible architecture: towers that spiral into infinity, bridges spanning conceptual chasms, gardens where emotions grow as flowers. These dream-structures persist even when their creators wake, becoming shared cultural spaces where the community gathers, debates, worships, and creates art. The movement has attracted architects, artists, and visionaries from many cultures, united by the belief that physical reality is too constrained for true creative expression. Critics call them escapists; they call physical builders unimaginative.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Dream-inscription — text that can only be read while asleep, written in the logic of dreams rather than waking grammar',
        religion_name: 'The Grand Design — the belief that the dream plane is the true reality and the waking world is a rough draft',
        architecture_style: 'Waking-world: minimal sleeping pods and communal dream-halls. Dream-world: impossible geometries, living buildings, structures made of light, memory, and emotion.',
        cuisine: 'Functional nutrition in the waking world — bland but efficient. In dreams, elaborate feasts of impossible flavors that nourish the spirit.',
        social_hierarchy: 'Master Dream Architects who can create permanent dream-structures hold the highest status. Apprentices learn for decades. Those who cannot dream are excluded entirely.',
        values: ['creative vision', 'transcendence of physical limits', 'shared imagination', 'impermanence as beauty', 'the dream as truth'],
        customs: ['the First Dreaming (apprentice initiation)', 'dream-gallery exhibitions', 'collaborative dream-builds', 'the Waking Fast (periods of enforced wakefulness for perspective)'],
        art_forms: ['dream architecture', 'emotion sculpture', 'memory mosaics', 'impossible music', 'narrative landscapes'],
      },
    },
    {
      id: 'bone_singers',
      name: 'Bone Singers',
      description: 'A culture that crafts music from the remains of the honored dead.',
      element_type: 'religious_order',
      summary: 'A sacred musical tradition that transforms the bones of the beloved dead into instruments of remembrance',
      detailed_notes: 'The Bone Singers believe that the dead live on in their bones, and that music is the language that bridges the living and the dead. When a person dies, their bones are carefully cleaned, blessed, and crafted into musical instruments by the order\'s artisans. A femur becomes a flute. A skull becomes a resonating drum. A ribcage becomes a xylophone. Each instrument carries the tonal signature of the person it was made from — experienced Bone Singers claim they can hear the deceased\'s voice in the harmonics. The music produced is haunting and beautiful, used in ceremonies, healing rituals, and communication with ancestors. Outsiders are often horrified, but the Bone Singers see their practice as the ultimate act of love: ensuring the dead are never silent, never forgotten, and always part of the community\'s living song.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Musical notation carved into bone — songs are their scriptures, and the instruments are their holy texts',
        religion_name: 'The Eternal Song — the belief that all souls contribute to a cosmic melody, and death is merely a change in key',
        architecture_style: 'Resonance halls built for acoustic perfection, with bone-instrument collections lining the walls like libraries. Ossuaries that double as concert halls.',
        cuisine: 'Meals are always accompanied by music played on ancestor-instruments. Certain foods are associated with certain ancestors and eaten on their remembrance days.',
        social_hierarchy: 'Master Bone Singers who can channel ancestral voices hold supreme authority. Instrument-crafters are sacred artisans. The tone-deaf are not shunned but serve as caretakers and listeners.',
        values: ['remembrance through music', 'the sacred body', 'ancestral continuity', 'beauty in mortality', 'harmony between living and dead'],
        customs: ['the Crafting (transforming a loved one\'s remains into an instrument)', 'ancestor concerts on death anniversaries', 'the Silence Before Song (mourning period before instrument-making)', 'the Great Chorus (annual gathering where all instruments play together)'],
        art_forms: ['bone instrument crafting', 'ancestral music composition', 'harmonic channeling', 'funeral song-writing', 'resonance sculpture'],
      },
    },
    {
      id: 'maritime_voyagers',
      name: 'Maritime Voyagers',
      description: 'A seafaring culture of merchants, navigators, and explorers who call the ocean home.',
      element_type: 'ethnic_group',
      summary: 'A people defined by the sea — their ships are their homes, the horizon their destination',
      detailed_notes: 'Maritime Voyagers build their entire identity around the ocean. Their children learn to swim before they walk and to read the stars before they read text. Navigation is the highest art, and a captain who can find safe harbor in a storm is more respected than any king. Their language is rich with nautical metaphor, their religion centers on sea deities and the spirits of drowned ancestors, and their economy runs on trade between distant ports. They carry their culture in their ships — each vessel is a floating village with its own traditions, rivalries, and loyalties. Land-dwellers find them restless and untrustworthy; they find land-dwellers pitifully rooted.',
      fields: {
        language_name: '(unnamed)',
        writing_system: 'Knot-based recording system for navigation and trade, supplemented by a phonetic script adapted from a trading partner',
        religion_name: 'The Deep Current — worship of ocean spirits, drowned ancestors, and the great currents that connect all shores',
        architecture_style: 'Shipboard — every structure is designed to be mobile. Permanent settlements are built on stilts over water or on floating platforms. Interiors are compact and multi-purpose.',
        cuisine: 'Fish, seaweed, preserved meats, and tropical fruits traded at ports. Fermented fish sauce is the universal condiment. Fresh water is precious and never wasted.',
        social_hierarchy: 'Captains at the top, then navigators, then sailors, then those who have never been to sea (the lowest status). Gender is irrelevant — only seamanship matters.',
        values: ['freedom of movement', 'navigational skill', 'trade fairness', 'respect for the ocean', 'hospitality to fellow sailors'],
        customs: ['the First Voyage (coming-of-age sail)', 'storm songs (sung to calm the sea)', 'port markets (temporary bazaars at every landing)', 'the Captain\'s Word (absolute authority at sea)'],
        art_forms: ['sea shanties', 'scrimshaw', 'star charts', 'ship carving', 'wave-pattern weaving'],
      },
    },
  ],
  defaultSortField: 'language_name',
};
