import type { DomainConfig } from '../types/domains.js';

export const ecosystemsConfig: DomainConfig = {
  id: 'ecosystems',
  name: 'Ecosystem',
  namePlural: 'Ecosystems',
  icon: 'network',
  color: '#1abc9c',
  description: 'Model the interconnected webs of life that tie flora, fauna, and environment together. Ecosystems capture food webs, energy flows, and the delicate balances that sustain—or threaten—your world\'s biodiversity.',
  tableName: 'ecosystems',
  category: 'natural',
  fields: [
    {
      name: 'ecosystem_type',
      label: 'Ecosystem Type',
      type: 'text',
      required: true,
      placeholder: 'e.g. coral reef, old-growth forest, deep cave network',
      helpText: 'A descriptive name for this type of ecosystem.',
    },
    {
      name: 'energy_source',
      label: 'Primary Energy Source',
      type: 'text',
      placeholder: 'e.g. solar, geothermal, chemosynthetic, magical',
      helpText: 'The fundamental energy source driving this ecosystem.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      required: true,
      options: ['stable', 'fragile', 'resilient', 'collapsing', 'recovering'],
      helpText: 'The current health and resilience of this ecosystem.',
    },
    {
      name: 'biodiversity_index',
      label: 'Biodiversity Index',
      type: 'text',
      placeholder: 'e.g. very high, moderate, low',
      helpText: 'A qualitative or quantitative measure of species diversity.',
    },
    {
      name: 'keystone_species_id',
      label: 'Keystone Species',
      type: 'text',
      placeholder: 'ID of the keystone species',
      helpText: 'The species whose removal would cause the ecosystem to collapse or fundamentally change.',
    },
    {
      name: 'biome_ids',
      label: 'Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "wetland_biome_2"]',
      helpText: 'The biomes this ecosystem spans or exists within.',
    },
    {
      name: 'threats',
      label: 'Threats',
      type: 'json',
      placeholder: '["deforestation", "invasive species", "mana depletion"]',
      helpText: 'Current threats to this ecosystem\'s health and stability.',
    },
  ],
  elementTypes: ['terrestrial', 'aquatic', 'aerial', 'subterranean', 'magical', 'artificial'],
  prompts: [
    'What are the keystone species in your major ecosystems? What would happen if they disappeared?',
    'How do food webs work in your world? Are there unusual trophic levels or energy sources beyond sunlight?',
    'Are any ecosystems currently under threat from civilization, climate change, or magical disruption?',
    'Have any ecosystems been artificially created—magical gardens, terraformed wastelands, or engineered habitats?',
    'How do ecosystems recover after catastrophic events like volcanic eruptions, wars, or magical disasters?',
  ],
  magicPermeation: {
    companionTable: 'ecosystems_magic_aspects',
    fields: [
      {
        name: 'mana_cycle_id',
        label: 'Mana Cycle',
        type: 'text',
        placeholder: 'ID of the associated mana cycle',
        helpText: 'The mana cycle that governs magical energy flow through this ecosystem.',
      },
      {
        name: 'magical_food_web_id',
        label: 'Magical Food Web',
        type: 'text',
        placeholder: 'ID of the magical food web',
        helpText: 'The magical trophic network—which organisms produce, transfer, and consume mana.',
      },
      {
        name: 'ambient_mana_level',
        label: 'Ambient Mana Level',
        type: 'textarea',
        helpText: 'The baseline level of free magical energy in this ecosystem.',
      },
      {
        name: 'mana_flow_patterns',
        label: 'Mana Flow Patterns',
        type: 'textarea',
        helpText: 'How mana moves through the ecosystem—ley currents, seasonal tides, organism-driven cycles.',
      },
      {
        name: 'keystone_magical_species',
        label: 'Keystone Magical Species',
        type: 'textarea',
        helpText: 'Species whose magical function is critical to the ecosystem\'s mana balance.',
      },
      {
        name: 'magical_carrying_capacity',
        label: 'Magical Carrying Capacity',
        type: 'textarea',
        helpText: 'The maximum amount of magical activity this ecosystem can sustain before degradation.',
      },
      {
        name: 'magical_disturbance_history',
        label: 'Magical Disturbance History',
        type: 'textarea',
        helpText: 'Past magical events that damaged or transformed this ecosystem.',
      },
      {
        name: 'recovery_from_magical_damage',
        label: 'Recovery from Magical Damage',
        type: 'textarea',
        helpText: 'How this ecosystem heals after magical disruption—natural recovery, remediation, or permanent scarring.',
      },
      {
        name: 'magical_succession',
        label: 'Magical Succession',
        type: 'textarea',
        helpText: 'How the magical character of the ecosystem changes over time as it matures—pioneer mana-species giving way to climax communities.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this ecosystem\'s functioning.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Is there a "mana cycle" analogous to the water or carbon cycle? How does magical energy flow through producers, consumers, and decomposers?',
      'What happens when an ecosystem\'s magical carrying capacity is exceeded—mana storms, mutations, dead zones?',
      'Are there keystone magical species whose mana production or regulation keeps the entire ecosystem in balance?',
    ],
  },
  defaultSortField: 'ecosystem_type',
};
