import type { DomainConfig } from '../types/domains.js';

export const ecosystemsConfig: DomainConfig = {
  id: 'ecosystems',
  name: 'Ecosystem',
  namePlural: 'Ecosystems',
  icon: 'network',
  color: '#1abc9c',
  description: 'Model the interconnected webs of life that tie flora, fauna, and environment together. Ecosystems capture food webs, energy flows, and the delicate balances that sustain—or threaten—your world\'s biodiversity.',
  tableName: 'ecosystems',
  category: 'natural',
  fields: [
    {
      name: 'ecosystem_type',
      label: 'Ecosystem Type',
      type: 'text',
      required: true,
      placeholder: 'e.g. coral reef, old-growth forest, deep cave network',
      helpText: 'A descriptive name for this type of ecosystem.',
    },
    {
      name: 'energy_source',
      label: 'Primary Energy Source',
      type: 'text',
      placeholder: 'e.g. solar, geothermal, chemosynthetic, magical',
      helpText: 'The fundamental energy source driving this ecosystem.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      required: true,
      options: ['stable', 'fragile', 'resilient', 'collapsing', 'recovering'],
      helpText: 'The current health and resilience of this ecosystem.',
    },
    {
      name: 'biodiversity_index',
      label: 'Biodiversity Index',
      type: 'text',
      placeholder: 'e.g. very high, moderate, low',
      helpText: 'A qualitative or quantitative measure of species diversity.',
    },
    {
      name: 'keystone_species_id',
      label: 'Keystone Species',
      type: 'text',
      placeholder: 'ID of the keystone species',
      helpText: 'The species whose removal would cause the ecosystem to collapse or fundamentally change.',
    },
    {
      name: 'biome_ids',
      label: 'Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "wetland_biome_2"]',
      helpText: 'The biomes this ecosystem spans or exists within.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'text',
      placeholder: 'e.g. 500 km², a single valley, continent-wide',
      helpText: 'The approximate area or extent of this ecosystem.',
    },
    {
      name: 'succession_stage',
      label: 'Succession Stage',
      type: 'select',
      options: ['pioneer', 'early', 'developing', 'mature', 'climax', 'degraded'],
      helpText: 'The ecological succession stage — how mature and established this ecosystem is.',
    },
    {
      name: 'age',
      label: 'Age',
      type: 'text',
      placeholder: 'e.g. 10,000 years, recently formed, ancient',
      helpText: 'How long this ecosystem has existed in its current form.',
    },
    {
      name: 'threats',
      label: 'Threats',
      type: 'json',
      placeholder: '["deforestation", "invasive species", "mana depletion"]',
      helpText: 'Current threats to this ecosystem\'s health and stability.',
    },
  ],
  elementTypes: ['terrestrial', 'aquatic', 'aerial', 'subterranean', 'magical', 'artificial'],
  elementTypeDescriptions: {
    terrestrial: 'A land-based ecosystem — forests, grasslands, deserts, and the interconnected webs of life that sustain them.',
    aquatic: 'A water-based ecosystem — oceans, rivers, lakes, and wetlands, from sunlit shallows to the deep abyss.',
    aerial: 'An ecosystem that exists primarily in the air — sky islands, floating spore clouds, or communities of flying organisms.',
    subterranean: 'An underground ecosystem sustained without sunlight — cave networks, fungal forests, or deep thermal vent communities.',
    magical: 'An ecosystem powered or fundamentally shaped by magic — mana flows replace sunlight, and creatures feed on arcane energy.',
    artificial: 'An ecosystem deliberately created or maintained by sentient beings — terraformed zones, enchanted gardens, or sealed habitats.',
  },
  prompts: [
    'What are the keystone species in your major ecosystems? What would happen if they disappeared?',
    'How do food webs work in your world? Are there unusual trophic levels or energy sources beyond sunlight?',
    'Are any ecosystems currently under threat from civilization, climate change, or magical disruption?',
    'Have any ecosystems been artificially created—magical gardens, terraformed wastelands, or engineered habitats?',
    'How do ecosystems recover after catastrophic events like volcanic eruptions, wars, or magical disasters?',
  ],
  magicPermeation: {
    companionTable: 'ecosystems_magic_aspects',
    fields: [
      {
        name: 'mana_cycle_id',
        label: 'Mana Cycle',
        type: 'text',
        placeholder: 'ID of the associated mana cycle',
        helpText: 'The mana cycle that governs magical energy flow through this ecosystem.',
      },
      {
        name: 'magical_food_web_id',
        label: 'Magical Food Web',
        type: 'text',
        placeholder: 'ID of the magical food web',
        helpText: 'The magical trophic network—which organisms produce, transfer, and consume mana.',
      },
      {
        name: 'ambient_mana_level',
        label: 'Ambient Mana Level',
        type: 'textarea',
        helpText: 'The baseline level of free magical energy in this ecosystem.',
      },
      {
        name: 'mana_flow_patterns',
        label: 'Mana Flow Patterns',
        type: 'textarea',
        helpText: 'How mana moves through the ecosystem—ley currents, seasonal tides, organism-driven cycles.',
      },
      {
        name: 'keystone_magical_species',
        label: 'Keystone Magical Species',
        type: 'textarea',
        helpText: 'Species whose magical function is critical to the ecosystem\'s mana balance.',
      },
      {
        name: 'magical_carrying_capacity',
        label: 'Magical Carrying Capacity',
        type: 'textarea',
        helpText: 'The maximum amount of magical activity this ecosystem can sustain before degradation.',
      },
      {
        name: 'magical_disturbance_history',
        label: 'Magical Disturbance History',
        type: 'textarea',
        helpText: 'Past magical events that damaged or transformed this ecosystem.',
      },
      {
        name: 'recovery_from_magical_damage',
        label: 'Recovery from Magical Damage',
        type: 'textarea',
        helpText: 'How this ecosystem heals after magical disruption—natural recovery, remediation, or permanent scarring.',
      },
      {
        name: 'magical_succession',
        label: 'Magical Succession',
        type: 'textarea',
        helpText: 'How the magical character of the ecosystem changes over time as it matures—pioneer mana-species giving way to climax communities.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this ecosystem\'s functioning.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Is there a "mana cycle" analogous to the water or carbon cycle? How does magical energy flow through producers, consumers, and decomposers?',
      'What happens when an ecosystem\'s magical carrying capacity is exceeded—mana storms, mutations, dead zones?',
      'Are there keystone magical species whose mana production or regulation keeps the entire ecosystem in balance?',
    ],
  },
  archetypes: [
    {
      id: 'old_growth_forest',
      name: 'Old-Growth Forest Ecosystem',
      description: 'A mature, undisturbed forest ecosystem with centuries of accumulated complexity.',
      element_type: 'terrestrial',
      summary: 'An ancient forest ecosystem at climax succession',
      fields: {
        ecosystem_type: 'Temperate old-growth forest',
        energy_source: 'Solar radiation via photosynthesis',
        stability: 'resilient',
        biodiversity_index: 'High — hundreds of species in complex food webs',
        geographic_scope: 'Regional (thousands of square kilometers)',
        succession_stage: 'climax',
        age: 'Several thousand years undisturbed',
      },
    },
    {
      id: 'coral_reef_ecosystem',
      name: 'Coral Reef Ecosystem',
      description: 'A fragile marine ecosystem of extraordinary diversity built on a living coral framework.',
      element_type: 'aquatic',
      summary: 'A fragile but spectacularly biodiverse underwater world',
      fields: {
        ecosystem_type: 'Tropical coral reef',
        energy_source: 'Photosynthetic algae (zooxanthellae) in symbiosis with coral',
        stability: 'fragile',
        biodiversity_index: 'Extremely high — thousands of interdependent species',
        geographic_scope: 'Local to regional (reef system)',
        succession_stage: 'mature',
        age: 'Thousands of years of continuous coral growth',
      },
    },
    {
      id: 'hydrothermal_vent',
      name: 'Hydrothermal Vent Ecosystem',
      description: 'A deep-sea ecosystem sustained entirely by chemosynthesis around volcanic vents.',
      element_type: 'aquatic',
      summary: 'A bizarre ecosystem thriving in superheated darkness on the ocean floor',
      fields: {
        ecosystem_type: 'Deep-sea hydrothermal vent',
        energy_source: 'Chemosynthesis from volcanic mineral-rich superheated water',
        stability: 'fragile',
        biodiversity_index: 'Low species count but high endemism — most species found nowhere else',
        geographic_scope: 'Extremely localized (single vent field)',
        succession_stage: 'developing',
        age: 'Decades to centuries (vents are geologically ephemeral)',
      },
    },
    {
      id: 'freshwater_wetland',
      name: 'Freshwater Wetland Ecosystem',
      description: 'A seasonally flooded ecosystem that filters water and supports incredible bird and fish diversity.',
      element_type: 'terrestrial',
      summary: 'A waterlogged paradise for birds, fish, and amphibians',
      fields: {
        ecosystem_type: 'Freshwater marsh and riparian wetland',
        energy_source: 'Solar radiation and nutrient-rich flooding',
        stability: 'resilient',
        biodiversity_index: 'High — especially for birds, amphibians, and aquatic insects',
        geographic_scope: 'Local (river floodplain or lake margin)',
        succession_stage: 'mature',
        age: 'Hundreds to thousands of years',
      },
    },
    {
      id: 'symbiotic_megaorganism',
      name: 'Symbiotic Megaorganism',
      description: 'An ecosystem so tightly integrated that it functions as a single living superorganism — every species is an organ.',
      element_type: 'magical',
      summary: 'An ecosystem that IS a creature — every species within it functions like an organ',
      fields: {
        ecosystem_type: 'Symbiotic megaorganism (borderline single entity)',
        energy_source: 'Shared circulatory system distributing nutrients from photosynthetic and chemosynthetic members',
        stability: 'fragile',
        biodiversity_index: 'Moderate species count but total interdependence — remove one species and the whole system fails',
        geographic_scope: 'Local (a single valley, island, or cavern)',
        succession_stage: 'climax',
        age: 'Ancient — the integration deepened over millions of years of co-evolution',
      },
    },
    {
      id: 'war_scarred',
      name: 'War-Scarred Ecosystem',
      description: 'An ecosystem recovering from a magical or military catastrophe. Craters, dead zones, and pioneer species reclaiming ruined land.',
      element_type: 'terrestrial',
      summary: 'A devastated landscape slowly being reclaimed by life after catastrophic destruction',
      detailed_notes: 'War-Scarred Ecosystems are the ecological aftermath of devastating conflict — whether conventional warfare, magical cataclysm, or both. The landscape bears visible wounds: blast craters filled with stagnant water, scorched earth where nothing grows, twisted remnants of fortifications, and soil contaminated with alchemical residue or lingering enchantments. Yet life is resilient. Pioneer species — hardy weeds, scavenging insects, and opportunistic fungi — are the first to return, breaking down debris and building new soil. Over decades, more complex species follow. These ecosystems are ecologically fascinating but emotionally haunting, serving as living memorials to the cost of war. Some cultures deliberately preserve them as warnings; others race to rehabilitate them.',
      fields: {
        ecosystem_type: 'Post-catastrophe recovery zone',
        energy_source: 'Solar radiation, supplemented by residual magical energy from wartime enchantments',
        stability: 'recovering',
        biodiversity_index: 'Low but rapidly increasing — pioneer species dominate, with complexity growing each decade',
        geographic_scope: 'Regional (former battlefields, siege zones, or areas of magical bombardment)',
        succession_stage: 'pioneer',
        age: 'Decades to centuries since the catastrophe',
        threats: ['residual magical contamination', 'unexploded enchantments', 'soil toxicity', 'invasive pioneer species crowding out native returnees'],
      },
    },
    {
      id: 'parasitic_network',
      name: 'Parasitic Network',
      description: 'An ecosystem dominated by parasitic relationships rather than predation. Every species feeds off another.',
      element_type: 'magical',
      summary: 'A nightmarish web of life where every organism is both parasite and host',
      detailed_notes: 'In a Parasitic Network, the dominant ecological relationship is not predation or competition but parasitism. Every species in the system feeds off at least one other, and is in turn fed upon by something else. The result is a complex, interlocking chain of exploitation that is paradoxically stable — no single parasite can afford to kill its host, because the host\'s parasites depend on it too. The ecosystem achieves a grim equilibrium where every organism is simultaneously suffering and sustaining. These systems often arise in mana-rich environments where magical energy subsidizes the metabolic cost of supporting parasites. They are deeply unsettling to visit — the forest seems alive in the wrong way, with organisms visibly attached to, growing from, or burrowing into one another.',
      fields: {
        ecosystem_type: 'Parasitism-dominated trophic network',
        energy_source: 'Ambient magical energy subsidizing the metabolic cost of universal parasitism',
        stability: 'stable',
        biodiversity_index: 'High — parasitic specialization drives extreme speciation',
        geographic_scope: 'Local to regional (mana-saturated zones, cursed forests, corrupted wetlands)',
        succession_stage: 'climax',
        age: 'Centuries to millennia — parasitic equilibrium takes many generations to stabilize',
        threats: ['mana depletion destabilizing the energy subsidy', 'introduction of non-parasitic competitors', 'magical cleansing attempts that disrupt the balance'],
      },
    },
    {
      id: 'seasonal_migration',
      name: 'Great Migration Ecosystem',
      description: 'An ecosystem defined by massive annual animal movements across hundreds of miles.',
      element_type: 'terrestrial',
      summary: 'A continent-spanning ecosystem that exists only because of annual mass animal migration',
      detailed_notes: 'The Great Migration Ecosystem is not defined by a place but by a movement. Millions of animals travel hundreds or thousands of miles annually, following rains, green growth, or breeding instincts. The ecosystem encompasses the entire migration corridor — the calving grounds, the grazing plains, the river crossings, the predator gauntlets, and the dry-season refugia. Every organism along the route has adapted to the annual pulse of abundance and scarcity: grasses evolved to regrow from heavy grazing, predators time their breeding to the arrival of herds, scavengers follow the column of inevitable death, and dung beetles process the mountains of waste into fertile soil. Disrupting any segment of the corridor — a new fence, a drained river, a city built across the path — threatens the entire system.',
      fields: {
        ecosystem_type: 'Migration-corridor ecosystem spanning multiple biomes',
        energy_source: 'Solar radiation driving the grassland productivity that fuels the migration',
        stability: 'resilient',
        biodiversity_index: 'Very high — the migration supports distinct communities at every point along the route',
        geographic_scope: 'Continental (migration corridors spanning hundreds to thousands of kilometers)',
        succession_stage: 'mature',
        age: 'Tens of thousands of years — the migration routes predate most civilizations',
        threats: ['corridor fragmentation by settlements or fences', 'overhunting of migratory herds', 'climate shifts altering rainfall patterns', 'river damming blocking crossing points'],
      },
    },
    {
      id: 'graveyard_ecosystem',
      name: 'Graveyard Ecosystem',
      description: 'Thrives on death: scavengers, fungi, bacteria forming rich necro-ecology.',
      element_type: 'terrestrial',
      summary: 'An ecosystem that feeds on death itself — a thriving necro-ecology of scavengers, decomposers, and recyclers',
      detailed_notes: 'The Graveyard Ecosystem is a macabre but ecologically fascinating system that has developed in areas of sustained, concentrated mortality — ancient battlefields, mass burial sites, creature migration die-off zones, or natural traps where animals have been falling and dying for millennia. Unlike typical ecosystems that begin with photosynthesis, the Graveyard Ecosystem\'s primary energy input is death. The base of the food web is composed of specialized decomposers: bacteria that break down bone and flesh, fungi that digest keratin and chiite, and insects that feed on every stage of decay. Above them, scavenging vertebrates patrol for fresh inputs, and predators hunt the scavengers. The soil is extraordinarily rich — centuries of decomposition have created a deep, black humus that supports explosive plant growth around the margins of the active death zone. The ecosystem is self-reinforcing: the rich vegetation at the margins attracts herbivores, whose eventual deaths add to the organic input. Some Graveyard Ecosystems have persisted for so long that they have developed unique species found nowhere else — organisms so specialized for death-processing that they cannot survive in living-dominated ecosystems.',
      fields: {
        ecosystem_type: 'Death-sustained decomposer community',
        energy_source: 'Organic matter from continuous mortality events — biological energy rather than solar',
        stability: 'stable',
        biodiversity_index: 'Moderate — highly specialized species with low redundancy',
        threats: ['depletion of mortality source', 'soil contamination from alchemical or magical residue in remains', 'cultural disruption from communities that consider the sites sacred'],
        succession_stage: 'climax',
      },
    },
    {
      id: 'symbiotic_city',
      name: 'Symbiotic City Ecosystem',
      description: 'Urban ecosystem where buildings, organisms, and magic form an interdependent web.',
      element_type: 'artificial',
      summary: 'A city that is itself an ecosystem — buildings, organisms, and infrastructure forming a living, interdependent web',
      detailed_notes: 'The Symbiotic City Ecosystem represents the endpoint of urban ecology: a settlement where the boundary between built environment and living system has dissolved entirely. Buildings are grown from living materials — coral-like organisms that secrete structural compounds, trees trained and shaped into load-bearing frameworks, fungal networks that form self-repairing insulation. Waste is processed by engineered decomposer organisms that convert refuse into soil and building materials. Water is filtered through living root systems embedded in every wall. Air is cleaned by photosynthetic organisms growing on every surface. The city breathes, grows, heals, and adapts. Every resident is a participant in the ecosystem: their waste feeds the decomposers, their breath feeds the plants, their body heat warms the living walls in winter. In return, the city provides shelter, clean air, fresh water, and food from integrated urban agriculture. The system is resilient but interconnected — a blight affecting one organism can cascade through the entire urban web.',
      fields: {
        ecosystem_type: 'Integrated urban-biological system',
        energy_source: 'Solar radiation supplemented by metabolic heat from inhabitants and geothermal taps',
        stability: 'resilient',
        biodiversity_index: 'High — hundreds of engineered and adapted species working in concert',
        threats: ['novel pathogens affecting keystone building-organisms', 'population decline reducing metabolic inputs', 'magical disruption destabilizing bio-architectural bonds'],
        succession_stage: 'mature',
      },
    },
    {
      id: 'void_edge',
      name: 'Void Edge Ecosystem',
      description: 'Ecosystem at the boundary of magical dead zones.',
      element_type: 'magical',
      summary: 'A liminal ecosystem clinging to the edge of magical dead zones — where mana-dependent life meets mundane reality',
      detailed_notes: 'Void Edge Ecosystems form at the boundaries between mana-saturated regions and magical dead zones — areas where ambient magical energy drops to zero. The boundary is often sharp, creating a dramatic ecological gradient over a few hundred meters. On the mana-rich side, magical organisms thrive: mana-photosynthetic plants, spell-casting predators, and creatures that feed directly on ambient energy. On the dead side, only mundane organisms survive, stripped of any magical enhancement. At the edge itself, a unique community has developed — organisms that have adapted to fluctuating mana levels, switching between magical and mundane metabolisms as the boundary shifts. These edge-specialists are among the most adaptable organisms in the world, and they provide crucial ecosystem services: they process mana runoff that would otherwise poison the dead zone, and they introduce organic nutrients into the mana side where magical energy alone might not sustain complex food webs. The Void Edge is ecologically fragile — if the dead zone expands, the edge community is pushed back, and the magical ecosystem behind it loses its buffer.',
      fields: {
        ecosystem_type: 'Mana-gradient boundary community',
        energy_source: 'Mixed — ambient mana on the magical side, solar radiation on the dead side, both at the boundary',
        stability: 'fragile',
        biodiversity_index: 'High at the boundary itself, declining sharply into the dead zone',
        threats: ['dead zone expansion consuming the edge habitat', 'mana surges overwhelming edge-adapted organisms', 'exploitation of edge-specialist organisms for their dual-metabolism properties'],
        succession_stage: 'developing',
      },
    },
  ],
  defaultSortField: 'ecosystem_type',
};
