import type { DomainConfig } from '../types/domains.js';

export const ecosystemsConfig: DomainConfig = {
  id: 'ecosystems',
  name: 'Ecosystem',
  namePlural: 'Ecosystems',
  icon: 'network',
  color: '#1abc9c',
  description: 'Model the interconnected webs of life that tie flora, fauna, and environment together. Ecosystems capture food webs, energy flows, and the delicate balances that sustain—or threaten—your world\'s biodiversity.',
  tableName: 'ecosystems',
  category: 'natural',
  fields: [
    {
      name: 'ecosystem_type',
      label: 'Ecosystem Type',
      type: 'text',
      required: true,
      placeholder: 'e.g. coral reef, old-growth forest, deep cave network',
      helpText: 'A descriptive name for this type of ecosystem.',
    },
    {
      name: 'energy_source',
      label: 'Primary Energy Source',
      type: 'text',
      placeholder: 'e.g. solar, geothermal, chemosynthetic, magical',
      helpText: 'The fundamental energy source driving this ecosystem.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      required: true,
      options: ['stable', 'fragile', 'resilient', 'collapsing', 'recovering'],
      helpText: 'The current health and resilience of this ecosystem.',
    },
    {
      name: 'biodiversity_index',
      label: 'Biodiversity Index',
      type: 'text',
      placeholder: 'e.g. very high, moderate, low',
      helpText: 'A qualitative or quantitative measure of species diversity.',
    },
    {
      name: 'keystone_species_id',
      label: 'Keystone Species',
      type: 'text',
      placeholder: 'ID of the keystone species',
      helpText: 'The species whose removal would cause the ecosystem to collapse or fundamentally change.',
    },
    {
      name: 'biome_ids',
      label: 'Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "wetland_biome_2"]',
      helpText: 'The biomes this ecosystem spans or exists within.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'text',
      placeholder: 'e.g. 500 km², a single valley, continent-wide',
      helpText: 'The approximate area or extent of this ecosystem.',
    },
    {
      name: 'succession_stage',
      label: 'Succession Stage',
      type: 'select',
      options: ['pioneer', 'early', 'developing', 'mature', 'climax', 'degraded'],
      helpText: 'The ecological succession stage — how mature and established this ecosystem is.',
    },
    {
      name: 'age',
      label: 'Age',
      type: 'text',
      placeholder: 'e.g. 10,000 years, recently formed, ancient',
      helpText: 'How long this ecosystem has existed in its current form.',
    },
    {
      name: 'threats',
      label: 'Threats',
      type: 'json',
      placeholder: '["deforestation", "invasive species", "mana depletion"]',
      helpText: 'Current threats to this ecosystem\'s health and stability.',
    },
  ],
  elementTypes: ['terrestrial', 'aquatic', 'aerial', 'subterranean', 'magical', 'artificial'],
  prompts: [
    'What are the keystone species in your major ecosystems? What would happen if they disappeared?',
    'How do food webs work in your world? Are there unusual trophic levels or energy sources beyond sunlight?',
    'Are any ecosystems currently under threat from civilization, climate change, or magical disruption?',
    'Have any ecosystems been artificially created—magical gardens, terraformed wastelands, or engineered habitats?',
    'How do ecosystems recover after catastrophic events like volcanic eruptions, wars, or magical disasters?',
  ],
  magicPermeation: {
    companionTable: 'ecosystems_magic_aspects',
    fields: [
      {
        name: 'mana_cycle_id',
        label: 'Mana Cycle',
        type: 'text',
        placeholder: 'ID of the associated mana cycle',
        helpText: 'The mana cycle that governs magical energy flow through this ecosystem.',
      },
      {
        name: 'magical_food_web_id',
        label: 'Magical Food Web',
        type: 'text',
        placeholder: 'ID of the magical food web',
        helpText: 'The magical trophic network—which organisms produce, transfer, and consume mana.',
      },
      {
        name: 'ambient_mana_level',
        label: 'Ambient Mana Level',
        type: 'textarea',
        helpText: 'The baseline level of free magical energy in this ecosystem.',
      },
      {
        name: 'mana_flow_patterns',
        label: 'Mana Flow Patterns',
        type: 'textarea',
        helpText: 'How mana moves through the ecosystem—ley currents, seasonal tides, organism-driven cycles.',
      },
      {
        name: 'keystone_magical_species',
        label: 'Keystone Magical Species',
        type: 'textarea',
        helpText: 'Species whose magical function is critical to the ecosystem\'s mana balance.',
      },
      {
        name: 'magical_carrying_capacity',
        label: 'Magical Carrying Capacity',
        type: 'textarea',
        helpText: 'The maximum amount of magical activity this ecosystem can sustain before degradation.',
      },
      {
        name: 'magical_disturbance_history',
        label: 'Magical Disturbance History',
        type: 'textarea',
        helpText: 'Past magical events that damaged or transformed this ecosystem.',
      },
      {
        name: 'recovery_from_magical_damage',
        label: 'Recovery from Magical Damage',
        type: 'textarea',
        helpText: 'How this ecosystem heals after magical disruption—natural recovery, remediation, or permanent scarring.',
      },
      {
        name: 'magical_succession',
        label: 'Magical Succession',
        type: 'textarea',
        helpText: 'How the magical character of the ecosystem changes over time as it matures—pioneer mana-species giving way to climax communities.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this ecosystem\'s functioning.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: false,
    prompts: [
      'Is there a "mana cycle" analogous to the water or carbon cycle? How does magical energy flow through producers, consumers, and decomposers?',
      'What happens when an ecosystem\'s magical carrying capacity is exceeded—mana storms, mutations, dead zones?',
      'Are there keystone magical species whose mana production or regulation keeps the entire ecosystem in balance?',
    ],
  },
  archetypes: [
    {
      id: 'old_growth_forest',
      name: 'Old-Growth Forest Ecosystem',
      description: 'A mature, undisturbed forest ecosystem with centuries of accumulated complexity.',
      element_type: 'terrestrial',
      summary: 'An ancient forest ecosystem at climax succession',
      fields: {
        ecosystem_type: 'Temperate old-growth forest',
        energy_source: 'Solar radiation via photosynthesis',
        stability: 'resilient',
        biodiversity_index: 'High — hundreds of species in complex food webs',
        geographic_scope: 'Regional (thousands of square kilometers)',
        succession_stage: 'climax',
        age: 'Several thousand years undisturbed',
      },
    },
    {
      id: 'coral_reef_ecosystem',
      name: 'Coral Reef Ecosystem',
      description: 'A fragile marine ecosystem of extraordinary diversity built on a living coral framework.',
      element_type: 'aquatic',
      summary: 'A fragile but spectacularly biodiverse underwater world',
      fields: {
        ecosystem_type: 'Tropical coral reef',
        energy_source: 'Photosynthetic algae (zooxanthellae) in symbiosis with coral',
        stability: 'fragile',
        biodiversity_index: 'Extremely high — thousands of interdependent species',
        geographic_scope: 'Local to regional (reef system)',
        succession_stage: 'mature',
        age: 'Thousands of years of continuous coral growth',
      },
    },
    {
      id: 'hydrothermal_vent',
      name: 'Hydrothermal Vent Ecosystem',
      description: 'A deep-sea ecosystem sustained entirely by chemosynthesis around volcanic vents.',
      element_type: 'aquatic',
      summary: 'A bizarre ecosystem thriving in superheated darkness on the ocean floor',
      fields: {
        ecosystem_type: 'Deep-sea hydrothermal vent',
        energy_source: 'Chemosynthesis from volcanic mineral-rich superheated water',
        stability: 'fragile',
        biodiversity_index: 'Low species count but high endemism — most species found nowhere else',
        geographic_scope: 'Extremely localized (single vent field)',
        succession_stage: 'developing',
        age: 'Decades to centuries (vents are geologically ephemeral)',
      },
    },
    {
      id: 'freshwater_wetland',
      name: 'Freshwater Wetland Ecosystem',
      description: 'A seasonally flooded ecosystem that filters water and supports incredible bird and fish diversity.',
      element_type: 'terrestrial',
      summary: 'A waterlogged paradise for birds, fish, and amphibians',
      fields: {
        ecosystem_type: 'Freshwater marsh and riparian wetland',
        energy_source: 'Solar radiation and nutrient-rich flooding',
        stability: 'resilient',
        biodiversity_index: 'High — especially for birds, amphibians, and aquatic insects',
        geographic_scope: 'Local (river floodplain or lake margin)',
        succession_stage: 'mature',
        age: 'Hundreds to thousands of years',
      },
    },
    {
      id: 'symbiotic_megaorganism',
      name: 'Symbiotic Megaorganism',
      description: 'An ecosystem so tightly integrated that it functions as a single living superorganism — every species is an organ.',
      element_type: 'magical',
      summary: 'An ecosystem that IS a creature — every species within it functions like an organ',
      fields: {
        ecosystem_type: 'Symbiotic megaorganism (borderline single entity)',
        energy_source: 'Shared circulatory system distributing nutrients from photosynthetic and chemosynthetic members',
        stability: 'fragile',
        biodiversity_index: 'Moderate species count but total interdependence — remove one species and the whole system fails',
        geographic_scope: 'Local (a single valley, island, or cavern)',
        succession_stage: 'climax',
        age: 'Ancient — the integration deepened over millions of years of co-evolution',
      },
    },
  ],
  defaultSortField: 'ecosystem_type',
};
