import type { DomainConfig } from '../types/domains.js';

export const faunaConfig: DomainConfig = {
  id: 'fauna',
  name: 'Fauna',
  namePlural: 'Fauna',
  icon: 'paw-print',
  color: '#e67e22',
  description: 'Catalog the animals, beasts, and creatures of your world—from mundane livestock to apex predators to legendary monsters. Fauna fills every ecological niche and shapes how civilizations live, fight, and travel.',
  tableName: 'fauna',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'text',
      placeholder: 'e.g. quadruped, serpentine, avian, amorphous',
      helpText: 'The general body plan and morphology of this creature.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      required: true,
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'custom'],
      helpText: 'What this creature eats.',
    },
    {
      name: 'locomotion',
      label: 'Locomotion',
      type: 'json',
      placeholder: '["walking", "flying", "swimming"]',
      helpText: 'Methods of movement this creature uses.',
    },
    {
      name: 'max_size',
      label: 'Maximum Size',
      type: 'text',
      placeholder: 'e.g. 3m long, 500kg, colossal',
      helpText: 'The largest size an adult of this species reaches.',
    },
    {
      name: 'lifespan',
      label: 'Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 3 months, ageless',
      helpText: 'Typical natural lifespan.',
    },
    {
      name: 'intelligence_level',
      label: 'Intelligence Level',
      type: 'select',
      required: true,
      options: ['instinctive', 'animal', 'clever', 'near_sentient', 'sentient'],
      helpText: 'The cognitive capability of this species.',
    },
    {
      name: 'social_structure',
      label: 'Social Structure',
      type: 'text',
      placeholder: 'e.g. solitary, pack, herd, hive, family unit',
      helpText: 'How individuals of this species organize socially.',
    },
    {
      name: 'rarity',
      label: 'Rarity',
      type: 'select',
      options: ['common', 'uncommon', 'rare', 'very_rare', 'unique'],
      helpText: 'How commonly this species is encountered in its native habitat.',
    },
    {
      name: 'domesticable',
      label: 'Domesticable',
      type: 'boolean',
      helpText: 'Whether this species can be tamed or domesticated by sentient beings.',
    },
    {
      name: 'migration_pattern',
      label: 'Migration Pattern',
      type: 'textarea',
      placeholder: 'Describe seasonal movements, routes, triggers...',
      helpText: 'Seasonal or cyclical movement patterns — routes, timing, and what triggers migration.',
    },
    {
      name: 'habitat_niche',
      label: 'Habitat Niche',
      type: 'text',
      placeholder: 'e.g. forest canopy, deep ocean floor, cave systems',
      helpText: 'The specific microhabitat this species occupies within its biome.',
    },
    {
      name: 'communication',
      label: 'Communication',
      type: 'textarea',
      placeholder: 'Describe calls, songs, pheromones, displays...',
      helpText: 'How this species communicates — vocalizations, chemical signals, visual displays, etc.',
    },
    {
      name: 'habitat_description',
      label: 'Habitat Description',
      type: 'textarea',
      placeholder: 'Describe preferred environment, shelter, territory needs...',
      helpText: 'Prose description of habitat preferences beyond biome classification.',
    },
    {
      name: 'biome_ids',
      label: 'Native Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "grassland_biome_2"]',
      helpText: 'Biomes where this species is naturally found.',
    },
  ],
  elementTypes: ['mammal', 'reptile', 'bird', 'fish', 'insect', 'amphibian', 'invertebrate', 'mythical_beast', 'custom'],
  prompts: [
    'What creatures serve as beasts of burden, mounts, or companions? How were they domesticated, and what do they need?',
    'What apex predators sit at the top of your food chains? How do civilizations defend against or coexist with them?',
    'Are there migratory species whose movements mark the seasons or create hazards for travelers?',
    'What creatures have gone extinct in your world, and what ecological or cultural impacts did their loss cause?',
    'How have sentient species bred, modified, or engineered animals for war, labor, entertainment, or companionship?',
  ],
  magicPermeation: {
    companionTable: 'fauna_magic_aspects',
    fields: [
      {
        name: 'innate_magical_abilities',
        label: 'Innate Magical Abilities',
        type: 'textarea',
        helpText: 'Magical powers this species naturally possesses—breath weapons, illusions, phasing, etc.',
      },
      {
        name: 'mana_interaction',
        label: 'Mana Interaction',
        type: 'select',
        options: ['none', 'absorber', 'producer', 'conductor', 'storage', 'converter', 'dampener'],
        helpText: 'How this species interacts with ambient mana.',
      },
      {
        name: 'magical_classification',
        label: 'Magical Classification',
        type: 'select',
        options: ['mundane', 'mana_touched', 'magical_beast', 'arcane_creature', 'elemental', 'construct', 'undead', 'planar', 'divine', 'custom'],
        helpText: 'Where this creature falls in the magical taxonomy.',
      },
      {
        name: 'familiar_potential',
        label: 'Familiar Potential',
        type: 'boolean',
        helpText: 'Whether this species can serve as a wizard\'s familiar.',
      },
      {
        name: 'familiar_bond_type',
        label: 'Familiar Bond Type',
        type: 'text',
        placeholder: 'e.g. telepathic, empathic, mana-shared',
        helpText: 'The nature of the magical bond when this creature serves as a familiar.',
      },
      {
        name: 'summonable',
        label: 'Summonable',
        type: 'boolean',
        helpText: 'Whether this creature can be magically summoned.',
      },
      {
        name: 'summoning_requirements',
        label: 'Summoning Requirements',
        type: 'textarea',
        helpText: 'What is needed to summon this creature—rituals, reagents, conditions.',
      },
      {
        name: 'magical_materials_harvestable',
        label: 'Harvestable Magical Materials',
        type: 'textarea',
        helpText: 'Magical components that can be harvested—scales, blood, venom, heartstone, etc.',
      },
      {
        name: 'mana_diet',
        label: 'Feeds on Mana',
        type: 'boolean',
        helpText: 'Whether this creature partially or wholly sustains itself on magical energy.',
      },
      {
        name: 'magical_evolution_path',
        label: 'Magical Evolution Path',
        type: 'textarea',
        helpText: 'How exposure to magic can cause this species to evolve or transform over generations.',
      },
      {
        name: 'intelligence_magical',
        label: 'Magical Intelligence',
        type: 'textarea',
        helpText: 'How magic enhances or grants intelligence beyond the species\' natural level.',
      },
      {
        name: 'domestication_magical',
        label: 'Magical Domestication',
        type: 'textarea',
        helpText: 'Special magical methods required to tame or bond with this creature.',
      },
      {
        name: 'native_plane_id',
        label: 'Native Plane',
        type: 'text',
        placeholder: 'ID of the creature\'s plane of origin',
        helpText: 'If extraplanar, the plane this creature originates from.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' existence and behavior.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Which creatures have innate magical abilities? Did they evolve these powers naturally, or were they shaped by ancient enchantments?',
      'Can magical creatures serve as familiars, mounts, or guardians? What kind of bond forms between creature and mage?',
      'Are there creatures that feed on mana itself? How does their presence affect the magical ecosystem around them?',
    ],
  },
  archetypes: [
    {
      id: 'apex_predator',
      name: 'Apex Predator',
      description: 'A dominant carnivore at the top of its food chain — feared, respected, and ecologically vital.',
      element_type: 'mammal',
      summary: 'A powerful top predator that shapes the ecosystem through fear and predation',
      fields: {
        body_type: 'Large quadruped, muscular build',
        diet: 'carnivore',
        max_size: '3-5 meters, 200-600 kg',
        lifespan: '20-40 years',
        intelligence_level: 'clever',
        social_structure: 'Solitary or small family groups with large territories',
        rarity: 'uncommon',
        domesticable: false,
        habitat_niche: 'Dominant predator of open and forested terrain',
        communication: 'Roars, scent marking, and body language to establish territory. Vocalizations can carry for kilometers.',
      },
    },
    {
      id: 'beast_of_burden',
      name: 'Beast of Burden',
      description: 'A strong, domesticated animal used for hauling, plowing, or riding.',
      element_type: 'mammal',
      summary: 'A strong domesticated animal essential to agriculture and transport',
      fields: {
        body_type: 'Large quadruped, heavy-boned',
        diet: 'herbivore',
        max_size: '2-3 meters tall, 500-1000 kg',
        lifespan: '25-40 years',
        intelligence_level: 'animal',
        social_structure: 'Herd animal, bonds with handlers',
        rarity: 'common',
        domesticable: true,
        habitat_niche: 'Grasslands and farmland',
        communication: 'Low vocalizations, ear and tail positioning, stamping.',
      },
    },
    {
      id: 'migratory_herder',
      name: 'Migratory Herder',
      description: 'A gregarious herbivore that travels in vast herds following seasonal food sources.',
      element_type: 'mammal',
      summary: 'A herd animal whose mass migrations reshape the landscape',
      fields: {
        body_type: 'Medium quadruped, built for endurance',
        diet: 'herbivore',
        max_size: '1.5-2 meters at shoulder, 200-400 kg',
        lifespan: '15-25 years',
        intelligence_level: 'animal',
        social_structure: 'Massive herds of hundreds to thousands',
        rarity: 'common',
        domesticable: false,
        migration_pattern: 'Annual north-south migration following the rains and fresh grass. Herds travel thousands of kilometers, crossing rivers and navigating predator territories.',
        habitat_niche: 'Open grasslands and savannahs',
        communication: 'Grunting, bellowing during mating season, and alarm snorts when predators are detected.',
      },
    },
    {
      id: 'colonial_insect',
      name: 'Colonial Insect',
      description: 'A eusocial insect species with complex hive structures and caste-based division of labor.',
      element_type: 'insect',
      summary: 'A hive-building insect species with rigid social castes',
      fields: {
        body_type: 'Hexapod with segmented exoskeleton',
        diet: 'omnivore',
        max_size: '1-5 cm per individual; colonies span meters',
        lifespan: 'Workers: months. Queens: 10-30 years',
        intelligence_level: 'instinctive',
        social_structure: 'Eusocial — queen, workers, soldiers, and drones',
        rarity: 'common',
        domesticable: false,
        habitat_niche: 'Underground or arboreal nests',
        communication: 'Chemical pheromone trails, vibration patterns through the nest substrate, and antenna touching.',
      },
    },
    {
      id: 'deep_sea_leviathan',
      name: 'Deep-Sea Leviathan',
      description: 'A colossal marine creature dwelling in the lightless depths, the stuff of sailors\' nightmares.',
      element_type: 'fish',
      summary: 'A titanic deep-ocean predator of legendary proportions',
      fields: {
        body_type: 'Serpentine or cephalopod, massive',
        diet: 'carnivore',
        max_size: '30-100+ meters',
        lifespan: 'Unknown — possibly centuries',
        intelligence_level: 'clever',
        social_structure: 'Solitary',
        rarity: 'very_rare',
        domesticable: false,
        habitat_niche: 'Abyssal ocean depths, 1000m+',
        communication: 'Deep infrasonic pulses that travel vast distances through the water. Bioluminescent displays.',
      },
    },
    {
      id: 'sky_whale',
      name: 'Sky Whale',
      description: 'A colossal lighter-than-air creature that filter-feeds on atmospheric plankton, drifting between continents.',
      element_type: 'mythical_beast',
      summary: 'A gentle giant that swims through the sky, its shadow darkening entire towns',
      fields: {
        body_type: 'Cetacean-like with gas bladders and membranous fins for steering',
        diet: 'filter_feeder',
        max_size: '80-200 meters in length',
        lifespan: 'Unknown — oldest tracked individual exceeds 500 years',
        intelligence_level: 'near_sentient',
        social_structure: 'Small pods of 3-7 that sing to each other across hundreds of kilometers',
        rarity: 'rare',
        domesticable: false,
        habitat_niche: 'Upper atmosphere, 2000-8000m altitude',
        communication: 'Infrasonic songs that resonate through the atmosphere for hundreds of kilometers. The songs shift seasonally and may encode navigational information. Scholars debate whether the songs constitute language.',
        migration_pattern: 'Annual circumnavigation following atmospheric plankton blooms. Calving grounds are above remote mountain ranges where updrafts support newborns learning to stay aloft.',
      },
    },
    {
      id: 'mimic_predator',
      name: 'Terrain Mimic',
      description: 'A creature that perfectly disguises itself as a patch of terrain — a boulder, a fallen log, even a stretch of path.',
      element_type: 'invertebrate',
      summary: 'A patient ambush predator indistinguishable from its surroundings',
      fields: {
        body_type: 'Amorphous, flattened — reshapes its outer tissue to match local terrain',
        diet: 'carnivore',
        max_size: '2-8 meters across when flattened',
        lifespan: '30-60 years',
        intelligence_level: 'clever',
        social_structure: 'Solitary and fiercely territorial — two mimics near each other results in a slow, silent war of camouflage and ambush',
        rarity: 'uncommon',
        domesticable: false,
        habitat_niche: 'Anywhere with foot traffic — forest paths, river crossings, cave entrances',
        communication: 'Chemical signals left in mucus trails. Other mimics can read these to determine territory boundaries, mating readiness, and prey density.',
      },
    },
  ],
  defaultSortField: 'diet',
};
