import type { DomainConfig } from '../types/domains.js';

export const faunaConfig: DomainConfig = {
  id: 'fauna',
  name: 'Fauna',
  namePlural: 'Fauna',
  icon: 'paw-print',
  color: '#e67e22',
  description: 'Catalog the animals, beasts, and creatures of your world—from mundane livestock to apex predators to legendary monsters. Fauna fills every ecological niche and shapes how civilizations live, fight, and travel.',
  tableName: 'fauna',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'text',
      placeholder: 'e.g. quadruped, serpentine, avian, amorphous',
      helpText: 'The general body plan and morphology of this creature.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      required: true,
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'custom'],
      helpText: 'What this creature eats.',
    },
    {
      name: 'locomotion',
      label: 'Locomotion',
      type: 'json',
      placeholder: '["walking", "flying", "swimming"]',
      helpText: 'Methods of movement this creature uses.',
    },
    {
      name: 'max_size',
      label: 'Maximum Size',
      type: 'text',
      placeholder: 'e.g. 3m long, 500kg, colossal',
      helpText: 'The largest size an adult of this species reaches.',
    },
    {
      name: 'lifespan',
      label: 'Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 3 months, ageless',
      helpText: 'Typical natural lifespan.',
    },
    {
      name: 'intelligence_level',
      label: 'Intelligence Level',
      type: 'select',
      required: true,
      options: ['instinctive', 'animal', 'clever', 'near_sentient', 'sentient'],
      helpText: 'The cognitive capability of this species.',
    },
    {
      name: 'social_structure',
      label: 'Social Structure',
      type: 'text',
      placeholder: 'e.g. solitary, pack, herd, hive, family unit',
      helpText: 'How individuals of this species organize socially.',
    },
    {
      name: 'rarity',
      label: 'Rarity',
      type: 'select',
      options: ['common', 'uncommon', 'rare', 'very_rare', 'unique'],
      helpText: 'How commonly this species is encountered in its native habitat.',
    },
    {
      name: 'domesticable',
      label: 'Domesticable',
      type: 'boolean',
      helpText: 'Whether this species can be tamed or domesticated by sentient beings.',
    },
    {
      name: 'biome_ids',
      label: 'Native Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "grassland_biome_2"]',
      helpText: 'Biomes where this species is naturally found.',
    },
  ],
  elementTypes: ['mammal', 'reptile', 'bird', 'fish', 'insect', 'amphibian', 'invertebrate', 'mythical_beast', 'custom'],
  prompts: [
    'What creatures serve as beasts of burden, mounts, or companions? How were they domesticated, and what do they need?',
    'What apex predators sit at the top of your food chains? How do civilizations defend against or coexist with them?',
    'Are there migratory species whose movements mark the seasons or create hazards for travelers?',
    'What creatures have gone extinct in your world, and what ecological or cultural impacts did their loss cause?',
    'How have sentient species bred, modified, or engineered animals for war, labor, entertainment, or companionship?',
  ],
  magicPermeation: {
    companionTable: 'fauna_magic_aspects',
    fields: [
      {
        name: 'innate_magical_abilities',
        label: 'Innate Magical Abilities',
        type: 'textarea',
        helpText: 'Magical powers this species naturally possesses—breath weapons, illusions, phasing, etc.',
      },
      {
        name: 'mana_interaction',
        label: 'Mana Interaction',
        type: 'select',
        options: ['none', 'absorber', 'producer', 'conductor', 'storage', 'converter', 'dampener'],
        helpText: 'How this species interacts with ambient mana.',
      },
      {
        name: 'magical_classification',
        label: 'Magical Classification',
        type: 'select',
        options: ['mundane', 'mana_touched', 'magical_beast', 'arcane_creature', 'elemental', 'construct', 'undead', 'planar', 'divine', 'custom'],
        helpText: 'Where this creature falls in the magical taxonomy.',
      },
      {
        name: 'familiar_potential',
        label: 'Familiar Potential',
        type: 'boolean',
        helpText: 'Whether this species can serve as a wizard\'s familiar.',
      },
      {
        name: 'familiar_bond_type',
        label: 'Familiar Bond Type',
        type: 'text',
        placeholder: 'e.g. telepathic, empathic, mana-shared',
        helpText: 'The nature of the magical bond when this creature serves as a familiar.',
      },
      {
        name: 'summonable',
        label: 'Summonable',
        type: 'boolean',
        helpText: 'Whether this creature can be magically summoned.',
      },
      {
        name: 'summoning_requirements',
        label: 'Summoning Requirements',
        type: 'textarea',
        helpText: 'What is needed to summon this creature—rituals, reagents, conditions.',
      },
      {
        name: 'magical_materials_harvestable',
        label: 'Harvestable Magical Materials',
        type: 'textarea',
        helpText: 'Magical components that can be harvested—scales, blood, venom, heartstone, etc.',
      },
      {
        name: 'mana_diet',
        label: 'Feeds on Mana',
        type: 'boolean',
        helpText: 'Whether this creature partially or wholly sustains itself on magical energy.',
      },
      {
        name: 'magical_evolution_path',
        label: 'Magical Evolution Path',
        type: 'textarea',
        helpText: 'How exposure to magic can cause this species to evolve or transform over generations.',
      },
      {
        name: 'intelligence_magical',
        label: 'Magical Intelligence',
        type: 'textarea',
        helpText: 'How magic enhances or grants intelligence beyond the species\' natural level.',
      },
      {
        name: 'domestication_magical',
        label: 'Magical Domestication',
        type: 'textarea',
        helpText: 'Special magical methods required to tame or bond with this creature.',
      },
      {
        name: 'native_plane_id',
        label: 'Native Plane',
        type: 'text',
        placeholder: 'ID of the creature\'s plane of origin',
        helpText: 'If extraplanar, the plane this creature originates from.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' existence and behavior.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Which creatures have innate magical abilities? Did they evolve these powers naturally, or were they shaped by ancient enchantments?',
      'Can magical creatures serve as familiars, mounts, or guardians? What kind of bond forms between creature and mage?',
      'Are there creatures that feed on mana itself? How does their presence affect the magical ecosystem around them?',
    ],
  },
  defaultSortField: 'diet',
};
