import type { DomainConfig } from '../types/domains.js';

export const faunaConfig: DomainConfig = {
  id: 'fauna',
  name: 'Fauna',
  namePlural: 'Fauna',
  icon: 'paw-print',
  color: '#e67e22',
  description: 'Catalog the animals, beasts, and creatures of your world—from mundane livestock to apex predators to legendary monsters. Fauna fills every ecological niche and shapes how civilizations live, fight, and travel.',
  tableName: 'fauna',
  category: 'natural',
  fields: [
    {
      name: 'body_type',
      label: 'Body Type',
      type: 'text',
      placeholder: 'e.g. quadruped, serpentine, avian, amorphous',
      helpText: 'The general body plan and morphology of this creature.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      required: true,
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'custom'],
      helpText: 'What this creature eats.',
    },
    {
      name: 'locomotion',
      label: 'Locomotion',
      type: 'json',
      placeholder: '["walking", "flying", "swimming"]',
      helpText: 'Methods of movement this creature uses.',
    },
    {
      name: 'max_size',
      label: 'Maximum Size',
      type: 'text',
      placeholder: 'e.g. 3m long, 500kg, colossal',
      helpText: 'The largest size an adult of this species reaches.',
    },
    {
      name: 'lifespan',
      label: 'Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 3 months, ageless',
      helpText: 'Typical natural lifespan.',
    },
    {
      name: 'intelligence_level',
      label: 'Intelligence Level',
      type: 'select',
      required: true,
      options: ['instinctive', 'animal', 'clever', 'near_sentient', 'sentient'],
      helpText: 'The cognitive capability of this species.',
    },
    {
      name: 'social_structure',
      label: 'Social Structure',
      type: 'text',
      placeholder: 'e.g. solitary, pack, herd, hive, family unit',
      helpText: 'How individuals of this species organize socially.',
    },
    {
      name: 'rarity',
      label: 'Rarity',
      type: 'select',
      options: ['common', 'uncommon', 'rare', 'very_rare', 'unique'],
      helpText: 'How commonly this species is encountered in its native habitat.',
    },
    {
      name: 'domesticable',
      label: 'Domesticable',
      type: 'boolean',
      helpText: 'Whether this species can be tamed or domesticated by sentient beings.',
    },
    {
      name: 'migration_pattern',
      label: 'Migration Pattern',
      type: 'textarea',
      placeholder: 'Describe seasonal movements, routes, triggers...',
      helpText: 'Seasonal or cyclical movement patterns — routes, timing, and what triggers migration.',
    },
    {
      name: 'habitat_niche',
      label: 'Habitat Niche',
      type: 'text',
      placeholder: 'e.g. forest canopy, deep ocean floor, cave systems',
      helpText: 'The specific microhabitat this species occupies within its biome.',
    },
    {
      name: 'communication',
      label: 'Communication',
      type: 'textarea',
      placeholder: 'Describe calls, songs, pheromones, displays...',
      helpText: 'How this species communicates — vocalizations, chemical signals, visual displays, etc.',
    },
    {
      name: 'habitat_description',
      label: 'Habitat Description',
      type: 'textarea',
      placeholder: 'Describe preferred environment, shelter, territory needs...',
      helpText: 'Prose description of habitat preferences beyond biome classification.',
    },
    {
      name: 'biome_ids',
      label: 'Native Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "grassland_biome_2"]',
      helpText: 'Biomes where this species is naturally found.',
    },
  ],
  elementTypes: ['mammal', 'reptile', 'bird', 'fish', 'insect', 'amphibian', 'invertebrate', 'mythical_beast', 'custom'],
  elementTypeDescriptions: {
    mammal: 'A warm-blooded vertebrate with hair or fur that nurses its young with milk. Includes predators, livestock, and companion animals.',
    reptile: 'A cold-blooded, scaly vertebrate that lays eggs or bears live young. Includes lizards, snakes, turtles, and dragons.',
    bird: 'A feathered, warm-blooded vertebrate with wings. Most can fly, and they fill roles from predator to messenger to sacred symbol.',
    fish: 'A cold-blooded aquatic vertebrate that breathes through gills. Inhabits oceans, rivers, and lakes in enormous variety.',
    insect: 'A six-legged arthropod, often winged. The most numerous animals on any world — pollinators, pests, hive-builders, and decomposers.',
    amphibian: 'A vertebrate that typically lives in water as a larva and on land as an adult. Sensitive to environmental changes.',
    invertebrate: 'An animal without a backbone — worms, mollusks, crustaceans, jellyfish, and more. Diverse and ecologically essential.',
    mythical_beast: 'A creature of legend — dragons, griffins, basilisks, or beings unique to your world that defy natural classification.',
    custom: 'A creature that doesn\'t fit standard categories — something unique to your world\'s biology.',
  },
  prompts: [
    'What creatures serve as beasts of burden, mounts, or companions? How were they domesticated, and what do they need?',
    'What apex predators sit at the top of your food chains? How do civilizations defend against or coexist with them?',
    'Are there migratory species whose movements mark the seasons or create hazards for travelers?',
    'What creatures have gone extinct in your world, and what ecological or cultural impacts did their loss cause?',
    'How have sentient species bred, modified, or engineered animals for war, labor, entertainment, or companionship?',
  ],
  magicPermeation: {
    companionTable: 'fauna_magic_aspects',
    fields: [
      {
        name: 'innate_magical_abilities',
        label: 'Innate Magical Abilities',
        type: 'textarea',
        helpText: 'Magical powers this species naturally possesses—breath weapons, illusions, phasing, etc.',
      },
      {
        name: 'mana_interaction',
        label: 'Mana Interaction',
        type: 'select',
        options: ['none', 'absorber', 'producer', 'conductor', 'storage', 'converter', 'dampener'],
        helpText: 'How this species interacts with ambient mana.',
      },
      {
        name: 'magical_classification',
        label: 'Magical Classification',
        type: 'select',
        options: ['mundane', 'mana_touched', 'magical_beast', 'arcane_creature', 'elemental', 'construct', 'undead', 'planar', 'divine', 'custom'],
        helpText: 'Where this creature falls in the magical taxonomy.',
      },
      {
        name: 'familiar_potential',
        label: 'Familiar Potential',
        type: 'boolean',
        helpText: 'Whether this species can serve as a wizard\'s familiar.',
      },
      {
        name: 'familiar_bond_type',
        label: 'Familiar Bond Type',
        type: 'text',
        placeholder: 'e.g. telepathic, empathic, mana-shared',
        helpText: 'The nature of the magical bond when this creature serves as a familiar.',
      },
      {
        name: 'summonable',
        label: 'Summonable',
        type: 'boolean',
        helpText: 'Whether this creature can be magically summoned.',
      },
      {
        name: 'summoning_requirements',
        label: 'Summoning Requirements',
        type: 'textarea',
        helpText: 'What is needed to summon this creature—rituals, reagents, conditions.',
      },
      {
        name: 'magical_materials_harvestable',
        label: 'Harvestable Magical Materials',
        type: 'textarea',
        helpText: 'Magical components that can be harvested—scales, blood, venom, heartstone, etc.',
      },
      {
        name: 'mana_diet',
        label: 'Feeds on Mana',
        type: 'boolean',
        helpText: 'Whether this creature partially or wholly sustains itself on magical energy.',
      },
      {
        name: 'magical_evolution_path',
        label: 'Magical Evolution Path',
        type: 'textarea',
        helpText: 'How exposure to magic can cause this species to evolve or transform over generations.',
      },
      {
        name: 'intelligence_magical',
        label: 'Magical Intelligence',
        type: 'textarea',
        helpText: 'How magic enhances or grants intelligence beyond the species\' natural level.',
      },
      {
        name: 'domestication_magical',
        label: 'Magical Domestication',
        type: 'textarea',
        helpText: 'Special magical methods required to tame or bond with this creature.',
      },
      {
        name: 'native_plane_id',
        label: 'Native Plane',
        type: 'text',
        placeholder: 'ID of the creature\'s plane of origin',
        helpText: 'If extraplanar, the plane this creature originates from.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' existence and behavior.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Which creatures have innate magical abilities? Did they evolve these powers naturally, or were they shaped by ancient enchantments?',
      'Can magical creatures serve as familiars, mounts, or guardians? What kind of bond forms between creature and mage?',
      'Are there creatures that feed on mana itself? How does their presence affect the magical ecosystem around them?',
    ],
  },
  archetypes: [
    {
      id: 'apex_predator',
      name: 'Apex Predator',
      description: 'A dominant carnivore at the top of its food chain — feared, respected, and ecologically vital.',
      element_type: 'mammal',
      summary: 'A powerful top predator that shapes the ecosystem through fear and predation',
      fields: {
        body_type: 'Large quadruped, muscular build',
        diet: 'carnivore',
        max_size: '3-5 meters, 200-600 kg',
        lifespan: '20-40 years',
        intelligence_level: 'clever',
        social_structure: 'Solitary or small family groups with large territories',
        rarity: 'uncommon',
        domesticable: false,
        habitat_niche: 'Dominant predator of open and forested terrain',
        communication: 'Roars, scent marking, and body language to establish territory. Vocalizations can carry for kilometers.',
      },
    },
    {
      id: 'beast_of_burden',
      name: 'Beast of Burden',
      description: 'A strong, domesticated animal used for hauling, plowing, or riding.',
      element_type: 'mammal',
      summary: 'A strong domesticated animal essential to agriculture and transport',
      fields: {
        body_type: 'Large quadruped, heavy-boned',
        diet: 'herbivore',
        max_size: '2-3 meters tall, 500-1000 kg',
        lifespan: '25-40 years',
        intelligence_level: 'animal',
        social_structure: 'Herd animal, bonds with handlers',
        rarity: 'common',
        domesticable: true,
        habitat_niche: 'Grasslands and farmland',
        communication: 'Low vocalizations, ear and tail positioning, stamping.',
      },
    },
    {
      id: 'migratory_herder',
      name: 'Migratory Herder',
      description: 'A gregarious herbivore that travels in vast herds following seasonal food sources.',
      element_type: 'mammal',
      summary: 'A herd animal whose mass migrations reshape the landscape',
      fields: {
        body_type: 'Medium quadruped, built for endurance',
        diet: 'herbivore',
        max_size: '1.5-2 meters at shoulder, 200-400 kg',
        lifespan: '15-25 years',
        intelligence_level: 'animal',
        social_structure: 'Massive herds of hundreds to thousands',
        rarity: 'common',
        domesticable: false,
        migration_pattern: 'Annual north-south migration following the rains and fresh grass. Herds travel thousands of kilometers, crossing rivers and navigating predator territories.',
        habitat_niche: 'Open grasslands and savannahs',
        communication: 'Grunting, bellowing during mating season, and alarm snorts when predators are detected.',
      },
    },
    {
      id: 'colonial_insect',
      name: 'Colonial Insect',
      description: 'A eusocial insect species with complex hive structures and caste-based division of labor.',
      element_type: 'insect',
      summary: 'A hive-building insect species with rigid social castes',
      fields: {
        body_type: 'Hexapod with segmented exoskeleton',
        diet: 'omnivore',
        max_size: '1-5 cm per individual; colonies span meters',
        lifespan: 'Workers: months. Queens: 10-30 years',
        intelligence_level: 'instinctive',
        social_structure: 'Eusocial — queen, workers, soldiers, and drones',
        rarity: 'common',
        domesticable: false,
        habitat_niche: 'Underground or arboreal nests',
        communication: 'Chemical pheromone trails, vibration patterns through the nest substrate, and antenna touching.',
      },
    },
    {
      id: 'deep_sea_leviathan',
      name: 'Deep-Sea Leviathan',
      description: 'A colossal marine creature dwelling in the lightless depths, the stuff of sailors\' nightmares.',
      element_type: 'fish',
      summary: 'A titanic deep-ocean predator of legendary proportions',
      fields: {
        body_type: 'Serpentine or cephalopod, massive',
        diet: 'carnivore',
        max_size: '30-100+ meters',
        lifespan: 'Unknown — possibly centuries',
        intelligence_level: 'clever',
        social_structure: 'Solitary',
        rarity: 'very_rare',
        domesticable: false,
        habitat_niche: 'Abyssal ocean depths, 1000m+',
        communication: 'Deep infrasonic pulses that travel vast distances through the water. Bioluminescent displays.',
      },
    },
    {
      id: 'sky_whale',
      name: 'Sky Whale',
      description: 'A colossal lighter-than-air creature that filter-feeds on atmospheric plankton, drifting between continents.',
      element_type: 'mythical_beast',
      summary: 'A gentle giant that swims through the sky, its shadow darkening entire towns',
      fields: {
        body_type: 'Cetacean-like with gas bladders and membranous fins for steering',
        diet: 'filter_feeder',
        max_size: '80-200 meters in length',
        lifespan: 'Unknown — oldest tracked individual exceeds 500 years',
        intelligence_level: 'near_sentient',
        social_structure: 'Small pods of 3-7 that sing to each other across hundreds of kilometers',
        rarity: 'rare',
        domesticable: false,
        habitat_niche: 'Upper atmosphere, 2000-8000m altitude',
        communication: 'Infrasonic songs that resonate through the atmosphere for hundreds of kilometers. The songs shift seasonally and may encode navigational information. Scholars debate whether the songs constitute language.',
        migration_pattern: 'Annual circumnavigation following atmospheric plankton blooms. Calving grounds are above remote mountain ranges where updrafts support newborns learning to stay aloft.',
      },
    },
    {
      id: 'mimic_predator',
      name: 'Terrain Mimic',
      description: 'A creature that perfectly disguises itself as a patch of terrain — a boulder, a fallen log, even a stretch of path.',
      element_type: 'invertebrate',
      summary: 'A patient ambush predator indistinguishable from its surroundings',
      fields: {
        body_type: 'Amorphous, flattened — reshapes its outer tissue to match local terrain',
        diet: 'carnivore',
        max_size: '2-8 meters across when flattened',
        lifespan: '30-60 years',
        intelligence_level: 'clever',
        social_structure: 'Solitary and fiercely territorial — two mimics near each other results in a slow, silent war of camouflage and ambush',
        rarity: 'uncommon',
        domesticable: false,
        habitat_niche: 'Anywhere with foot traffic — forest paths, river crossings, cave entrances',
        communication: 'Chemical signals left in mucus trails. Other mimics can read these to determine territory boundaries, mating readiness, and prey density.',
      },
    },
    {
      id: 'symbiotic_pair',
      name: 'Symbiotic Pair',
      description: 'Two species so interdependent they function as one organism — one provides mobility, the other provides senses or defense.',
      element_type: 'invertebrate',
      summary: 'A dual-species organism where neither half can survive without the other',
      detailed_notes: 'The Symbiotic Pair is not one creature but two — so deeply co-evolved that they are never found apart. The Carrier is a large, muscular invertebrate with powerful limbs but vestigial sensory organs. The Rider is a smaller, sessile organism with extraordinary sensory and defensive capabilities but no means of locomotion. The Rider fuses to the Carrier\'s dorsal surface early in life, their nervous systems intertwining until they share a unified perception of the world. The Carrier moves; the Rider sees, hears, and fights. Naturalists debate whether to classify them as one species or two — and the question has philosophical implications for how we define individuality.',
      fields: {
        body_type: 'Composite — a large muscular base creature (the Carrier) with a sensory/defensive organism (the Rider) fused to its back',
        diet: 'omnivore',
        max_size: 'Combined: 1-2 meters. Carrier: 0.8-1.5m. Rider: 0.3-0.5m',
        lifespan: '40-70 years (both components age and die together)',
        intelligence_level: 'clever',
        social_structure: 'Mated pairs of Pairs — four organisms functioning as two, who cooperate in hunting and nesting',
        rarity: 'rare',
        domesticable: false,
        habitat_niche: 'Dense undergrowth and forest floors where the Rider\'s sensory advantage compensates for poor visibility',
        communication: 'The Rider produces ultrasonic clicks for echolocation and communication with other Pairs. The Carrier communicates through ground vibrations.',
      },
    },
    {
      id: 'domesticated_predator',
      name: 'Domesticated Predator',
      description: 'A dangerous carnivore bred over generations into a loyal but volatile companion. Still deadly, but bonded.',
      element_type: 'mammal',
      summary: 'A tamed apex carnivore that serves as a fearsome but unpredictable companion',
      detailed_notes: 'Domesticated Predators are the result of centuries of selective breeding from a wild apex carnivore. They retain their lethal natural weapons — fangs, claws, speed, and predatory instinct — but have been bred for a capacity to bond with a single handler. The bond is genuine but not absolute; these creatures are not pets. They require constant reinforcement, expert handling, and sufficient hunting to satisfy their predatory drive. Handlers bear scars as a matter of course. Cultures that breed Domesticated Predators view the handler-beast relationship as a sacred compact: the handler provides purpose and companionship, the beast provides protection and status. A handler whose predator turns on them is considered to have broken the compact through negligence or cruelty.',
      fields: {
        body_type: 'Large quadruped, lean and muscular with retractable claws and powerful jaws',
        diet: 'carnivore',
        max_size: '1.5-2.5 meters at the shoulder, 150-300 kg',
        lifespan: '15-25 years',
        intelligence_level: 'clever',
        social_structure: 'Bonds with a single handler; tolerates the handler\'s family. Aggressive toward strangers.',
        rarity: 'rare',
        domesticable: true,
        habitat_niche: 'Kept in handler compounds, kennels, or military camps. Wild ancestors inhabited dense forests and rocky highlands.',
        communication: 'Low rumbling purrs when content, snarling and hissing in warning. Handlers learn to read ear position, tail carriage, and muscle tension for mood.',
      },
    },
    {
      id: 'living_fossil',
      name: 'Living Fossil',
      description: 'A creature unchanged for millions of years — a relic of a prior geological age, now rare and revered.',
      element_type: 'reptile',
      summary: 'An ancient species that has survived unchanged since a forgotten age of the world',
      detailed_notes: 'The Living Fossil is a survivor — a species so perfectly adapted to a stable niche that evolution found no reason to change it. Its body plan, behavior, and physiology are identical to fossils dating back millions of years, predating the rise of every current sentient species. Encountering one is like looking through a window into deep time. They are slow, patient, and profoundly resilient, having survived every extinction event that reshaped the world around them. Many cultures revere them as sacred, believing they carry ancestral memory or that harming one invites geological-scale misfortune. Naturalists prize them as living laboratories for understanding ancient ecosystems.',
      fields: {
        body_type: 'Heavily armored quadruped with a thick carapace, short limbs, and a beaked jaw',
        diet: 'herbivore',
        max_size: '1-3 meters in length, 50-200 kg',
        lifespan: '200-500 years',
        intelligence_level: 'animal',
        social_structure: 'Solitary except during brief annual mating gatherings at ancestral sites',
        rarity: 'very_rare',
        domesticable: false,
        habitat_niche: 'Isolated valleys, deep caves, and remote islands — refugia that have remained ecologically stable for geological ages',
        communication: 'Deep, resonant bellowing during mating season that can carry for kilometers. Otherwise silent and cryptic.',
        migration_pattern: 'No migration — extreme site fidelity. Individuals may occupy the same territory for their entire centuries-long lives.',
      },
    },
    {
      id: 'echo_bat',
      name: 'Echo Bat',
      description: 'Navigates by psychic echolocation, sensing minds instead of surfaces.',
      element_type: 'mammal',
      summary: 'A bat that navigates by sensing conscious minds rather than physical surfaces — a living thought-detector',
      detailed_notes: 'The Echo Bat has abandoned conventional echolocation entirely. Instead of emitting sound and listening for reflections, it emits a low-frequency psychic pulse and detects the "echo" from conscious minds in its vicinity. The bat perceives the world as a map of thoughts: bright, active minds appear as vivid landmarks, sleeping minds as dim waypoints, and the mindless — rocks, trees, empty air — as void. This adaptation makes the Echo Bat a superlative predator of intelligent or semi-intelligent prey, as it can locate hiding creatures by their thoughts alone. It also makes them deeply unsettling to sentient beings: the sensation of being "pinged" by an Echo Bat is described as a brief, invasive tickle at the edge of awareness, like someone glancing at your thoughts. In dense populations of sentient creatures, Echo Bats become disoriented by the cacophony of minds and avoid cities. They are prized by intelligence services, as a trained Echo Bat can detect hidden persons through walls, underground, or in magical concealment that blocks conventional senses.',
      fields: {
        body_type: 'Small winged mammal with oversized cranium and vestigial ears',
        diet: 'carnivore',
        max_size: '15-25 cm wingspan, 20-40 grams',
        intelligence_level: 'clever',
        social_structure: 'Small colonies of 10-30 roosting together, hunting individually',
        rarity: 'uncommon',
      },
    },
    {
      id: 'glass_snake',
      name: 'Glass Snake',
      description: 'A transparent reptile, beautiful and venomous, nearly invisible.',
      element_type: 'reptile',
      summary: 'A completely transparent serpent — lethally venomous and nearly impossible to see',
      detailed_notes: 'The Glass Snake is a marvel of evolutionary camouflage. Its body is almost entirely transparent: skin, muscle, and bone are composed of proteins with a refractive index matching the surrounding air, rendering the creature effectively invisible to the naked eye. Only its eyes — tiny, dark pinpoints — and the faint shadow it casts in direct sunlight betray its presence. The transparency serves both defensive and offensive purposes: predators cannot see it, and prey does not flee until the strike has already landed. The Glass Snake\'s venom is a potent neurotoxin that causes progressive paralysis within minutes. Treatment exists but requires knowing you\'ve been bitten, which is problematic when the snake is invisible. Collectors prize Glass Snakes for their beauty — when placed against a dark background, their crystalline bodies refract light into prismatic patterns. This demand, combined with habitat loss, has made them increasingly rare. Handling them is extraordinarily dangerous, as keepers frequently lose track of their specimens.',
      fields: {
        body_type: 'Serpentine, slender, with fully transparent tissues',
        diet: 'carnivore',
        max_size: '0.5-1.5 meters in length',
        lifespan: '15-30 years',
        intelligence_level: 'animal',
        social_structure: 'Solitary and territorial — encounters between Glass Snakes are violent',
        rarity: 'rare',
        domesticable: false,
        habitat_niche: 'Forest floors, rocky outcrops, and tall grass where transparency provides maximum concealment',
        communication: 'Vibrations transmitted through the ground. Mating pairs locate each other by rhythmic tail-tapping on stone surfaces.',
      },
    },
    {
      id: 'grief_moth',
      name: 'Grief Moth',
      description: 'An insect attracted to emotional pain. Swarms appear at funerals and battlefields.',
      element_type: 'insect',
      summary: 'A dark-winged moth drawn to sorrow and suffering, swarming wherever grief concentrates',
      detailed_notes: 'The Grief Moth is a large, dark-winged insect that is attracted not to light, as most moths are, but to emotional suffering. The mechanism is poorly understood — the leading theory proposes that grief, stress, and trauma cause sentient beings to emit specific pheromones or bio-electric signatures that the moth\'s antennae are exquisitely tuned to detect. Whatever the mechanism, the correlation is undeniable: Grief Moths appear in swarms at funerals, battlefields, hospitals, sites of disaster, and anywhere that sapient beings gather in pain. The moths are not harmful — they do not bite, sting, or carry disease. They simply gather, settling on surfaces near the grieving and slowly opening and closing their dark wings. Many cultures interpret their presence as spiritual: the moths are said to carry sorrow away, or to be the souls of the dead visiting their mourners, or to feed on sadness itself. Others find their presence deeply unsettling — a visible, fluttering manifestation of collective pain. A swarm of Grief Moths at an unexpected location is considered a dire omen, suggesting hidden suffering or impending tragedy.',
      fields: {
        body_type: 'Winged insect with broad, dark velvet wings and feathered antennae',
        diet: 'herbivore',
        max_size: '8-15 cm wingspan',
        lifespan: '2-4 weeks as adults; larvae feed on decaying plant matter for months',
        intelligence_level: 'instinctive',
        social_structure: 'Swarm behavior triggered by grief-pheromone detection. No permanent social structure — swarms form and dissolve with the emotional state of nearby sapient beings.',
        rarity: 'common',
        domesticable: false,
        habitat_niche: 'Ubiquitous near sapient settlements. Larvae develop in damp soil and leaf litter. Adults are nomadic, drawn wherever sorrow concentrates.',
        communication: 'Wing-beat frequency patterns within swarms. Pheromone trails to direct other moths toward grief sources.',
      },
    },
  ],
  defaultSortField: 'diet',
};
