import type { DomainConfig } from '../types/domains.js';

export const floraConfig: DomainConfig = {
  id: 'flora',
  name: 'Flora',
  namePlural: 'Flora',
  icon: 'leaf',
  color: '#27ae60',
  description: 'Catalog the plants, fungi, algae, and other sessile organisms of your world. From towering world-trees to bioluminescent mushrooms, flora forms the foundation of every food chain and many economies.',
  tableName: 'flora',
  category: 'natural',
  fields: [
    {
      name: 'kingdom',
      label: 'Kingdom',
      type: 'select',
      required: true,
      options: ['plant', 'fungus', 'algae', 'custom'],
      helpText: 'The biological kingdom this organism belongs to.',
    },
    {
      name: 'growth_form',
      label: 'Growth Form',
      type: 'select',
      required: true,
      options: ['tree', 'shrub', 'grass', 'vine', 'moss', 'aquatic', 'fungal'],
      helpText: 'The physical growth habit of this organism.',
    },
    {
      name: 'max_height',
      label: 'Maximum Height',
      type: 'text',
      placeholder: 'e.g. 30m, 2cm, towering',
      helpText: 'The tallest this species typically grows.',
    },
    {
      name: 'lifespan',
      label: 'Lifespan',
      type: 'text',
      placeholder: 'e.g. 500 years, annual, immortal',
      helpText: 'Typical lifespan of an individual organism.',
    },
    {
      name: 'reproduction_method',
      label: 'Reproduction Method',
      type: 'text',
      placeholder: 'e.g. spores, seeds, rhizome, budding',
      helpText: 'How this species reproduces and spreads.',
    },
    {
      name: 'uses',
      label: 'Uses',
      type: 'json',
      placeholder: '["food", "medicine", "timber", "dye", "poison"]',
      helpText: 'Practical uses for this organism—food, medicine, materials, etc.',
    },
    {
      name: 'rarity',
      label: 'Rarity',
      type: 'select',
      options: ['common', 'uncommon', 'rare', 'very_rare', 'unique'],
      helpText: 'How commonly this species is found in the wild.',
    },
    {
      name: 'sentient',
      label: 'Sentient',
      type: 'boolean',
      helpText: 'Whether this species possesses any form of awareness or intelligence.',
    },
    {
      name: 'seasonal_behavior',
      label: 'Seasonal Behavior',
      type: 'textarea',
      placeholder: 'Describe deciduous/evergreen cycles, dormancy, bloom timing...',
      helpText: 'How this species changes through the seasons — leaf drop, dormancy, flowering, fruiting cycles.',
    },
    {
      name: 'cultivation_difficulty',
      label: 'Cultivation Difficulty',
      type: 'select',
      options: ['wild_only', 'difficult', 'moderate', 'easy', 'domesticated'],
      helpText: 'How difficult it is to cultivate or farm this species.',
    },
    {
      name: 'endangered_status',
      label: 'Endangered Status',
      type: 'select',
      options: ['thriving', 'stable', 'declining', 'endangered', 'critical', 'extinct_in_wild'],
      helpText: 'The current population health and conservation status of this species.',
    },
    {
      name: 'habitat_description',
      label: 'Habitat Description',
      type: 'textarea',
      placeholder: 'Describe preferred growing conditions, soil, light, moisture...',
      helpText: 'Prose description of habitat preferences — where and how this species grows.',
    },
    {
      name: 'biome_ids',
      label: 'Native Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "wetland_biome_3"]',
      helpText: 'Biomes where this species naturally occurs.',
    },
  ],
  elementTypes: ['tree', 'shrub', 'grass', 'vine', 'moss', 'aquatic_plant', 'fungus', 'algae', 'custom'],
  prompts: [
    'What staple crops feed your world\'s civilizations? Were they domesticated, magically bred, or gifted by gods?',
    'Are there plants with unusual properties—carnivorous trees, luminous flowers, or fungi that form vast underground networks?',
    'How do seasons affect plant life? Are there species that bloom only during eclipses, mana surges, or once per century?',
    'What role do forests play in your world\'s mythology, politics, and warfare?',
    'Are there plants that have gone extinct, and what consequences has their loss had on ecosystems?',
  ],
  magicPermeation: {
    companionTable: 'flora_magic_aspects',
    fields: [
      {
        name: 'magical_properties',
        label: 'Magical Properties',
        type: 'textarea',
        helpText: 'Inherent magical properties of this species—glowing, warding, healing aura, etc.',
      },
      {
        name: 'mana_interaction',
        label: 'Mana Interaction',
        type: 'select',
        options: ['none', 'absorber', 'producer', 'conductor', 'storage', 'converter', 'dampener'],
        helpText: 'How this species interacts with ambient mana.',
      },
      {
        name: 'mana_production_rate',
        label: 'Mana Production Rate',
        type: 'text',
        placeholder: 'e.g. low, moderate, high',
        helpText: 'If a producer, how much mana this species generates.',
      },
      {
        name: 'use_in_potions',
        label: 'Use in Potions',
        type: 'textarea',
        helpText: 'How parts of this organism are used in potion-making and alchemy.',
      },
      {
        name: 'use_as_reagent',
        label: 'Use as Reagent',
        type: 'textarea',
        helpText: 'How this species serves as a spell component or magical reagent.',
      },
      {
        name: 'sentience_level',
        label: 'Magical Sentience Level',
        type: 'select',
        options: ['none', 'reactive', 'semi_sentient', 'sentient', 'sapient'],
        helpText: 'The degree of magical awareness or consciousness.',
      },
      {
        name: 'communication_method',
        label: 'Communication Method',
        type: 'textarea',
        helpText: 'How sentient or semi-sentient flora communicates—pheromones, telepathy, root networks, etc.',
      },
      {
        name: 'magical_symbiosis',
        label: 'Magical Symbiosis',
        type: 'textarea',
        helpText: 'Magical symbiotic relationships with other organisms or magical fields.',
      },
      {
        name: 'cultivation_requirements_magical',
        label: 'Magical Cultivation Requirements',
        type: 'textarea',
        helpText: 'Special magical conditions needed to grow or cultivate this species.',
      },
      {
        name: 'magical_life_cycle',
        label: 'Magical Life Cycle',
        type: 'textarea',
        helpText: 'Stages of the life cycle that are magical in nature—mana-bloom, arcane fruiting, etc.',
      },
      {
        name: 'toxicity_magical',
        label: 'Magical Toxicity',
        type: 'textarea',
        helpText: 'Magical poisons, curses, or harmful effects produced by this species.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' biology and role.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: false,
    prompts: [
      'Do certain plants absorb, store, or produce mana? Has this made them targets for harvesting or cultivation by mages?',
      'Are there sentient or semi-sentient plant species that communicate through magical root networks or telepathy?',
      'What alchemical or potion ingredients come from your world\'s flora? Are any dangerously addictive, forbidden, or extinct?',
    ],
  },
  archetypes: [
    {
      id: 'ancient_hardwood',
      name: 'Ancient Hardwood',
      description: 'A massive, slow-growing tree that can live for millennia and forms the backbone of old-growth forests.',
      element_type: 'tree',
      summary: 'A towering ancient tree prized for its wood and ecological importance',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '40-60 meters',
        lifespan: '1000-5000 years',
        rarity: 'uncommon',
        cultivation_difficulty: 'difficult',
        endangered_status: 'declining',
        seasonal_behavior: 'Deciduous in temperate climates, shedding leaves in autumn. Spring growth is slow but produces extremely dense, valuable wood.',
      },
    },
    {
      id: 'staple_grain',
      name: 'Staple Grain',
      description: 'A cultivated grass that feeds nations — the foundation of agriculture and civilization.',
      element_type: 'grass',
      summary: 'A domesticated cereal crop central to agriculture',
      fields: {
        kingdom: 'plant',
        growth_form: 'grass',
        max_height: '1-2 meters',
        lifespan: 'Annual (one growing season)',
        rarity: 'common',
        cultivation_difficulty: 'domesticated',
        endangered_status: 'thriving',
        seasonal_behavior: 'Planted in spring, harvested in late summer or autumn. Requires fertile soil and adequate rainfall or irrigation.',
      },
    },
    {
      id: 'medicinal_herb',
      name: 'Medicinal Herb',
      description: 'A small plant with potent curative properties, gathered by healers and herbalists.',
      element_type: 'shrub',
      summary: 'A valued healing plant sought by herbalists and apothecaries',
      fields: {
        kingdom: 'plant',
        growth_form: 'shrub',
        max_height: '0.3-1 meter',
        lifespan: 'Perennial (5-20 years)',
        rarity: 'uncommon',
        cultivation_difficulty: 'moderate',
        endangered_status: 'stable',
        seasonal_behavior: 'Flowers in midsummer when medicinal compounds are at peak concentration. Must be harvested at the right lunar phase for full potency (according to folk tradition).',
      },
    },
    {
      id: 'carnivorous_plant',
      name: 'Carnivorous Plant',
      description: 'A predatory plant that supplements poor soil nutrition by trapping and digesting small creatures.',
      element_type: 'shrub',
      summary: 'A predatory plant that lures and digests prey',
      fields: {
        kingdom: 'plant',
        growth_form: 'shrub',
        max_height: '0.5-3 meters',
        lifespan: '20-100 years',
        rarity: 'rare',
        cultivation_difficulty: 'difficult',
        endangered_status: 'stable',
        seasonal_behavior: 'Most active during warm, humid months when insect prey is abundant. Traps may close or go dormant in cold seasons.',
      },
    },
    {
      id: 'cave_fungus',
      name: 'Cave Fungus',
      description: 'A bioluminescent fungus that carpets underground surfaces, providing faint light in the deep dark.',
      element_type: 'fungus',
      summary: 'A glowing underground fungus illuminating the deep places of the world',
      fields: {
        kingdom: 'fungus',
        growth_form: 'fungal',
        max_height: '0.01-0.3 meters',
        lifespan: 'Colony can persist indefinitely',
        rarity: 'uncommon',
        cultivation_difficulty: 'difficult',
        endangered_status: 'stable',
        habitat_description: 'Found on damp cave walls and rotting wood in underground environments. Requires complete darkness and high humidity.',
      },
    },
    {
      id: 'wandering_grove',
      name: 'Wandering Grove',
      description: 'A tree that migrates — its root system slowly pulls it across the landscape over decades, following water or ley lines.',
      element_type: 'tree',
      summary: 'A slow-walking tree that migrates across the landscape over centuries',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '15-25 meters',
        lifespan: 'Thousands of years — individual trees have been tracked across continents',
        rarity: 'rare',
        cultivation_difficulty: 'wild_only',
        endangered_status: 'declining',
        seasonal_behavior: 'Movement accelerates in spring when groundwater is abundant. The tree "walks" by extending roots forward and retracting them behind, moving 2-5 meters per year. Groves migrate together in loose formations.',
        habitat_description: 'Found in open grasslands and sparse woodlands where root-travel is unobstructed. Ancient paths of compacted soil mark routes used for millennia. Some civilizations track grove movements to predict water table shifts.',
      },
    },
    {
      id: 'dreaming_lotus',
      name: 'Dreaming Lotus',
      description: 'An aquatic flower whose pollen induces shared visions in nearby sleepers — a natural psychic network.',
      element_type: 'aquatic_plant',
      summary: 'A psychoactive water lily that links the dreams of those who sleep near it',
      fields: {
        kingdom: 'plant',
        growth_form: 'aquatic',
        max_height: '0.1 meters above waterline, root systems extend 3m down',
        lifespan: 'Individual flowers: one lunar cycle. Root colony: centuries',
        rarity: 'very_rare',
        cultivation_difficulty: 'difficult',
        endangered_status: 'endangered',
        seasonal_behavior: 'Blooms only during full moons. Pollen release peaks at midnight. Those sleeping within 100 meters of a blooming colony share a vivid dreamscape shaped by the lotus. Cultures that understand this use it for councils, therapy, or espionage.',
      },
    },
  ],
  defaultSortField: 'kingdom',
};
