import type { DomainConfig } from '../types/domains.js';

export const floraConfig: DomainConfig = {
  id: 'flora',
  name: 'Flora',
  namePlural: 'Flora',
  icon: 'leaf',
  color: '#27ae60',
  description: 'Catalog the plants, fungi, algae, and other sessile organisms of your world. From towering world-trees to bioluminescent mushrooms, flora forms the foundation of every food chain and many economies.',
  tableName: 'flora',
  category: 'natural',
  fields: [
    {
      name: 'kingdom',
      label: 'Kingdom',
      type: 'select',
      required: true,
      options: ['plant', 'fungus', 'algae', 'custom'],
      helpText: 'The biological kingdom this organism belongs to.',
    },
    {
      name: 'growth_form',
      label: 'Growth Form',
      type: 'select',
      required: true,
      options: ['tree', 'shrub', 'grass', 'vine', 'moss', 'aquatic', 'fungal'],
      helpText: 'The physical growth habit of this organism.',
    },
    {
      name: 'max_height',
      label: 'Maximum Height',
      type: 'text',
      placeholder: 'e.g. 30m, 2cm, towering',
      helpText: 'The tallest this species typically grows.',
    },
    {
      name: 'lifespan',
      label: 'Lifespan',
      type: 'text',
      placeholder: 'e.g. 500 years, annual, immortal',
      helpText: 'Typical lifespan of an individual organism.',
    },
    {
      name: 'reproduction_method',
      label: 'Reproduction Method',
      type: 'text',
      placeholder: 'e.g. spores, seeds, rhizome, budding',
      helpText: 'How this species reproduces and spreads.',
    },
    {
      name: 'uses',
      label: 'Uses',
      type: 'json',
      placeholder: '["food", "medicine", "timber", "dye", "poison"]',
      helpText: 'Practical uses for this organism—food, medicine, materials, etc.',
    },
    {
      name: 'rarity',
      label: 'Rarity',
      type: 'select',
      options: ['common', 'uncommon', 'rare', 'very_rare', 'unique'],
      helpText: 'How commonly this species is found in the wild.',
    },
    {
      name: 'sentient',
      label: 'Sentient',
      type: 'boolean',
      helpText: 'Whether this species possesses any form of awareness or intelligence.',
    },
    {
      name: 'seasonal_behavior',
      label: 'Seasonal Behavior',
      type: 'textarea',
      placeholder: 'Describe deciduous/evergreen cycles, dormancy, bloom timing...',
      helpText: 'How this species changes through the seasons — leaf drop, dormancy, flowering, fruiting cycles.',
    },
    {
      name: 'cultivation_difficulty',
      label: 'Cultivation Difficulty',
      type: 'select',
      options: ['wild_only', 'difficult', 'moderate', 'easy', 'domesticated'],
      helpText: 'How difficult it is to cultivate or farm this species.',
    },
    {
      name: 'endangered_status',
      label: 'Endangered Status',
      type: 'select',
      options: ['thriving', 'stable', 'declining', 'endangered', 'critical', 'extinct_in_wild'],
      helpText: 'The current population health and conservation status of this species.',
    },
    {
      name: 'habitat_description',
      label: 'Habitat Description',
      type: 'textarea',
      placeholder: 'Describe preferred growing conditions, soil, light, moisture...',
      helpText: 'Prose description of habitat preferences — where and how this species grows.',
    },
    {
      name: 'biome_ids',
      label: 'Native Biomes',
      type: 'json',
      placeholder: '["forest_biome_1", "wetland_biome_3"]',
      helpText: 'Biomes where this species naturally occurs.',
    },
  ],
  elementTypes: ['tree', 'shrub', 'grass', 'vine', 'moss', 'aquatic_plant', 'fungus', 'algae', 'custom'],
  elementTypeDescriptions: {
    tree: 'A tall, woody perennial plant with a central trunk and branching canopy. Foundation of forests and source of timber, fruit, and shelter.',
    shrub: 'A woody plant smaller than a tree, often multi-stemmed. Forms undergrowth, hedgerows, and scrublands.',
    grass: 'A low-growing plant with narrow leaves, forming meadows, prairies, and lawns. Includes cereal crops that feed civilizations.',
    vine: 'A climbing or trailing plant that uses other structures for support. Can blanket forests, walls, or ruins.',
    moss: 'A small, non-vascular plant that grows in dense green mats on moist surfaces. Among the oldest land plants.',
    aquatic_plant: 'A plant adapted to life in or on water — rooted in riverbeds, floating on lakes, or drifting in open ocean.',
    fungus: 'A spore-producing organism that feeds on organic matter. Includes mushrooms, molds, and vast underground mycelial networks.',
    algae: 'A simple photosynthetic organism found in water or damp environments. Ranges from single-celled to massive kelp forests.',
    custom: 'A plant or plant-like organism that doesn\'t fit standard categories — something unique to your world.',
  },
  prompts: [
    'What staple crops feed your world\'s civilizations? Were they domesticated, magically bred, or gifted by gods?',
    'Are there plants with unusual properties—carnivorous trees, luminous flowers, or fungi that form vast underground networks?',
    'How do seasons affect plant life? Are there species that bloom only during eclipses, mana surges, or once per century?',
    'What role do forests play in your world\'s mythology, politics, and warfare?',
    'Are there plants that have gone extinct, and what consequences has their loss had on ecosystems?',
  ],
  magicPermeation: {
    companionTable: 'flora_magic_aspects',
    fields: [
      {
        name: 'magical_properties',
        label: 'Magical Properties',
        type: 'textarea',
        helpText: 'Inherent magical properties of this species—glowing, warding, healing aura, etc.',
      },
      {
        name: 'mana_interaction',
        label: 'Mana Interaction',
        type: 'select',
        options: ['none', 'absorber', 'producer', 'conductor', 'storage', 'converter', 'dampener'],
        helpText: 'How this species interacts with ambient mana.',
      },
      {
        name: 'mana_production_rate',
        label: 'Mana Production Rate',
        type: 'text',
        placeholder: 'e.g. low, moderate, high',
        helpText: 'If a producer, how much mana this species generates.',
      },
      {
        name: 'use_in_potions',
        label: 'Use in Potions',
        type: 'textarea',
        helpText: 'How parts of this organism are used in potion-making and alchemy.',
      },
      {
        name: 'use_as_reagent',
        label: 'Use as Reagent',
        type: 'textarea',
        helpText: 'How this species serves as a spell component or magical reagent.',
      },
      {
        name: 'sentience_level',
        label: 'Magical Sentience Level',
        type: 'select',
        options: ['none', 'reactive', 'semi_sentient', 'sentient', 'sapient'],
        helpText: 'The degree of magical awareness or consciousness.',
      },
      {
        name: 'communication_method',
        label: 'Communication Method',
        type: 'textarea',
        helpText: 'How sentient or semi-sentient flora communicates—pheromones, telepathy, root networks, etc.',
      },
      {
        name: 'magical_symbiosis',
        label: 'Magical Symbiosis',
        type: 'textarea',
        helpText: 'Magical symbiotic relationships with other organisms or magical fields.',
      },
      {
        name: 'cultivation_requirements_magical',
        label: 'Magical Cultivation Requirements',
        type: 'textarea',
        helpText: 'Special magical conditions needed to grow or cultivate this species.',
      },
      {
        name: 'magical_life_cycle',
        label: 'Magical Life Cycle',
        type: 'textarea',
        helpText: 'Stages of the life cycle that are magical in nature—mana-bloom, arcane fruiting, etc.',
      },
      {
        name: 'toxicity_magical',
        label: 'Magical Toxicity',
        type: 'textarea',
        helpText: 'Magical poisons, curses, or harmful effects produced by this species.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' biology and role.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: false,
    prompts: [
      'Do certain plants absorb, store, or produce mana? Has this made them targets for harvesting or cultivation by mages?',
      'Are there sentient or semi-sentient plant species that communicate through magical root networks or telepathy?',
      'What alchemical or potion ingredients come from your world\'s flora? Are any dangerously addictive, forbidden, or extinct?',
    ],
  },
  archetypes: [
    {
      id: 'ancient_hardwood',
      name: 'Ancient Hardwood',
      description: 'A massive, slow-growing tree that can live for millennia and forms the backbone of old-growth forests.',
      element_type: 'tree',
      summary: 'A towering ancient tree prized for its wood and ecological importance',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '40-60 meters',
        lifespan: '1000-5000 years',
        rarity: 'uncommon',
        cultivation_difficulty: 'difficult',
        endangered_status: 'declining',
        seasonal_behavior: 'Deciduous in temperate climates, shedding leaves in autumn. Spring growth is slow but produces extremely dense, valuable wood.',
      },
    },
    {
      id: 'staple_grain',
      name: 'Staple Grain',
      description: 'A cultivated grass that feeds nations — the foundation of agriculture and civilization.',
      element_type: 'grass',
      summary: 'A domesticated cereal crop central to agriculture',
      fields: {
        kingdom: 'plant',
        growth_form: 'grass',
        max_height: '1-2 meters',
        lifespan: 'Annual (one growing season)',
        rarity: 'common',
        cultivation_difficulty: 'domesticated',
        endangered_status: 'thriving',
        seasonal_behavior: 'Planted in spring, harvested in late summer or autumn. Requires fertile soil and adequate rainfall or irrigation.',
      },
    },
    {
      id: 'medicinal_herb',
      name: 'Medicinal Herb',
      description: 'A small plant with potent curative properties, gathered by healers and herbalists.',
      element_type: 'shrub',
      summary: 'A valued healing plant sought by herbalists and apothecaries',
      fields: {
        kingdom: 'plant',
        growth_form: 'shrub',
        max_height: '0.3-1 meter',
        lifespan: 'Perennial (5-20 years)',
        rarity: 'uncommon',
        cultivation_difficulty: 'moderate',
        endangered_status: 'stable',
        seasonal_behavior: 'Flowers in midsummer when medicinal compounds are at peak concentration. Must be harvested at the right lunar phase for full potency (according to folk tradition).',
      },
    },
    {
      id: 'carnivorous_plant',
      name: 'Carnivorous Plant',
      description: 'A predatory plant that supplements poor soil nutrition by trapping and digesting small creatures.',
      element_type: 'shrub',
      summary: 'A predatory plant that lures and digests prey',
      fields: {
        kingdom: 'plant',
        growth_form: 'shrub',
        max_height: '0.5-3 meters',
        lifespan: '20-100 years',
        rarity: 'rare',
        cultivation_difficulty: 'difficult',
        endangered_status: 'stable',
        seasonal_behavior: 'Most active during warm, humid months when insect prey is abundant. Traps may close or go dormant in cold seasons.',
      },
    },
    {
      id: 'cave_fungus',
      name: 'Cave Fungus',
      description: 'A bioluminescent fungus that carpets underground surfaces, providing faint light in the deep dark.',
      element_type: 'fungus',
      summary: 'A glowing underground fungus illuminating the deep places of the world',
      fields: {
        kingdom: 'fungus',
        growth_form: 'fungal',
        max_height: '0.01-0.3 meters',
        lifespan: 'Colony can persist indefinitely',
        rarity: 'uncommon',
        cultivation_difficulty: 'difficult',
        endangered_status: 'stable',
        habitat_description: 'Found on damp cave walls and rotting wood in underground environments. Requires complete darkness and high humidity.',
      },
    },
    {
      id: 'wandering_grove',
      name: 'Wandering Grove',
      description: 'A tree that migrates — its root system slowly pulls it across the landscape over decades, following water or ley lines.',
      element_type: 'tree',
      summary: 'A slow-walking tree that migrates across the landscape over centuries',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '15-25 meters',
        lifespan: 'Thousands of years — individual trees have been tracked across continents',
        rarity: 'rare',
        cultivation_difficulty: 'wild_only',
        endangered_status: 'declining',
        seasonal_behavior: 'Movement accelerates in spring when groundwater is abundant. The tree "walks" by extending roots forward and retracting them behind, moving 2-5 meters per year. Groves migrate together in loose formations.',
        habitat_description: 'Found in open grasslands and sparse woodlands where root-travel is unobstructed. Ancient paths of compacted soil mark routes used for millennia. Some civilizations track grove movements to predict water table shifts.',
      },
    },
    {
      id: 'dreaming_lotus',
      name: 'Dreaming Lotus',
      description: 'An aquatic flower whose pollen induces shared visions in nearby sleepers — a natural psychic network.',
      element_type: 'aquatic_plant',
      summary: 'A psychoactive water lily that links the dreams of those who sleep near it',
      fields: {
        kingdom: 'plant',
        growth_form: 'aquatic',
        max_height: '0.1 meters above waterline, root systems extend 3m down',
        lifespan: 'Individual flowers: one lunar cycle. Root colony: centuries',
        rarity: 'very_rare',
        cultivation_difficulty: 'difficult',
        endangered_status: 'endangered',
        seasonal_behavior: 'Blooms only during full moons. Pollen release peaks at midnight. Those sleeping within 100 meters of a blooming colony share a vivid dreamscape shaped by the lotus. Cultures that understand this use it for councils, therapy, or espionage.',
      },
    },
    {
      id: 'singing_tree',
      name: 'Singing Tree',
      description: 'A tree whose hollow branches produce haunting music when wind passes through them. Culturally sacred, often found near temples.',
      element_type: 'tree',
      summary: 'A wind-instrument tree that produces eerie, beautiful melodies revered by many cultures',
      detailed_notes: 'The Singing Tree develops naturally hollow branches with precisely shaped apertures that act as flutes and resonating chambers. Different wind speeds and directions produce different harmonies, and no two trees sound alike. Many religions consider these trees to be the voices of gods or ancestors. Temple groves are carefully cultivated so that the combined sound of dozens of trees creates complex, ever-changing symphonies. The wood, if harvested, makes superlative musical instruments — but cutting a Singing Tree is taboo in most cultures.',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '20-35 meters',
        lifespan: '300-800 years',
        rarity: 'rare',
        uses: ['musical instruments', 'sacred groves', 'temple construction', 'meditation'],
        cultivation_difficulty: 'difficult',
        endangered_status: 'declining',
        seasonal_behavior: 'Branches hollow out gradually as the tree matures, with the first audible tones emerging around age 50. In autumn, falling leaves alter the acoustic profile, producing deeper, more mournful tones. Spring growth temporarily mutes some chambers until new wood hardens.',
        habitat_description: 'Prefers exposed ridgelines, hilltops, and open valleys where wind is reliable. Temple groundskeepers carefully manage surrounding vegetation to shape wind flow.',
      },
    },
    {
      id: 'corpse_bloom',
      name: 'Corpse Bloom',
      description: 'A massive flower that only grows from decomposing organic matter. Beautiful and unsettling, used in funerary rites.',
      element_type: 'shrub',
      summary: 'A gorgeous but macabre flower that blooms exclusively from death and decay',
      detailed_notes: 'The Corpse Bloom is both revered and feared. Its seeds remain dormant in soil for decades until they detect the chemical signature of significant decomposition — a large animal carcass or, notably, a humanoid burial. Within weeks, a spectacular flower emerges: deep crimson petals veined with iridescent gold, sometimes reaching a meter across. The bloom is intensely fragrant, smelling paradoxically of honey and rain rather than rot. Many cultures have adopted the Corpse Bloom into funerary traditions, planting seeds with the dead so that beauty literally rises from loss. Others consider it an ill omen, a sign that death has visited unseen.',
      fields: {
        kingdom: 'plant',
        growth_form: 'shrub',
        max_height: '0.5-1.5 meters',
        lifespan: 'Individual bloom: 2-4 weeks. Seeds viable for decades in dormancy.',
        rarity: 'uncommon',
        uses: ['funerary rites', 'perfume', 'dye', 'memorial gardens'],
        cultivation_difficulty: 'difficult',
        endangered_status: 'stable',
        seasonal_behavior: 'Not governed by seasons but by the availability of decomposing matter. Can bloom at any time of year. After flowering, produces dark seed pods that scatter in wind, lying dormant until triggered by decay chemistry.',
        habitat_description: 'Found in battlefields, ancient graveyards, forest floors where large animals have died, and compost-rich areas near settlements. Thrives in moist, nutrient-dense soil.',
      },
    },
    {
      id: 'iron_root',
      name: 'Iron Root',
      description: 'A plant whose roots extract and concentrate metal from soil, producing metallic nodules. Used in primitive smelting.',
      element_type: 'tree',
      summary: 'A metallophyte tree that mines ore from the earth through its root system',
      detailed_notes: 'The Iron Root is a hyperaccumulator — a tree that draws dissolved metals from groundwater and soil, concentrating them in dense nodules along its root system and at the base of its trunk. Over decades, a mature Iron Root can produce hundreds of kilograms of metal-rich nodules that are significantly easier to smelt than raw ore. Early civilizations discovered that harvesting these nodules was far simpler than mining, and some scholars argue that the Iron Root was the catalyst for the first metal-working cultures. The tree itself suffers no ill effects from the metal concentration; indeed, the metallic deposits in its bark make it highly resistant to pests, fire, and even axe blows.',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '10-20 meters',
        lifespan: '200-500 years',
        rarity: 'uncommon',
        uses: ['ore extraction', 'primitive smelting', 'soil remediation', 'armor-grade timber'],
        cultivation_difficulty: 'moderate',
        endangered_status: 'declining',
        seasonal_behavior: 'Metal accumulation is fastest during the wet season when dissolved minerals are most available in groundwater. In autumn, the tree sheds metallic-tinged leaves that glitter like coins — a reliable sign of mineral-rich soil beneath.',
        habitat_description: 'Found in regions with mineral-rich subsoil, particularly near ore deposits, volcanic terrain, and ancient riverbeds. The presence of Iron Roots is used by prospectors as a reliable indicator of underground mineral wealth.',
      },
    },
    {
      id: 'memory_moss',
      name: 'Memory Moss',
      description: 'A moss that records sounds and replays them when touched. Used for record-keeping.',
      element_type: 'moss',
      summary: 'A remarkable moss that absorbs and replays ambient sounds, serving as a living recording medium',
      detailed_notes: 'Memory Moss is a small, velvety organism that has evolved the extraordinary ability to encode sound vibrations into its cellular structure and replay them when physically stimulated. The moss grows in soft, dense mats on damp stone surfaces, and its cells contain a unique crystalline organelle that vibrates in response to sound waves, locking the vibration pattern into a semi-permanent molecular configuration. When the moss is touched — pressed, stroked, or squeezed — it releases the stored vibrations as audible sound, replaying whatever it last "heard" with remarkable fidelity. The recordings degrade over time, with older sounds becoming faint and distorted, but fresh recordings can persist for weeks or months. Cultures that have discovered this property use cultivated Memory Moss for record-keeping, message relay, and legal testimony. Moss-scribes carefully tend patches of Memory Moss, dictating records into them and storing the living mats in climate-controlled archives. Wild Memory Moss in old ruins can sometimes be coaxed into replaying the voices of people dead for centuries.',
      fields: {
        kingdom: 'plant',
        growth_form: 'moss',
        max_height: '0.5-3 cm',
        lifespan: 'Individual patches: 5-15 years. Colonies can persist indefinitely through vegetative growth.',
        rarity: 'rare',
        uses: ['record-keeping', 'message relay', 'legal testimony', 'archaeological research', 'musical composition'],
      },
    },
    {
      id: 'blood_oak',
      name: 'Blood Oak',
      description: 'A tree with red sap used medicinally. Over-harvesting threatens it.',
      element_type: 'tree',
      summary: 'A massive tree that bleeds crimson sap prized for its potent medicinal properties',
      detailed_notes: 'The Blood Oak is a towering hardwood distinguished by its deep red sap — a thick, viscous fluid that oozes from cuts in the bark like blood from a wound. The sap contains a complex cocktail of bioactive compounds with remarkable medicinal properties: it accelerates wound healing, reduces fever, fights infection, and — in concentrated doses — can even slow the progression of certain poisons and diseases. For these reasons, Blood Oak sap is one of the most valuable natural substances in the world, commanding prices that rival precious metals. This value has driven aggressive harvesting. Tappers score the bark deeply and repeatedly, weakening trees and leaving them vulnerable to disease and wind damage. Old-growth Blood Oaks that once dominated temperate forests are now rare, surviving mainly in protected groves maintained by healer guilds and religious orders. The tree grows slowly and takes decades to reach sap-producing maturity, making recovery from over-harvesting a generational project.',
      fields: {
        kingdom: 'plant',
        growth_form: 'tree',
        max_height: '25-40 meters',
        lifespan: '400-1200 years',
        rarity: 'rare',
        uses: ['medicine', 'wound treatment', 'fever reduction', 'antitoxin base', 'sacred rites'],
        cultivation_difficulty: 'difficult',
        endangered_status: 'endangered',
        seasonal_behavior: 'Sap flow peaks in early spring as the tree breaks dormancy, making this the primary harvesting season. Autumn brings deep red foliage that is visually indistinguishable from the sap-stained bark, camouflaging tap wounds.',
        habitat_description: 'Native to temperate old-growth forests with deep, moist soil. Requires decades of undisturbed growth to reach maturity. Surviving groves are fiercely protected by local communities and healer orders.',
      },
    },
    {
      id: 'spore_tower',
      name: 'Spore Tower',
      description: 'A massive fungal column releasing clouds of spores seasonally.',
      element_type: 'fungus',
      summary: 'A colossal fungal column that towers above the canopy, releasing vast clouds of spores that reshape the surrounding landscape',
      detailed_notes: 'The Spore Tower is among the largest single organisms in the world — a fungal fruiting body that can reach 40 meters in height and 8 meters in diameter at the base. It grows from a mycelial network that may extend for kilometers underground, and its sole purpose is the production and dispersal of spores. During the sporulation season, the Tower\'s upper chambers split open and release billowing clouds of spores so dense they blot out the sun and coat everything within miles in a fine, powdery layer. The spore clouds are visible from enormous distances as pillar-shaped plumes rising from the canopy. The ecological impact is immense: the spores serve as food for insects and filter-feeding organisms, as fertilizer when they decompose, and as the reproductive medium for new Spore Tower colonies. However, the spore clouds are a respiratory hazard for larger organisms, and settlements downwind of a Tower must seal their buildings during sporulation or face widespread "spore lung" infection.',
      fields: {
        kingdom: 'fungus',
        growth_form: 'fungal',
        max_height: '20-40 meters',
        lifespan: 'Individual fruiting body: 50-200 years. Underlying mycelial network: potentially thousands of years.',
        rarity: 'uncommon',
        uses: ['fertilizer', 'insect feed', 'alchemical reagent', 'building material (dried stalk)'],
        cultivation_difficulty: 'wild_only',
        endangered_status: 'stable',
        seasonal_behavior: 'Sporulation occurs once annually, typically triggered by the first heavy rains after a dry period. The event lasts 3-7 days and is preceded by visible swelling of the upper chambers. Post-sporulation, the Tower enters a dormant growth phase, slowly regenerating its spore reserves over the following year.',
        habitat_description: 'Found in humid forests and wetlands with deep organic soil layers. Requires extensive underground mycelial territory and abundant decaying matter. Often grows near water sources where moisture sustains the massive fruiting body.',
      },
    },
  ],
  defaultSortField: 'kingdom',
};
