import type { DomainConfig } from '../types/domains.js';

export const geographyConfig: DomainConfig = {
  id: 'geography',
  name: 'Geographic Place',
  namePlural: 'Geography',
  icon: 'map-pin',
  color: '#e67e22',
  description: 'Place the cities, fortresses, roads, temples, and landmarks of your world on the map. Geography ties together the natural landscape with the built environment, giving your civilizations concrete locations and your stories tangible settings.',
  tableName: 'geographical_places',
  category: 'meta',
  fields: [
    {
      name: 'place_type',
      label: 'Place Type',
      type: 'select',
      required: true,
      options: ['city', 'town', 'village', 'fortress', 'ruin', 'landmark', 'road', 'port', 'temple', 'academy'],
      helpText: 'The primary classification of this geographic location.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 50,000; abandoned; seasonal',
      helpText: 'Current population or occupancy of this location.',
    },
    {
      name: 'founded_era_id',
      label: 'Founded Era',
      type: 'text',
      placeholder: 'ID of the era when this place was established',
      helpText: 'The historical era in which this place was founded or first settled.',
    },
    {
      name: 'climate_zone_id',
      label: 'Climate Zone',
      type: 'text',
      placeholder: 'ID of the climate zone this place is in',
      helpText: 'The climate zone governing this location\'s weather and seasons.',
    },
    {
      name: 'biome_id',
      label: 'Biome',
      type: 'text',
      placeholder: 'ID of the biome this place is in',
      helpText: 'The biome or ecological region this location sits within.',
    },
    {
      name: 'terrain_description',
      label: 'Terrain Description',
      type: 'textarea',
      placeholder: 'Describe the physical landscape — hills, rivers, soil, vegetation...',
      helpText: 'The physical terrain and natural features of this location and its surroundings.',
    },
    {
      name: 'controlling_civilization_id',
      label: 'Controlling Civilization',
      type: 'text',
      placeholder: 'ID of the civilization that currently controls this place',
      helpText: 'The civilization, faction, or power that currently governs this location.',
    },
    {
      name: 'coordinates_x',
      label: 'Map X Coordinate',
      type: 'number',
      helpText: 'Horizontal position on the world map.',
    },
    {
      name: 'coordinates_y',
      label: 'Map Y Coordinate',
      type: 'number',
      helpText: 'Vertical position on the world map.',
    },
    {
      name: 'map_id',
      label: 'Map',
      type: 'text',
      placeholder: 'ID of the map this place appears on',
      helpText: 'The map on which this location is placed.',
    },
    {
      name: 'resources',
      label: 'Resources',
      type: 'textarea',
      placeholder: 'Describe available natural, economic, or magical resources...',
      helpText: 'Natural, economic, or magical resources available at or near this location.',
    },
    {
      name: 'trade_role',
      label: 'Trade Role',
      type: 'select',
      options: ['isolated', 'minor_stop', 'regional_hub', 'major_crossroads', 'capital_market', 'global_nexus'],
      helpText: 'This location\'s importance in trade networks.',
    },
    {
      name: 'accessibility',
      label: 'Accessibility',
      type: 'select',
      options: ['inaccessible', 'remote', 'difficult', 'moderate', 'accessible', 'major_thoroughfare'],
      helpText: 'How easy it is to reach this location by conventional means.',
    },
  ],
  elementTypes: ['city', 'town', 'village', 'fortress', 'ruin', 'landmark', 'road', 'port', 'temple', 'academy', 'wilderness', 'custom'],
  prompts: [
    'What makes the greatest city in your world great? Is it size, wealth, magical power, strategic location, or cultural prestige?',
    'What ruins dot the landscape, and what stories do they tell about civilizations that came before?',
    'How do trade routes and roads connect the major settlements? Are there dangerous stretches that travelers fear?',
    'Where are the sacred sites—temples, groves, ley line nexuses—and who controls access to them?',
    'What natural landmarks define the mental map of your world\'s inhabitants? What mountains, rivers, or forests do they use to orient themselves?',
  ],
  magicPermeation: {
    companionTable: 'geography_magic_aspects',
    fields: [
      {
        name: 'magical_landmarks',
        label: 'Magical Landmarks',
        type: 'textarea',
        helpText: 'Notable magical features at this location—arcane towers, enchanted springs, petrified titans, floating islands.',
      },
      {
        name: 'ley_line_geography',
        label: 'Ley Line Geography',
        type: 'textarea',
        helpText: 'How ley lines pass through, converge at, or avoid this location. Ley line nodes and their effects.',
      },
      {
        name: 'planar_crossings',
        label: 'Planar Crossings',
        type: 'textarea',
        helpText: 'Points where other planes bleed through—permanent portals, thin spots, seasonal gates.',
      },
      {
        name: 'enchanted_territories',
        label: 'Enchanted Territories',
        type: 'textarea',
        helpText: 'Areas under persistent magical effects—ever-winter zones, time-dilated regions, areas of wild magic.',
      },
      {
        name: 'mana_density_map_description',
        label: 'Mana Density Description',
        type: 'textarea',
        helpText: 'A description of the ambient mana levels across this location—high, low, fluctuating, dead zones.',
      },
      {
        name: 'magical_borders',
        label: 'Magical Borders',
        type: 'textarea',
        helpText: 'Borders enforced or defined by magic—ward walls, cursed boundaries, detection barriers.',
      },
      {
        name: 'sacred_profane_sites',
        label: 'Sacred & Profane Sites',
        type: 'textarea',
        helpText: 'Locations of powerful positive or negative magical significance—blessed groves, cursed battlefields, sites of sacrifice.',
      },
      {
        name: 'magical_travel_routes',
        label: 'Magical Travel Routes',
        type: 'textarea',
        helpText: 'Teleportation circles, ley line highways, shadow roads, or other magical travel infrastructure.',
      },
      {
        name: 'forbidden_zones',
        label: 'Forbidden Zones',
        type: 'textarea',
        helpText: 'Areas too dangerous or corrupted to enter—wild magic storms, undead domains, residual curse fields.',
      },
      {
        name: 'magical_resource_geography',
        label: 'Magical Resource Geography',
        type: 'textarea',
        helpText: 'Where magical resources are found near this location—mana crystal mines, reagent forests, essence springs.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the identity and function of this place.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: true,
    prompts: [
      'How does the magical geography of your world influence where civilizations build their cities? Do settlements cluster around ley line nexuses, mana springs, or portal sites?',
      'Are there places so saturated with magic that they are fundamentally altered—forests that think, mountains that move, deserts where time flows backward?',
      'What forbidden zones exist, and what catastrophe or corruption created them? Do people dare to enter, and what do they find?',
    ],
  },
  defaultSortField: 'place_type',
};
