import type { DomainConfig } from '../types/domains.js';

export const geographyConfig: DomainConfig = {
  id: 'geography',
  name: 'Geographic Place',
  namePlural: 'Geography',
  icon: 'map-pin',
  color: '#e67e22',
  description: 'Place the cities, fortresses, roads, temples, and landmarks of your world on the map. Geography ties together the natural landscape with the built environment, giving your civilizations concrete locations and your stories tangible settings.',
  tableName: 'geographical_places',
  category: 'meta',
  fields: [
    {
      name: 'place_type',
      label: 'Place Type',
      type: 'select',
      required: true,
      options: ['city', 'town', 'village', 'fortress', 'ruin', 'landmark', 'road', 'port', 'temple', 'academy'],
      helpText: 'The primary classification of this geographic location.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 50,000; abandoned; seasonal',
      helpText: 'Current population or occupancy of this location.',
    },
    {
      name: 'founded_era_id',
      label: 'Founded Era',
      type: 'text',
      placeholder: 'ID of the era when this place was established',
      helpText: 'The historical era in which this place was founded or first settled.',
    },
    {
      name: 'climate_zone_id',
      label: 'Climate Zone',
      type: 'text',
      placeholder: 'ID of the climate zone this place is in',
      helpText: 'The climate zone governing this location\'s weather and seasons.',
    },
    {
      name: 'biome_id',
      label: 'Biome',
      type: 'text',
      placeholder: 'ID of the biome this place is in',
      helpText: 'The biome or ecological region this location sits within.',
    },
    {
      name: 'terrain_description',
      label: 'Terrain Description',
      type: 'textarea',
      placeholder: 'Describe the physical landscape — hills, rivers, soil, vegetation...',
      helpText: 'The physical terrain and natural features of this location and its surroundings.',
    },
    {
      name: 'controlling_civilization_id',
      label: 'Controlling Civilization',
      type: 'text',
      placeholder: 'ID of the civilization that currently controls this place',
      helpText: 'The civilization, faction, or power that currently governs this location.',
    },
    {
      name: 'coordinates_x',
      label: 'Map X Coordinate',
      type: 'number',
      helpText: 'Horizontal position on the world map.',
    },
    {
      name: 'coordinates_y',
      label: 'Map Y Coordinate',
      type: 'number',
      helpText: 'Vertical position on the world map.',
    },
    {
      name: 'map_id',
      label: 'Map',
      type: 'text',
      placeholder: 'ID of the map this place appears on',
      helpText: 'The map on which this location is placed.',
    },
    {
      name: 'resources',
      label: 'Resources',
      type: 'textarea',
      placeholder: 'Describe available natural, economic, or magical resources...',
      helpText: 'Natural, economic, or magical resources available at or near this location.',
    },
    {
      name: 'trade_role',
      label: 'Trade Role',
      type: 'select',
      options: ['isolated', 'minor_stop', 'regional_hub', 'major_crossroads', 'capital_market', 'global_nexus'],
      helpText: 'This location\'s importance in trade networks.',
    },
    {
      name: 'accessibility',
      label: 'Accessibility',
      type: 'select',
      options: ['inaccessible', 'remote', 'difficult', 'moderate', 'accessible', 'major_thoroughfare'],
      helpText: 'How easy it is to reach this location by conventional means.',
    },
  ],
  elementTypes: ['city', 'town', 'village', 'fortress', 'ruin', 'landmark', 'road', 'port', 'temple', 'academy', 'wilderness', 'custom'],
  elementTypeDescriptions: {
    city: 'A large, densely populated settlement — a center of trade, governance, culture, and power.',
    town: 'A mid-sized settlement larger than a village but smaller than a city. Often serves as a regional hub for trade and services.',
    village: 'A small rural settlement, typically agricultural. The most common form of community in most worlds.',
    fortress: 'A heavily fortified structure built for defense — castles, citadels, wall complexes, or magical strongholds.',
    ruin: 'The remains of a once-great structure or settlement, now abandoned. Holds secrets, dangers, and echoes of the past.',
    landmark: 'A notable natural or constructed feature used for navigation and cultural identity — a great tree, monument, or unusual formation.',
    road: 'A constructed route connecting settlements. Trade roads, highways, pilgrimage paths, or magical ley-line highways.',
    port: 'A coastal or riverine settlement built around maritime trade. Where ships dock, goods flow, and cultures mix.',
    temple: 'A sacred site dedicated to worship, spiritual practice, or magical study. May hold significant power or relics.',
    academy: 'An institution of learning — universities, wizard schools, military academies, or monastic centers of knowledge.',
    wilderness: 'An untamed region with no permanent settlements. Forests, wastelands, or uncharted territories beyond civilization\'s reach.',
    custom: 'A place that doesn\'t fit standard categories — something unique to your world\'s geography.',
  },
  prompts: [
    'What makes the greatest city in your world great? Is it size, wealth, magical power, strategic location, or cultural prestige?',
    'What ruins dot the landscape, and what stories do they tell about civilizations that came before?',
    'How do trade routes and roads connect the major settlements? Are there dangerous stretches that travelers fear?',
    'Where are the sacred sites—temples, groves, ley line nexuses—and who controls access to them?',
    'What natural landmarks define the mental map of your world\'s inhabitants? What mountains, rivers, or forests do they use to orient themselves?',
  ],
  magicPermeation: {
    companionTable: 'geography_magic_aspects',
    fields: [
      {
        name: 'magical_landmarks',
        label: 'Magical Landmarks',
        type: 'textarea',
        helpText: 'Notable magical features at this location—arcane towers, enchanted springs, petrified titans, floating islands.',
      },
      {
        name: 'ley_line_geography',
        label: 'Ley Line Geography',
        type: 'textarea',
        helpText: 'How ley lines pass through, converge at, or avoid this location. Ley line nodes and their effects.',
      },
      {
        name: 'planar_crossings',
        label: 'Planar Crossings',
        type: 'textarea',
        helpText: 'Points where other planes bleed through—permanent portals, thin spots, seasonal gates.',
      },
      {
        name: 'enchanted_territories',
        label: 'Enchanted Territories',
        type: 'textarea',
        helpText: 'Areas under persistent magical effects—ever-winter zones, time-dilated regions, areas of wild magic.',
      },
      {
        name: 'mana_density_map_description',
        label: 'Mana Density Description',
        type: 'textarea',
        helpText: 'A description of the ambient mana levels across this location—high, low, fluctuating, dead zones.',
      },
      {
        name: 'magical_borders',
        label: 'Magical Borders',
        type: 'textarea',
        helpText: 'Borders enforced or defined by magic—ward walls, cursed boundaries, detection barriers.',
      },
      {
        name: 'sacred_profane_sites',
        label: 'Sacred & Profane Sites',
        type: 'textarea',
        helpText: 'Locations of powerful positive or negative magical significance—blessed groves, cursed battlefields, sites of sacrifice.',
      },
      {
        name: 'magical_travel_routes',
        label: 'Magical Travel Routes',
        type: 'textarea',
        helpText: 'Teleportation circles, ley line highways, shadow roads, or other magical travel infrastructure.',
      },
      {
        name: 'forbidden_zones',
        label: 'Forbidden Zones',
        type: 'textarea',
        helpText: 'Areas too dangerous or corrupted to enter—wild magic storms, undead domains, residual curse fields.',
      },
      {
        name: 'magical_resource_geography',
        label: 'Magical Resource Geography',
        type: 'textarea',
        helpText: 'Where magical resources are found near this location—mana crystal mines, reagent forests, essence springs.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the identity and function of this place.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: true,
    prompts: [
      'How does the magical geography of your world influence where civilizations build their cities? Do settlements cluster around ley line nexuses, mana springs, or portal sites?',
      'Are there places so saturated with magic that they are fundamentally altered—forests that think, mountains that move, deserts where time flows backward?',
      'What forbidden zones exist, and what catastrophe or corruption created them? Do people dare to enter, and what do they find?',
    ],
  },
  archetypes: [
    {
      id: 'capital_city',
      name: 'Capital City',
      description: 'A major city serving as the seat of government, trade, and culture for a civilization.',
      element_type: 'city',
      summary: 'A bustling capital city at the heart of a realm',
      fields: {
        place_type: 'city',
        population: '50,000-500,000',
        trade_role: 'capital_market',
        accessibility: 'major_thoroughfare',
        terrain_description: 'Built at a strategic confluence of roads and rivers. The city sprawls outward from a fortified inner district, with distinct quarters for merchants, artisans, temples, and the poor.',
        resources: 'As a capital, it draws resources from across the realm — grain from the provinces, luxury goods from trade partners, and taxes in coin and kind.',
      },
    },
    {
      id: 'frontier_town',
      name: 'Frontier Town',
      description: 'A rough-hewn settlement on the edge of civilization, attracting pioneers, outcasts, and the ambitious.',
      element_type: 'town',
      summary: 'A rough settlement at the edge of the known world',
      fields: {
        place_type: 'town',
        population: '500-3,000',
        trade_role: 'minor_stop',
        accessibility: 'difficult',
        terrain_description: 'A cluster of wooden buildings around a central well or crossroads, with a palisade wall in various states of repair. Surrounded by partially cleared wilderness.',
        resources: 'Timber, furs, and whatever the surrounding wilderness provides. A jumping-off point for prospectors, hunters, and those fleeing settled lands.',
      },
    },
    {
      id: 'ancient_ruins',
      name: 'Ancient Ruins',
      description: 'The crumbling remains of a once-great structure or settlement, now reclaimed by nature.',
      element_type: 'ruin',
      summary: 'Mysterious ruins of a fallen civilization',
      fields: {
        place_type: 'ruin',
        population: 'Uninhabited (or squatters and creatures)',
        trade_role: 'isolated',
        accessibility: 'difficult',
        terrain_description: 'Overgrown stone foundations and toppled columns half-buried in vegetation. The original layout is barely discernible. Underground levels may remain partially intact.',
        resources: 'Archaeological salvage, ancient artifacts, and whatever creatures have made the ruins their lair. Scholars and treasure-hunters are drawn here.',
      },
    },
    {
      id: 'mountain_fortress',
      name: 'Mountain Fortress',
      description: 'A heavily fortified stronghold built into or atop a mountain, commanding the surrounding terrain.',
      element_type: 'fortress',
      summary: 'An impregnable fortress carved into the mountainside',
      fields: {
        place_type: 'fortress',
        population: '200-2,000 (garrison)',
        trade_role: 'isolated',
        accessibility: 'difficult',
        terrain_description: 'Cut into the living rock of a mountain peak or cliff face. A single switchback road provides the only approach, easily defended. Cisterns and storerooms allow extended siege survival.',
        resources: 'Minimal local resources — the fortress depends on supply from lower elevations. Mountain springs provide water. Stone quarrying for ongoing construction.',
      },
    },
    {
      id: 'trade_port',
      name: 'Trade Port',
      description: 'A coastal or riverine port city whose wealth flows from maritime commerce.',
      element_type: 'port',
      summary: 'A thriving harbor city built on maritime trade',
      fields: {
        place_type: 'port',
        population: '10,000-100,000',
        trade_role: 'major_crossroads',
        accessibility: 'accessible',
        terrain_description: 'Built around a natural harbor or river mouth. Warehouses and docks dominate the waterfront, while merchant houses and markets fill the streets behind. A lighthouse marks the harbor entrance.',
        resources: 'Fish, salt, and maritime goods. The true wealth is in trade — goods from distant lands pass through the harbor and are taxed, stored, and redistributed.',
      },
    },
    {
      id: 'walking_citadel',
      name: 'Walking Citadel',
      description: 'A fortress built on the back of a colossal creature or animated construct, endlessly wandering the landscape.',
      element_type: 'fortress',
      summary: 'A mobile fortress that never stops moving — find it if you can',
      fields: {
        place_type: 'fortress',
        population: '500-5,000',
        trade_role: 'isolated',
        accessibility: 'inaccessible',
        terrain_description: 'A fortified structure built atop an enormous walking construct or living creature. The citadel sways gently with each step. Rope ladders and pulley lifts provide access when it pauses. Its route is predictable only to those who have studied its patterns for decades.',
        resources: 'Whatever the citadel walks over — it deploys harvesting teams at stops. Rain-catchers and onboard gardens provide water and food. Trade happens at predictable pause-points where merchants gather to wait.',
      },
    },
    {
      id: 'sunken_library',
      name: 'Sunken Library',
      description: 'A vast repository of knowledge submerged beneath lake or sea — its original builders chose water as the ultimate firebreak.',
      element_type: 'ruin',
      summary: 'An underwater archive, still intact, holding knowledge the surface world has forgotten',
      fields: {
        place_type: 'ruin',
        population: 'A small order of amphibious scholar-divers maintains it',
        trade_role: 'isolated',
        accessibility: 'inaccessible',
        terrain_description: 'Domed chambers of enchanted glass and coral-encrusted stone, visible from above as a shimmer beneath the surface. Air-filled reading rooms connect via flooded corridors. Bioluminescent organisms provide light. The collection is written on waterproof metal sheets and crystal tablets.',
        resources: 'Knowledge itself is the resource — maps, histories, and spell formulae from a fallen civilization. Scholars pay dearly for transcriptions. Some chambers remain sealed and their contents are unknown.',
      },
    },
    {
      id: 'crossroads_town',
      name: 'Crossroads Town',
      description: 'A settlement at the intersection of major trade routes. Cosmopolitan, wealthy, contested by powers on all sides.',
      element_type: 'town',
      summary: 'A prosperous town where trade routes converge, drawing merchants and conflict in equal measure',
      detailed_notes: 'Crossroads towns exist because geography demands them. Where major roads meet, rivers fork, or mountain passes converge, a settlement inevitably grows to service the travelers and merchants who pass through. These towns are defined by their diversity — every culture, language, and religion is represented in their markets. Wealth flows freely, but so does tension. Multiple powers claim influence or outright sovereignty, and the town\'s independence — if it has any — depends on playing rivals against each other. The permanent residents are outnumbered by transients, giving the town a restless, impermanent energy. Everything is for sale, everyone is passing through, and loyalties shift with the trade winds.',
      fields: {
        place_type: 'town',
        population: '5,000-20,000 permanent, with transient population doubling the count during trading seasons',
        trade_role: 'major_crossroads',
        accessibility: 'major_thoroughfare',
        terrain_description: 'Built at the intersection of two or more major roads, often near a river crossing or bridge. The town radiates outward from a central market square. Inns, warehouses, and stables dominate the architecture. Caravansaries and trading posts ring the outskirts.',
        resources: 'The town produces little itself — its wealth comes from taxing, storing, and facilitating the trade that passes through. Money-changers, translators, and brokers are the true industries. Information is bought and sold as readily as grain.',
      },
    },
    {
      id: 'forbidden_zone',
      name: 'Forbidden Zone',
      description: 'An area sealed off by magic, law, or danger. No one enters. Those who do don\'t return. Rumors abound.',
      element_type: 'wilderness',
      summary: 'A sealed and shunned territory where something terrible happened or still lurks',
      detailed_notes: 'Forbidden zones are places the world has decided to forget. They are sealed — by magical barriers, military cordons, or simply by the terror of what lies within. The reasons vary: a magical catastrophe that left the area lethally unstable, a contained threat that must not be released, a curse so potent that proximity is dangerous, or a secret so valuable that access is controlled by force. Maps mark them with warnings or leave them blank. Local populations develop traditions of avoidance passed down through generations. But the forbidden always attracts — treasure hunters, scholars, desperate refugees, and those who believe the official story is a lie. Some return with riches or knowledge. Most do not return at all.',
      fields: {
        place_type: 'ruin',
        population: 'Officially uninhabited. Unofficially, something lives inside.',
        trade_role: 'isolated',
        accessibility: 'inaccessible',
        terrain_description: 'The boundary is marked — ward-stones, military checkpoints, or simply a line where all vegetation dies. Beyond, the terrain is wrong in ways that are hard to articulate. Trees grow at angles. Shadows fall in the wrong direction. The air tastes of metal. Deeper in, the landscape becomes increasingly alien, as if the rules governing reality have been rewritten.',
        resources: 'Unknown. Expeditions that enter rarely return, and those that do bring back fragments — strange materials, corrupted artifacts, or samples of flora and fauna found nowhere else. The forbidden zone may contain extraordinary resources, but the cost of extraction exceeds what any rational actor would pay.',
      },
    },
    {
      id: 'sky_port',
      name: 'Sky Port',
      description: 'A docking station for flying ships, sky whales, or aerial transport. A city in the clouds, built for altitude.',
      element_type: 'port',
      summary: 'An aerial harbor for flying vessels, perched at altitude where the sky meets commerce',
      detailed_notes: 'Sky ports are engineering marvels built to service aerial transportation — flying ships, tamed sky creatures, or magical conveyances that travel through the upper atmosphere. They are constructed on mountaintops, floating platforms, or anchored to levitating rock formations, and they serve the same function as maritime ports but for the sky trade. Docking spires extend outward for vessel mooring, while cargo platforms use gravity-manipulation enchantments to load and unload goods. The permanent population lives in a vertical city adapted to altitude — pressurized quarters, wind-shielded markets, and heated commons. Sky ports are rare, expensive to maintain, and strategically invaluable, as they control access to the fastest trade routes in the world.',
      fields: {
        place_type: 'port',
        population: '2,000-15,000 permanent, with transient airship crews and passengers',
        trade_role: 'regional_hub',
        accessibility: 'difficult',
        terrain_description: 'Built on a high mountain peak, floating rock formation, or artificially levitated platform. Docking spires jut outward from the main structure like the branches of a dead tree. Cargo nets and gravity lifts move goods between levels. The wind is constant and brutal — all structures are aerodynamic and anchored against storms. Views extend to the horizon in every direction.',
        resources: 'Thin-air agriculture is impossible — all food is imported by the very ships the port services. Water is collected from clouds using condensation arrays. The sky port\'s true resource is its position: the only place for hundreds of miles where aerial vessels can dock, refuel, and trade.',
      },
    },
    {
      id: 'moving_city',
      name: 'Moving City',
      description: 'A settlement that physically relocates on legs, wheels, or magic.',
      element_type: 'city',
      summary: 'A city that walks, rolls, or floats across the landscape — never staying in one place for long',
      detailed_notes: 'The Moving City is a fully functional urban settlement built on a mobile platform — enormous mechanical legs, enchanted wheels, a levitating foundation, or the back of a colossal creature. The city migrates according to seasonal patterns, resource availability, or the political decisions of its rulers. Its inhabitants are urban dwellers who have never known stationary life: buildings are designed to withstand movement, streets are cambered for tilting, and all infrastructure is shock-mounted. The city\'s arrival at a region brings trade, cultural exchange, and economic disruption in equal measure. Its departure leaves trampled ground, depleted resources, and communities that grew dependent on its markets suddenly bereft. Rival moving cities compete for migration routes, and stationary settlements view them with a mixture of excitement and dread.',
      fields: {
        place_type: 'city',
        population: '20,000-100,000',
        trade_role: 'major_crossroads',
        accessibility: 'difficult',
        terrain_description: 'The city itself is the terrain — a multi-leveled urban platform that moves across the landscape. Structures are built to absorb vibration and tilt. Docking ramps extend during stops for trade. The ground beneath the city\'s path is permanently scarred by its passage — compacted earth, crushed vegetation, and deep track-marks.',
        resources: 'The city harvests resources from the regions it passes through — timber, water, game, and mana from ley lines it crosses. Onboard gardens and rainwater collection supplement external harvesting. The moving city\'s primary resource is its mobility — it goes where the resources are.',
      },
    },
    {
      id: 'prison_island',
      name: 'Prison Island',
      description: 'A remote island for exiles, now a civilization of its own.',
      element_type: 'village',
      summary: 'Once a prison colony, now a fiercely independent society built by generations of exiles',
      detailed_notes: 'Prison Island began as a dumping ground — a remote, inhospitable island where civilizations sent their criminals, political dissidents, and undesirables. Cut off from the mainland with no means of return, the exiles were expected to die. Instead, they survived, organized, and over generations built a society from nothing. The island civilization is shaped by its origins: fiercely egalitarian (no one claims superiority when everyone is an exile\'s descendant), deeply pragmatic (survival demanded practical skills above all), and profoundly suspicious of external authority. The island has developed its own language, customs, and legal system — one notably more merciful than the civilizations that created the prison colony. Mainland nations now find themselves dealing with an independent polity they never intended to create, and the island\'s strategic maritime position gives it leverage far beyond its small population.',
      fields: {
        place_type: 'village',
        population: '2,000-8,000',
        trade_role: 'minor_stop',
        accessibility: 'remote',
        terrain_description: 'A rocky, windswept island with harsh cliffs on the seaward side and a sheltered bay on the leeward. The original prison structures — stone walls, watchtowers — have been repurposed as communal buildings. Terraced gardens climb the hillsides. A modest harbor services fishing boats and the occasional trade vessel.',
        resources: 'Fish, seabirds, salt, and whatever can be coaxed from thin volcanic soil. The island\'s strategic position along maritime trade routes is its most valuable asset. Salvage from shipwrecks supplements material needs.',
      },
    },
    {
      id: 'vertical_city',
      name: 'Vertical City',
      description: 'Built into a cliff face or ravine. Hundreds of levels, no flat ground.',
      element_type: 'city',
      summary: 'A city built vertically into a cliff face — hundreds of levels, no flat ground, life lived in three dimensions',
      detailed_notes: 'The Vertical City clings to the face of an enormous cliff or fills a deep ravine from top to bottom. There is no flat ground — every surface is a wall, a ledge, or a staircase. Buildings are carved into the rock face or cantilevered out over the void on reinforced platforms. Transportation is vertical: rope lifts, pulley systems, enchanted platforms, and carved staircases connect the hundreds of levels. Social stratification is literally vertical — the wealthy live at the top where sunlight reaches, the poor at the bottom in perpetual shadow. The city developed in this extreme location because the cliff provided natural defense, the rock contained valuable minerals, or flat land was unavailable. Its inhabitants are as comfortable climbing as walking and have a culture shaped by verticality: status is "high" or "low" in the most literal sense, falling is the primary cause of death, and the concept of "horizon" is purely theoretical to most residents.',
      fields: {
        place_type: 'city',
        population: '15,000-60,000',
        trade_role: 'regional_hub',
        accessibility: 'difficult',
        terrain_description: 'Carved into and protruding from a massive cliff face or deep ravine. Hundreds of levels connected by staircases, rope bridges, and pulley-lifts. Buildings are terraced, cantilevered, or tunneled into the rock. Waterfalls cascade down the cliff through the city, powering mills and providing water. The bottom levels are shadowed and damp; the top levels catch wind and sun.',
        resources: 'Minerals and stone from the cliff itself. Water from mountain springs and rainfall channeled through carved aqueducts. Limited agriculture on terraced ledges — mostly vertical gardens and mushroom cultivation in interior caves. Trade goods hauled up from the base by lift systems.',
      },
    },
  ],
  defaultSortField: 'place_type',
};
