import type { DomainConfig } from '../types/domains.js';

export const geologyConfig: DomainConfig = {
  id: 'geology',
  name: 'Geology',
  namePlural: 'Geological Features',
  icon: 'mountain',
  color: '#a0785a',
  description: 'Define the tectonic plates, mountain ranges, volcanoes, cave systems, and mineral deposits that shape your world\'s terrain. Geology underpins biomes, resources, and civilizations.',
  tableName: 'geological_features',
  category: 'natural',
  fields: [
    {
      name: 'feature_type',
      label: 'Feature Type',
      type: 'select',
      required: true,
      options: ['mountain_range', 'volcano', 'canyon', 'plain', 'cave_system', 'fault_line', 'crater', 'plateau', 'island', 'rift_valley', 'mesa', 'fjord', 'badlands', 'delta'],
      optionDescriptions: {
        mountain_range: 'A chain of mountains formed by tectonic collision, volcanism, or magical upheaval. Defines borders, climate barriers, and resource-rich highlands.',
        volcano: 'An opening in the crust where magma reaches the surface. May be active, dormant, or extinct — and a source of fertile soil, minerals, or danger.',
        canyon: 'A deep, narrow valley carved by water erosion, tectonic splitting, or catastrophic events. Often reveals exposed geological strata.',
        plain: 'A broad, flat expanse of land with minimal elevation change. Ideal for agriculture, large settlements, and overland travel.',
        cave_system: 'Underground networks of chambers and passages formed by water dissolution, lava tubes, or subterranean forces. May host hidden ecosystems or civilizations.',
        fault_line: 'A fracture in the crust where tectonic plates meet and shift. Source of earthquakes, geothermal activity, and geological instability.',
        crater: 'A bowl-shaped depression formed by meteorite impact, volcanic collapse, or magical detonation. May contain lakes, settlements, or unusual mineral deposits.',
        plateau: 'An elevated flat-topped landform rising sharply above surrounding terrain. Often isolated, defensible, and climatically distinct from lowlands.',
        island: 'A body of land surrounded by water, formed by volcanism, tectonic uplift, or continental separation. Develops unique ecosystems through isolation.',
        rift_valley: 'A long, narrow depression where the crust is being pulled apart. Sites of volcanic activity, hot springs, and early civilizations along fertile lakeshores.',
        mesa: 'A flat-topped hill with steep sides, an erosion remnant of a former plateau. Often sacred or strategically significant due to their natural fortification.',
        fjord: 'A narrow, deep coastal inlet carved by glacial erosion. Steep-walled and sheltered, fjords make natural harbors and dramatic landscapes.',
        badlands: 'Heavily eroded terrain of ridges, gullies, and hoodoos with sparse vegetation. Difficult to traverse but rich in exposed fossils and minerals.',
        delta: 'A fan-shaped deposit of sediment where a river meets a larger body of water. Among the most fertile and densely populated landforms.',
      },
      helpText: 'The geological classification of this feature.',
    },
    {
      name: 'elevation_min',
      label: 'Minimum Elevation',
      type: 'number',
      placeholder: 'Meters above/below sea level',
      helpText: 'The lowest point of this feature in meters.',
    },
    {
      name: 'elevation_max',
      label: 'Maximum Elevation',
      type: 'number',
      placeholder: 'Meters above sea level',
      helpText: 'The highest point of this feature in meters.',
    },
    {
      name: 'age_description',
      label: 'Geological Age',
      type: 'text',
      placeholder: 'e.g. 300 million years, ancient, newly formed',
      helpText: 'How old this feature is in your world\'s timeline.',
    },
    {
      name: 'mineral_composition',
      label: 'Mineral Composition',
      type: 'json',
      placeholder: '["granite", "quartz", "obsidian"]',
      helpText: 'Notable minerals and materials found in this feature.',
    },
    {
      name: 'tectonic_plate',
      label: 'Tectonic Plate',
      type: 'text',
      placeholder: 'Name of the tectonic plate',
      helpText: 'Which tectonic plate this feature sits on or borders.',
    },
    {
      name: 'active',
      label: 'Geologically Active',
      type: 'boolean',
      helpText: 'Whether this feature is still geologically active (volcanic, seismic, etc.).',
    },
    {
      name: 'formation_process',
      label: 'Formation Process',
      type: 'textarea',
      placeholder: 'Describe how this feature was formed — tectonic collision, erosion, volcanic eruption, magical cataclysm...',
      helpText: 'The geological or supernatural forces that created this feature and over what timescale.',
    },
    {
      name: 'natural_resources',
      label: 'Natural Resources',
      type: 'textarea',
      placeholder: 'Describe ore veins, gemstone deposits, quarry stone, fossil fuels...',
      helpText: 'Extractable resources found in or around this feature — drives mining economies and settlement.',
    },
    {
      name: 'geographic_extent',
      label: 'Geographic Extent',
      type: 'text',
      placeholder: 'e.g. 800 km long, 50 km² area, 3 km deep',
      helpText: 'The lateral size, length, or area of this feature.',
    },
    {
      name: 'hazards',
      label: 'Geological Hazards',
      type: 'textarea',
      placeholder: 'Describe earthquakes, eruptions, landslides, sinkholes, toxic gas vents...',
      helpText: 'Active dangers posed by this feature — seismic events, eruptions, collapses, toxic emissions.',
    },
    {
      name: 'climate_impact',
      label: 'Climate Impact',
      type: 'textarea',
      placeholder: 'Describe rain shadows, wind barriers, temperature effects...',
      helpText: 'How this feature shapes the climate of surrounding regions — rain shadows, wind deflection, thermal effects.',
    },
  ],
  elementTypes: ['mountain_range', 'volcano', 'canyon', 'plain', 'cave_system', 'fault_line', 'crater', 'plateau', 'island', 'rift_valley', 'mesa', 'fjord', 'badlands', 'delta'],
  elementTypeDescriptions: {
    mountain_range: 'A chain of mountains formed by tectonic collision or volcanism. Defines borders, creates rain shadows, and holds mineral wealth.',
    volcano: 'An opening in the crust where magma reaches the surface. May be active, dormant, or extinct — a source of fertile soil and danger alike.',
    canyon: 'A deep, narrow valley carved by water erosion or tectonic splitting, often revealing exposed geological strata.',
    plain: 'A broad, flat expanse of land with minimal elevation change. Ideal for agriculture, settlements, and overland travel.',
    cave_system: 'Underground networks of chambers and passages formed by water dissolution, lava tubes, or subterranean forces.',
    fault_line: 'A fracture in the crust where tectonic plates meet and shift. Source of earthquakes, geothermal activity, and instability.',
    crater: 'A bowl-shaped depression formed by meteorite impact, volcanic collapse, or magical detonation.',
    plateau: 'An elevated flat-topped landform rising sharply above surrounding terrain. Often isolated and climatically distinct.',
    island: 'A body of land surrounded by water, formed by volcanism or tectonic uplift. Develops unique ecosystems through isolation.',
    rift_valley: 'A long depression where the crust is being pulled apart. Sites of volcanic activity and hot springs.',
    mesa: 'A flat-topped hill with steep sides, an erosion remnant of a former plateau. Naturally defensible and often sacred.',
    fjord: 'A narrow, deep coastal inlet carved by glacial erosion. Steep-walled and sheltered, making natural harbors.',
    badlands: 'Heavily eroded terrain of ridges, gullies, and hoodoos with sparse vegetation. Rich in exposed fossils and minerals.',
    delta: 'A fan-shaped deposit of sediment where a river meets a larger body of water. Among the most fertile landforms.',
  },
  prompts: [
    'What tectonic forces shaped your world? Are plates still moving, or has the crust stabilized?',
    'Are there unique minerals or geological materials that don\'t exist in our world? What properties do they have?',
    'How do cave systems and underground features connect? Are there entire civilizations beneath the surface?',
    'What geological disasters (earthquakes, volcanic eruptions, sinkholes) threaten or shape societies?',
    'How has erosion, glaciation, or other long-term processes sculpted the landscape over millennia?',
  ],
  magicPermeation: {
    companionTable: 'geology_magic_aspects',
    fields: [
      {
        name: 'ley_line_geology',
        label: 'Ley Line Geology',
        type: 'textarea',
        helpText: 'How ley lines interact with geological structures—do they follow fault lines, mineral veins, or mountain roots?',
      },
      {
        name: 'magical_minerals',
        label: 'Magical Minerals',
        type: 'textarea',
        helpText: 'Minerals with magical properties found within this feature.',
      },
      {
        name: 'mana_crystallized_formations',
        label: 'Mana-Crystallized Formations',
        type: 'textarea',
        helpText: 'Geological formations created by or infused with crystallized mana.',
      },
      {
        name: 'tectonic_magic_interaction',
        label: 'Tectonic-Magic Interaction',
        type: 'textarea',
        helpText: 'How tectonic activity affects or is affected by magical energy.',
      },
      {
        name: 'underground_mana_reservoirs',
        label: 'Underground Mana Reservoirs',
        type: 'textarea',
        helpText: 'Subterranean pools or veins of concentrated magical energy.',
      },
      {
        name: 'geological_age_magic_correlation',
        label: 'Geological Age & Magic Correlation',
        type: 'textarea',
        helpText: 'How the age of formations relates to their magical properties.',
      },
      {
        name: 'volcanic_magic',
        label: 'Volcanic Magic',
        type: 'textarea',
        helpText: 'Magical properties of volcanic activity—eruptions releasing stored mana, lava with magical properties, etc.',
      },
      {
        name: 'fossil_magic',
        label: 'Fossil Magic',
        type: 'textarea',
        helpText: 'Magical residue in fossils of ancient creatures or plants.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this geological feature.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: false,
    prompts: [
      'Do ley lines follow geological fault lines, or do they cut through the earth independently? Can mining disrupt them?',
      'Are there minerals that naturally store, conduct, or repel magical energy? How has this shaped mining economies?',
      'When volcanoes erupt, do they release concentrated magical energy along with lava and ash?',
    ],
  },
  archetypes: [
    {
      id: 'continental_mountain_range',
      name: 'Continental Mountain Range',
      description: 'A vast chain of mountains formed by tectonic collision, shaping weather and dividing civilizations.',
      element_type: 'mountain_range',
      summary: 'A continent-spanning mountain range born from tectonic collision',
      fields: {
        feature_type: 'mountain_range',
        elevation_max: 8000,
        elevation_min: 1500,
        active: true,
        formation_process: 'Formed by the collision of two continental plates over millions of years, with ongoing uplift creating jagged peaks and deep valleys.',
        natural_resources: 'Rich deposits of iron, copper, gold, and gemstones in the folded rock layers. Alpine meadows provide seasonal grazing.',
        climate_impact: 'Creates a major rain shadow effect, with lush forests on the windward side and arid plains on the leeward side.',
      },
    },
    {
      id: 'shield_volcano',
      name: 'Shield Volcano',
      description: 'A broad, gently sloping volcano built by successive flows of fluid lava.',
      element_type: 'volcano',
      summary: 'A broad, active shield volcano with fertile lower slopes',
      fields: {
        feature_type: 'volcano',
        elevation_max: 4000,
        elevation_min: 0,
        active: true,
        formation_process: 'Built up over millennia by repeated eruptions of low-viscosity basaltic lava that flows long distances before cooling.',
        natural_resources: 'Fertile volcanic soils on the lower slopes support lush agriculture. Obsidian and pumice deposits.',
        hazards: 'Slow-moving lava flows that can engulf settlements over days. Occasional explosive eruptions when water infiltrates the magma chamber.',
      },
    },
    {
      id: 'limestone_cave_network',
      name: 'Limestone Cave Network',
      description: 'A vast underground system of chambers and passages carved by water through ancient limestone.',
      element_type: 'cave_system',
      summary: 'An ancient network of limestone caves with underground rivers',
      fields: {
        feature_type: 'cave_system',
        active: false,
        age_description: 'Tens of millions of years',
        formation_process: 'Carved by slightly acidic groundwater dissolving limestone over geological time, creating vast chambers, stalactites, and underground rivers.',
        natural_resources: 'Crystal formations, underground freshwater reserves, and rare cave-adapted minerals. Guano deposits from bat colonies.',
      },
    },
    {
      id: 'rift_valley',
      name: 'Rift Valley',
      description: "A dramatic depression where the earth's crust is pulling apart, often geothermally active.",
      element_type: 'rift_valley',
      summary: 'A tectonic rift valley with geothermal springs and volcanic activity',
      fields: {
        feature_type: 'rift_valley',
        elevation_min: -200,
        elevation_max: 800,
        active: true,
        formation_process: 'Created by extensional tectonic forces pulling the crust apart, causing the central block to drop between parallel fault lines.',
        natural_resources: 'Geothermal energy, alkaline lakes rich in minerals, and fertile volcanic soils along the valley floor.',
        hazards: 'Frequent seismic activity, volcanic eruptions along the rift margins, and sudden ground subsidence.',
      },
    },
    {
      id: 'petrified_titan',
      name: 'Petrified Titan',
      description: 'A mountain range that is actually the fossilized remains of a colossal primordial creature.',
      element_type: 'mountain_range',
      summary: 'The stone bones of an ancient giant, mistaken for mountains',
      fields: {
        feature_type: 'mountain_range',
        elevation_max: 6000,
        elevation_min: 800,
        active: false,
        age_description: 'Older than recorded history — geological dating gives impossible results',
        formation_process: 'Not geological at all. The "mountains" are the petrified spine and ribcage of a creature so vast it was mistaken for terrain. The truth is preserved in indigenous oral tradition but dismissed by scholars.',
        natural_resources: 'Bone-ite — fossilized titan bone harder than granite. Marrow caverns contain veins of an opalescent mineral found nowhere else. Alchemists pay fortunes for it.',
        hazards: 'Sections occasionally shift as if the titan is stirring in its sleep. Earthquakes here follow no tectonic logic.',
      },
    },
    {
      id: 'floating_islands',
      name: 'Floating Islands',
      description: 'Masses of rock suspended above the ground by anti-gravity minerals, magical uplift, or gas pockets.',
      element_type: 'island',
      summary: 'Airborne landmasses hovering above the surface, defying conventional geology',
      detailed_notes: 'Floating islands are geological anomalies — fragments of terrain that have separated from the ground and hang suspended at varying altitudes. The mechanism varies: some are laced with anti-gravity minerals that repel the earth below, others ride on columns of superheated gas from volcanic vents, and still others are held aloft by ancient enchantments embedded in the bedrock. The islands drift slowly, their shadows tracking across the land below like roaming eclipses. Waterfalls pour from their edges into mist, and unique ecosystems develop in isolation. Civilizations build bridges of chain and rope between island clusters, and wars have been fought over the richest mineral-bearing floaters.',
      fields: {
        feature_type: 'island',
        elevation_min: 500,
        elevation_max: 4000,
        formation_process: 'Torn from the surface by concentrations of anti-gravity minerals (levitite) deposited by ancient volcanic activity. The minerals repel the planetary crust, and once a critical mass is reached, the surrounding rock shears free and rises until equilibrium is reached.',
        mineral_composition: '["levitite", "basalt", "quartz", "iron ore", "sky-moss calcite"]',
        hazards: 'Islands occasionally lose buoyancy and crash to the ground without warning. Edge erosion sends rockfalls thousands of meters to the surface. High winds make crossing between islands lethal without secured lines.',
      },
    },
    {
      id: 'glass_desert',
      name: 'Glass Desert',
      description: 'A vast plain of fused silica created by an ancient magical detonation or meteorite impact.',
      element_type: 'plain',
      summary: 'An endless expanse of fused glass — beautiful, blinding, and mercilessly hot',
      detailed_notes: 'The glass desert is what remains when unimaginable heat is applied to a sandy plain — the entire surface fused into a single sheet of silica glass stretching to the horizon. The surface is smooth in some places and fractured into jagged shards in others. During the day, sunlight reflects with blinding intensity, and the surface temperature can melt boot leather. At night, the glass cools rapidly and contracts, producing eerie cracking sounds that carry for miles. Beneath the glass layer, pockets of trapped air and sand create hollow chambers that collapse unpredictably. The event that created it — whether a meteor strike, a magical detonation, or a divine punishment — is a matter of fierce scholarly debate. Nothing grows on the surface, but hardy organisms survive in the cracks and beneath the glass crust.',
      fields: {
        feature_type: 'plain',
        elevation_min: 200,
        formation_process: 'Created by a cataclysmic thermal event approximately 3,000 years ago that fused the sand of a vast desert into a continuous sheet of glass. The heat signature suggests temperatures exceeding 3,000°C sustained for several minutes across an area of 40,000 km².',
        mineral_composition: '["fused silica", "fulgurite veins", "trinitite-analog", "obsidian nodules"]',
        hazards: 'Blinding reflected sunlight causes snow-blindness within minutes without eye protection. Surface temperatures reach 70°C at midday. The glass crust is brittle in places and collapses into subsurface voids. Sharp edges lacerate exposed skin and shred footwear.',
        climate_impact: 'The highly reflective surface creates a local albedo anomaly, deflecting heat upward and generating powerful thermals. Surrounding regions experience unusual wind patterns and reduced rainfall as moisture-laden air is pushed away by rising hot air columns.',
      },
    },
    {
      id: 'living_mountain',
      name: 'Living Mountain',
      description: 'A geological feature that is actually a dormant or sleeping creature of immense size.',
      element_type: 'mountain_range',
      summary: 'A mountain that breathes — a slumbering titan mistaken for terrain',
      detailed_notes: 'Unlike the petrified titan, the living mountain is not dead — it is sleeping. The "mountain" is the curled body of a creature so enormous that forests grow on its back and rivers run through the creases of its skin. Its breathing cycle spans decades: a slow inhale that lasts years, followed by an equally gradual exhale that changes wind patterns across the region. Geological surveys reveal that the rock is not rock at all but a keratinous hide covered in mineral deposits accumulated over millennia of stillness. The creature\'s heartbeat is detectable as a deep, rhythmic tremor every 72 hours. Entire civilizations have been built on its surface, unaware that their homeland is alive. The question that terrifies scholars is not whether it will wake — but what could possibly have put it to sleep, and whether that force is still in effect.',
      fields: {
        feature_type: 'mountain_range',
        elevation_max: 5500,
        active: true,
        formation_process: 'Not formed by geology. The "mountain" is a living organism of unknown origin that settled into its current position in prehistory and entered a dormant state. Mineral accretion over millennia gave it the appearance of natural terrain.',
        hazards: 'Periodic tremors from the creature\'s heartbeat cause structural damage to settlements. Excavation too deep risks piercing the hide and triggering a pain response. If it wakes, everything built upon it will be destroyed.',
      },
    },
    {
      id: 'bone_fields',
      name: 'Bone Fields',
      description: 'A plain made of compressed ancient bones. Fossils, ancient marrow, and opalescent mineral deposits.',
      element_type: 'plain',
      summary: 'A vast plain of compressed prehistoric bones — eerily flat, phosphorescent at night, and rich with strange minerals',
      detailed_notes: 'The Bone Fields are what remains after millions of years of death accumulation in a low basin that once served as a natural trap for megafauna. Over geological time, the bones compressed into a dense, pale stratum that now forms the surface layer across thousands of square kilometers. The terrain is unnervingly flat and white, broken only by occasional ridges where larger skeletal elements — ribs, skulls, femurs of creatures long extinct — protrude from the surface like abstract monuments. At night, phosphorescent minerals in the ancient marrow cause sections of the plain to glow with a faint blue-green light. The soil is extraordinarily rich in calcium and phosphorus, and opalescent deposits formed from mineralized marrow are prized by jewelers and alchemists. Despite its macabre composition, the Bone Fields support a unique ecosystem of calcium-tolerant grasses, burrowing insects, and scavenging birds that feed on the fossil-dwelling invertebrates.',
      fields: {
        feature_type: 'plain',
        formation_process: 'Millions of years of megafaunal die-offs in a natural basin, followed by compression and mineralization. The bone layer is 15-30 meters thick in places, representing countless generations of creatures drawn to the basin by water sources that have long since dried up.',
        mineral_composition: '["calcium phosphate", "opalescent marrow-stone", "fossilized keratin", "boneite", "trace rare earth elements"]',
        natural_resources: 'Opal-marrow gemstones, high-grade calcium phosphate for fertilizer and alchemy, fossilized keratin harder than steel, and rare earth elements concentrated by biological processes over millions of years.',
        hazards: 'The bone substrate is riddled with cavities and hollow chambers that collapse under heavy loads. Dust storms whip up bone powder that causes a choking respiratory illness called "marrow lung." At night, the phosphorescent glow attracts disoriented travelers into unmarked sinkholes.',
      },
    },
    {
      id: 'singing_stones',
      name: 'Singing Stones',
      description: 'Rock formations that resonate at specific frequencies, producing sound audible for miles.',
      element_type: 'mountain_range',
      summary: 'A mountain range of crystalline rock that produces haunting, resonant tones when wind or seismic activity passes through it',
      detailed_notes: 'The Singing Stones are a mountain range composed primarily of a rare piezoelectric mineral that converts mechanical stress into sound. When wind passes through the narrow canyons and eroded columns, the rock vibrates at precise frequencies, producing tones that range from deep, bone-shaking bass to high, crystalline notes audible for dozens of miles. Seismic activity triggers even more dramatic performances — an earthquake in the Singing Stones produces a chorus that can be heard across entire continents. The acoustic properties have made the range sacred to every culture within earshot. Temples are built at nodes where multiple resonant formations converge, producing permanent harmonies. Miners work the range carefully, because removing the wrong formation can silence an entire valley\'s song — or worse, create a dissonant frequency that causes headaches, nausea, and madness in nearby settlements.',
      fields: {
        feature_type: 'mountain_range',
        elevation_max: 4500,
        mineral_composition: '["piezoelectric quartz", "resonance crystal", "basalt", "granite", "sound-stone"]',
        formation_process: 'Formed by volcanic intrusion of silica-rich magma into existing limestone, creating veins of piezoelectric crystal that were later exposed by erosion. The specific geometry of the eroded formations — columns, arches, and tubes — amplifies the piezoelectric vibrations into audible sound.',
      },
    },
    {
      id: 'scar_of_god',
      name: 'Scar of God',
      description: 'A canyon or crater left by a divine weapon strike. Still radiates power millennia later.',
      element_type: 'crater',
      summary: 'A wound in the earth left by the strike of a divine weapon, still radiating residual power after millennia',
      detailed_notes: 'The Scar of God is not a natural geological formation. It is a wound — a gash in the crust of the world left by the strike of a weapon wielded by a deity during a war among gods. The crater is roughly 80 kilometers long and 15 kilometers wide, tapering to a point at each end as though the earth were slashed by a colossal blade. The walls are fused glass, the impact having vitrified the rock instantaneously. At the deepest point, the crater breaches the mantle, and a lake of slowly cooling magma still glows at the bottom, thousands of years after the strike. The residual divine energy is palpable — compasses spin, animals refuse to enter, and those who spend too long at the rim report visions of the battle that created it. The Scar has never healed. Geologists note that the surrounding crust is still recoiling from the impact, producing earthquakes that follow no natural pattern. Some theologians believe the wound is infected — that something fell into the breach during the divine war and is still down there, festering.',
      fields: {
        feature_type: 'crater',
        elevation_min: -8000,
        formation_process: 'Created by the strike of a divine weapon during a war among gods. The impact vitrified rock, breached the mantle, and left residual divine energy that prevents natural geological healing. The strike is dated to approximately 8,000 years ago by fused-glass analysis.',
        hazards: 'Residual divine energy disrupts navigation, induces hallucinations, and causes temporal distortion near the crater floor. The exposed magma lake produces toxic gases. Earthquakes centered on the Scar follow no tectonic logic and cannot be predicted. Expeditions to the crater floor have a low survival rate.',
        climate_impact: 'The exposed magma lake creates a permanent thermal updraft that disrupts weather patterns for hundreds of miles. A column of superheated air rises from the Scar, deflecting storm systems and creating a rain shadow in regions that would otherwise be fertile. Ash from the magma lake occasionally enters the upper atmosphere during seismic events.',
      },
    },
  ],
  defaultSortField: 'feature_type',
};
