import type { DomainConfig } from '../types/domains.js';

export const geologyConfig: DomainConfig = {
  id: 'geology',
  name: 'Geology',
  namePlural: 'Geological Features',
  icon: 'mountain',
  color: '#a0785a',
  description: 'Define the tectonic plates, mountain ranges, volcanoes, cave systems, and mineral deposits that shape your world\'s terrain. Geology underpins biomes, resources, and civilizations.',
  tableName: 'geological_features',
  category: 'natural',
  fields: [
    {
      name: 'feature_type',
      label: 'Feature Type',
      type: 'select',
      required: true,
      options: ['mountain_range', 'volcano', 'canyon', 'plain', 'cave_system', 'fault_line', 'crater', 'plateau', 'island', 'rift_valley', 'mesa', 'fjord', 'badlands', 'delta'],
      optionDescriptions: {
        mountain_range: 'A chain of mountains formed by tectonic collision, volcanism, or magical upheaval. Defines borders, climate barriers, and resource-rich highlands.',
        volcano: 'An opening in the crust where magma reaches the surface. May be active, dormant, or extinct — and a source of fertile soil, minerals, or danger.',
        canyon: 'A deep, narrow valley carved by water erosion, tectonic splitting, or catastrophic events. Often reveals exposed geological strata.',
        plain: 'A broad, flat expanse of land with minimal elevation change. Ideal for agriculture, large settlements, and overland travel.',
        cave_system: 'Underground networks of chambers and passages formed by water dissolution, lava tubes, or subterranean forces. May host hidden ecosystems or civilizations.',
        fault_line: 'A fracture in the crust where tectonic plates meet and shift. Source of earthquakes, geothermal activity, and geological instability.',
        crater: 'A bowl-shaped depression formed by meteorite impact, volcanic collapse, or magical detonation. May contain lakes, settlements, or unusual mineral deposits.',
        plateau: 'An elevated flat-topped landform rising sharply above surrounding terrain. Often isolated, defensible, and climatically distinct from lowlands.',
        island: 'A body of land surrounded by water, formed by volcanism, tectonic uplift, or continental separation. Develops unique ecosystems through isolation.',
        rift_valley: 'A long, narrow depression where the crust is being pulled apart. Sites of volcanic activity, hot springs, and early civilizations along fertile lakeshores.',
        mesa: 'A flat-topped hill with steep sides, an erosion remnant of a former plateau. Often sacred or strategically significant due to their natural fortification.',
        fjord: 'A narrow, deep coastal inlet carved by glacial erosion. Steep-walled and sheltered, fjords make natural harbors and dramatic landscapes.',
        badlands: 'Heavily eroded terrain of ridges, gullies, and hoodoos with sparse vegetation. Difficult to traverse but rich in exposed fossils and minerals.',
        delta: 'A fan-shaped deposit of sediment where a river meets a larger body of water. Among the most fertile and densely populated landforms.',
      },
      helpText: 'The geological classification of this feature.',
    },
    {
      name: 'elevation_min',
      label: 'Minimum Elevation',
      type: 'number',
      placeholder: 'Meters above/below sea level',
      helpText: 'The lowest point of this feature in meters.',
    },
    {
      name: 'elevation_max',
      label: 'Maximum Elevation',
      type: 'number',
      placeholder: 'Meters above sea level',
      helpText: 'The highest point of this feature in meters.',
    },
    {
      name: 'age_description',
      label: 'Geological Age',
      type: 'text',
      placeholder: 'e.g. 300 million years, ancient, newly formed',
      helpText: 'How old this feature is in your world\'s timeline.',
    },
    {
      name: 'mineral_composition',
      label: 'Mineral Composition',
      type: 'json',
      placeholder: '["granite", "quartz", "obsidian"]',
      helpText: 'Notable minerals and materials found in this feature.',
    },
    {
      name: 'tectonic_plate',
      label: 'Tectonic Plate',
      type: 'text',
      placeholder: 'Name of the tectonic plate',
      helpText: 'Which tectonic plate this feature sits on or borders.',
    },
    {
      name: 'active',
      label: 'Geologically Active',
      type: 'boolean',
      helpText: 'Whether this feature is still geologically active (volcanic, seismic, etc.).',
    },
  ],
  elementTypes: ['mountain_range', 'volcano', 'canyon', 'plain', 'cave_system', 'fault_line', 'crater', 'plateau', 'island', 'rift_valley', 'mesa', 'fjord', 'badlands', 'delta'],
  prompts: [
    'What tectonic forces shaped your world? Are plates still moving, or has the crust stabilized?',
    'Are there unique minerals or geological materials that don\'t exist in our world? What properties do they have?',
    'How do cave systems and underground features connect? Are there entire civilizations beneath the surface?',
    'What geological disasters (earthquakes, volcanic eruptions, sinkholes) threaten or shape societies?',
    'How has erosion, glaciation, or other long-term processes sculpted the landscape over millennia?',
  ],
  magicPermeation: {
    companionTable: 'geology_magic_aspects',
    fields: [
      {
        name: 'ley_line_geology',
        label: 'Ley Line Geology',
        type: 'textarea',
        helpText: 'How ley lines interact with geological structures—do they follow fault lines, mineral veins, or mountain roots?',
      },
      {
        name: 'magical_minerals',
        label: 'Magical Minerals',
        type: 'textarea',
        helpText: 'Minerals with magical properties found within this feature.',
      },
      {
        name: 'mana_crystallized_formations',
        label: 'Mana-Crystallized Formations',
        type: 'textarea',
        helpText: 'Geological formations created by or infused with crystallized mana.',
      },
      {
        name: 'tectonic_magic_interaction',
        label: 'Tectonic-Magic Interaction',
        type: 'textarea',
        helpText: 'How tectonic activity affects or is affected by magical energy.',
      },
      {
        name: 'underground_mana_reservoirs',
        label: 'Underground Mana Reservoirs',
        type: 'textarea',
        helpText: 'Subterranean pools or veins of concentrated magical energy.',
      },
      {
        name: 'geological_age_magic_correlation',
        label: 'Geological Age & Magic Correlation',
        type: 'textarea',
        helpText: 'How the age of formations relates to their magical properties.',
      },
      {
        name: 'volcanic_magic',
        label: 'Volcanic Magic',
        type: 'textarea',
        helpText: 'Magical properties of volcanic activity—eruptions releasing stored mana, lava with magical properties, etc.',
      },
      {
        name: 'fossil_magic',
        label: 'Fossil Magic',
        type: 'textarea',
        helpText: 'Magical residue in fossils of ancient creatures or plants.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this geological feature.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: false,
    prompts: [
      'Do ley lines follow geological fault lines, or do they cut through the earth independently? Can mining disrupt them?',
      'Are there minerals that naturally store, conduct, or repel magical energy? How has this shaped mining economies?',
      'When volcanoes erupt, do they release concentrated magical energy along with lava and ash?',
    ],
  },
  defaultSortField: 'feature_type',
};
