import type { DomainConfig } from '../types/domains.js';

export const historyConfig: DomainConfig = {
  id: 'history',
  name: 'Historical Event',
  namePlural: 'History',
  icon: 'scroll',
  color: '#95a5a6',
  description: 'Chronicle the major events, eras, and turning points that have shaped your world. From wars and discoveries to disasters and cultural revolutions, history provides the narrative backbone that connects all other domains across time.',
  tableName: 'historical_events',
  category: 'meta',
  fields: [
    {
      name: 'era_id',
      label: 'Era',
      type: 'text',
      placeholder: 'ID of the historical era this event belongs to',
      helpText: 'The broader era or age in which this event took place.',
    },
    {
      name: 'year_in_world',
      label: 'Year (In-World)',
      type: 'text',
      placeholder: 'e.g. 3rd Age, Year 1247; 500 BF (Before Founding)',
      helpText: 'The date or year of this event in your world\'s calendar system.',
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g. 3 days, 30 years, instantaneous',
      helpText: 'How long the event lasted—from a single moment to centuries-long processes.',
    },
    {
      name: 'event_type',
      label: 'Event Type',
      type: 'select',
      required: true,
      options: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural', 'political', 'magical', 'technological', 'economic'],
      helpText: 'The primary category of this historical event.',
    },
    {
      name: 'participants',
      label: 'Participants',
      type: 'json',
      placeholder: '["Kingdom of Aldara", "the Dragon Lords", "Archmage Velen"]',
      helpText: 'Key civilizations, factions, or individuals involved in this event.',
    },
    {
      name: 'consequences',
      label: 'Consequences',
      type: 'json',
      placeholder: '["fall of the old empire", "discovery of mithril", "planar seal broken"]',
      helpText: 'The major outcomes and lasting effects of this event.',
    },
  ],
  elementTypes: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural_shift', 'political_event', 'magical_event', 'technological_breakthrough', 'economic_event'],
  prompts: [
    'What are the defining conflicts in your world\'s history? Were they fought over land, resources, ideology, or magical power?',
    'What event do all cultures in your world agree was the most important, and how do their interpretations of it differ?',
    'What knowledge or capability has been lost to history? Are there dark ages that people are still recovering from?',
    'How reliable is the historical record? Who writes history, and what have they chosen to omit or distort?',
    'What is the most recent major event, and how are its consequences still unfolding in the present day?',
  ],
  magicPermeation: {
    companionTable: 'history_magic_aspects',
    fields: [
      {
        name: 'magical_cataclysms',
        label: 'Magical Cataclysms',
        type: 'textarea',
        helpText: 'Catastrophic magical events—mana explosions, ley line collapses, planar breaches that reshaped the world.',
      },
      {
        name: 'magic_discovery_milestones',
        label: 'Magic Discovery Milestones',
        type: 'textarea',
        helpText: 'Key moments when new forms of magic were discovered, understood, or unlocked.',
      },
      {
        name: 'magitech_revolutions',
        label: 'Magitech Revolutions',
        type: 'textarea',
        helpText: 'Periods when the fusion of magic and technology transformed society—equivalent to industrial revolutions.',
      },
      {
        name: 'magical_wars',
        label: 'Magical Wars',
        type: 'textarea',
        helpText: 'Conflicts fought primarily with or over magic—mage wars, resource wars over mana deposits, spell arms races.',
      },
      {
        name: 'rise_fall_magical_empires',
        label: 'Rise & Fall of Magical Empires',
        type: 'textarea',
        helpText: 'Civilizations whose power was built on magic and how they rose, peaked, and declined.',
      },
      {
        name: 'legendary_practitioners',
        label: 'Legendary Practitioners',
        type: 'textarea',
        helpText: 'Historical figures whose magical achievements or failures shaped the course of history.',
      },
      {
        name: 'magical_artifacts_historical',
        label: 'Historical Magical Artifacts',
        type: 'textarea',
        helpText: 'Legendary magical items whose creation, use, or loss was historically significant.',
      },
      {
        name: 'magical_plagues',
        label: 'Magical Plagues',
        type: 'textarea',
        helpText: 'Magical diseases, curses, or corruptions that swept through populations or regions.',
      },
      {
        name: 'periods_of_magical_suppression',
        label: 'Periods of Magical Suppression',
        type: 'textarea',
        helpText: 'Eras when magic was banned, persecuted, or deliberately forgotten—and why.',
      },
      {
        name: 'lost_magical_knowledge',
        label: 'Lost Magical Knowledge',
        type: 'textarea',
        helpText: 'Magical arts, spells, or techniques that were once known but have been lost to time.',
      },
      {
        name: 'prophecies',
        label: 'Prophecies',
        type: 'textarea',
        helpText: 'Prophecies, divinations, or magical foretellings that have influenced historical decisions.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the significance of this historical event.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'What was the most devastating magical cataclysm in your world\'s history, and how did survivors rebuild in its aftermath?',
      'Has magic been lost and rediscovered over the course of history? What caused the loss, and was the rediscovered magic the same as what came before?',
      'How have prophecies shaped history? Have rulers gone to war, built empires, or destroyed knowledge because of what seers foretold?',
    ],
  },
  defaultSortField: 'year_in_world',
};
