import type { DomainConfig } from '../types/domains.js';

export const historyConfig: DomainConfig = {
  id: 'history',
  name: 'Historical Event',
  namePlural: 'History',
  icon: 'scroll',
  color: '#95a5a6',
  description: 'Chronicle the major events, eras, and turning points that have shaped your world. From wars and discoveries to disasters and cultural revolutions, history provides the narrative backbone that connects all other domains across time.',
  tableName: 'historical_events',
  category: 'meta',
  fields: [
    {
      name: 'era_id',
      label: 'Era',
      type: 'text',
      placeholder: 'ID of the historical era this event belongs to',
      helpText: 'The broader era or age in which this event took place.',
    },
    {
      name: 'year_in_world',
      label: 'Year (In-World)',
      type: 'text',
      placeholder: 'e.g. 3rd Age, Year 1247; 500 BF (Before Founding)',
      helpText: 'The date or year of this event in your world\'s calendar system.',
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g. 3 days, 30 years, instantaneous',
      helpText: 'How long the event lasted—from a single moment to centuries-long processes.',
    },
    {
      name: 'event_type',
      label: 'Event Type',
      type: 'select',
      required: true,
      options: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural', 'political', 'magical', 'technological', 'economic'],
      helpText: 'The primary category of this historical event.',
    },
    {
      name: 'participants',
      label: 'Participants',
      type: 'json',
      placeholder: '["Kingdom of Aldara", "the Dragon Lords", "Archmage Velen"]',
      helpText: 'Key civilizations, factions, or individuals involved in this event.',
    },
    {
      name: 'consequences',
      label: 'Consequences',
      type: 'json',
      placeholder: '["fall of the old empire", "discovery of mithril", "planar seal broken"]',
      helpText: 'The major outcomes and lasting effects of this event.',
    },
    {
      name: 'reliability',
      label: 'Reliability',
      type: 'select',
      options: ['mythological', 'legendary', 'oral_tradition', 'partially_documented', 'well_documented', 'verified'],
      helpText: 'How trustworthy the historical record is for this event — from pure myth to verified fact.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'select',
      options: ['local', 'regional', 'continental', 'global', 'planar', 'cosmic'],
      helpText: 'How geographically widespread this event\'s impact was.',
    },
    {
      name: 'significance',
      label: 'Significance',
      type: 'select',
      options: ['minor', 'moderate', 'major', 'transformative', 'world_altering'],
      helpText: 'The overall historical importance and lasting impact of this event.',
    },
  ],
  elementTypes: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural_shift', 'political_event', 'magical_event', 'technological_breakthrough', 'economic_event'],
  prompts: [
    'What are the defining conflicts in your world\'s history? Were they fought over land, resources, ideology, or magical power?',
    'What event do all cultures in your world agree was the most important, and how do their interpretations of it differ?',
    'What knowledge or capability has been lost to history? Are there dark ages that people are still recovering from?',
    'How reliable is the historical record? Who writes history, and what have they chosen to omit or distort?',
    'What is the most recent major event, and how are its consequences still unfolding in the present day?',
  ],
  magicPermeation: {
    companionTable: 'history_magic_aspects',
    fields: [
      {
        name: 'magical_cataclysms',
        label: 'Magical Cataclysms',
        type: 'textarea',
        helpText: 'Catastrophic magical events—mana explosions, ley line collapses, planar breaches that reshaped the world.',
      },
      {
        name: 'magic_discovery_milestones',
        label: 'Magic Discovery Milestones',
        type: 'textarea',
        helpText: 'Key moments when new forms of magic were discovered, understood, or unlocked.',
      },
      {
        name: 'magitech_revolutions',
        label: 'Magitech Revolutions',
        type: 'textarea',
        helpText: 'Periods when the fusion of magic and technology transformed society—equivalent to industrial revolutions.',
      },
      {
        name: 'magical_wars',
        label: 'Magical Wars',
        type: 'textarea',
        helpText: 'Conflicts fought primarily with or over magic—mage wars, resource wars over mana deposits, spell arms races.',
      },
      {
        name: 'rise_fall_magical_empires',
        label: 'Rise & Fall of Magical Empires',
        type: 'textarea',
        helpText: 'Civilizations whose power was built on magic and how they rose, peaked, and declined.',
      },
      {
        name: 'legendary_practitioners',
        label: 'Legendary Practitioners',
        type: 'textarea',
        helpText: 'Historical figures whose magical achievements or failures shaped the course of history.',
      },
      {
        name: 'magical_artifacts_historical',
        label: 'Historical Magical Artifacts',
        type: 'textarea',
        helpText: 'Legendary magical items whose creation, use, or loss was historically significant.',
      },
      {
        name: 'magical_plagues',
        label: 'Magical Plagues',
        type: 'textarea',
        helpText: 'Magical diseases, curses, or corruptions that swept through populations or regions.',
      },
      {
        name: 'periods_of_magical_suppression',
        label: 'Periods of Magical Suppression',
        type: 'textarea',
        helpText: 'Eras when magic was banned, persecuted, or deliberately forgotten—and why.',
      },
      {
        name: 'lost_magical_knowledge',
        label: 'Lost Magical Knowledge',
        type: 'textarea',
        helpText: 'Magical arts, spells, or techniques that were once known but have been lost to time.',
      },
      {
        name: 'prophecies',
        label: 'Prophecies',
        type: 'textarea',
        helpText: 'Prophecies, divinations, or magical foretellings that have influenced historical decisions.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the significance of this historical event.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'What was the most devastating magical cataclysm in your world\'s history, and how did survivors rebuild in its aftermath?',
      'Has magic been lost and rediscovered over the course of history? What caused the loss, and was the rediscovered magic the same as what came before?',
      'How have prophecies shaped history? Have rulers gone to war, built empires, or destroyed knowledge because of what seers foretold?',
    ],
  },
  archetypes: [
    {
      id: 'great_war',
      name: 'Great War',
      description: 'A devastating conflict that reshapes borders, topples dynasties, and scars the land for generations.',
      element_type: 'war',
      summary: 'A continent-spanning conflict that redrew the map',
      detailed_notes: 'A conflict drawn from deep grievances — territorial disputes, succession crises, or ideological divides. Multiple civilizations are drawn in through alliances and opportunism. The war ends with a new political order, but the resentments smolder.',
      fields: {
        event_type: 'war',
        duration: 'Years to decades',
        reliability: 'well_documented',
        geographic_scope: 'continental',
        significance: 'transformative',
      },
    },
    {
      id: 'founding_of_nation',
      name: 'Founding of a Nation',
      description: 'The birth of a new civilization — through revolution, unification, or colonization of new lands.',
      element_type: 'founding',
      summary: 'The founding moment of a civilization',
      detailed_notes: 'A pivotal moment when scattered peoples coalesce into a recognized polity. The founding myth will be retold for millennia, growing grander with each generation. The founder-figures become legends, their flaws forgotten.',
      fields: {
        event_type: 'founding',
        duration: 'A single pivotal year or a decade of consolidation',
        reliability: 'partially_documented',
        geographic_scope: 'regional',
        significance: 'major',
      },
    },
    {
      id: 'natural_catastrophe',
      name: 'Natural Catastrophe',
      description: 'A cataclysmic natural event — eruption, flood, or impact — that devastates a region.',
      element_type: 'disaster',
      summary: 'A natural disaster that permanently altered the region',
      detailed_notes: 'The catastrophe strikes without warning or politics. A volcano buries cities in ash, a tsunami erases coastal civilizations, or a plague sweeps across trade routes. Survivors rebuild, but the cultural trauma endures in myth and architecture.',
      fields: {
        event_type: 'disaster',
        duration: 'Days to months (immediate), decades (recovery)',
        reliability: 'oral_tradition',
        geographic_scope: 'regional',
        significance: 'transformative',
      },
    },
    {
      id: 'age_of_discovery',
      name: 'Age of Discovery',
      description: 'An era of exploration and contact, when isolated civilizations first encounter each other.',
      element_type: 'discovery',
      summary: 'An age of exploration and first contact between distant civilizations',
      detailed_notes: 'Explorers venture beyond known maps, driven by trade, curiosity, or divine mandate. First contact between civilizations is rarely peaceful — disease, trade disputes, and cultural misunderstanding follow. But the exchange of ideas and goods transforms both sides.',
      fields: {
        event_type: 'discovery',
        duration: 'A generation or more',
        reliability: 'partially_documented',
        geographic_scope: 'global',
        significance: 'world_altering',
      },
    },
    {
      id: 'the_silence',
      name: 'The Silence',
      description: 'An event where all magic suddenly stopped working — every spell failed, every enchantment died, every magical creature collapsed.',
      element_type: 'magical_event',
      summary: 'The day magic died — and the long dark that followed',
      detailed_notes: 'Without warning, magic ceased. Wards fell. Flying cities crashed. Healing spells stopped mid-cast. Familiars went still. The event lasted anywhere from days to years depending on the account, and its cause remains the most debated question in history. When magic returned, it was... different. Changed. Some schools of magic never recovered.',
      fields: {
        event_type: 'magical',
        duration: 'Disputed — between three days and seven years, depending on the source',
        reliability: 'oral_tradition',
        geographic_scope: 'cosmic',
        significance: 'world_altering',
      },
    },
  ],
  defaultSortField: 'year_in_world',
};
