import type { DomainConfig } from '../types/domains.js';

export const historyConfig: DomainConfig = {
  id: 'history',
  name: 'Historical Event',
  namePlural: 'History',
  icon: 'scroll',
  color: '#95a5a6',
  description: 'Chronicle the major events, eras, and turning points that have shaped your world. From wars and discoveries to disasters and cultural revolutions, history provides the narrative backbone that connects all other domains across time.',
  tableName: 'historical_events',
  category: 'meta',
  fields: [
    {
      name: 'era_id',
      label: 'Era',
      type: 'text',
      placeholder: 'ID of the historical era this event belongs to',
      helpText: 'The broader era or age in which this event took place.',
    },
    {
      name: 'year_in_world',
      label: 'Year (In-World)',
      type: 'text',
      placeholder: 'e.g. 3rd Age, Year 1247; 500 BF (Before Founding)',
      helpText: 'The date or year of this event in your world\'s calendar system.',
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g. 3 days, 30 years, instantaneous',
      helpText: 'How long the event lasted—from a single moment to centuries-long processes.',
    },
    {
      name: 'event_type',
      label: 'Event Type',
      type: 'select',
      required: true,
      options: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural', 'political', 'magical', 'technological', 'economic'],
      helpText: 'The primary category of this historical event.',
    },
    {
      name: 'participants',
      label: 'Participants',
      type: 'json',
      placeholder: '["Kingdom of Aldara", "the Dragon Lords", "Archmage Velen"]',
      helpText: 'Key civilizations, factions, or individuals involved in this event.',
    },
    {
      name: 'consequences',
      label: 'Consequences',
      type: 'json',
      placeholder: '["fall of the old empire", "discovery of mithril", "planar seal broken"]',
      helpText: 'The major outcomes and lasting effects of this event.',
    },
    {
      name: 'reliability',
      label: 'Reliability',
      type: 'select',
      options: ['mythological', 'legendary', 'oral_tradition', 'partially_documented', 'well_documented', 'verified'],
      helpText: 'How trustworthy the historical record is for this event — from pure myth to verified fact.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'select',
      options: ['local', 'regional', 'continental', 'global', 'planar', 'cosmic'],
      helpText: 'How geographically widespread this event\'s impact was.',
    },
    {
      name: 'significance',
      label: 'Significance',
      type: 'select',
      options: ['minor', 'moderate', 'major', 'transformative', 'world_altering'],
      helpText: 'The overall historical importance and lasting impact of this event.',
    },
  ],
  elementTypes: ['war', 'discovery', 'founding', 'disaster', 'migration', 'cultural_shift', 'political_event', 'magical_event', 'technological_breakthrough', 'economic_event'],
  elementTypeDescriptions: {
    war: 'An armed conflict between civilizations, factions, or species. Reshapes borders, topples powers, and scars landscapes for generations.',
    discovery: 'A moment when something previously unknown is found or understood — new lands, scientific principles, magical techniques, or lost knowledge.',
    founding: 'The establishment of something new — a city, nation, order, or institution that will shape the future.',
    disaster: 'A catastrophic event — natural, magical, or artificial — that devastates a region, population, or way of life.',
    migration: 'A large-scale movement of people from one region to another, driven by opportunity, threat, or environmental change.',
    cultural_shift: 'A fundamental change in beliefs, values, or practices across a society — religious reformation, enlightenment, or social revolution.',
    political_event: 'A significant change in governance — coups, treaties, elections, successions, or diplomatic breakthroughs.',
    magical_event: 'A historically significant magical occurrence — a great working, catastrophic spell failure, or shift in the nature of magic itself.',
    technological_breakthrough: 'An invention or discovery that fundamentally changes what a civilization can do — new materials, techniques, or devices.',
    economic_event: 'A major economic shift — trade route discovery, resource depletion, market collapse, or the rise of a new industry.',
  },
  prompts: [
    'What are the defining conflicts in your world\'s history? Were they fought over land, resources, ideology, or magical power?',
    'What event do all cultures in your world agree was the most important, and how do their interpretations of it differ?',
    'What knowledge or capability has been lost to history? Are there dark ages that people are still recovering from?',
    'How reliable is the historical record? Who writes history, and what have they chosen to omit or distort?',
    'What is the most recent major event, and how are its consequences still unfolding in the present day?',
  ],
  magicPermeation: {
    companionTable: 'history_magic_aspects',
    fields: [
      {
        name: 'magical_cataclysms',
        label: 'Magical Cataclysms',
        type: 'textarea',
        helpText: 'Catastrophic magical events—mana explosions, ley line collapses, planar breaches that reshaped the world.',
      },
      {
        name: 'magic_discovery_milestones',
        label: 'Magic Discovery Milestones',
        type: 'textarea',
        helpText: 'Key moments when new forms of magic were discovered, understood, or unlocked.',
      },
      {
        name: 'magitech_revolutions',
        label: 'Magitech Revolutions',
        type: 'textarea',
        helpText: 'Periods when the fusion of magic and technology transformed society—equivalent to industrial revolutions.',
      },
      {
        name: 'magical_wars',
        label: 'Magical Wars',
        type: 'textarea',
        helpText: 'Conflicts fought primarily with or over magic—mage wars, resource wars over mana deposits, spell arms races.',
      },
      {
        name: 'rise_fall_magical_empires',
        label: 'Rise & Fall of Magical Empires',
        type: 'textarea',
        helpText: 'Civilizations whose power was built on magic and how they rose, peaked, and declined.',
      },
      {
        name: 'legendary_practitioners',
        label: 'Legendary Practitioners',
        type: 'textarea',
        helpText: 'Historical figures whose magical achievements or failures shaped the course of history.',
      },
      {
        name: 'magical_artifacts_historical',
        label: 'Historical Magical Artifacts',
        type: 'textarea',
        helpText: 'Legendary magical items whose creation, use, or loss was historically significant.',
      },
      {
        name: 'magical_plagues',
        label: 'Magical Plagues',
        type: 'textarea',
        helpText: 'Magical diseases, curses, or corruptions that swept through populations or regions.',
      },
      {
        name: 'periods_of_magical_suppression',
        label: 'Periods of Magical Suppression',
        type: 'textarea',
        helpText: 'Eras when magic was banned, persecuted, or deliberately forgotten—and why.',
      },
      {
        name: 'lost_magical_knowledge',
        label: 'Lost Magical Knowledge',
        type: 'textarea',
        helpText: 'Magical arts, spells, or techniques that were once known but have been lost to time.',
      },
      {
        name: 'prophecies',
        label: 'Prophecies',
        type: 'textarea',
        helpText: 'Prophecies, divinations, or magical foretellings that have influenced historical decisions.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to the significance of this historical event.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'passive',
    planeAware: true,
    prompts: [
      'What was the most devastating magical cataclysm in your world\'s history, and how did survivors rebuild in its aftermath?',
      'Has magic been lost and rediscovered over the course of history? What caused the loss, and was the rediscovered magic the same as what came before?',
      'How have prophecies shaped history? Have rulers gone to war, built empires, or destroyed knowledge because of what seers foretold?',
    ],
  },
  archetypes: [
    {
      id: 'great_war',
      name: 'Great War',
      description: 'A devastating conflict that reshapes borders, topples dynasties, and scars the land for generations.',
      element_type: 'war',
      summary: 'A continent-spanning conflict that redrew the map',
      detailed_notes: 'A conflict drawn from deep grievances — territorial disputes, succession crises, or ideological divides. Multiple civilizations are drawn in through alliances and opportunism. The war ends with a new political order, but the resentments smolder.',
      fields: {
        event_type: 'war',
        duration: 'Years to decades',
        reliability: 'well_documented',
        geographic_scope: 'continental',
        significance: 'transformative',
      },
    },
    {
      id: 'founding_of_nation',
      name: 'Founding of a Nation',
      description: 'The birth of a new civilization — through revolution, unification, or colonization of new lands.',
      element_type: 'founding',
      summary: 'The founding moment of a civilization',
      detailed_notes: 'A pivotal moment when scattered peoples coalesce into a recognized polity. The founding myth will be retold for millennia, growing grander with each generation. The founder-figures become legends, their flaws forgotten.',
      fields: {
        event_type: 'founding',
        duration: 'A single pivotal year or a decade of consolidation',
        reliability: 'partially_documented',
        geographic_scope: 'regional',
        significance: 'major',
      },
    },
    {
      id: 'natural_catastrophe',
      name: 'Natural Catastrophe',
      description: 'A cataclysmic natural event — eruption, flood, or impact — that devastates a region.',
      element_type: 'disaster',
      summary: 'A natural disaster that permanently altered the region',
      detailed_notes: 'The catastrophe strikes without warning or politics. A volcano buries cities in ash, a tsunami erases coastal civilizations, or a plague sweeps across trade routes. Survivors rebuild, but the cultural trauma endures in myth and architecture.',
      fields: {
        event_type: 'disaster',
        duration: 'Days to months (immediate), decades (recovery)',
        reliability: 'oral_tradition',
        geographic_scope: 'regional',
        significance: 'transformative',
      },
    },
    {
      id: 'age_of_discovery',
      name: 'Age of Discovery',
      description: 'An era of exploration and contact, when isolated civilizations first encounter each other.',
      element_type: 'discovery',
      summary: 'An age of exploration and first contact between distant civilizations',
      detailed_notes: 'Explorers venture beyond known maps, driven by trade, curiosity, or divine mandate. First contact between civilizations is rarely peaceful — disease, trade disputes, and cultural misunderstanding follow. But the exchange of ideas and goods transforms both sides.',
      fields: {
        event_type: 'discovery',
        duration: 'A generation or more',
        reliability: 'partially_documented',
        geographic_scope: 'global',
        significance: 'world_altering',
      },
    },
    {
      id: 'the_silence',
      name: 'The Silence',
      description: 'An event where all magic suddenly stopped working — every spell failed, every enchantment died, every magical creature collapsed.',
      element_type: 'magical_event',
      summary: 'The day magic died — and the long dark that followed',
      detailed_notes: 'Without warning, magic ceased. Wards fell. Flying cities crashed. Healing spells stopped mid-cast. Familiars went still. The event lasted anywhere from days to years depending on the account, and its cause remains the most debated question in history. When magic returned, it was... different. Changed. Some schools of magic never recovered.',
      fields: {
        event_type: 'magical',
        duration: 'Disputed — between three days and seven years, depending on the source',
        reliability: 'oral_tradition',
        geographic_scope: 'cosmic',
        significance: 'world_altering',
      },
    },
    {
      id: 'the_sundering',
      name: 'The Sundering',
      description: 'A cataclysmic event that broke the world. Continents split, magic changed its nature, civilizations fell in a single day.',
      element_type: 'disaster',
      summary: 'The day the world broke apart — continents shattered, magic transformed, and the old order ended',
      detailed_notes: 'The Sundering was not a war or a natural disaster — it was a fundamental rupture in the fabric of reality. In a single cataclysmic day, the world\'s geography was violently rewritten. Continents cracked apart along lines that may have followed ley line faults. The seas rushed into new chasms. Mountain ranges rose where plains had been. Entire civilizations — their cities, their histories, their peoples — were swallowed by the earth or drowned by new oceans. Magic itself changed: spells that had worked for millennia failed, while new forms of magic emerged from the raw energy released by the breaking. Every culture that survived has a version of the story, and none of them agree on the cause.',
      fields: {
        event_type: 'disaster',
        duration: 'The event itself lasted a single day. The aftershocks — geological, magical, and civilizational — continued for centuries.',
        reliability: 'legendary',
        geographic_scope: 'global',
        significance: 'world_altering',
        participants: '["Every civilization that existed at the time — most did not survive"]',
        consequences: '["Continental geography rewritten", "Pre-Sundering magic lost", "New forms of magic emerged", "Population reduced by an estimated 90%", "All political structures collapsed", "New civilizations built on the ruins"]',
      },
    },
    {
      id: 'first_contact_event',
      name: 'First Contact',
      description: 'The moment two completely isolated civilizations discovered each other\'s existence. Changed everything for both.',
      element_type: 'discovery',
      summary: 'The meeting of two worlds that had never known the other existed',
      detailed_notes: 'First contact is the hinge-point between isolation and interconnection. Two civilizations, each convinced they were alone in the world — or at least in their corner of it — suddenly confront the reality of the other. The initial encounter is almost never peaceful, not from hostility but from sheer incomprehension. Language barriers, incompatible magic systems, different relationships with the divine, and conflicting claims to the same resources create friction that takes generations to resolve. But the exchange that follows — of ideas, technologies, magical traditions, and genetic diversity — transforms both cultures beyond recognition. Neither side remains what it was.',
      fields: {
        event_type: 'discovery',
        duration: 'The initial encounter is a single moment, but the consequences unfold over generations',
        reliability: 'partially_documented',
        geographic_scope: 'continental',
        significance: 'transformative',
        participants: '["Two previously isolated civilizations"]',
        consequences: '["Exchange of magical traditions", "New trade routes established", "Cultural upheaval in both civilizations", "Disease exchange with devastating population effects", "Territorial disputes and eventual wars", "Hybrid cultures emerging in border regions"]',
      },
    },
    {
      id: 'forbidden_knowledge_event',
      name: 'The Forbidden Discovery',
      description: 'A discovery so dangerous that all nations agreed to suppress it. The knowledge persists in whispers.',
      element_type: 'discovery',
      summary: 'A discovery so terrible that every nation agreed it must be forgotten — but knowledge is hard to kill',
      detailed_notes: 'Some knowledge is too dangerous to possess. The Forbidden Discovery — its true nature varies by world, but it is always something that could end civilization if widely known — was made by a researcher, explorer, or mage who immediately recognized its destructive potential. In a rare moment of international cooperation, rival nations agreed to suppress the discovery: records were burned, researchers were silenced (by oath, by magic, or by execution), and the very existence of the knowledge was denied. But suppression is never complete. Fragments survive in coded texts, oral traditions among secret societies, and the independent rediscovery by brilliant minds who stumble onto the same path. The tension between those who guard the secret and those who seek it drives conspiracies, inquisitions, and shadow wars across generations.',
      fields: {
        event_type: 'discovery',
        duration: 'The discovery itself was instantaneous. The suppression campaign lasted decades. The secret has persisted for centuries.',
        reliability: 'oral_tradition',
        geographic_scope: 'global',
        significance: 'world_altering',
        participants: '["The original discoverer (identity disputed or erased)", "A coalition of nations that agreed to suppress", "Secret societies that preserved fragments", "Inquisitorial orders tasked with enforcing the ban"]',
        consequences: '["International suppression treaty — one of the few agreements all nations honor", "Creation of inquisitorial orders to hunt forbidden knowledge", "Underground networks preserving and trading fragments", "Periodic rediscoveries triggering crises", "A culture of academic censorship and self-censorship that persists to this day"]',
      },
    },
    {
      id: 'the_silence',
      name: 'The Silence',
      description: 'An era when all magic stopped. Devastating consequences for magic-dependent civilizations.',
      element_type: 'magical_event',
      summary: 'A period when all magic ceased to function — the lights went out and stayed out',
      detailed_notes: 'The Silence was not a gradual decline but a sudden, total cessation. One moment magic worked; the next, it did not. Enchantments failed. Wards collapsed. Flying cities fell from the sky. Magical creatures sickened and died. Entire civilizations built on magical infrastructure — their lighting, heating, agriculture, transportation, and governance all dependent on mana — collapsed within weeks. The non-magical world adapted more easily, but even they suffered as trade networks, communication systems, and military balances built around magic dissolved overnight. The cause of the Silence remains the most debated question in history: divine punishment, a natural mana cycle reaching its nadir, a deliberate act of sabotage by an unknown agent, or simply a failure mode that no one anticipated. When magic returned, it was subtly different — some schools stronger, others weaker, and a few entirely new.',
      fields: {
        event_type: 'magical',
        duration: 'Disputed — estimates range from three months to seven years depending on the source and region',
        reliability: 'oral_tradition',
        geographic_scope: 'cosmic',
        significance: 'world_altering',
        participants: '["Every magic-dependent civilization", "Non-magical societies that inherited the power vacuum", "Unknown cause or agent"]',
        consequences: '["Collapse of magic-dependent civilizations", "Rise of non-magical powers", "Permanent loss of several schools of magic", "Development of non-magical backup systems", "Profound cultural trauma and anti-magic sentiment in some regions", "New forms of magic emerged when the Silence ended"]',
      },
    },
    {
      id: 'golden_age',
      name: 'The Golden Age',
      description: 'Unprecedented peace and prosperity, now lost and romanticized.',
      element_type: 'cultural_shift',
      summary: 'An era of unmatched peace, prosperity, and achievement — now lost and endlessly mourned',
      detailed_notes: 'Every civilization has its Golden Age — a period of unprecedented peace, prosperity, cultural flowering, and technological or magical advancement. The Golden Age is always in the past, always romanticized, and always more complex than the stories suggest. The peace was maintained by a balance of power that could not last. The prosperity was unevenly distributed. The cultural achievements were real but built on labor and sacrifice that the nostalgic narratives omit. Nevertheless, the Golden Age represents a genuine peak in civilizational achievement: great works of art, architecture, and scholarship were produced; populations grew and thrived; and the major powers cooperated more than they competed. Its end — through war, disaster, internal decay, or simple exhaustion — defines the trajectory of everything that follows. Every subsequent generation measures itself against the Golden Age and finds itself wanting.',
      fields: {
        event_type: 'cultural',
        duration: 'One to three centuries — long enough to seem eternal to those living in it, short enough to be recognizable as an era in retrospect',
        reliability: 'partially_documented',
        geographic_scope: 'continental',
        significance: 'transformative',
        participants: '["The dominant civilizations of the period", "Artists, scholars, and builders whose works define the era", "The underclasses whose labor supported the golden age (often omitted from accounts)"]',
        consequences: '["A cultural benchmark against which all subsequent eras are measured", "Monumental works of art, architecture, and literature that survive", "A nostalgia that shapes politics for centuries after", "The seeds of the era\'s own destruction, planted during its peak"]',
      },
    },
    {
      id: 'the_awakening',
      name: 'The Awakening',
      description: 'The moment a world\'s population collectively gained magical ability.',
      element_type: 'magical_event',
      summary: 'The day everyone became a mage — and the world was never the same',
      detailed_notes: 'The Awakening was the moment when magical ability, previously limited to a rare few, suddenly manifested in every sentient being simultaneously. A farmer discovered he could ignite fires with a thought. A child levitated in her cradle. A king found his court wizard was no longer special. The immediate aftermath was chaos: untrained magic users caused devastating accidental damage, power structures built on magical exclusivity collapsed overnight, and the sheer volume of ambient mana being channeled by billions of new practitioners destabilized ley lines and planar boundaries. Over the following decades, society completely restructured around universal magical ability. Education systems were overhauled. Legal frameworks were rewritten. Economic systems adapted to a world where anyone could enchant, heal, or destroy. The Awakening is the single most transformative event in recorded history — the moment when magic ceased to be a privilege and became a fact of life.',
      fields: {
        event_type: 'magical',
        duration: 'The Awakening itself was instantaneous. The social transformation it triggered continues for generations.',
        reliability: 'well_documented',
        geographic_scope: 'global',
        significance: 'world_altering',
        participants: '["Every sentient being alive at the moment of Awakening", "Former magical elites who lost their monopoly", "Governments scrambling to adapt", "New institutions created to manage universal magic"]',
        consequences: '["Universal magical ability across all sentient species", "Collapse of magical aristocracies and exclusivity", "Mass casualties from untrained magical accidents", "Complete restructuring of education, law, and economy", "Destabilization of ley lines and planar boundaries from massive mana draw", "Emergence of new social hierarchies based on magical talent rather than magical access"]',
      },
    },
    {
      id: 'founding_nation',
      name: 'Founding of a Nation',
      description: 'The birth of a new civilization through revolution, unification, or colonization.',
      element_type: 'founding',
      summary: 'The pivotal moment when a new nation was born',
      detailed_notes: 'A founding event marks the moment scattered peoples, rebel factions, or colonial settlers coalesce into a recognized polity. The founding myth — whether revolution, divine mandate, or treaty — will be retold and embellished for millennia. The founder-figures become legends, their compromises forgotten and their flaws erased by grateful descendants.',
      fields: {
        event_type: 'founding',
        duration: 'A single pivotal year or a decade of consolidation',
        reliability: 'partially_documented',
        geographic_scope: 'regional',
        significance: 'major',
      },
    },
  ],
  defaultSortField: 'year_in_world',
};
