import type { DomainConfig } from '../types/domains.js';

export const hydrologyConfig: DomainConfig = {
  id: 'hydrology',
  name: 'Hydrology',
  namePlural: 'Water Bodies',
  icon: 'droplet',
  color: '#4a9eff',
  description: 'Map the oceans, rivers, lakes, glaciers, and aquifers of your world. Water shapes civilizations, trade routes, and ecosystems in fundamental ways.',
  tableName: 'water_bodies',
  category: 'natural',
  fields: [
    {
      name: 'water_type',
      label: 'Water Type',
      type: 'select',
      required: true,
      options: ['ocean', 'sea', 'lake', 'river', 'glacier', 'aquifer', 'swamp', 'hot_spring', 'estuary', 'geyser', 'spring', 'reef'],
      helpText: 'The classification of this water body.',
    },
    {
      name: 'volume',
      label: 'Volume',
      type: 'text',
      placeholder: 'e.g. 1.335 billion km³',
      helpText: 'Approximate volume of water contained.',
    },
    {
      name: 'salinity',
      label: 'Salinity',
      type: 'text',
      placeholder: 'e.g. 35 ppt (parts per thousand)',
      helpText: 'Salt concentration—fresh, brackish, or salt water.',
    },
    {
      name: 'depth_max',
      label: 'Maximum Depth',
      type: 'number',
      placeholder: 'Meters',
      helpText: 'The deepest point of this water body in meters.',
    },
    {
      name: 'flow_direction',
      label: 'Flow Direction',
      type: 'text',
      placeholder: 'e.g. North to South, circular current',
      helpText: 'Primary direction of flow or current patterns.',
    },
    {
      name: 'temperature_range',
      label: 'Temperature Range',
      type: 'text',
      placeholder: 'e.g. 2°C - 28°C',
      helpText: 'Typical water temperature range across seasons.',
    },
    {
      name: 'water_quality',
      label: 'Water Quality',
      type: 'textarea',
      placeholder: 'Describe clarity, purity, drinkability, pollutants...',
      helpText: 'The quality, clarity, and potability of the water — important for ecosystems and settlements.',
    },
    {
      name: 'connected_to',
      label: 'Connected Water Bodies',
      type: 'json',
      placeholder: '["River Aelith", "Sea of Storms"]',
      helpText: 'Other water bodies this one flows into or connects with.',
    },
  ],
  elementTypes: ['ocean', 'sea', 'lake', 'river', 'glacier', 'aquifer', 'swamp', 'hot_spring', 'waterfall'],
  prompts: [
    'How does the water cycle work in your world? Are there unusual sources of precipitation or evaporation?',
    'What role do rivers and oceans play in trade, travel, and the spread of civilizations?',
    'Are there bodies of water with unusual properties—colors, densities, or behaviors unlike our world?',
    'How do underground aquifers and water tables affect where settlements can thrive?',
    'What creatures or hazards lurk in the deep waters? Are there unexplored ocean trenches or subterranean rivers?',
  ],
  magicPermeation: {
    companionTable: 'hydrology_magic_aspects',
    fields: [
      {
        name: 'enchanted_waters',
        label: 'Enchanted Waters',
        type: 'textarea',
        helpText: 'Waters with inherent magical properties—healing springs, cursed lakes, etc.',
      },
      {
        name: 'mana_springs',
        label: 'Mana Springs',
        type: 'textarea',
        helpText: 'Natural upwellings where mana dissolves into or emerges from water.',
      },
      {
        name: 'magical_currents',
        label: 'Magical Currents',
        type: 'textarea',
        helpText: 'Currents that carry magical energy, creating paths of power through waterways.',
      },
      {
        name: 'water_mana_conductivity',
        label: 'Water-Mana Conductivity',
        type: 'textarea',
        helpText: 'How well this water conducts, stores, or resists magical energy.',
      },
      {
        name: 'tidal_magic_effects',
        label: 'Tidal Magic Effects',
        type: 'textarea',
        helpText: 'How tides (influenced by moons, celestial bodies) affect local magic levels.',
      },
      {
        name: 'deep_water_magic',
        label: 'Deep Water Magic',
        type: 'textarea',
        helpText: 'Magical phenomena in the deepest parts of this water body.',
      },
      {
        name: 'purification_corruption',
        label: 'Purification & Corruption',
        type: 'textarea',
        helpText: 'How magic purifies or corrupts the water, and the effects downstream.',
      },
      {
        name: 'water_elemental_connection',
        label: 'Water Elemental Connection',
        type: 'textarea',
        helpText: 'Relationship to water elementals, spirits, or planar water realms.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this water body.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: false,
    prompts: [
      'Does water conduct or store magical energy? Can mana dissolve into water like minerals do?',
      'Are there sacred or cursed springs whose waters grant boons or afflictions to those who drink?',
      'How do ocean tides, driven by magical moons, create surges or dead zones of magical power along coastlines?',
    ],
  },
  defaultSortField: 'water_type',
};
