import type { DomainConfig } from '../types/domains.js';

export const hydrologyConfig: DomainConfig = {
  id: 'hydrology',
  name: 'Hydrology',
  namePlural: 'Water Bodies',
  icon: 'droplet',
  color: '#4a9eff',
  description: 'Map the oceans, rivers, lakes, glaciers, and aquifers of your world. Water shapes civilizations, trade routes, and ecosystems in fundamental ways.',
  tableName: 'water_bodies',
  category: 'natural',
  fields: [
    {
      name: 'water_type',
      label: 'Water Type',
      type: 'select',
      required: true,
      options: ['ocean', 'sea', 'lake', 'river', 'glacier', 'aquifer', 'swamp', 'hot_spring', 'estuary', 'geyser', 'spring', 'reef'],
      helpText: 'The classification of this water body.',
    },
    {
      name: 'volume',
      label: 'Volume',
      type: 'text',
      placeholder: 'e.g. 1.335 billion km³',
      helpText: 'Approximate volume of water contained.',
    },
    {
      name: 'salinity',
      label: 'Salinity',
      type: 'text',
      placeholder: 'e.g. 35 ppt (parts per thousand)',
      helpText: 'Salt concentration—fresh, brackish, or salt water.',
    },
    {
      name: 'depth_max',
      label: 'Maximum Depth',
      type: 'number',
      placeholder: 'Meters',
      helpText: 'The deepest point of this water body in meters.',
    },
    {
      name: 'flow_direction',
      label: 'Flow Direction',
      type: 'text',
      placeholder: 'e.g. North to South, circular current',
      helpText: 'Primary direction of flow or current patterns.',
    },
    {
      name: 'temperature_range',
      label: 'Temperature Range',
      type: 'text',
      placeholder: 'e.g. 2°C - 28°C',
      helpText: 'Typical water temperature range across seasons.',
    },
    {
      name: 'water_quality',
      label: 'Water Quality',
      type: 'textarea',
      placeholder: 'Describe clarity, purity, drinkability, pollutants...',
      helpText: 'The quality, clarity, and potability of the water — important for ecosystems and settlements.',
    },
    {
      name: 'connected_to',
      label: 'Connected Water Bodies',
      type: 'json',
      placeholder: '["River Aelith", "Sea of Storms"]',
      helpText: 'Other water bodies this one flows into or connects with.',
    },
  ],
  elementTypes: ['ocean', 'sea', 'lake', 'river', 'glacier', 'aquifer', 'swamp', 'hot_spring', 'waterfall'],
  elementTypeDescriptions: {
    ocean: 'A vast body of saltwater covering a major portion of a world\'s surface. Drives climate, enables trade, and harbors deep mysteries.',
    sea: 'A smaller body of saltwater, often partially enclosed by land. More navigable than oceans, and central to coastal civilizations.',
    lake: 'A body of standing water surrounded by land, fed by rivers, rain, or underground springs. Fresh or salt, shallow or abyssal.',
    river: 'A flowing body of freshwater following gravity from high ground to a larger body of water. The lifeline of civilizations.',
    glacier: 'A massive, slow-moving body of compressed ice. Carves landscapes over millennia and stores vast quantities of freshwater.',
    aquifer: 'An underground layer of rock or sediment that holds and transmits groundwater. The hidden water supply beneath the surface.',
    swamp: 'A wetland with standing water and dense vegetation. Rich in biodiversity, difficult to traverse, and often culturally feared.',
    hot_spring: 'A geothermally heated pool of water rising from underground. Often mineral-rich, sacred, or home to extremophile life.',
    waterfall: 'A point where a river drops vertically over a rock formation. Landmarks of beauty, power, and often spiritual significance.',
  },
  prompts: [
    'How does the water cycle work in your world? Are there unusual sources of precipitation or evaporation?',
    'What role do rivers and oceans play in trade, travel, and the spread of civilizations?',
    'Are there bodies of water with unusual properties—colors, densities, or behaviors unlike our world?',
    'How do underground aquifers and water tables affect where settlements can thrive?',
    'What creatures or hazards lurk in the deep waters? Are there unexplored ocean trenches or subterranean rivers?',
  ],
  magicPermeation: {
    companionTable: 'hydrology_magic_aspects',
    fields: [
      {
        name: 'enchanted_waters',
        label: 'Enchanted Waters',
        type: 'textarea',
        helpText: 'Waters with inherent magical properties—healing springs, cursed lakes, etc.',
      },
      {
        name: 'mana_springs',
        label: 'Mana Springs',
        type: 'textarea',
        helpText: 'Natural upwellings where mana dissolves into or emerges from water.',
      },
      {
        name: 'magical_currents',
        label: 'Magical Currents',
        type: 'textarea',
        helpText: 'Currents that carry magical energy, creating paths of power through waterways.',
      },
      {
        name: 'water_mana_conductivity',
        label: 'Water-Mana Conductivity',
        type: 'textarea',
        helpText: 'How well this water conducts, stores, or resists magical energy.',
      },
      {
        name: 'tidal_magic_effects',
        label: 'Tidal Magic Effects',
        type: 'textarea',
        helpText: 'How tides (influenced by moons, celestial bodies) affect local magic levels.',
      },
      {
        name: 'deep_water_magic',
        label: 'Deep Water Magic',
        type: 'textarea',
        helpText: 'Magical phenomena in the deepest parts of this water body.',
      },
      {
        name: 'purification_corruption',
        label: 'Purification & Corruption',
        type: 'textarea',
        helpText: 'How magic purifies or corrupts the water, and the effects downstream.',
      },
      {
        name: 'water_elemental_connection',
        label: 'Water Elemental Connection',
        type: 'textarea',
        helpText: 'Relationship to water elementals, spirits, or planar water realms.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this water body.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'reactive',
    planeAware: false,
    prompts: [
      'Does water conduct or store magical energy? Can mana dissolve into water like minerals do?',
      'Are there sacred or cursed springs whose waters grant boons or afflictions to those who drink?',
      'How do ocean tides, driven by magical moons, create surges or dead zones of magical power along coastlines?',
    ],
  },
  archetypes: [
    {
      id: 'major_ocean',
      name: 'Major Ocean',
      description: "A vast body of saltwater covering a significant portion of the world's surface.",
      element_type: 'ocean',
      summary: 'A vast ocean teeming with marine life and shaping global weather patterns',
      fields: {
        water_type: 'ocean',
        salinity: '~35 parts per thousand',
        depth_max: 11000,
        temperature_range: '-2°C to 30°C depending on depth and latitude',
        water_quality: 'Generally clean open waters with diverse marine ecosystems. Coastal areas vary with proximity to settlements and river outflows.',
      },
    },
    {
      id: 'great_river',
      name: 'Great River',
      description: 'A major river system that drains a large watershed and serves as a lifeline for civilizations.',
      element_type: 'river',
      summary: 'A mighty river flowing from highland sources to the sea',
      fields: {
        water_type: 'river',
        depth_max: 60,
        temperature_range: '4°C to 28°C seasonally',
        water_quality: 'Clear headwaters becoming increasingly silty downstream. Fertile floodplains along the lower reaches support dense agriculture.',
      },
    },
    {
      id: 'alpine_lake',
      name: 'Alpine Lake',
      description: 'A deep, cold, crystal-clear lake fed by mountain snowmelt and glacial runoff.',
      element_type: 'lake',
      summary: 'A deep mountain lake fed by glacial meltwater',
      fields: {
        water_type: 'lake',
        salinity: 'Freshwater',
        depth_max: 300,
        temperature_range: '2°C to 15°C',
        water_quality: 'Exceptionally clear due to low nutrient content and cold temperatures. Oligotrophic waters support specialized cold-adapted species.',
      },
    },
    {
      id: 'coastal_wetlands',
      name: 'Coastal Wetlands',
      description: 'A tidal marshland where freshwater rivers meet the sea, rich with life.',
      element_type: 'swamp',
      summary: 'Tidal wetlands teeming with birds, fish, and shellfish',
      fields: {
        water_type: 'estuary',
        salinity: 'Brackish, varying with tides (5-25 ppt)',
        depth_max: 3,
        temperature_range: '10°C to 30°C seasonally',
        water_quality: 'Nutrient-rich waters support dense vegetation and serve as critical nursery habitat for marine species. Natural water filtration.',
      },
    },
    {
      id: 'memory_river',
      name: 'Memory River',
      description: 'A river whose waters carry dissolved memories — drink from it and experience fragments of the past.',
      element_type: 'river',
      summary: 'A river saturated with the memories of everything that has lived along its banks',
      fields: {
        water_type: 'river',
        depth_max: 15,
        temperature_range: 'Unnaturally constant at 18°C regardless of season',
        water_quality: 'Crystal clear but faintly luminescent at night. Fish in the river display uncanny intelligence. Settlements along its banks report shared dreams and déjà vu. Long-term exposure causes difficulty distinguishing personal memories from absorbed ones.',
      },
    },
    {
      id: 'underground_ocean',
      name: 'Underground Ocean',
      description: 'A vast body of water in a subterranean cavern, with its own tides, currents, and blind ecosystems.',
      element_type: 'ocean',
      summary: 'A hidden ocean beneath the earth, vast enough to have its own weather and tides',
      detailed_notes: 'Miles below the surface, past layers of rock and the roots of mountains, lies an ocean no smaller than the seas above. Its cavern ceiling is so high it vanishes into darkness, and its far shores have never been mapped. The water is warmed from below by geothermal vents, creating a habitable if lightless environment. Bioluminescent organisms provide the only illumination — ghostly blue and green glows that shift with the currents. The ocean has its own tidal system, driven not by moons but by the rhythmic expansion and contraction of the cavern itself as tectonic pressures shift. Blind leviathans patrol the deep, navigating by echolocation and pressure sense. Surface civilizations who have discovered access points treat them as closely guarded secrets, for the underground ocean connects distant continents through subterranean channels.',
      fields: {
        water_type: 'ocean',
        salinity: '28 ppt — less salty than surface oceans due to constant freshwater seepage through rock',
        depth_max: 8000,
        temperature_range: '4°C in open water to 90°C near geothermal vents',
        water_quality: 'Mineral-rich and slightly acidic from dissolved limestone. Clear in open water but clouded near vent fields by mineral precipitation. Undrinkable without treatment due to heavy mineral content, but supports a thriving chemosynthetic food chain.',
      },
    },
    {
      id: 'blood_sea',
      name: 'Blood Tide Sea',
      description: 'A sea with red water from dissolved minerals, iron-rich algae, or ancient magical contamination.',
      element_type: 'sea',
      summary: 'A crimson sea whose waters run red from iron, algae, and ancient sorcery',
      detailed_notes: 'The Blood Tide Sea is named for its unsettling color — a deep, opaque red that ranges from arterial scarlet near the coast to dark maroon in the deep. The color comes from a convergence of factors: iron-rich mineral runoff from surrounding red sandstone cliffs, a dominant species of crimson algae that thrives in the iron-saturated water, and — according to local tradition — the residual taint of a magical war fought over its waters millennia ago. The sea stains anything it touches: ships return to port with red-streaked hulls, fishermen\'s nets are permanently dyed, and coastal settlements have a distinctive rust-colored tideline. Despite its alarming appearance, the sea supports a rich ecosystem. The iron content promotes explosive algal growth, which feeds dense schools of fish. However, periodic algal blooms create hypoxic dead zones, and the tides themselves sometimes carry a faint metallic scent that unsettles animals.',
      fields: {
        water_type: 'sea',
        salinity: '38 ppt — higher than average due to mineral concentration',
        depth_max: 2200,
        temperature_range: '12°C to 26°C, with warm iron-rich upwellings creating local hot spots',
        water_quality: 'Heavily colored but not toxic — the red tint is primarily biological and mineral. High iron content makes it unsuitable for drinking or irrigation without filtration. Fish caught here have reddish flesh and a faintly metallic taste prized in some cuisines and avoided in others.',
      },
    },
    {
      id: 'frozen_highway',
      name: 'Frozen River Highway',
      description: 'A permanently frozen river used as a road by civilizations — a highway of ice connecting distant settlements.',
      element_type: 'glacier',
      summary: 'A river frozen solid year-round, serving as the primary road between distant settlements',
      detailed_notes: 'The Frozen Highway is a river that has not flowed in living memory. Its surface is a smooth, durable sheet of ice thick enough to support caravan traffic, siege engines, and even permanent waystation structures built directly on the frozen surface. The river\'s original course carved a natural path through otherwise impassable mountain terrain, and when it froze — whether from climate shift, magical curse, or the death of whatever geothermal source once warmed it — the ice-road it left behind became the only viable route between the settlements on either end. The ice is not ordinary: it does not melt even in summer, and its surface regenerates from scratches and ruts over a period of weeks. Beneath the transparent upper layer, the dark shapes of the original river\'s fish can be seen, frozen mid-swim in water that turned to ice in an instant. Traders, armies, and pilgrims all share the highway, and a culture of ice-road etiquette has developed over centuries.',
      fields: {
        water_type: 'glacier',
        temperature_range: '-40°C to -15°C — the ice never approaches melting point',
        flow_direction: 'None — permanently frozen. Original flow was east to west through a mountain pass.',
        connected_to: '["Lake Vetharn (eastern terminus)", "The Shattered Delta (western terminus)", "Seven waystation settlements along the route"]',
      },
    },
    {
      id: 'time_pool',
      name: 'Time Pool',
      description: 'A body of water that shows visions of the past or future to those who gaze into it.',
      element_type: 'lake',
      summary: 'A sacred lake whose still surface reveals visions of other times to those who dare to look',
      detailed_notes: 'The Time Pool is a small, preternaturally still body of water nestled in a location of geological and magical significance — often a mountain hollow, a cave chamber, or the center of an ancient ruin. Its surface is mirror-smooth at all times, undisturbed by wind, rainfall, or even objects thrown into it (which sink without producing ripples). Those who gaze into the water see not their own reflection but scenes from the past or future — fragmented, non-linear, and often deeply personal. The visions are not controllable: seekers may see the death of a loved one, the fall of a kingdom, or a moment of no apparent significance that only becomes clear years later. Prolonged gazing is dangerous. Those who stare too long report difficulty distinguishing between present reality and temporal echoes, a condition called "time-sickness" that can become permanent. Cultures that know of Time Pools treat them with reverence and fear, posting guardians to prevent casual use.',
      fields: {
        water_type: 'lake',
        depth_max: 12,
        temperature_range: 'Constant 4°C regardless of season or ambient temperature',
        water_quality: 'Impossibly clear — the water appears to have no substance at all, as though the lake were a hole in reality. No organisms live in it. Chemical analysis returns contradictory results. It is not potable — those who drink it experience uncontrollable temporal visions for days.',
      },
    },
    {
      id: 'acid_lake',
      name: 'Acid Lake',
      description: 'A lake of corrosive liquid — natural defense and industrial resource.',
      element_type: 'lake',
      summary: 'A lake of highly corrosive acid that serves as both natural fortress and industrial resource',
      detailed_notes: 'The Acid Lake is a large body of corrosive liquid occupying a volcanic caldera. The acidity is extreme — approaching pH 0 in the deepest zones — the result of sustained volcanic outgassing of sulfuric and hydrochloric acids into groundwater that collects in the basin. The lake is visually striking: its surface is a vivid, unnatural green or yellow depending on mineral content and acid concentration, and steaming fumaroles along the shoreline add to the hellish atmosphere. Nothing conventional survives in the lake, though extremophile microorganisms thrive in the shallows and form colorful biofilms along the margins. Despite its hostility, the lake is economically valuable: acidic water is used industrially for ore processing, mineral extraction, and alchemical preparation. Settlements at a safe distance from the shore pump acid through ceramic channels, and the lake serves as a natural moat that makes the caldera nearly impregnable.',
      fields: {
        water_type: 'lake',
        salinity: 'Not applicable — dissolved sulfuric and hydrochloric acids at extreme concentration',
        depth_max: 180,
        temperature_range: '45°C to 95°C, heated by volcanic activity beneath the caldera',
        water_quality: 'Extremely corrosive, pH 0.5-2.0. Dissolves metal, bone, and organic matter within hours. Produces toxic fumes at the surface. Utterly undrinkable. The surrounding soil is bleached white by acid spray carried on the wind.',
      },
    },
    {
      id: 'tide_maze',
      name: 'Tide Maze',
      description: 'A coastal system where passages appear and vanish with the tide.',
      element_type: 'swamp',
      summary: 'A treacherous coastal labyrinth of channels that shift with every tide, trapping the unwary',
      detailed_notes: 'The Tide Maze is a vast coastal wetland where the interaction of extreme tidal ranges, shifting sandbars, and dense mangrove-like vegetation creates a labyrinth that reconfigures itself twice daily. At high tide, the maze is a network of navigable channels winding between islands of vegetation. At low tide, the water drains to reveal a trackless mudflat riddled with quicksand, exposed roots, and stranded marine life. The channels that were passable at high tide become impassable walls of mud and vegetation. Navigating the maze requires intimate knowledge of tidal timing and channel behavior that takes years to acquire — knowledge jealously guarded by local pilots who charge steep fees. Those who enter without a guide are frequently trapped by a turning tide: channels close behind them, new ones open in unfamiliar directions, and the rising water brings with it predators adapted to hunt in the confusion. The Tide Maze serves as a natural fortress for settlements built on the few permanent high-ground islands within it.',
      fields: {
        water_type: 'swamp',
        depth_max: 8,
        temperature_range: '15°C to 28°C, varying with tidal inflow',
        flow_direction: 'Reverses entirely with the tide — inward during flood, outward during ebb. Interior channels create chaotic eddies where opposing flows meet.',
      },
    },
  ],
  defaultSortField: 'water_type',
};
