import type { DomainConfig } from '../types/domains.js';

export const magicEcologyConfig: DomainConfig = {
  id: 'magic_ecology',
  name: 'Magic Ecology',
  namePlural: 'Magic Ecology',
  icon: 'sprout',
  color: '#2ecc71',
  description: 'Explore how magic functions as a natural force within ecosystems. Define mana cycles, magical mutations, enchanted food webs, and environments saturated with arcane energy. Magic ecology treats mana as a resource that flows, pools, and transforms just like water or sunlight.',
  tableName: 'mana_cycles',
  category: 'magic',
  fields: [
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type involved in this cycle',
      helpText: 'The specific type of magical energy that flows through this cycle.',
    },
    {
      name: 'stages',
      label: 'Cycle Stages',
      type: 'json',
      required: true,
      placeholder: '["generation", "dispersal", "absorption", "transformation", "release"]',
      helpText: 'The ordered stages through which mana flows in this ecological cycle.',
    },
    {
      name: 'cycle_duration',
      label: 'Cycle Duration',
      type: 'text',
      placeholder: 'e.g. 28 days (lunar), 1 year, centuries, irregular',
      helpText: 'How long one complete cycle takes from start to finish.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'select',
      options: ['local', 'regional', 'continental', 'global', 'planar', 'cosmic'],
      helpText: 'The spatial scale at which this cycle operates.',
    },
    {
      name: 'key_organisms',
      label: 'Key Organisms',
      type: 'textarea',
      placeholder: 'Species that play critical roles in this mana cycle...',
      helpText: 'Flora, fauna, or other organisms that are essential participants in this cycle.',
    },
    {
      name: 'key_geological_features',
      label: 'Key Geological Features',
      type: 'textarea',
      placeholder: 'Ley line nodes, mana springs, crystal formations...',
      helpText: 'Geographic or geological features that anchor or channel this cycle.',
    },
    {
      name: 'disruption_risks',
      label: 'Disruption Risks',
      type: 'textarea',
      placeholder: 'What could break this cycle? Over-harvesting, pollution, planar shifts...',
      helpText: 'Threats that could disrupt, weaken, or destroy this mana cycle.',
    },
    {
      name: 'historical_disruptions',
      label: 'Historical Disruptions',
      type: 'textarea',
      placeholder: 'Past events that disrupted this cycle and their consequences...',
      helpText: 'Known historical instances where this cycle was disrupted and what resulted.',
    },
    {
      name: 'mana_pollution',
      label: 'Mana Pollution',
      type: 'textarea',
      placeholder: 'Describe magical waste, contamination, toxic mana buildup...',
      helpText: 'How magical waste, byproducts, or contamination affects this cycle and the surrounding environment.',
    },
    {
      name: 'dead_zones',
      label: 'Dead Zones',
      type: 'textarea',
      placeholder: 'Describe mana-barren areas, causes, and effects on life...',
      helpText: 'Areas where mana has been depleted or blocked — their causes, boundaries, and impact on magical and mundane life.',
    },
  ],
  elementTypes: ['mana_cycle', 'mutation', 'magical_food_web', 'saturated_environment'],
  elementTypeDescriptions: {
    mana_cycle: 'The path mana follows through an ecosystem — how it\'s generated, consumed, recycled, and lost. The magical equivalent of a water or carbon cycle.',
    mutation: 'A magical alteration to a living organism — new abilities, changed anatomy, or corrupted biology caused by mana exposure.',
    magical_food_web: 'The network of mana transfer between organisms — who produces, consumes, and concentrates magical energy in an ecosystem.',
    saturated_environment: 'A region so infused with mana that the environment itself behaves magically — glowing soil, living weather, or reality distortions.',
  },
  prompts: [
    'How does mana flow through your world\'s ecosystems? Is it more like water (following gravity and channels) or like sunlight (radiating from sources)?',
    'What happens to an ecosystem when its mana cycle is disrupted? Do creatures mutate, die off, or adapt in unexpected ways?',
    'Are there keystone species in the magical ecosystem—organisms whose removal would cause cascading mana collapse?',
    'How do mana-saturated environments differ from normal ones? Are there magical equivalents of rainforests, deserts, or deep-sea vents?',
    'Can new mana cycles emerge naturally, or are they all ancient? Has civilization ever accidentally created one through magical pollution or infrastructure?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'atmospheric_mana_cycle',
      name: 'Atmospheric Mana Cycle',
      description: 'Mana evaporates, condenses in the upper atmosphere, and precipitates back as mana rain or dew.',
      element_type: 'mana_cycle',
      summary: 'A global cycle where mana rises, condenses, and rains back to the surface',
      fields: {
        cycle_duration: 'Seasonal — peaks during equinoxes, ebbs at solstices',
        geographic_scope: 'global',
        key_organisms: 'Mana-absorbing canopy trees draw ambient mana and release it through transpiration. High-altitude mana plankton seed condensation.',
        key_geological_features: 'Mountain ranges force mana-laden air upward, creating mana rain shadows. Ley line intersections act as mana springs.',
        disruption_risks: 'Deforestation breaks the transpiration cycle. Large-scale magical warfare can punch holes in the mana layer. Industrial mana extraction depletes ground reserves.',
      },
    },
    {
      id: 'geological_mana_cycle',
      name: 'Geological Mana Cycle',
      description: 'Mana wells up from deep within the earth through volcanic and tectonic processes.',
      element_type: 'mana_cycle',
      summary: "Mana rising from the planet's depths through faults and volcanic vents",
      fields: {
        cycle_duration: 'Geological — major pulses every few centuries, minor seepage continuous',
        geographic_scope: 'continental',
        key_organisms: 'Deep-root fungi network that transports mana from geological seeps to surface ecosystems. Mana worms that burrow along ley lines.',
        key_geological_features: 'Volcanic vents and hot springs as primary mana sources. Ley lines follow tectonic fault systems. Crystal caverns act as natural mana reservoirs.',
        disruption_risks: 'Over-mining of mana crystals depletes reservoirs. Tectonic shifts can redirect or seal ley lines. Volcanic eruptions release catastrophic mana surges.',
      },
    },
    {
      id: 'biological_mana_cycle',
      name: 'Biological Mana Cycle',
      description: 'Living organisms generate, store, and release mana through their life processes.',
      element_type: 'mana_cycle',
      summary: 'A living web where mana flows through food chains and decomposition',
      fields: {
        cycle_duration: 'Continuous, with generational accumulation',
        geographic_scope: 'regional',
        key_organisms: 'All living things participate — plants absorb ambient mana during growth, animals concentrate it through diet, decomposers release it back to the soil. Apex magical predators are the most mana-dense.',
        key_geological_features: 'Ancient burial grounds and fossil beds are mana-rich. Old-growth forests accumulate mana over centuries. Mass extinction sites create mana dead zones.',
        disruption_risks: 'Extinction of keystone magical species collapses the local mana web. Necromantic practices trap mana in undeath, removing it from the cycle. Overhunting magical fauna depletes concentrated reserves.',
      },
    },
    {
      id: 'necrotic_mana_cycle',
      name: 'Necrotic Mana Cycle',
      description: 'A mana cycle fueled by death itself — where dying releases more magical energy than living, creating perverse ecological incentives.',
      element_type: 'mana_cycle',
      summary: 'A dark cycle where death generates more mana than life, with disturbing consequences',
      fields: {
        cycle_duration: 'Continuous, with spikes during mass death events',
        geographic_scope: 'regional',
        key_organisms: 'Scavengers and decomposers are the primary mana producers — the more death they process, the more mana enters the system. Predators have evolved to kill more than they eat, wasting flesh but harvesting mana. Plants in these regions are carnivorous by default.',
        key_geological_features: 'Ancient battlefields and plague pits are permanent mana hotspots. Bone-rich soil layers act as slow-release mana sources. Graveyards in these regions must be warded or they spontaneously generate undead.',
        disruption_risks: 'Peace is ecologically destabilizing — extended periods without death cause mana famines. Civilizations in these regions face a horrifying incentive structure around warfare and sacrifice.',
        mana_pollution: 'Excess necrotic mana causes spontaneous undeath, ghostly manifestations, and a general miasma of despair. Long-term residents develop a tolerance that outsiders find deeply unsettling.',
      },
    },
    {
      id: 'mana_desert',
      name: 'Mana Dead Zone',
      description: 'A region completely drained of magical energy. No spells work, enchantments fail, magical creatures sicken and die.',
      element_type: 'saturated_environment',
      summary: 'A barren region where all magic has been stripped away, leaving a void',
      detailed_notes: 'Mana dead zones are ecological wastelands from a magical perspective. They form when mana is catastrophically over-extracted, drained by a magical disaster, or deliberately purged. Within the zone, no spell functions, no enchantment holds, and no magical creature can survive for long. Mundane life persists — ordinary plants and animals thrive in the absence of magical competition — but the boundary between the dead zone and the living magical world is sharp and dangerous. Creatures that depend on mana weaken as they approach and die if they cross in. For non-magical communities, dead zones offer a strange sanctuary from magical threats, but at the cost of total isolation from magical infrastructure.',
      fields: {
        cycle_duration: 'Persistent — dead zones can last centuries or millennia once established',
        geographic_scope: 'regional',
        key_organisms: 'Mundane species dominate. Non-magical variants of normally magical creatures evolve within the zone. Mana-dependent species die at the boundary. A unique border ecology develops at the edge where mana concentration drops to zero.',
        key_geological_features: 'The zone often centers on a site of magical catastrophe — a crater, a collapsed ley line nexus, or a drained mana reservoir. The boundaries are visible as a sharp transition where magical flora abruptly gives way to mundane vegetation.',
        disruption_risks: 'Dead zones can expand if the surrounding mana cycle weakens, or contract if mana pressure from healthy regions pushes inward. Artificial re-introduction of mana is possible but expensive and unstable — the zone tends to drain introduced mana rapidly.',
        dead_zones: 'The zone itself is the dead zone. Ambient mana reads at absolute zero. Mana detection instruments fail or read negative values at the deepest points. Even latent magical ability in living beings is suppressed.',
        historical_disruptions: 'Most dead zones trace their origin to a specific catastrophic event — a great battle, a failed ritual of enormous scale, or deliberate mana-scorching as a weapon of war.',
      },
    },
    {
      id: 'ley_line_nexus',
      name: 'Ley Line Nexus',
      description: 'A point where multiple ley lines intersect. Enormous magical power, enormous instability, and a magnet for settlements and disasters.',
      element_type: 'mana_cycle',
      summary: 'A convergence point of multiple ley lines radiating immense and volatile magical energy',
      detailed_notes: 'Ley line nexuses are the most powerful natural concentrations of magical energy in the world. Where two or more ley lines cross, their combined flow creates a vortex of mana that saturates the surrounding area. The effects are dramatic: magic is amplified, spells are more powerful, and the ambient mana can be tapped for enormous projects. But nexuses are also dangerously unstable. Mana surges, wild magic eruptions, and spontaneous planar thinning are constant risks. Despite this, civilizations have always been drawn to nexuses — the power is simply too valuable to ignore. The greatest cities, temples, and academies are built on nexus points, and wars have been fought over their control.',
      fields: {
        cycle_duration: 'Continuous, with tidal fluctuations tied to celestial and seasonal cycles',
        geographic_scope: 'local',
        key_organisms: 'Mana-gorged flora and fauna of exaggerated size and magical potency. Trees that glow, animals with innate spellcasting, and apex predators that feed on pure mana. Mutations are common and often beneficial near a nexus.',
        key_geological_features: 'The nexus itself is often marked by a natural formation — a standing stone circle, a crystalline outcrop, or a perpetually flowing spring of luminous water. Ley lines are visible to mana-sensitive individuals as glowing rivers of energy converging on the point.',
        disruption_risks: 'Ley line diversion — natural or artificial — can starve a nexus, collapsing the ecosystems and civilizations built around it. Over-tapping the nexus for industrial or military use can cause a mana blowout, releasing centuries of accumulated energy in a single catastrophic event.',
        mana_pollution: 'Excess mana at a nexus can cause wild magic zones, spontaneous enchantments, and reality distortions. Long-term residents may develop magical sensitivity, unusual abilities, or physical mutations.',
      },
    },
    {
      id: 'magical_apex_predator',
      name: 'Mana Apex Predator',
      description: 'A creature at the top of the magical food chain. Absorbs ambient mana and drains it from other creatures.',
      element_type: 'magical_food_web',
      summary: 'A dominant creature that feeds on magical energy itself, reshaping the ecosystem around it',
      detailed_notes: 'Mana apex predators are the keystone species of magical ecosystems. These creatures have evolved to feed not on flesh but on magical energy — absorbing ambient mana from the environment and draining it directly from other magical beings. Their presence creates a "mana shadow" — a region of reduced magical energy in their territory where lesser magical creatures are weakened and mundane species gain a competitive advantage. The predator\'s movements create a dynamic, shifting landscape of mana-rich and mana-poor zones. When a mana apex predator dies, the ecological consequences are enormous: mana floods back into the territory, triggering explosive magical growth, mutation cascades, and the emergence of new magical species to fill the void.',
      fields: {
        cycle_duration: 'Tied to the predator\'s life cycle — territorial feeding patterns create seasonal mana fluctuations',
        geographic_scope: 'regional',
        key_organisms: 'The predator itself is the keystone. Symbiotic species ride in its mana shadow, thriving in low-mana conditions. Parasitic species attempt to siphon mana from the predator. Prey species develop mana-concealment adaptations to avoid detection.',
        key_geological_features: 'The predator\'s lair is typically a mana-depleted zone surrounded by rings of increasing mana density. Migration paths are visible as corridors of reduced mana. Nesting sites become permanent low-mana landmarks.',
        disruption_risks: 'Killing or driving off the apex predator causes mana flooding — an ecological catastrophe where unchecked magical energy triggers runaway mutations, spontaneous enchantments, and the emergence of dangerous new species. Conversely, the introduction of a second apex predator creates territorial conflict that destabilizes entire regions.',
        historical_disruptions: 'The extinction of a mana apex predator in the Third Age is credited with the creation of the Shimmerwood — a hyper-magical forest that grew from ordinary woodland in a single decade after the predator\'s death.',
      },
    },
    {
      id: 'mana_bloom',
      name: 'Mana Bloom',
      description: 'Periodic explosion of magical energy where flora/fauna go wild, mutations spike.',
      element_type: 'mana_cycle',
      summary: 'A periodic eruption of magical energy that drives explosive growth, mutation, and ecological chaos',
      detailed_notes: 'Mana blooms are cyclical events where ambient magical energy spikes dramatically over a region, triggering explosive biological and magical responses. During a bloom, plants grow at hundreds of times their normal rate, animals undergo rapid mutation, dormant magical abilities activate spontaneously, and the boundary between the material plane and adjacent realities thins dangerously. Blooms last days to weeks and leave the affected region permanently altered — forests grow in hours, new species emerge, and the landscape is transformed. Civilizations near bloom-prone areas have adapted: some harvest the surge for industrial and agricultural purposes, while others evacuate until the chaos subsides. Predicting blooms is an imprecise science, and unexpected blooms in populated areas are among the most feared natural magical disasters.',
      fields: {
        cycle_duration: 'Irregular — typically every 7-15 years, with minor blooms between major events. Duration of each bloom: 3-21 days.',
        geographic_scope: 'regional',
        key_organisms: 'Bloom-adapted flora that remains dormant between events, exploding into growth during surges. Bloom-predators that migrate to affected areas to feed on the sudden abundance. Mana-sponge organisms that absorb excess energy and stabilize the environment post-bloom.',
        key_geological_features: 'Bloom epicenters are typically ley line nodes or sites of ancient magical events. The affected radius follows ley line paths outward from the epicenter. Post-bloom terrain features include mana-crystal formations, mutated rock structures, and permanently enchanted soil.',
        disruption_risks: 'Artificial mana extraction can suppress blooms, causing dangerous buildup that eventually releases as a catastrophic super-bloom. Ecological damage to bloom-adapted species disrupts the cycle\'s self-regulation, making blooms more intense and unpredictable.',
      },
    },
    {
      id: 'dead_magic_adaptation',
      name: 'Dead Magic Adaptation',
      description: 'Organisms evolved to survive in mana-depleted zones.',
      element_type: 'mutation',
      summary: 'Creatures that have evolved to thrive where magic cannot reach — the anti-magical ecosystem',
      detailed_notes: 'Dead magic adaptation is the suite of biological mutations that allow organisms to survive and even thrive in mana-depleted zones. Where magical ecosystems collapse, these adapted species fill the void. They are mana-null — not only surviving without magic but actively resisting it. Their tissues absorb and neutralize ambient mana, their metabolisms run on purely chemical energy, and some have evolved the ability to drain magical energy from their environment or from magical creatures that wander into their territory. This makes them ecologically dominant within dead zones and dangerous to magical beings at the boundaries. Some civilizations have weaponized dead-magic organisms, deploying mana-draining creatures against magical enemies or cultivating anti-magical materials for ward-breaking.',
      fields: {
        cycle_duration: 'Evolutionary — adaptations develop over generations, with rapid mutation in newly formed dead zones',
        geographic_scope: 'local',
        key_organisms: 'Null-moss — a mana-absorbing plant that carpets dead zone floors. Void beetles — insects whose carapaces nullify magic on contact. Silence wolves — predators that hunt by draining the mana from magical prey, leaving them weakened. Pale trees — enormous albino trees that thrive without magical photosynthesis.',
        key_geological_features: 'Dead zone boundaries where adapted and non-adapted ecosystems compete. Mana-sink formations — geological features that actively drain ambient magic. Null-crystal deposits — anti-magical mineral formations unique to dead zones.',
        disruption_risks: 'Re-introduction of mana to a dead zone can devastate adapted organisms. Conversely, dead-magic adapted species escaping their zone can disrupt magical ecosystems by draining ambient mana from healthy environments.',
      },
    },
    {
      id: 'magical_symbiosis',
      name: 'Magical Symbiosis',
      description: 'Two species sharing mana: one generates, one shapes, both benefit.',
      element_type: 'magical_food_web',
      summary: 'A symbiotic relationship where two species share magical energy — one produces mana, the other shapes it',
      detailed_notes: 'Magical symbiosis occurs when two species evolve a complementary relationship around mana production and manipulation. One species — the generator — produces mana through biological processes but lacks the ability to use it, while the other — the shaper — can manipulate mana but cannot produce its own. Together, they form a unit more powerful than either alone. The most famous example involves mana-producing coral that provides raw energy to the intelligent cephalopods living within it — the cephalopods shape the mana into defensive barriers, growth-promoting fields, and communication networks that benefit both species. These symbioses are ecological keystones: disrupting the relationship crashes local mana cycles and can trigger cascading ecosystem failures. Some sentient species have entered into similar arrangements with non-sentient mana generators, raising questions about whether the relationship is symbiosis or domestication.',
      fields: {
        cycle_duration: 'Continuous — the symbiotic exchange operates constantly, with daily and seasonal fluctuations in mana production and shaping',
        geographic_scope: 'local',
        key_organisms: 'Mana generators — organisms that produce magical energy as a metabolic byproduct (bioluminescent fungi, mana-coral, ley-root trees). Mana shapers — organisms that can manipulate ambient mana but cannot generate their own (certain intelligent species, spell-weaving spiders, ward-singing birds). Parasitic third parties that attempt to siphon mana from the symbiotic pair.',
        key_geological_features: 'Symbiotic zones are identifiable by their unusual ecological stability — mana levels are consistent, growth is balanced, and wild magic events are rare. The shaped mana often creates visible environmental effects: glowing forests, perpetually calm waters, or temperature-regulated microclimates.',
        disruption_risks: 'Removing either symbiotic partner collapses the relationship — generators flood the area with uncontrolled mana, while shapers starve and die. Pollution, habitat destruction, or poaching of either species threatens the entire local ecosystem.',
      },
    },
  ],
  defaultSortField: 'cycle_duration',
};
