import type { DomainConfig } from '../types/domains.js';

export const magicEcologyConfig: DomainConfig = {
  id: 'magic_ecology',
  name: 'Magic Ecology',
  namePlural: 'Magic Ecology',
  icon: 'sprout',
  color: '#2ecc71',
  description: 'Explore how magic functions as a natural force within ecosystems. Define mana cycles, magical mutations, enchanted food webs, and environments saturated with arcane energy. Magic ecology treats mana as a resource that flows, pools, and transforms just like water or sunlight.',
  tableName: 'mana_cycles',
  category: 'magic',
  fields: [
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type involved in this cycle',
      helpText: 'The specific type of magical energy that flows through this cycle.',
    },
    {
      name: 'stages',
      label: 'Cycle Stages',
      type: 'json',
      required: true,
      placeholder: '["generation", "dispersal", "absorption", "transformation", "release"]',
      helpText: 'The ordered stages through which mana flows in this ecological cycle.',
    },
    {
      name: 'cycle_duration',
      label: 'Cycle Duration',
      type: 'text',
      placeholder: 'e.g. 28 days (lunar), 1 year, centuries, irregular',
      helpText: 'How long one complete cycle takes from start to finish.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'select',
      options: ['local', 'regional', 'continental', 'global', 'planar', 'cosmic'],
      helpText: 'The spatial scale at which this cycle operates.',
    },
    {
      name: 'key_organisms',
      label: 'Key Organisms',
      type: 'textarea',
      placeholder: 'Species that play critical roles in this mana cycle...',
      helpText: 'Flora, fauna, or other organisms that are essential participants in this cycle.',
    },
    {
      name: 'key_geological_features',
      label: 'Key Geological Features',
      type: 'textarea',
      placeholder: 'Ley line nodes, mana springs, crystal formations...',
      helpText: 'Geographic or geological features that anchor or channel this cycle.',
    },
    {
      name: 'disruption_risks',
      label: 'Disruption Risks',
      type: 'textarea',
      placeholder: 'What could break this cycle? Over-harvesting, pollution, planar shifts...',
      helpText: 'Threats that could disrupt, weaken, or destroy this mana cycle.',
    },
    {
      name: 'historical_disruptions',
      label: 'Historical Disruptions',
      type: 'textarea',
      placeholder: 'Past events that disrupted this cycle and their consequences...',
      helpText: 'Known historical instances where this cycle was disrupted and what resulted.',
    },
    {
      name: 'mana_pollution',
      label: 'Mana Pollution',
      type: 'textarea',
      placeholder: 'Describe magical waste, contamination, toxic mana buildup...',
      helpText: 'How magical waste, byproducts, or contamination affects this cycle and the surrounding environment.',
    },
    {
      name: 'dead_zones',
      label: 'Dead Zones',
      type: 'textarea',
      placeholder: 'Describe mana-barren areas, causes, and effects on life...',
      helpText: 'Areas where mana has been depleted or blocked — their causes, boundaries, and impact on magical and mundane life.',
    },
  ],
  elementTypes: ['mana_cycle', 'mutation', 'magical_food_web', 'saturated_environment'],
  prompts: [
    'How does mana flow through your world\'s ecosystems? Is it more like water (following gravity and channels) or like sunlight (radiating from sources)?',
    'What happens to an ecosystem when its mana cycle is disrupted? Do creatures mutate, die off, or adapt in unexpected ways?',
    'Are there keystone species in the magical ecosystem—organisms whose removal would cause cascading mana collapse?',
    'How do mana-saturated environments differ from normal ones? Are there magical equivalents of rainforests, deserts, or deep-sea vents?',
    'Can new mana cycles emerge naturally, or are they all ancient? Has civilization ever accidentally created one through magical pollution or infrastructure?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'atmospheric_mana_cycle',
      name: 'Atmospheric Mana Cycle',
      description: 'Mana evaporates, condenses in the upper atmosphere, and precipitates back as mana rain or dew.',
      element_type: 'mana_cycle',
      summary: 'A global cycle where mana rises, condenses, and rains back to the surface',
      fields: {
        cycle_duration: 'Seasonal — peaks during equinoxes, ebbs at solstices',
        geographic_scope: 'global',
        key_organisms: 'Mana-absorbing canopy trees draw ambient mana and release it through transpiration. High-altitude mana plankton seed condensation.',
        key_geological_features: 'Mountain ranges force mana-laden air upward, creating mana rain shadows. Ley line intersections act as mana springs.',
        disruption_risks: 'Deforestation breaks the transpiration cycle. Large-scale magical warfare can punch holes in the mana layer. Industrial mana extraction depletes ground reserves.',
      },
    },
    {
      id: 'geological_mana_cycle',
      name: 'Geological Mana Cycle',
      description: 'Mana wells up from deep within the earth through volcanic and tectonic processes.',
      element_type: 'mana_cycle',
      summary: "Mana rising from the planet's depths through faults and volcanic vents",
      fields: {
        cycle_duration: 'Geological — major pulses every few centuries, minor seepage continuous',
        geographic_scope: 'continental',
        key_organisms: 'Deep-root fungi network that transports mana from geological seeps to surface ecosystems. Mana worms that burrow along ley lines.',
        key_geological_features: 'Volcanic vents and hot springs as primary mana sources. Ley lines follow tectonic fault systems. Crystal caverns act as natural mana reservoirs.',
        disruption_risks: 'Over-mining of mana crystals depletes reservoirs. Tectonic shifts can redirect or seal ley lines. Volcanic eruptions release catastrophic mana surges.',
      },
    },
    {
      id: 'biological_mana_cycle',
      name: 'Biological Mana Cycle',
      description: 'Living organisms generate, store, and release mana through their life processes.',
      element_type: 'mana_cycle',
      summary: 'A living web where mana flows through food chains and decomposition',
      fields: {
        cycle_duration: 'Continuous, with generational accumulation',
        geographic_scope: 'regional',
        key_organisms: 'All living things participate — plants absorb ambient mana during growth, animals concentrate it through diet, decomposers release it back to the soil. Apex magical predators are the most mana-dense.',
        key_geological_features: 'Ancient burial grounds and fossil beds are mana-rich. Old-growth forests accumulate mana over centuries. Mass extinction sites create mana dead zones.',
        disruption_risks: 'Extinction of keystone magical species collapses the local mana web. Necromantic practices trap mana in undeath, removing it from the cycle. Overhunting magical fauna depletes concentrated reserves.',
      },
    },
    {
      id: 'necrotic_mana_cycle',
      name: 'Necrotic Mana Cycle',
      description: 'A mana cycle fueled by death itself — where dying releases more magical energy than living, creating perverse ecological incentives.',
      element_type: 'mana_cycle',
      summary: 'A dark cycle where death generates more mana than life, with disturbing consequences',
      fields: {
        cycle_duration: 'Continuous, with spikes during mass death events',
        geographic_scope: 'regional',
        key_organisms: 'Scavengers and decomposers are the primary mana producers — the more death they process, the more mana enters the system. Predators have evolved to kill more than they eat, wasting flesh but harvesting mana. Plants in these regions are carnivorous by default.',
        key_geological_features: 'Ancient battlefields and plague pits are permanent mana hotspots. Bone-rich soil layers act as slow-release mana sources. Graveyards in these regions must be warded or they spontaneously generate undead.',
        disruption_risks: 'Peace is ecologically destabilizing — extended periods without death cause mana famines. Civilizations in these regions face a horrifying incentive structure around warfare and sacrifice.',
        mana_pollution: 'Excess necrotic mana causes spontaneous undeath, ghostly manifestations, and a general miasma of despair. Long-term residents develop a tolerance that outsiders find deeply unsettling.',
      },
    },
  ],
  defaultSortField: 'cycle_duration',
};
