import type { DomainConfig } from '../types/domains.js';

export const magicEconomyConfig: DomainConfig = {
  id: 'magic_economy',
  name: 'Magic Economy',
  namePlural: 'Magic Economy',
  icon: 'coins',
  color: '#f1c40f',
  description: 'Define the economic dimensions of magic in your world. From mana resources and their extraction to magical trade goods, enchanter guilds, regulatory frameworks, and black markets—this domain covers how magic creates, distributes, and concentrates wealth and power.',
  tableName: 'mana_resources',
  category: 'magic',
  fields: [
    {
      name: 'resource_type',
      label: 'Resource Type',
      type: 'select',
      required: true,
      options: ['crystallized_mana', 'liquid_mana', 'ambient_field', 'biological', 'geological', 'planar_bleed', 'refined_product', 'byproduct', 'custom'],
      helpText: 'The fundamental form of this magical resource.',
    },
    {
      name: 'source_id',
      label: 'Source',
      type: 'text',
      placeholder: 'ID of the magic source that produces this resource',
      helpText: 'The magical source from which this resource originates.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type',
      helpText: 'The type of magical energy this resource contains or produces.',
    },
    {
      name: 'extraction_method',
      label: 'Extraction Method',
      type: 'textarea',
      placeholder: 'How is this resource gathered or harvested?',
      helpText: 'The techniques and tools used to extract or collect this resource.',
    },
    {
      name: 'refinement_process',
      label: 'Refinement Process',
      type: 'textarea',
      placeholder: 'How is the raw resource processed into usable form?',
      helpText: 'Steps to refine raw magical material into a form suitable for use.',
    },
    {
      name: 'quality_grades',
      label: 'Quality Grades',
      type: 'json',
      placeholder: '["crude", "refined", "pure", "transcendent"]',
      helpText: 'The quality tiers this resource is graded into.',
    },
    {
      name: 'geographic_distribution',
      label: 'Geographic Distribution',
      type: 'textarea',
      placeholder: 'Where in the world is this resource found?',
      helpText: 'The regions, biomes, or conditions where this resource naturally occurs.',
    },
    {
      name: 'total_estimated_reserves',
      label: 'Total Estimated Reserves',
      type: 'text',
      placeholder: 'e.g. vast, declining, nearly exhausted, unknown',
      helpText: 'The estimated total remaining supply of this resource.',
    },
    {
      name: 'renewability',
      label: 'Renewability',
      type: 'select',
      options: ['non_renewable', 'slowly_renewable', 'renewable', 'rapidly_renewable', 'infinite', 'unknown'],
      helpText: 'Whether and how quickly this resource replenishes naturally.',
    },
    {
      name: 'depletion_rate',
      label: 'Depletion Rate',
      type: 'text',
      placeholder: 'e.g. sustainable, accelerating, critical',
      helpText: 'How quickly current consumption is outpacing natural replenishment.',
    },
    {
      name: 'environmental_impact_of_extraction',
      label: 'Environmental Impact',
      type: 'textarea',
      placeholder: 'What damage does extraction cause to the surrounding environment?',
      helpText: 'Ecological consequences of harvesting this resource—mana dead zones, mutations, planar thinning.',
    },
    {
      name: 'controlling_entities',
      label: 'Controlling Entities',
      type: 'textarea',
      placeholder: 'Which civilizations, guilds, or factions control this resource?',
      helpText: 'The political and economic powers that control access to this resource.',
    },
    {
      name: 'strategic_importance',
      label: 'Strategic Importance',
      type: 'select',
      options: ['negligible', 'minor', 'moderate', 'major', 'critical', 'existential'],
      helpText: 'How important this resource is to geopolitical power and military capability.',
    },
    {
      name: 'market_structure',
      label: 'Market Structure',
      type: 'select',
      options: ['monopoly', 'oligopoly', 'guild_controlled', 'free_market', 'state_run', 'barter', 'auction', 'mixed'],
      helpText: 'How the market for this resource is organized and controlled.',
    },
    {
      name: 'black_market_details',
      label: 'Black Market Details',
      type: 'textarea',
      placeholder: 'Describe illicit trade, smuggling routes, penalties...',
      helpText: 'How this resource is traded illegally — smuggling networks, penalties for possession, price premiums.',
    },
  ],
  elementTypes: ['resource', 'trade_good', 'profession', 'regulation', 'black_market'],
  prompts: [
    'What is the most valuable magical resource in your world, and who controls it? Has this control ever been the cause of wars?',
    'How do magical professions fit into the broader economy? Is an enchanter more like an artisan, an engineer, or a doctor in social and economic standing?',
    'What magical goods and services are available to ordinary people versus only the wealthy? Is there a magical middle class?',
    'What does the black market for magic look like? What is sold illegally, and why is it forbidden?',
    'Are magical resources being depleted? Is there a conservation movement, and do powerful interests resist it?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'crystallized_mana_resource',
      name: 'Crystallized Mana',
      description: 'Solid mana crystals mined from deep deposits — the gold standard of magical currency.',
      element_type: 'resource',
      summary: 'Precious mana crystals mined from deep beneath ley lines',
      fields: {
        resource_type: 'crystallized_mana',
        extraction_method: 'Deep mining operations in ley line convergence points. Crystals grow in geological timescales and must be carefully extracted to avoid shattering and mana release.',
        refinement_process: 'Raw crystals are cut, polished, and graded by certified mana-smiths. Impurities are burned off in controlled arcane furnaces.',
        geographic_distribution: 'Concentrated near tectonic fault lines and ancient ley line nexuses. Some surface deposits exist in magically saturated regions.',
        renewability: 'slowly_renewable',
        strategic_importance: 'critical',
        market_structure: 'guild_controlled',
      },
    },
    {
      id: 'ambient_mana_field',
      name: 'Ambient Mana Field',
      description: 'A region of naturally elevated background mana that can be harvested or tapped.',
      element_type: 'resource',
      summary: 'Naturally occurring magical energy harvested from the environment',
      fields: {
        resource_type: 'ambient_field',
        extraction_method: 'Mana collectors — tower-mounted arrays of resonant crystals that draw in and concentrate ambient magical energy from the surrounding area.',
        refinement_process: 'Collected ambient mana is compressed and stored in capacitor crystals. Low-grade but consistent output.',
        geographic_distribution: 'Strongest near ley line intersections, old-growth magical forests, and sites of historical magical events. Weakest in urban areas and mana-dead zones.',
        renewability: 'renewable',
        strategic_importance: 'major',
        market_structure: 'mixed',
      },
    },
    {
      id: 'biological_magic_source',
      name: 'Biological Magic Source',
      description: 'Magical materials harvested from living or recently living organisms.',
      element_type: 'resource',
      summary: 'Magical reagents and materials harvested from enchanted creatures and plants',
      fields: {
        resource_type: 'biological',
        extraction_method: 'Harvesting from magical creatures (scales, blood, heartstone), cultivating magical plants, or collecting natural magical secretions like phoenix tears or unicorn hair.',
        refinement_process: 'Biological materials are preserved through alchemical processes, then ground, distilled, or infused depending on the intended use.',
        geographic_distribution: 'Wherever magical flora and fauna thrive — primarily old-growth magical forests, deep oceans, and planar border regions.',
        renewability: 'renewable',
        strategic_importance: 'moderate',
        market_structure: 'free_market',
        environmental_impact_of_extraction: 'Overharvesting threatens magical species. Poaching of rare creatures is a major conservation and law enforcement challenge.',
      },
    },
    {
      id: 'stolen_futures',
      name: 'Temporal Mana Futures',
      description: 'Mana borrowed from the future — spend it now, but somewhere down the timeline, someone pays the debt with interest.',
      element_type: 'trade_good',
      summary: 'Magical energy extracted from future timelines — powerful now, catastrophic later',
      fields: {
        resource_type: 'custom',
        extraction_method: 'Temporal siphoning rituals draw mana from potential futures. The process is simple — worryingly so — and the mana is high-purity. The problem is that every unit borrowed creates a mana-debt that compounds across time.',
        refinement_process: 'None needed — temporal mana arrives pre-refined. This is part of what makes it so dangerous and attractive.',
        geographic_distribution: 'Can be extracted anywhere with a trained temporal mage. Concentration is highest near temporal anomalies, thin spots in the timestream, and sites of prophecy.',
        renewability: 'unknown',
        strategic_importance: 'existential',
        market_structure: 'auction',
        environmental_impact_of_extraction: 'Localized temporal instability — clocks run backward, people experience déjà vu, cause and effect occasionally reverse. Heavy extraction creates temporal dead zones where the future has been "spent" and nothing new can happen.',
        controlling_entities: 'Officially banned by every major civilization. In practice, a shadow network of temporal brokers operates across borders. Some governments are secretly the largest buyers.',
      },
    },
  ],
  defaultSortField: 'resource_type',
};
