import type { DomainConfig } from '../types/domains.js';

export const magicSystemsConfig: DomainConfig = {
  id: 'magic_systems',
  name: 'Magic System',
  namePlural: 'Magic Systems',
  icon: 'sparkles',
  color: '#f39c12',
  description: 'Define the fundamental rules, sources, and taxonomies of magic in your world. This is the master domain for all things magical—energy types, laws, spell classifications, costs, and phenomena. The sub-tables handle the detailed breakdowns; this domain ties them together.',
  tableName: 'world_elements',
  category: 'magic',
  fields: [
    {
      name: 'magic_philosophy',
      label: 'Magic Philosophy',
      type: 'textarea',
      placeholder: 'Describe the overall paradigm — hard vs soft magic, deterministic vs chaotic, scientific vs mystical...',
      helpText: 'The overarching philosophy or paradigm of this magic system — how rigorous, predictable, and systematized magic is in your world.',
    },
    {
      name: 'properties',
      label: 'Properties',
      type: 'json',
      placeholder: '{}',
      helpText: 'Additional properties for this magic system element. The real detail lives in the magic sub-tables (sources, energy types, laws, taxonomies, materials, spells, costs, phenomena, power scaling).',
    },
  ],
  elementTypes: ['source', 'energy_type', 'law', 'taxonomy', 'material', 'spell', 'cost', 'phenomenon', 'power_tier'],
  elementTypeDescriptions: {
    source: 'Where magic comes from — an ambient field, divine gift, biological trait, planar bleed, or something stranger entirely.',
    energy_type: 'A distinct form of magical energy with its own properties — color, behavior, storage potential, and interactions with other types.',
    law: 'A fundamental rule governing how magic works — conservation laws, forbidden actions, required conditions, or universal constraints.',
    taxonomy: 'A classification system for organizing magic — schools, elements, traditions, or any framework practitioners use to categorize spells.',
    material: 'A substance with inherent magical properties — crystals, herbs, metals, or exotic matter used in casting, crafting, or enchanting.',
    spell: 'A discrete, repeatable magical effect that can be learned, cast, and classified within the magic system.',
    cost: 'The price magic demands — physical toll, mental strain, life force, moral corruption, or other consequences of wielding power.',
    phenomenon: 'A naturally occurring magical event — mana storms, wild magic surges, ley line eruptions, or ambient enchantments.',
    power_tier: 'A level within the power scaling framework — defining what abilities, energy capacity, and status a practitioner holds.',
  },
  prompts: [
    'What is the fundamental source of magic in your world? Is it an ambient energy field, a gift from deities, an innate biological trait, or something stranger?',
    'What are the hard limits of magic? Every compelling magic system has costs and constraints—what can magic never do, and what price does it extract?',
    'How many distinct types of magical energy exist? Do they interact, combine, or cancel each other out?',
    'How is magic classified by its practitioners? Do they use schools, elements, colors, musical keys, or something unique to your world?',
    'What happens when magic goes wrong? Are there catastrophic failures, wild magic surges, or subtle corruptions that accumulate over time?',
  ],
  magicPermeation: null,
  defaultSortField: 'name',
  archetypes: [
    {
      id: 'ambient_field',
      name: 'Ambient Mana Field',
      description: 'Magic as a pervasive environmental energy that can be tapped, shaped, and depleted — like an invisible atmosphere of power.',
      element_type: 'source',
      summary: 'A pervasive energy field saturating the world, varying in density by region and influenced by geography, celestial events, and living things.',
      detailed_notes: 'The ambient mana field is the most common source model for high-magic worlds. Mana exists everywhere but pools in certain locations (ley line intersections, ancient forests, mountain peaks) and thins in others (deserts, dead zones, heavily industrialized areas). Practitioners draw on this field to fuel spells, and overuse can locally deplete it, causing ecological consequences.',
      fields: {
        magic_philosophy: 'Magic is a natural force, like gravity or electromagnetism. It can be studied, measured, and manipulated through learned techniques. The field is finite but renewable — it regenerates over time unless something disrupts the cycle.',
      },
    },
    {
      id: 'divine_gift',
      name: 'Divine Gift',
      description: 'Magic granted by gods to chosen mortals — prayers answered, blessings bestowed, and divine wrath unleashed.',
      element_type: 'source',
      summary: 'Magical power flows from deities to their worshippers, granted through prayer, devotion, or divine covenant.',
      detailed_notes: 'In a divine gift system, mortals cannot generate magic on their own. All power comes from a patron deity, spirit, or cosmic entity. The relationship is transactional — devotion in exchange for power. Losing faith or breaking divine commandments can sever the connection entirely. Different gods grant different types of magic, creating natural factions among practitioners.',
      fields: {
        magic_philosophy: 'Magic is a gift, not a right. It flows from beings of immense power to those they deem worthy. Understanding magic means understanding the will of the gods — theology and spellcasting are one and the same.',
      },
    },
    {
      id: 'blood_magic_law',
      name: 'Law of Equivalent Exchange',
      description: 'All magic requires sacrifice proportional to the effect — blood, life force, memories, or years of life.',
      element_type: 'law',
      summary: 'Every magical effect demands a cost equal in weight to what it produces. Nothing is created from nothing.',
      detailed_notes: 'The Law of Equivalent Exchange is the central constraint of this magic system. Healing a wound means taking that wound onto yourself or another. Creating fire means draining heat from somewhere else. Raising the dead means someone else must die. The law is absolute and cannot be cheated — though many have tried, and the consequences of attempting to circumvent it are catastrophic. This creates inherent moral tension in every act of magic.',
      fields: {
        magic_philosophy: 'Hard magic with absolute rules. The universe keeps a perfect ledger — every magical transaction must balance. Practitioners are as much accountants as wizards, calculating costs before casting.',
      },
    },
    {
      id: 'elemental_taxonomy',
      name: 'Elemental Schools',
      description: 'Magic classified into elemental categories — fire, water, earth, air, and stranger elements unique to your world.',
      element_type: 'taxonomy',
      summary: 'All magic is organized into elemental schools, each with distinct properties, techniques, and cultural associations.',
      detailed_notes: 'The elemental taxonomy divides magic into fundamental categories based on the natural (or supernatural) elements. Classic systems use four or five elements, but this can expand to include light, shadow, metal, wood, void, time, or elements unique to your world. Each school has strengths, weaknesses, and interactions with others — fire beats wood, water douses fire, but what beats void? Practitioners typically specialize in one or two schools, and cultural traditions favor certain elements.',
      fields: {
        magic_philosophy: 'Magic mirrors the structure of the natural world. Each element represents a fundamental force, and mastering an element means understanding its nature deeply. Cross-element casting is possible but exponentially harder.',
      },
    },
    {
      id: 'wild_surge',
      name: 'Wild Magic Surge',
      description: 'Uncontrolled magical eruptions that warp reality in unpredictable ways — beautiful, terrifying, and always unexpected.',
      element_type: 'phenomenon',
      summary: 'Spontaneous magical discharges that occur when ambient mana reaches critical density or when spellcasting fails catastrophically.',
      detailed_notes: 'Wild magic surges are unpredictable eruptions of raw magical energy. They can turn stone to glass, reverse gravity locally, cause temporary time loops, or transform living creatures. Surges occur naturally in areas of high mana concentration but can also be triggered by botched spells, emotional extremes, or celestial alignments. Some cultures fear them as divine punishment; others seek them out for the unique magical effects they can produce. Entire ecosystems have evolved around surge-prone areas.',
      fields: {
        magic_philosophy: 'A reminder that magic is fundamentally chaotic. No matter how much practitioners systematize it, raw mana is a wild force that resists complete control. Surges are the price of a world saturated with power.',
      },
    },
    {
      id: 'apprentice_to_archmage',
      name: 'Apprentice-to-Archmage Scale',
      description: 'A structured power progression from untrained novice to world-shaking archmage — with defined tiers, titles, and expectations.',
      element_type: 'power_tier',
      summary: 'A formal ranking system that categorizes magic users by their power, knowledge, and demonstrated ability.',
      detailed_notes: 'This power scaling framework defines clear tiers of magical ability. At the bottom, Novices can barely light a candle. Apprentices learn fundamentals under a mentor. Journeymen can operate independently. Full Mages command significant power. Masters reshape local environments. Archmages can alter reality on a regional scale. Each tier requires years of study, specific trials or achievements, and carries social expectations and responsibilities. The framework is recognized across cultures, though different civilizations may use different names.',
      fields: {
        magic_philosophy: 'Power is earned through disciplined study and practice. The ranking system reflects genuine differences in capability — it is meritocratic in theory, though politics and access to training create inequality in practice.',
      },
    },
    {
      id: 'innate_biological',
      name: 'Innate Biological Magic',
      description: 'Magic as a biological trait — some species or bloodlines are born with it, others never will be.',
      element_type: 'source',
      summary: 'Magical ability is encoded in biology — a gland, organ, or genetic trait that some creatures possess and others lack entirely.',
      detailed_notes: 'In this system, magic is not learned but inherited. Certain species evolved magical organs (mana glands, aetheric nerves, resonance bones) that allow them to channel magical energy. Among species where magic is variable, it runs in bloodlines — magical families jealously guard their lineages. Those born without the trait can never learn magic, creating deep social divisions. Cross-breeding between magical and non-magical lines produces unpredictable results.',
      fields: {
        magic_philosophy: 'Magic is biology, not philosophy. You either have the organ for it or you don\'t. Training refines what nature gave you, but it cannot create what isn\'t there. This makes magic inherently unequal — a fact that shapes every society it touches.',
      },
    },
    {
      id: 'mana_crystal',
      name: 'Crystallized Mana',
      description: 'Solid magic that can be mined, refined, traded, and consumed as fuel — the coal and oil of a magical economy.',
      element_type: 'material',
      summary: 'Mana that has solidified into physical crystals over millennia, forming extractable deposits deep underground.',
      detailed_notes: 'Mana crystals form where ambient magical energy has pooled and compressed over geological timescales — often near ley line intersections or sites of ancient magical events. Raw crystals contain unfocused energy that must be refined before use. Different crystal colors indicate different magical affinities. The largest deposits drive entire economies, with mining towns, trade routes, and wars emerging around them. Crystals can be consumed (destroyed for a burst of power), embedded in devices (slow release), or ground into powder for potions and inks.',
      fields: {
        magic_philosophy: 'Magic is a natural resource — finite, extractable, and valuable. Like any resource, it can be hoarded, traded, fought over, and eventually exhausted. The question every civilization faces: what happens when the crystals run out?',
      },
    },
    {
      id: 'forbidden_spell',
      name: 'Forbidden Working',
      description: 'A spell so dangerous or morally abhorrent that all civilizations agree to ban it — but someone always tries.',
      element_type: 'spell',
      summary: 'A category of magic universally prohibited due to catastrophic risk, moral transgression, or both.',
      detailed_notes: 'Forbidden workings are spells that cross lines every culture agrees should not be crossed. This might include true resurrection (which tears holes between the planes of living and dead), time reversal (which creates paradoxes that compound until reality breaks), or soul binding (which enslaves a consciousness for eternity). The ban is enforced by international treaty, religious doctrine, or magical failsafes built into the fabric of reality itself. Despite this, forbidden knowledge persists — hidden in sealed libraries, encoded in children\'s rhymes, or whispered by entities from other planes.',
      fields: {
        magic_philosophy: 'Some doors are closed for a reason. Forbidden workings represent the ethical boundaries of magical practice — the recognition that power without restraint is not freedom but catastrophe.',
      },
    },
    {
      id: 'soul_cost',
      name: 'Soul Erosion',
      description: 'Every spell wears away a piece of the caster — personality, memory, emotion, or self slowly grinding down with each casting.',
      element_type: 'cost',
      summary: 'Casting magic gradually erodes the caster\'s soul, stripping away memories, emotions, personality traits, and eventually identity itself.',
      detailed_notes: 'Soul erosion is the hidden price of magic. Each spell is small — you might forget a childhood afternoon, lose your taste for a favorite food, or find that anger comes slightly less easily. But over a lifetime of casting, the erosion compounds. Powerful mages are often hollow people — technically brilliant but emotionally flat, their personalities worn smooth like river stones. The most powerful archmages barely remember their own names. Some practitioners try to offset erosion by living intensely between castings, building up reserves of experience and emotion. Others accept the trade, viewing mortal attachments as distractions from pure magical pursuit.',
      fields: {
        magic_philosophy: 'Magic takes what makes you human. The cost isn\'t physical pain or exhaustion — it\'s you. Every spell is a transaction where the currency is identity itself. The greatest mages are also the least recognizably themselves.',
      },
    },
    {
      id: 'runic_system',
      name: 'Runic Inscription System',
      description: 'Magic encoded in written symbols — carved, painted, or tattooed. The language of power, made literal.',
      element_type: 'taxonomy',
      summary: 'A magical framework where power is channeled through specific written symbols, each encoding a particular effect or concept.',
      detailed_notes: 'In a runic system, magic is fundamentally linguistic. Each rune represents a concept (fire, protection, growth, binding) and drawing the rune correctly channels that concept into reality. Runes can be combined into sentences of power — complex enchantments built from simple components. The medium matters: runes carved in stone are permanent but inflexible; runes drawn in the air are fleeting but responsive; runes tattooed on skin are always available but limited in number. Different cultures have developed different runic alphabets, and translation between them is an advanced discipline. The act of writing new runes — encoding previously unexpressed concepts — is the highest form of magical research.',
      fields: {
        magic_philosophy: 'Magic is language. Reality responds to being described in the right way, in the right symbols. Learning magic is learning to write in the tongue that the universe itself reads.',
      },
    },
    {
      id: 'music_magic',
      name: 'Music Magic',
      description: 'Magic cast through song, rhythm, and harmony. Each spell is a composition.',
      element_type: 'taxonomy',
      summary: 'A magical framework where spells are songs and power flows through melody, rhythm, and harmony',
      detailed_notes: 'In music magic, every spell is a composition. Simple cantrips are single notes or short phrases; complex workings are symphonies requiring multiple casters performing in concert. Pitch determines the type of effect (high notes for light and air, low notes for earth and shadow), rhythm controls duration and intensity, and harmony allows multiple effects to be layered simultaneously. Solo practitioners are limited to what one voice or instrument can produce; the most powerful magic requires orchestras. Different musical traditions produce different magical styles — percussive war-magic, lilting healing songs, discordant curses, and the terrifying silence-magic of those who weaponize the absence of sound. Errors in performance cause proportional errors in the spell, making magical performance anxiety a literal occupational hazard.',
      fields: {
        magic_philosophy: 'Magic is music — the universe vibrates at fundamental frequencies, and those who can match those frequencies with voice or instrument can reshape reality. Every practitioner is a performer, and every spell is a composition that must be executed with precision and feeling.',
      },
    },
    {
      id: 'contract_magic',
      name: 'Contract Magic',
      description: 'All magic requires a binding agreement. The universe itself enforces contracts.',
      element_type: 'law',
      summary: 'A legal framework of magic where every spell is a binding contract enforced by the fabric of reality itself',
      detailed_notes: 'Contract magic operates on the principle that the universe is fundamentally legalistic. To cast a spell, a practitioner must draft a contract specifying exactly what they want, what they offer in exchange, and the terms and conditions of the effect. The contract can be with an element, a spirit, a concept, or reality itself. Once signed (in blood, mana, or true name), the contract is binding and self-enforcing — the universe ensures compliance from both parties. This makes magic extremely reliable but also dangerously literal. Poorly worded contracts produce technically correct but disastrous results. Loopholes are exploited by clever practitioners and cleverer entities. An entire legal profession has emerged around magical contract law, and the best magical lawyers are more feared than the most powerful combat mages.',
      fields: {
        magic_philosophy: 'Magic is law. The universe operates on binding agreements, and power flows to those who can draft the most precise and advantageous contracts. Every spell is a negotiation, every enchantment a treaty, and every magical disaster a breach of contract with cosmic consequences.',
      },
    },
    {
      id: 'emotion_fuel',
      name: 'Emotion-Fueled Magic',
      description: 'Magic powered by the caster\'s emotions. Joy heals, rage destroys, grief wards.',
      element_type: 'source',
      summary: 'A magic system fueled by raw emotion — the deeper you feel, the more power you command',
      detailed_notes: 'Emotion-fueled magic draws its power directly from the caster\'s emotional state. Joy produces healing and growth magic. Rage fuels destructive and combat magic. Grief creates powerful wards and barriers. Love enables enchantment and binding. Fear amplifies illusion and concealment. The system is intuitive — anyone who feels strongly can cast — but mastering it requires extraordinary emotional discipline. The most powerful practitioners are not those who suppress emotion but those who can summon genuine, intense feeling on demand and then channel it precisely. This creates a paradox: the best emotion-mages are simultaneously the most emotionally volatile and the most emotionally controlled people alive. The system has dark implications: some practitioners cultivate suffering in themselves or others to fuel their magic, and the line between therapeutic emotional expression and exploitative emotional harvesting is dangerously thin.',
      fields: {
        magic_philosophy: 'Magic is feeling. The heart is the organ of power, not the mind. Emotional authenticity is the key to magical strength — forced or false emotions produce weak, unstable effects. The universe responds to genuine passion, making magic an inherently personal and unpredictable art.',
      },
    },
  ],
};
