import type { DomainConfig } from '../types/domains.js';

export const magicEcologyConfig: DomainConfig = {
  id: 'magic_ecology',
  name: 'Magic Ecology',
  namePlural: 'Magic Ecology',
  icon: 'sprout',
  color: '#2ecc71',
  description: 'Explore how magic functions as a natural force within ecosystems. Define mana cycles, magical mutations, enchanted food webs, and environments saturated with arcane energy. Magic ecology treats mana as a resource that flows, pools, and transforms just like water or sunlight.',
  tableName: 'mana_cycles',
  category: 'magic',
  fields: [
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type involved in this cycle',
      helpText: 'The specific type of magical energy that flows through this cycle.',
    },
    {
      name: 'stages',
      label: 'Cycle Stages',
      type: 'json',
      required: true,
      placeholder: '["generation", "dispersal", "absorption", "transformation", "release"]',
      helpText: 'The ordered stages through which mana flows in this ecological cycle.',
    },
    {
      name: 'cycle_duration',
      label: 'Cycle Duration',
      type: 'text',
      placeholder: 'e.g. 28 days (lunar), 1 year, centuries, irregular',
      helpText: 'How long one complete cycle takes from start to finish.',
    },
    {
      name: 'geographic_scope',
      label: 'Geographic Scope',
      type: 'select',
      options: ['local', 'regional', 'continental', 'global', 'planar', 'cosmic'],
      helpText: 'The spatial scale at which this cycle operates.',
    },
    {
      name: 'key_organisms',
      label: 'Key Organisms',
      type: 'textarea',
      placeholder: 'Species that play critical roles in this mana cycle...',
      helpText: 'Flora, fauna, or other organisms that are essential participants in this cycle.',
    },
    {
      name: 'key_geological_features',
      label: 'Key Geological Features',
      type: 'textarea',
      placeholder: 'Ley line nodes, mana springs, crystal formations...',
      helpText: 'Geographic or geological features that anchor or channel this cycle.',
    },
    {
      name: 'disruption_risks',
      label: 'Disruption Risks',
      type: 'textarea',
      placeholder: 'What could break this cycle? Over-harvesting, pollution, planar shifts...',
      helpText: 'Threats that could disrupt, weaken, or destroy this mana cycle.',
    },
    {
      name: 'historical_disruptions',
      label: 'Historical Disruptions',
      type: 'textarea',
      placeholder: 'Past events that disrupted this cycle and their consequences...',
      helpText: 'Known historical instances where this cycle was disrupted and what resulted.',
    },
    {
      name: 'mana_pollution',
      label: 'Mana Pollution',
      type: 'textarea',
      placeholder: 'Describe magical waste, contamination, toxic mana buildup...',
      helpText: 'How magical waste, byproducts, or contamination affects this cycle and the surrounding environment.',
    },
    {
      name: 'dead_zones',
      label: 'Dead Zones',
      type: 'textarea',
      placeholder: 'Describe mana-barren areas, causes, and effects on life...',
      helpText: 'Areas where mana has been depleted or blocked — their causes, boundaries, and impact on magical and mundane life.',
    },
  ],
  elementTypes: ['mana_cycle', 'mutation', 'magical_food_web', 'saturated_environment'],
  prompts: [
    'How does mana flow through your world\'s ecosystems? Is it more like water (following gravity and channels) or like sunlight (radiating from sources)?',
    'What happens to an ecosystem when its mana cycle is disrupted? Do creatures mutate, die off, or adapt in unexpected ways?',
    'Are there keystone species in the magical ecosystem—organisms whose removal would cause cascading mana collapse?',
    'How do mana-saturated environments differ from normal ones? Are there magical equivalents of rainforests, deserts, or deep-sea vents?',
    'Can new mana cycles emerge naturally, or are they all ancient? Has civilization ever accidentally created one through magical pollution or infrastructure?',
  ],
  magicPermeation: null,
  defaultSortField: 'cycle_duration',
};
