import type { DomainConfig } from '../types/domains.js';

export const magicEconomyConfig: DomainConfig = {
  id: 'magic_economy',
  name: 'Magic Economy',
  namePlural: 'Magic Economy',
  icon: 'coins',
  color: '#f1c40f',
  description: 'Define the economic dimensions of magic in your world. From mana resources and their extraction to magical trade goods, enchanter guilds, regulatory frameworks, and black markets—this domain covers how magic creates, distributes, and concentrates wealth and power.',
  tableName: 'mana_resources',
  category: 'magic',
  fields: [
    {
      name: 'resource_type',
      label: 'Resource Type',
      type: 'select',
      required: true,
      options: ['crystallized_mana', 'liquid_mana', 'ambient_field', 'biological', 'geological', 'planar_bleed', 'refined_product', 'byproduct', 'custom'],
      helpText: 'The fundamental form of this magical resource.',
    },
    {
      name: 'source_id',
      label: 'Source',
      type: 'text',
      placeholder: 'ID of the magic source that produces this resource',
      helpText: 'The magical source from which this resource originates.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type',
      helpText: 'The type of magical energy this resource contains or produces.',
    },
    {
      name: 'extraction_method',
      label: 'Extraction Method',
      type: 'textarea',
      placeholder: 'How is this resource gathered or harvested?',
      helpText: 'The techniques and tools used to extract or collect this resource.',
    },
    {
      name: 'refinement_process',
      label: 'Refinement Process',
      type: 'textarea',
      placeholder: 'How is the raw resource processed into usable form?',
      helpText: 'Steps to refine raw magical material into a form suitable for use.',
    },
    {
      name: 'quality_grades',
      label: 'Quality Grades',
      type: 'json',
      placeholder: '["crude", "refined", "pure", "transcendent"]',
      helpText: 'The quality tiers this resource is graded into.',
    },
    {
      name: 'geographic_distribution',
      label: 'Geographic Distribution',
      type: 'textarea',
      placeholder: 'Where in the world is this resource found?',
      helpText: 'The regions, biomes, or conditions where this resource naturally occurs.',
    },
    {
      name: 'total_estimated_reserves',
      label: 'Total Estimated Reserves',
      type: 'text',
      placeholder: 'e.g. vast, declining, nearly exhausted, unknown',
      helpText: 'The estimated total remaining supply of this resource.',
    },
    {
      name: 'renewability',
      label: 'Renewability',
      type: 'select',
      options: ['non_renewable', 'slowly_renewable', 'renewable', 'rapidly_renewable', 'infinite', 'unknown'],
      helpText: 'Whether and how quickly this resource replenishes naturally.',
    },
    {
      name: 'depletion_rate',
      label: 'Depletion Rate',
      type: 'text',
      placeholder: 'e.g. sustainable, accelerating, critical',
      helpText: 'How quickly current consumption is outpacing natural replenishment.',
    },
    {
      name: 'environmental_impact_of_extraction',
      label: 'Environmental Impact',
      type: 'textarea',
      placeholder: 'What damage does extraction cause to the surrounding environment?',
      helpText: 'Ecological consequences of harvesting this resource—mana dead zones, mutations, planar thinning.',
    },
    {
      name: 'controlling_entities',
      label: 'Controlling Entities',
      type: 'textarea',
      placeholder: 'Which civilizations, guilds, or factions control this resource?',
      helpText: 'The political and economic powers that control access to this resource.',
    },
    {
      name: 'strategic_importance',
      label: 'Strategic Importance',
      type: 'select',
      options: ['negligible', 'minor', 'moderate', 'major', 'critical', 'existential'],
      helpText: 'How important this resource is to geopolitical power and military capability.',
    },
    {
      name: 'market_structure',
      label: 'Market Structure',
      type: 'select',
      options: ['monopoly', 'oligopoly', 'guild_controlled', 'free_market', 'state_run', 'barter', 'auction', 'mixed'],
      helpText: 'How the market for this resource is organized and controlled.',
    },
    {
      name: 'black_market_details',
      label: 'Black Market Details',
      type: 'textarea',
      placeholder: 'Describe illicit trade, smuggling routes, penalties...',
      helpText: 'How this resource is traded illegally — smuggling networks, penalties for possession, price premiums.',
    },
  ],
  elementTypes: ['resource', 'trade_good', 'profession', 'regulation', 'black_market'],
  elementTypeDescriptions: {
    resource: 'A raw magical material that can be extracted, harvested, or mined — mana crystals, ley line energy, enchanted ore, or ambient magic.',
    trade_good: 'A finished or processed magical product bought and sold — enchanted items, potions, spell scrolls, or magical services.',
    profession: 'A magical occupation or career — enchanters, alchemists, ward-smiths, mana harvesters, or any job that requires magical skill.',
    regulation: 'A law, treaty, or institutional rule governing magic — licensing requirements, banned spells, trade restrictions, or safety standards.',
    black_market: 'Illegal magical trade — forbidden spells, stolen artifacts, unlicensed enchantments, or substances banned by magical authorities.',
  },
  prompts: [
    'What is the most valuable magical resource in your world, and who controls it? Has this control ever been the cause of wars?',
    'How do magical professions fit into the broader economy? Is an enchanter more like an artisan, an engineer, or a doctor in social and economic standing?',
    'What magical goods and services are available to ordinary people versus only the wealthy? Is there a magical middle class?',
    'What does the black market for magic look like? What is sold illegally, and why is it forbidden?',
    'Are magical resources being depleted? Is there a conservation movement, and do powerful interests resist it?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'crystallized_mana_resource',
      name: 'Crystallized Mana',
      description: 'Solid mana crystals mined from deep deposits — the gold standard of magical currency.',
      element_type: 'resource',
      summary: 'Precious mana crystals mined from deep beneath ley lines',
      fields: {
        resource_type: 'crystallized_mana',
        extraction_method: 'Deep mining operations in ley line convergence points. Crystals grow in geological timescales and must be carefully extracted to avoid shattering and mana release.',
        refinement_process: 'Raw crystals are cut, polished, and graded by certified mana-smiths. Impurities are burned off in controlled arcane furnaces.',
        geographic_distribution: 'Concentrated near tectonic fault lines and ancient ley line nexuses. Some surface deposits exist in magically saturated regions.',
        renewability: 'slowly_renewable',
        strategic_importance: 'critical',
        market_structure: 'guild_controlled',
      },
    },
    {
      id: 'ambient_mana_field',
      name: 'Ambient Mana Field',
      description: 'A region of naturally elevated background mana that can be harvested or tapped.',
      element_type: 'resource',
      summary: 'Naturally occurring magical energy harvested from the environment',
      fields: {
        resource_type: 'ambient_field',
        extraction_method: 'Mana collectors — tower-mounted arrays of resonant crystals that draw in and concentrate ambient magical energy from the surrounding area.',
        refinement_process: 'Collected ambient mana is compressed and stored in capacitor crystals. Low-grade but consistent output.',
        geographic_distribution: 'Strongest near ley line intersections, old-growth magical forests, and sites of historical magical events. Weakest in urban areas and mana-dead zones.',
        renewability: 'renewable',
        strategic_importance: 'major',
        market_structure: 'mixed',
      },
    },
    {
      id: 'biological_magic_source',
      name: 'Biological Magic Source',
      description: 'Magical materials harvested from living or recently living organisms.',
      element_type: 'resource',
      summary: 'Magical reagents and materials harvested from enchanted creatures and plants',
      fields: {
        resource_type: 'biological',
        extraction_method: 'Harvesting from magical creatures (scales, blood, heartstone), cultivating magical plants, or collecting natural magical secretions like phoenix tears or unicorn hair.',
        refinement_process: 'Biological materials are preserved through alchemical processes, then ground, distilled, or infused depending on the intended use.',
        geographic_distribution: 'Wherever magical flora and fauna thrive — primarily old-growth magical forests, deep oceans, and planar border regions.',
        renewability: 'renewable',
        strategic_importance: 'moderate',
        market_structure: 'free_market',
        environmental_impact_of_extraction: 'Overharvesting threatens magical species. Poaching of rare creatures is a major conservation and law enforcement challenge.',
      },
    },
    {
      id: 'stolen_futures',
      name: 'Temporal Mana Futures',
      description: 'Mana borrowed from the future — spend it now, but somewhere down the timeline, someone pays the debt with interest.',
      element_type: 'trade_good',
      summary: 'Magical energy extracted from future timelines — powerful now, catastrophic later',
      fields: {
        resource_type: 'custom',
        extraction_method: 'Temporal siphoning rituals draw mana from potential futures. The process is simple — worryingly so — and the mana is high-purity. The problem is that every unit borrowed creates a mana-debt that compounds across time.',
        refinement_process: 'None needed — temporal mana arrives pre-refined. This is part of what makes it so dangerous and attractive.',
        geographic_distribution: 'Can be extracted anywhere with a trained temporal mage. Concentration is highest near temporal anomalies, thin spots in the timestream, and sites of prophecy.',
        renewability: 'unknown',
        strategic_importance: 'existential',
        market_structure: 'auction',
        environmental_impact_of_extraction: 'Localized temporal instability — clocks run backward, people experience déjà vu, cause and effect occasionally reverse. Heavy extraction creates temporal dead zones where the future has been "spent" and nothing new can happen.',
        controlling_entities: 'Officially banned by every major civilization. In practice, a shadow network of temporal brokers operates across borders. Some governments are secretly the largest buyers.',
      },
    },
    {
      id: 'enchanter_guild',
      name: 'Enchanter\'s Guild',
      description: 'A powerful professional guild that monopolizes enchantment services. Controls quality, pricing, and who can practice.',
      element_type: 'profession',
      summary: 'A monopolistic guild controlling who may enchant, what they charge, and how good it has to be',
      detailed_notes: 'The Enchanter\'s Guild emerged from centuries of unregulated enchantment — a period marked by fraudulent enchantments, dangerous failures, and price-gouging. The guild standardized training, established quality grades, and created a licensing system that effectively bars unlicensed enchanters from legal practice. Guild members benefit from collective bargaining, shared research, and legal protection. Critics argue the guild has become a monopoly that inflates prices, stifles innovation, and gates access to enchantment services behind wealth and social connections. Underground enchanters operate outside the guild, offering cheaper work of variable quality — and risking severe legal penalties.',
      fields: {
        resource_type: 'refined_product',
        extraction_method: 'Guild members perform enchantments using standardized techniques and certified materials. Apprenticeship takes seven years, followed by a masterwork examination. Only licensed guild members may legally sell enchantment services.',
        refinement_process: 'Raw magical materials are processed in guild-certified workshops using approved methods. Each enchanted item receives a guild seal certifying its quality grade and the enchanter responsible.',
        geographic_distribution: 'Guild halls in every major city, with regional chapters in larger towns. Rural areas are underserved — traveling guild enchanters visit on seasonal circuits, charging premium rates.',
        renewability: 'renewable',
        strategic_importance: 'major',
        market_structure: 'guild_controlled',
        controlling_entities: 'The Grand Council of Enchanters sets policy, pricing floors, and licensing standards. Regional guild-masters enforce compliance. The guild maintains close relationships with governments, who rely on guild services for military and infrastructure enchantments.',
        black_market_details: 'Unlicensed enchanters operate in back alleys and frontier towns, offering work at half the guild rate. Quality ranges from surprisingly competent journeymen who refused to join, to dangerous amateurs whose enchantments fail catastrophically. The guild employs investigators to identify and prosecute illegal practitioners.',
      },
    },
    {
      id: 'mana_currency',
      name: 'Mana Currency',
      description: 'A society that uses raw mana as money. You literally spend magical energy to buy goods.',
      element_type: 'trade_good',
      summary: 'A monetary system where raw magical energy serves as currency — spend your power to buy your bread',
      detailed_notes: 'In mana-currency economies, standardized units of magical energy function as money. Mana is stored in certified crystals of precise capacity, issued by a central authority, and exchanged for goods and services. The system has elegant properties: mana cannot be counterfeited (each crystal has a unique resonance signature), supply is tied to real magical production, and the currency is intrinsically useful — in an emergency, you can shatter your savings and cast a spell with it. The downsides are severe: the wealthy literally have more magical power than the poor, inflation means spells get more expensive, and a banking crisis could trigger a mana explosion.',
      fields: {
        resource_type: 'crystallized_mana',
        extraction_method: 'Mana is harvested from ambient fields, ley lines, and biological sources, then compressed into standardized denomination crystals by licensed mana-minters. Each crystal is attuned to a central ledger for tracking.',
        refinement_process: 'Raw mana is purified, measured, and sealed into certified crystal vessels of standard sizes. Denominations range from motes (daily purchases) to orbs (major transactions) to cores (national-level exchanges).',
        geographic_distribution: 'Dominant in mana-rich regions where the supply of magical energy is reliable. Mana-poor regions use hybrid systems or reject mana currency entirely in favor of metal coinage.',
        renewability: 'renewable',
        strategic_importance: 'critical',
        market_structure: 'state_run',
        controlling_entities: 'Central Mana Banks regulate supply, set interest rates (measured in mana-flow), and maintain the ledger crystals. Governments derive power from their ability to mint and control mana currency.',
        environmental_impact_of_extraction: 'Currency production requires continuous mana harvesting, creating economic pressure to exploit mana sources. Regions whose mana is extracted for currency production experience ecological depletion while wealthy cities accumulate dangerous concentrations of stored mana.',
      },
    },
    {
      id: 'spell_insurance',
      name: 'Spell Insurance',
      description: 'A business that insures against magical accidents. The actuarial science of fireballs.',
      element_type: 'regulation',
      summary: 'An insurance industry built around the unpredictable risks of magic — premiums scaled to spell danger',
      detailed_notes: 'Spell insurance emerged after a series of catastrophic magical accidents bankrupted the individuals responsible. The industry provides coverage for property damage, personal injury, and liability arising from magical practice. Policies cover everything from alchemical workshop explosions to summoning mishaps to enchantment failures. Premiums are calculated using arcane actuarial models that factor in spell school, caster experience, local mana conditions, and historical incident rates. The industry has become a powerful force for magical safety regulation — insurers refuse to cover practitioners who skip safety protocols, effectively enforcing standards that governments struggle to mandate.',
      fields: {
        resource_type: 'refined_product',
        extraction_method: 'Insurance premiums are collected from magical practitioners, businesses that use enchanted goods, and property owners in magically active areas. Claims are investigated by specialist magical adjusters who determine fault and assess arcane damage.',
        refinement_process: 'Risk assessment involves divination-assisted actuarial modeling, historical incident analysis, and on-site magical hazard surveys. Policies are written on enchanted contracts that are self-enforcing — attempts to defraud trigger automatic claim denial.',
        geographic_distribution: 'Concentrated in urban areas with high magical activity. Major insurers operate from financial capitals. Rural and frontier areas are often deemed "uninsurable" due to lack of data and emergency response infrastructure.',
        renewability: 'renewable',
        strategic_importance: 'moderate',
        market_structure: 'oligopoly',
        controlling_entities: 'A handful of major insurance houses dominate the market, backed by vast mana reserves to cover catastrophic claims. Reinsurance — insuring the insurers — is handled by a single ancient institution with enough reserves to survive a magical apocalypse.',
        black_market_details: 'Fraudulent insurance is rampant at the margins — fake policies sold to naive practitioners, staged accidents for claims payouts, and arson-by-enchantment schemes. The insurers\' investigation departments are among the most feared magical law enforcement bodies in existence.',
      },
    },
    {
      id: 'soul_market',
      name: 'Soul Market',
      description: 'A market for trading soul fragments: memories, skills, years of life.',
      element_type: 'black_market',
      summary: 'An underground market where fragments of the soul are bought and sold — memories, skills, and years of life as commodities',
      detailed_notes: 'The Soul Market trades in the most personal currency imaginable: pieces of the self. Through forbidden necromantic and psychic techniques, soul fragments can be extracted, bottled, and sold. A warrior\'s combat reflexes, a scholar\'s decades of study, a lover\'s most passionate memories — all can be purchased and integrated by the buyer. The market operates in hidden locations, shifting to avoid authorities, and its customers include the desperate (selling memories of trauma), the ambitious (buying skills they lack time to learn), and the dying (selling remaining years to fund their heirs). Prices are set by rarity and quality — a master swordsman\'s muscle memory costs more than a farmhand\'s. The trade is universally illegal and universally practiced. Its existence raises the darkest questions about personhood: if you sell your memories of childhood, are you still the same person? If you buy another\'s skills, are your achievements your own?',
      fields: {
        resource_type: 'biological',
        extraction_method: 'Soul-tapping — a forbidden psychic technique performed by trained extractors using enchanted implements. The seller enters a trance state while the extractor isolates and removes the targeted fragment. The process is painful and disorienting. Involuntary extraction is possible but leaves obvious psychic scarring.',
        geographic_distribution: 'Soul Markets operate in the shadows of every major city. The largest and most sophisticated markets are found in cosmopolitan trade hubs where law enforcement is stretched thin. Some frontier regions tolerate the trade openly.',
        strategic_importance: 'critical',
        market_structure: 'auction',
        controlling_entities: 'A loose network of soul-brokers who verify quality, mediate disputes, and enforce the market\'s internal rules. No single entity controls the trade, but several criminal organizations provide protection and logistics in exchange for a cut of every transaction.',
        environmental_impact_of_extraction: 'Victims of excessive soul extraction become hollow — functional but emotionless, identity-less husks. Communities with heavy soul-market activity report increased depression, anomie, and a pervasive sense of loss among the general population, suggesting ambient psychic contamination.',
      },
    },
    {
      id: 'mana_bank',
      name: 'Mana Bank',
      description: 'An institution that stores and lends magical energy. Interest accrues as spell potential.',
      element_type: 'regulation',
      summary: 'A financial institution that stores mana deposits and issues mana loans — banking redefined for a magical economy',
      detailed_notes: 'Mana banks operate on the same principles as conventional banks but with magical energy instead of currency. Depositors store excess mana in crystalline vaults, earning interest as the bank invests their deposits in mana-intensive enterprises. Borrowers take mana loans to fund magical projects — enchantment workshops, ward installations, or agricultural growth-spells — and repay with interest. The system has enabled large-scale magical infrastructure that no individual practitioner could fund alone. Mana banks have become enormously powerful institutions, controlling access to magical energy and thereby influencing which projects proceed and which fail. The risk of a mana bank run — all depositors withdrawing simultaneously — is the financial system\'s greatest fear, as the resulting mana release could be physically catastrophic in addition to economically devastating.',
      fields: {
        resource_type: 'crystallized_mana',
        extraction_method: 'Depositors channel mana into standardized storage crystals maintained in the bank\'s vault. Withdrawal requires identity verification through mana-signature matching. Interest is calculated as a percentage of mana-flow and crystallized at regular intervals.',
        geographic_distribution: 'Major mana banks operate in every significant city, with headquarters in financial capitals. Branch networks extend into larger towns. Rural areas are served by traveling mana-agents who collect deposits and issue small loans.',
        strategic_importance: 'major',
        market_structure: 'oligopoly',
        controlling_entities: 'A small number of ancient banking houses control the majority of mana deposits. These institutions wield political influence rivaling governments, as their lending decisions determine which magical projects — and therefore which civilizations — thrive or wither.',
        environmental_impact_of_extraction: 'Mana banking concentrates magical energy in urban vaults, draining it from the surrounding environment. Bank districts often exhibit mana-dead zones in their immediate vicinity while the vaults themselves are dangerously over-saturated. Vault breaches release catastrophic mana surges.',
      },
    },
    {
      id: 'artifice_factory',
      name: 'Artifice Factory',
      description: 'Mass production of enchanted goods. Magical industrialization.',
      element_type: 'profession',
      summary: 'Factories that mass-produce enchanted goods — the magical equivalent of industrial manufacturing',
      detailed_notes: 'Artifice factories represent the industrialization of enchantment. Where once every magical item was a unique creation of a master enchanter, factories use standardized enchantment templates, assembly-line processes, and semi-skilled workers to produce enchanted goods at scale. Glow-lamps, warming stones, self-sharpening blades, preservation boxes — these everyday enchantments are now affordable consumer goods rather than luxury items. The factories employ hundreds of workers performing repetitive enchantment tasks, guided by master templates created by high-level artificers. The quality is consistent but uninspired — factory enchantments lack the artistry and potency of hand-crafted work. The social consequences mirror industrial revolution dynamics: traditional enchanters are displaced, factory workers face repetitive mana-exposure injuries, and enchantment guilds are locked in conflict with factory owners over labor practices and quality standards.',
      fields: {
        resource_type: 'refined_product',
        extraction_method: 'Assembly-line enchantment using standardized templates. Raw goods enter one end of the factory, pass through sequential enchantment stations where workers apply specific spell-layers, and emerge as finished enchanted products. Quality control mages inspect output at the end of the line.',
        geographic_distribution: 'Concentrated in cities with strong mana infrastructure and large labor pools. Industrial districts cluster around ley line access points for power. Factory towns have sprung up around major mana crystal deposits, combining extraction and production.',
        strategic_importance: 'major',
        market_structure: 'free_market',
        controlling_entities: 'Factory owners — a new class of magical industrialists — control production. Enchantment guilds fight for regulatory oversight and labor standards. Governments are torn between the economic benefits of cheap enchanted goods and the social costs of displacing traditional artisans.',
        environmental_impact_of_extraction: 'Factory enchantment processes produce magical waste — residual mana contaminated with spell fragments that cannot be safely recycled. Mana pollution accumulates in factory districts, causing localized wild magic events, health problems in workers, and environmental degradation. Waste disposal is poorly regulated and often involves dumping contaminated mana into waterways or soil.',
      },
    },
    {
      id: 'mana_debt',
      name: 'Mana Debt',
      description: 'Magical energy borrowed from the future. Spend now, pay later — with interest.',
      element_type: 'resource',
      summary: 'Mana borrowed against the future — powerful now, catastrophic when the bill comes due',
      detailed_notes: 'Mana debt is the practice of drawing magical energy from potential futures and spending it in the present. The mechanism varies — temporal siphoning, over-drafting ley lines, or binding future generations to repay current expenditures. The borrowed mana is high-quality and immediately available, making it irresistible for large-scale projects, wars, and infrastructure. But the debt compounds. Interest accrues as mana-entropy, and the future from which the energy was borrowed becomes impoverished. Regions that have taken on too much mana debt experience temporal instability, ecological collapse, and the gradual dimming of all magical potential. Civilizations that rely on mana debt are engaged in a slow-motion catastrophe — each generation inherits less magical potential than the last, driving them to borrow even more.',
      fields: {
        resource_type: 'custom',
        extraction_method: 'Temporal siphoning rituals draw mana from future timelines. Ley line over-drafting pulls more mana than the natural cycle can sustain. Generational binding contracts pledge descendant communities to repay with their own magical potential.',
        refinement_process: 'Borrowed mana arrives ready to use — no refinement needed. This convenience is part of what makes it so dangerous and addictive.',
        geographic_distribution: 'Mana debt is most prevalent in civilizations facing existential threats or pursuing ambitious projects beyond their natural magical means. War-torn regions, declining empires, and newly founded states are common borrowers.',
        renewability: 'non_renewable',
        strategic_importance: 'critical',
        market_structure: 'auction',
        controlling_entities: 'Shadow brokers and temporal mages facilitate the lending. Some governments are secretly the largest debtors. A few ancient institutions track the total outstanding debt and warn — mostly unheeded — of approaching collapse thresholds.',
        environmental_impact_of_extraction: 'Localized temporal instability — clocks stutter, cause and effect hiccup, and déjà vu becomes endemic. Heavy debt regions experience mana dimming as the future\'s magical potential is consumed in advance.',
      },
    },
  ],
  defaultSortField: 'resource_type',
};
