import type { DomainConfig } from '../types/domains.js';

export const magicEconomyConfig: DomainConfig = {
  id: 'magic_economy',
  name: 'Magic Economy',
  namePlural: 'Magic Economy',
  icon: 'coins',
  color: '#f1c40f',
  description: 'Define the economic dimensions of magic in your world. From mana resources and their extraction to magical trade goods, enchanter guilds, regulatory frameworks, and black markets—this domain covers how magic creates, distributes, and concentrates wealth and power.',
  tableName: 'mana_resources',
  category: 'magic',
  fields: [
    {
      name: 'resource_type',
      label: 'Resource Type',
      type: 'select',
      required: true,
      options: ['crystallized_mana', 'liquid_mana', 'ambient_field', 'biological', 'geological', 'planar_bleed', 'refined_product', 'byproduct', 'custom'],
      helpText: 'The fundamental form of this magical resource.',
    },
    {
      name: 'source_id',
      label: 'Source',
      type: 'text',
      placeholder: 'ID of the magic source that produces this resource',
      helpText: 'The magical source from which this resource originates.',
    },
    {
      name: 'energy_type_id',
      label: 'Energy Type',
      type: 'text',
      placeholder: 'ID of the magical energy type',
      helpText: 'The type of magical energy this resource contains or produces.',
    },
    {
      name: 'extraction_method',
      label: 'Extraction Method',
      type: 'textarea',
      placeholder: 'How is this resource gathered or harvested?',
      helpText: 'The techniques and tools used to extract or collect this resource.',
    },
    {
      name: 'refinement_process',
      label: 'Refinement Process',
      type: 'textarea',
      placeholder: 'How is the raw resource processed into usable form?',
      helpText: 'Steps to refine raw magical material into a form suitable for use.',
    },
    {
      name: 'quality_grades',
      label: 'Quality Grades',
      type: 'json',
      placeholder: '["crude", "refined", "pure", "transcendent"]',
      helpText: 'The quality tiers this resource is graded into.',
    },
    {
      name: 'geographic_distribution',
      label: 'Geographic Distribution',
      type: 'textarea',
      placeholder: 'Where in the world is this resource found?',
      helpText: 'The regions, biomes, or conditions where this resource naturally occurs.',
    },
    {
      name: 'total_estimated_reserves',
      label: 'Total Estimated Reserves',
      type: 'text',
      placeholder: 'e.g. vast, declining, nearly exhausted, unknown',
      helpText: 'The estimated total remaining supply of this resource.',
    },
    {
      name: 'renewability',
      label: 'Renewability',
      type: 'select',
      options: ['non_renewable', 'slowly_renewable', 'renewable', 'rapidly_renewable', 'infinite', 'unknown'],
      helpText: 'Whether and how quickly this resource replenishes naturally.',
    },
    {
      name: 'depletion_rate',
      label: 'Depletion Rate',
      type: 'text',
      placeholder: 'e.g. sustainable, accelerating, critical',
      helpText: 'How quickly current consumption is outpacing natural replenishment.',
    },
    {
      name: 'environmental_impact_of_extraction',
      label: 'Environmental Impact',
      type: 'textarea',
      placeholder: 'What damage does extraction cause to the surrounding environment?',
      helpText: 'Ecological consequences of harvesting this resource—mana dead zones, mutations, planar thinning.',
    },
    {
      name: 'controlling_entities',
      label: 'Controlling Entities',
      type: 'textarea',
      placeholder: 'Which civilizations, guilds, or factions control this resource?',
      helpText: 'The political and economic powers that control access to this resource.',
    },
    {
      name: 'strategic_importance',
      label: 'Strategic Importance',
      type: 'select',
      options: ['negligible', 'minor', 'moderate', 'major', 'critical', 'existential'],
      helpText: 'How important this resource is to geopolitical power and military capability.',
    },
  ],
  elementTypes: ['resource', 'trade_good', 'profession', 'regulation', 'black_market'],
  prompts: [
    'What is the most valuable magical resource in your world, and who controls it? Has this control ever been the cause of wars?',
    'How do magical professions fit into the broader economy? Is an enchanter more like an artisan, an engineer, or a doctor in social and economic standing?',
    'What magical goods and services are available to ordinary people versus only the wealthy? Is there a magical middle class?',
    'What does the black market for magic look like? What is sold illegally, and why is it forbidden?',
    'Are magical resources being depleted? Is there a conservation movement, and do powerful interests resist it?',
  ],
  magicPermeation: null,
  defaultSortField: 'resource_type',
};
