import type { DomainConfig } from '../types/domains.js';

export const planarSystemsConfig: DomainConfig = {
  id: 'planar_systems',
  name: 'Planar System',
  namePlural: 'Planar Systems',
  icon: 'layers',
  color: '#3498db',
  description: 'Map the planes of existence that compose your world\'s cosmological structure. From the primary material plane to elemental realms, shadow dimensions, and divine domains—define the multiverse and the connections between its layers.',
  tableName: 'planes',
  category: 'magic',
  fields: [
    {
      name: 'plane_type',
      label: 'Plane Type',
      type: 'select',
      required: true,
      options: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
      helpText: 'The fundamental classification of this plane of existence.',
    },
    {
      name: 'is_primary_material',
      label: 'Is Primary Material Plane',
      type: 'boolean',
      helpText: 'Whether this is the primary material plane where most mortal life exists.',
    },
    {
      name: 'parent_plane_id',
      label: 'Parent Plane',
      type: 'text',
      placeholder: 'ID of the containing or parent plane',
      helpText: 'The plane that contains or spawned this one, if any (e.g. a demiplane within the Astral).',
    },
    {
      name: 'accessibility',
      label: 'Accessibility',
      type: 'textarea',
      placeholder: 'How can this plane be reached? Portals, rituals, death, dreams...',
      helpText: 'Methods of travel to and from this plane—natural portals, spells, conditions, or restrictions.',
    },
    {
      name: 'physical_laws',
      label: 'Physical Laws',
      type: 'json',
      placeholder: '{"gravity": "reversed", "time": "accelerated", "matter": "fluid"}',
      helpText: 'How the fundamental laws of physics differ from the material plane.',
    },
    {
      name: 'magic_laws_override',
      label: 'Magic Laws Override',
      type: 'textarea',
      helpText: 'How the rules of magic change in this plane—amplified schools, forbidden spells, wild magic zones.',
    },
    {
      name: 'dominant_energy_type_id',
      label: 'Dominant Energy Type',
      type: 'text',
      placeholder: 'ID of the primary magical energy type',
      helpText: 'The magical energy type that dominates or saturates this plane.',
    },
    {
      name: 'time_flow_rate',
      label: 'Time Flow Rate',
      type: 'text',
      placeholder: 'e.g. 1:1, 1:100 (1 day = 100 days material), stopped, variable',
      helpText: 'How time passes relative to the material plane.',
    },
    {
      name: 'spatial_properties',
      label: 'Spatial Properties',
      type: 'select',
      options: ['euclidean', 'non_euclidean', 'infinite', 'finite_bounded', 'looping', 'fractal', 'subjective', 'layered', 'custom'],
      helpText: 'The geometric and spatial nature of this plane.',
    },
    {
      name: 'native_environment',
      label: 'Native Environment',
      type: 'textarea',
      placeholder: 'Describe the default landscape, atmosphere, and conditions...',
      helpText: 'The baseline environmental conditions that prevail across this plane.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      options: ['permanent', 'stable', 'fluctuating', 'unstable', 'collapsing', 'forming', 'ephemeral'],
      helpText: 'How structurally stable this plane is over time.',
    },
    {
      name: 'age',
      label: 'Age',
      type: 'text',
      placeholder: 'e.g. primordial, 10,000 years, recent creation',
      helpText: 'How old this plane is, or when it came into existence.',
    },
    {
      name: 'creation_myth',
      label: 'Creation Myth',
      type: 'textarea',
      placeholder: 'How was this plane created? By whom or what?',
      helpText: 'The origin story of this plane—divine creation, magical accident, natural emergence, or unknown.',
    },
  ],
  elementTypes: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
  prompts: [
    'How are the planes of your world arranged? Is there a clear hierarchy (inner/outer planes), a web of connections, or something more chaotic?',
    'What happens to a mortal body when it crosses into another plane? Can flesh survive in the Elemental Plane of Fire, or does travel require transformation?',
    'Do the planes bleed into each other at weak points? What do these planar crossings look like, and who or what guards them?',
    'How does time flow differently across the planes? Has anyone exploited this for strategic advantage—or been trapped by it?',
    'Are new planes still being created? Can a sufficiently powerful mage or deity forge a demiplane, and what are the consequences?',
  ],
  magicPermeation: null,
  defaultSortField: 'plane_type',
};
