import type { DomainConfig } from '../types/domains.js';

export const planarSystemsConfig: DomainConfig = {
  id: 'planar_systems',
  name: 'Planar System',
  namePlural: 'Planar Systems',
  icon: 'layers',
  color: '#3498db',
  description: 'Map the planes of existence that compose your world\'s cosmological structure. From the primary material plane to elemental realms, shadow dimensions, and divine domains—define the multiverse and the connections between its layers.',
  tableName: 'planes',
  category: 'magic',
  fields: [
    {
      name: 'plane_type',
      label: 'Plane Type',
      type: 'select',
      required: true,
      options: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
      helpText: 'The fundamental classification of this plane of existence.',
    },
    {
      name: 'is_primary_material',
      label: 'Is Primary Material Plane',
      type: 'boolean',
      helpText: 'Whether this is the primary material plane where most mortal life exists.',
    },
    {
      name: 'parent_plane_id',
      label: 'Parent Plane',
      type: 'text',
      placeholder: 'ID of the containing or parent plane',
      helpText: 'The plane that contains or spawned this one, if any (e.g. a demiplane within the Astral).',
    },
    {
      name: 'accessibility',
      label: 'Accessibility',
      type: 'textarea',
      placeholder: 'How can this plane be reached? Portals, rituals, death, dreams...',
      helpText: 'Methods of travel to and from this plane—natural portals, spells, conditions, or restrictions.',
    },
    {
      name: 'physical_laws',
      label: 'Physical Laws',
      type: 'json',
      placeholder: '{"gravity": "reversed", "time": "accelerated", "matter": "fluid"}',
      helpText: 'How the fundamental laws of physics differ from the material plane.',
    },
    {
      name: 'magic_laws_override',
      label: 'Magic Laws Override',
      type: 'textarea',
      helpText: 'How the rules of magic change in this plane—amplified schools, forbidden spells, wild magic zones.',
    },
    {
      name: 'dominant_energy_type_id',
      label: 'Dominant Energy Type',
      type: 'text',
      placeholder: 'ID of the primary magical energy type',
      helpText: 'The magical energy type that dominates or saturates this plane.',
    },
    {
      name: 'time_flow_rate',
      label: 'Time Flow Rate',
      type: 'text',
      placeholder: 'e.g. 1:1, 1:100 (1 day = 100 days material), stopped, variable',
      helpText: 'How time passes relative to the material plane.',
    },
    {
      name: 'spatial_properties',
      label: 'Spatial Properties',
      type: 'select',
      options: ['euclidean', 'non_euclidean', 'infinite', 'finite_bounded', 'looping', 'fractal', 'subjective', 'layered', 'custom'],
      helpText: 'The geometric and spatial nature of this plane.',
    },
    {
      name: 'native_environment',
      label: 'Native Environment',
      type: 'textarea',
      placeholder: 'Describe the default landscape, atmosphere, and conditions...',
      helpText: 'The baseline environmental conditions that prevail across this plane.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      options: ['permanent', 'stable', 'fluctuating', 'unstable', 'collapsing', 'forming', 'ephemeral'],
      helpText: 'How structurally stable this plane is over time.',
    },
    {
      name: 'age',
      label: 'Age',
      type: 'text',
      placeholder: 'e.g. primordial, 10,000 years, recent creation',
      helpText: 'How old this plane is, or when it came into existence.',
    },
    {
      name: 'creation_myth',
      label: 'Creation Myth',
      type: 'textarea',
      placeholder: 'How was this plane created? By whom or what?',
      helpText: 'The origin story of this plane—divine creation, magical accident, natural emergence, or unknown.',
    },
    {
      name: 'inhabitants',
      label: 'Inhabitants',
      type: 'textarea',
      placeholder: 'Describe who or what lives in this plane...',
      helpText: 'The beings, entities, and civilizations native to or residing in this plane.',
    },
    {
      name: 'hazards',
      label: 'Hazards',
      type: 'textarea',
      placeholder: 'Describe environmental dangers, hostile entities, reality distortions...',
      helpText: 'Dangers that threaten visitors — environmental hazards, hostile natives, reality distortions, madness effects.',
    },
  ],
  elementTypes: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
  elementTypeDescriptions: {
    material: 'The primary physical reality where mortal life exists. Solid, tangible, and governed by natural law — the foundation plane.',
    astral: 'A plane of thought, psychic energy, and the silver void between other planes. Travel here is often mental rather than physical.',
    elemental: 'A plane of pure elemental force — fire, water, earth, air, or stranger elements in their most primal, concentrated form.',
    shadow: 'A dark reflection of the material world, drained of color and warmth. Home to shadow creatures and negative energy.',
    ethereal: 'A misty, overlapping plane that coexists with the material world. Ghosts and phase-shifted travelers walk here unseen.',
    divine: 'A plane shaped by and belonging to a deity or pantheon. Its nature reflects the god\'s domain and personality.',
    demonic: 'A plane of corruption, chaos, or infernal energy. Home to demons, devils, or whatever dark beings your world names.',
    fey: 'A plane of wild, untamed nature and capricious magic. Time flows strangely, and beauty hides danger.',
    dream: 'A plane formed from the collective unconscious — shaped by the dreams, nightmares, and imaginations of sleeping minds.',
    temporal: 'A plane where time itself is a navigable dimension. Past, present, and future may coexist or branch.',
    void: 'The empty space between planes — nothingness given form, or the absence that existed before creation.',
    mirror: 'A reversed reflection of another plane, where familiar things are distorted, inverted, or subtly wrong.',
    pocket: 'A small, self-contained plane — a bubble of reality with its own rules, often artificially created.',
    demiplane: 'A minor plane crafted by a powerful being. Limited in scope but fully sovereign in its own laws.',
    custom: 'A plane that doesn\'t fit standard categories — something unique to your world\'s cosmology.',
  },
  prompts: [
    'How are the planes of your world arranged? Is there a clear hierarchy (inner/outer planes), a web of connections, or something more chaotic?',
    'What happens to a mortal body when it crosses into another plane? Can flesh survive in the Elemental Plane of Fire, or does travel require transformation?',
    'Do the planes bleed into each other at weak points? What do these planar crossings look like, and who or what guards them?',
    'How does time flow differently across the planes? Has anyone exploited this for strategic advantage—or been trapped by it?',
    'Are new planes still being created? Can a sufficiently powerful mage or deity forge a demiplane, and what are the consequences?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'material_plane',
      name: 'Material Plane',
      description: 'The primary physical reality where mortal life exists — the foundation of the planar cosmology.',
      element_type: 'material',
      summary: 'The foundational plane of physical reality',
      fields: {
        plane_type: 'material',
        is_primary_material: true,
        spatial_properties: 'euclidean',
        stability: 'permanent',
        time_flow_rate: 'Standard — all other planes measured relative to this one',
        native_environment: 'An infinite expanse containing stars, planets, and the void between them. Physical laws are consistent and predictable.',
        accessibility: 'The default plane of existence. All portals and planar travel originate from or pass through here.',
      },
    },
    {
      id: 'elemental_realm',
      name: 'Elemental Realm',
      description: 'A plane of pure elemental energy — fire, water, earth, or air in its most primal form.',
      element_type: 'elemental',
      summary: 'A plane of pure elemental force, hostile to mortal life',
      fields: {
        plane_type: 'elemental',
        is_primary_material: false,
        spatial_properties: 'infinite',
        stability: 'stable',
        time_flow_rate: 'Roughly equivalent to the material plane',
        native_environment: 'An infinite expanse dominated by a single element in its purest form. The Plane of Fire is an endless inferno; the Plane of Water, a boundless ocean without surface or floor.',
        hazards: 'Unprotected mortals face instant death from environmental exposure. Elemental storms can reshape vast regions without warning.',
        inhabitants: 'Elemental beings of varying intelligence — from mindless motes to ancient elemental lords of godlike power.',
      },
    },
    {
      id: 'shadow_plane',
      name: 'Shadow Plane',
      description: 'A dark reflection of the material world, drained of color and infused with negative energy.',
      element_type: 'shadow',
      summary: 'A twilight mirror-world where reality frays at the edges',
      fields: {
        plane_type: 'shadow',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Subjective — hours can pass as minutes, or days as moments',
        native_environment: 'A dim, desaturated mirror of the material plane. Familiar landmarks exist but warped — buildings crumble, forests are skeletal, distances shift. Perpetual twilight.',
        hazards: 'Prolonged exposure drains vitality and color from living beings. Shadow creatures hunt by sensing life-force. Navigation is unreliable as geography shifts.',
        accessibility: 'Accessible through deep shadows, mirrors at midnight, or necromantic rituals. The barrier thins near sites of death and despair.',
      },
    },
    {
      id: 'fey_wilds',
      name: 'Fey Wilds',
      description: 'A plane of wild, untamed nature and capricious magic, home to the fey courts.',
      element_type: 'fey',
      summary: 'An enchanted wilderness ruled by the mercurial fey courts',
      fields: {
        plane_type: 'fey',
        is_primary_material: false,
        spatial_properties: 'subjective',
        stability: 'fluctuating',
        time_flow_rate: 'Wildly inconsistent — a night in the Feywild might be a year in the material plane, or vice versa',
        native_environment: 'A hyper-vivid version of the natural world — colors are brighter, emotions more intense, seasons change with the moods of the fey courts. Ancient forests stretch forever.',
        hazards: 'Time dilation can strand travelers for decades. Fey bargains are binding and literally enforced. Consuming fey food may trap you permanently.',
        inhabitants: 'The Seelie and Unseelie courts, nature spirits, talking beasts, trickster sprites, and ancient beings of terrifying beauty.',
      },
    },
    {
      id: 'living_plane',
      name: 'The Living Plane',
      description: 'This plane IS a creature. Its terrain is flesh, its weather is breath, and its earthquakes are heartbeats.',
      element_type: 'custom',
      summary: 'A plane of existence that is itself a living, thinking entity',
      fields: {
        plane_type: 'custom',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Tied to the entity\'s biological rhythms — time accelerates when it\'s active, nearly stops when it sleeps',
        native_environment: 'The "ground" is warm and faintly pulsing. Rivers carry a fluid that isn\'t quite water. Mountains rise and fall over decades like slow breathing. The sky is a membrane, and beyond it — another organ.',
        hazards: 'The entity\'s immune system attacks intruders. Antibody-creatures hunt foreign beings. Staying too long risks being absorbed and becoming part of the plane. If the entity dreams, local reality warps to match.',
        inhabitants: 'Symbiotic cultures that have adapted to life inside the entity — they maintain its health in exchange for shelter. Parasitic factions also exist, and the war between symbiote and parasite defines planar politics.',
      },
    },
    {
      id: 'bleeding_wound',
      name: 'Planar Wound',
      description: 'A place where two planes overlap and merge. Reality is unstable — physics from both planes apply simultaneously.',
      element_type: 'pocket',
      summary: 'A rift where two planes bleed into each other, creating a zone of dual reality',
      detailed_notes: 'Planar wounds occur when the barrier between two planes ruptures rather than forming a clean portal. The result is a region where both sets of physical laws, magic rules, and environmental conditions coexist. Gravity might pull in two directions. Fire and water occupy the same space. Creatures from both planes wander in, confused and hostile. The wound may heal on its own, be sealed by powerful magic, or slowly widen until one plane consumes the other.',
      fields: {
        plane_type: 'pocket',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'unstable',
        time_flow_rate: 'Erratic — time stutters and lurches as two temporal flows compete for dominance',
        native_environment: 'A surreal landscape where terrain from both planes intermingles. Trees made of crystal grow from volcanic soil. Snow falls upward into a burning sky. The boundaries shift constantly, and pockets of pure reality from either plane form and dissolve.',
        accessibility: 'Planar wounds are visible from both planes as shimmering distortions. Walking into one is easy — walking out is harder, as the exit shifts with each fluctuation.',
        hazards: 'Contradictory physics can tear matter apart. Visitors may be subject to two gravities, two atmospheres, or two magical fields at once. Creatures native to one plane may be hostile to beings from the other. Reality storms sweep through without warning.',
        inhabitants: 'Scavengers and refugees from both planes, along with hybrid creatures that have adapted to the dual-reality environment. Some scholars and mages study wounds at great personal risk.',
      },
    },
    {
      id: 'prison_plane',
      name: 'Sealed Prison Plane',
      description: 'A plane designed to contain something — sealed by ancient magic, now weakening. What\'s inside wants out.',
      element_type: 'demiplane',
      summary: 'A demiplane constructed as an inescapable prison, its seals now failing',
      detailed_notes: 'Prison planes are purpose-built demiplanes designed to contain entities too powerful to destroy. The original architects layered redundant seals, self-repairing wards, and reality-anchors to prevent escape. But nothing lasts forever. Entropy, external interference, or the sheer will of the prisoner has weakened the bindings. The plane itself may be aware of its purpose, actively working to maintain containment — or it may have been corrupted by its prisoner over the millennia.',
      fields: {
        plane_type: 'demiplane',
        is_primary_material: false,
        spatial_properties: 'finite_bounded',
        stability: 'unstable',
        time_flow_rate: 'Deliberately slowed — one year inside equals a century outside, to make the sentence feel shorter to the prisoner and longer to the world',
        native_environment: 'The interior reflects the nature of the prisoner. A demon\'s prison is scorched and sulfurous. An elder god\'s prison is a void of maddening geometry. The walls are inscribed with containment runes that pulse with fading light.',
        accessibility: 'Sealed by layers of ancient magic. The original keys were destroyed or hidden. Some seals have cracked, allowing whispers and influence to leak out — and occasionally letting foolish explorers in.',
        hazards: 'The prisoner\'s influence pervades everything. Dreams turn to nightmares near the inner seals. The plane itself may test intruders, unable to distinguish between would-be liberators and inspectors. If the prisoner escapes, the plane collapses.',
        inhabitants: 'The prisoner and whatever lesser beings have been drawn in or created by the prisoner\'s residual power. Guardian constructs built by the original architects may still patrol, though their loyalty is uncertain after so long.',
        creation_myth: 'Built by a coalition of the most powerful mages and gods of a prior age, at tremendous cost. The construction itself is a historical event — entire civilizations contributed resources and lives to the project.',
      },
    },
    {
      id: 'echo_plane',
      name: 'Echo Plane',
      description: 'A plane that replays past events on an eternal loop. Walk through frozen moments in history.',
      element_type: 'temporal',
      summary: 'A temporal plane where history replays in an endless, unchangeable cycle',
      detailed_notes: 'Echo planes are temporal anomalies where significant historical events have been imprinted so deeply into the fabric of reality that they replay endlessly. Visitors can walk through ancient battles, witness forgotten rituals, or observe the daily life of civilizations that vanished millennia ago. The echoes are not aware of observers and cannot be interacted with — they are recordings, not time travel. However, some echoes have begun to deviate from their original patterns, suggesting the plane itself may be developing a form of memory or intent.',
      fields: {
        plane_type: 'temporal',
        is_primary_material: false,
        spatial_properties: 'looping',
        stability: 'stable',
        time_flow_rate: 'Cyclical — each loop replays the same period of time, typically lasting hours to days before resetting. Visitors experience time normally but the environment resets around them.',
        native_environment: 'A perfect recreation of the time and place being echoed. A battle-echo shows the battlefield in pristine detail — the weather, the terrain, the armies. Between loops, the plane goes dark and still for a brief, unsettling moment before snapping back to the beginning.',
        accessibility: 'Echo planes form naturally at sites of tremendous historical significance. Accessing them requires temporal magic or stumbling through a thin spot at exactly the right moment in the loop cycle.',
        hazards: 'Becoming "entrained" in the loop — visitors who stay too long begin to fade into the echo, becoming part of the replay. Temporal disorientation makes it difficult to distinguish echo from reality. Some echoes contain events so traumatic that witnessing them causes psychic damage.',
        inhabitants: 'The echoes themselves are not truly alive, but some echo planes have attracted temporal scholars, historians seeking primary sources, and ghosts who have confused the echo for their actual past.',
      },
    },
    {
      id: 'memory_palace',
      name: 'Memory Palace',
      description: 'A plane formed from the accumulated memories of all who have died.',
      element_type: 'dream',
      summary: 'A vast plane built from the collected memories of the dead — an afterlife of recollection',
      detailed_notes: 'The Memory Palace is not a single palace but an ever-expanding plane constructed from the memories of every sentient being who has ever died. Upon death, a being\'s memories are absorbed into the plane, manifesting as physical locations — a beloved childhood home becomes a room, a lifetime of travel becomes a corridor of landscapes, a traumatic memory becomes a locked chamber. The plane is navigable but disorienting: walking through a door might take you from a farmer\'s sunset memory into a general\'s battlefield recollection. Explorers who visit seek lost knowledge, messages from the dead, or simply the experience of walking through another person\'s life. The danger is becoming lost — the plane is infinite and growing, and the memories are seductive. Many visitors become absorbed, their own memories merging with the plane while their bodies waste away in the material world.',
      fields: {
        plane_type: 'dream',
        is_primary_material: false,
        spatial_properties: 'subjective',
        stability: 'stable',
        time_flow_rate: 'Subjective — a visitor can experience years of memories in hours, or hours of memories in years. Time follows emotional weight, not clocks.',
        native_environment: 'An infinite labyrinth of remembered places — sunlit kitchens, rain-soaked battlefields, childhood bedrooms, alien landscapes. Each space is vivid and detailed, drawn from the actual memories of the dead. The architecture is impossible, connecting memories from different lives and eras without regard for geography or chronology.',
        accessibility: 'Accessible through deep meditation at sites of mass death, necromantic rituals, or natural planar thin-spots at ancient cemeteries. Some claim to reach it through intense nostalgia.',
        hazards: 'Memory absorption — visitors begin reliving others\' memories as their own, losing track of their identity. Traumatic memories manifest as hostile environments. The deeper one travels, the older and more alien the memories become, pre-dating any living culture.',
        inhabitants: 'Memory echoes of the dead — not ghosts, but vivid impressions that behave as the original person would have in that memory. They cannot learn or change. Rare visitors who became permanently absorbed wander as confused shades carrying fragments of hundreds of identities.',
      },
    },
    {
      id: 'inverse_plane',
      name: 'Inverse Plane',
      description: 'Where physical laws are reversed: fire cools, gravity repels, light darkens.',
      element_type: 'mirror',
      summary: 'A mirror-world where every physical law operates in reverse — beautiful, deadly, and deeply wrong',
      detailed_notes: 'The Inverse Plane is a reflection of the material world where every fundamental law operates in reverse. Fire absorbs heat, making things colder. Gravity pushes away from mass, requiring travelers to anchor themselves to surfaces. Light creates darkness, and shadows illuminate. Sound travels backward — you hear words before they are spoken. Healing magic causes harm, and harmful magic heals. The plane is not malicious; it simply runs on opposite principles. For scholars, it is an invaluable laboratory for understanding physical laws by observing their negation. For travelers, it is a nightmare of constant counter-intuitive danger where every survival instinct is exactly wrong.',
      fields: {
        plane_type: 'mirror',
        is_primary_material: false,
        spatial_properties: 'euclidean',
        stability: 'stable',
        time_flow_rate: 'Reversed in perception — inhabitants experience events in reverse chronological order, though visitors retain their normal time-sense, creating disorienting interactions.',
        native_environment: 'A landscape recognizable as a distorted reflection of the material plane, but wrong in every detail. Rivers flow uphill. Rain falls upward from the ground. Trees grow downward from a soil-sky. The horizon curves the wrong way.',
        accessibility: 'Accessible through perfectly reflective surfaces under specific conditions — mirrors at midnight, still pools during eclipses, or polished metal at the moment of a law\'s reversal (a fire going out, an object reaching the apex of a throw).',
        hazards: 'Every survival instinct is inverted. Running from danger brings you closer. Shielding yourself with armor makes you more vulnerable. Eating nourishing food starves you. Breathing fresh air suffocates. Visitors must consciously override every natural impulse.',
        inhabitants: 'Inverse beings — creatures that evolved under reversed physics and find the material plane as hostile as visitors find theirs. Rare scholars maintain research outposts at the boundary, studying inverse physics from a safe distance.',
      },
    },
    {
      id: 'boundary_plane',
      name: 'Boundary Plane',
      description: 'Exists only at the borders between other planes. Impossibly thin.',
      element_type: 'pocket',
      summary: 'A plane that exists only in the spaces between other planes — an infinitely thin membrane separating realities',
      detailed_notes: 'The Boundary Plane has no interior — it is pure edge. It exists as the membrane separating every other plane from its neighbors, an infinitely thin space that is somehow navigable. Travelers who enter the Boundary Plane can walk along the borders between realities, peering into adjacent planes through the translucent membrane on either side. The plane is invaluable for planar cartographers, as it provides a map of the entire cosmological structure — every plane is visible as a neighboring surface, and their relative positions and connections can be studied. However, the Boundary Plane is structurally fragile. Puncturing the membrane in either direction opens a rift between the planes on each side, and the Boundary Plane itself can tear, creating planar wounds. Those who dwell here — and a few beings do — are obsessed with maintaining the membrane\'s integrity, viewing themselves as custodians of cosmological stability.',
      fields: {
        plane_type: 'pocket',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Variable — time in the Boundary Plane matches whichever adjacent plane exerts the stronger temporal influence at any given point, creating zones of different time flow along its length.',
        native_environment: 'An impossibly thin corridor with translucent walls on either side, through which the adjacent planes are dimly visible. The floor is the membrane itself — firm but flexible, vibrating with the energies of neighboring realities. Colors shift as one walks, reflecting the nature of the planes on either side.',
        accessibility: 'Accessible at points where two planes nearly touch — planar thin-spots, portal edges, and the margins of demiplanes. Experienced planar travelers can slip sideways into the Boundary at any inter-planar crossing.',
        hazards: 'The membrane is thin and fragile — careless movement or combat can puncture it, opening rifts between adjacent planes with catastrophic results. Spatial compression means distance is unreliable. The plane narrows to nothing at certain points, trapping the unwary.',
        inhabitants: 'The Membrane Wardens — ancient beings of unknown origin who patrol the Boundary Plane, repairing tears and sealing rifts. They do not communicate with visitors but will violently expel anyone who damages the membrane.',
      },
    },
    {
      id: 'shadow_realm',
      name: 'Shadow Realm',
      description: 'A dark reflection of the material world, drained of color and warmth.',
      element_type: 'shadow',
      summary: 'A bleak mirror-world of twilight and decay where light goes to die',
      fields: {
        plane_type: 'shadow',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Subjective — time stretches and compresses without pattern',
        native_environment: 'A desaturated echo of the material world. Structures exist in decayed form, landscapes are muted and distorted, and a perpetual grey twilight hangs over everything. Sound is muffled. Colors drain from visitors the longer they stay.',
        hazards: 'Life force drains slowly but relentlessly. Shadow creatures stalk anything that radiates warmth or light. Emotional despair deepens with exposure, and prolonged stays risk permanent loss of vitality.',
        accessibility: 'Thin spots form in deep shadows, graveyards, and places of despair. Necromantic rituals and shadow magic can open passages deliberately.',
      },
    },
    {
      id: 'elemental_bastion',
      name: 'Elemental Bastion',
      description: 'A plane of pure elemental force in its most concentrated form.',
      element_type: 'elemental',
      summary: 'A fortress-plane of pure elemental power, overwhelming and absolute',
      fields: {
        plane_type: 'elemental',
        is_primary_material: false,
        spatial_properties: 'infinite',
        stability: 'stable',
        time_flow_rate: 'Roughly equivalent to the material plane',
        native_environment: 'An infinite expanse of a single element at its most extreme — an ocean of liquid fire, a continent of living stone, an endless hurricane, or an abyss of crushing water. No compromise, no mixture, no mercy.',
        hazards: 'Instant death for unprotected mortals. The element is not hostile — it simply IS, and anything that cannot survive pure elemental force is destroyed by proximity.',
        inhabitants: 'Elemental lords of immense power rule territories within the bastion. Lesser elementals swarm like wildlife. Rare mortal outposts exist inside protective wards, trading with elementals for raw materials.',
      },
    },
    {
      id: 'fey_wild',
      name: 'Fey Wild',
      description: 'A plane of untamed nature and capricious magic, home to the fey courts.',
      element_type: 'fey',
      summary: 'An enchanted wilderness where beauty and danger are the same thing',
      fields: {
        plane_type: 'fey',
        is_primary_material: false,
        spatial_properties: 'subjective',
        stability: 'fluctuating',
        time_flow_rate: 'Wildly variable — a day here might be a year in the material plane, or a century might pass in an afternoon',
        native_environment: 'A hyper-saturated version of the natural world — colors painfully vivid, emotions magnified, seasons shifting with the whims of the fey courts. Forests stretch beyond reason, rivers sing, and flowers watch you pass.',
        hazards: 'Time dilation strands travelers for lifetimes. Fey bargains are magically binding and always have a hidden cost. Eating fey food binds you to the plane. Beauty itself is dangerous — visitors forget to leave.',
        inhabitants: 'The Seelie and Unseelie courts vie for dominance. Trickster sprites, ancient treants, talking beasts, and beings of terrible beauty fill the wild spaces between the courts.',
      },
    },
    {
      id: 'living_realm',
      name: 'Living Realm',
      description: 'A plane that IS a creature — terrain is flesh, weather is breath.',
      element_type: 'material',
      summary: 'A plane of existence that is itself alive — its geography is anatomy',
      fields: {
        plane_type: 'custom',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Tied to the entity\'s biological rhythms — time races when it is active, crawls when it sleeps',
        native_environment: 'The ground pulses with warmth. Rivers carry something thicker than water. Mountains rise and fall like breathing. The sky is a membrane, and light filters through it like sunlight through skin.',
        hazards: 'The entity\'s immune system treats visitors as infections — antibody-creatures hunt foreign life. Staying too long risks absorption into the plane\'s tissue. When the entity dreams, local reality warps unpredictably.',
        inhabitants: 'Symbiotic cultures that maintain the entity\'s health in exchange for shelter. Parasitic factions exploit it. The war between symbiote and parasite is the defining conflict of the plane.',
      },
    },
    {
      id: 'divine_domain',
      name: 'Divine Domain',
      description: 'A plane shaped by and belonging to a deity. Its nature reflects the god\'s personality, power, and purpose.',
      element_type: 'divine',
      summary: 'A personal plane of a god — paradise, fortress, or cosmic throne shaped by divine will',
      detailed_notes: 'A divine domain is not just a place where a god lives — it IS the god, externalized as geography. Every feature reflects the deity\'s nature: a war god\'s domain is an eternal battlefield, a harvest goddess\'s realm is an infinite golden field, a trickster\'s domain shifts and deceives. The plane responds to the god\'s moods — storms when angry, blooming when pleased. Mortals who enter experience the deity\'s personality as environmental pressure — a domain of justice makes lies physically painful, a domain of love makes hostility impossible. The domain is also the source of the god\'s power — damage to the domain weakens the deity, and vice versa.',
      fields: {
        plane_type: 'divine',
        is_primary_material: false,
        spatial_properties: 'infinite_within_bounds',
        stability: 'stable',
        time_flow_rate: 'At the god\'s discretion — a mortal visitor might experience hours while centuries pass outside, or vice versa',
        native_environment: 'Perfectly reflects the deity\'s nature and portfolio. A sun god\'s domain is eternally lit, a death god\'s domain is shrouded in twilight. The landscape is idealized, beautiful in a way that is specific to the god\'s aesthetics.',
        accessibility: 'By divine invitation, powerful planar magic, or death (some domains serve as afterlives for the god\'s faithful). Uninvited entry is possible but extremely dangerous — the domain itself acts as immune system.',
        hazards: 'The domain enforces the god\'s will. Acting against the deity\'s nature causes escalating discomfort, then pain, then ejection or transformation. Staying too long without the god\'s favor risks being absorbed into the domain as a permanent feature.',
        inhabitants: 'The god, their celestial servants, petitioner souls of dead worshippers, and any mortal visitors or prisoners the god has collected.',
      },
    },
  ],
  defaultSortField: 'plane_type',
};
