import type { DomainConfig } from '../types/domains.js';

export const planarSystemsConfig: DomainConfig = {
  id: 'planar_systems',
  name: 'Planar System',
  namePlural: 'Planar Systems',
  icon: 'layers',
  color: '#3498db',
  description: 'Map the planes of existence that compose your world\'s cosmological structure. From the primary material plane to elemental realms, shadow dimensions, and divine domains—define the multiverse and the connections between its layers.',
  tableName: 'planes',
  category: 'magic',
  fields: [
    {
      name: 'plane_type',
      label: 'Plane Type',
      type: 'select',
      required: true,
      options: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
      helpText: 'The fundamental classification of this plane of existence.',
    },
    {
      name: 'is_primary_material',
      label: 'Is Primary Material Plane',
      type: 'boolean',
      helpText: 'Whether this is the primary material plane where most mortal life exists.',
    },
    {
      name: 'parent_plane_id',
      label: 'Parent Plane',
      type: 'text',
      placeholder: 'ID of the containing or parent plane',
      helpText: 'The plane that contains or spawned this one, if any (e.g. a demiplane within the Astral).',
    },
    {
      name: 'accessibility',
      label: 'Accessibility',
      type: 'textarea',
      placeholder: 'How can this plane be reached? Portals, rituals, death, dreams...',
      helpText: 'Methods of travel to and from this plane—natural portals, spells, conditions, or restrictions.',
    },
    {
      name: 'physical_laws',
      label: 'Physical Laws',
      type: 'json',
      placeholder: '{"gravity": "reversed", "time": "accelerated", "matter": "fluid"}',
      helpText: 'How the fundamental laws of physics differ from the material plane.',
    },
    {
      name: 'magic_laws_override',
      label: 'Magic Laws Override',
      type: 'textarea',
      helpText: 'How the rules of magic change in this plane—amplified schools, forbidden spells, wild magic zones.',
    },
    {
      name: 'dominant_energy_type_id',
      label: 'Dominant Energy Type',
      type: 'text',
      placeholder: 'ID of the primary magical energy type',
      helpText: 'The magical energy type that dominates or saturates this plane.',
    },
    {
      name: 'time_flow_rate',
      label: 'Time Flow Rate',
      type: 'text',
      placeholder: 'e.g. 1:1, 1:100 (1 day = 100 days material), stopped, variable',
      helpText: 'How time passes relative to the material plane.',
    },
    {
      name: 'spatial_properties',
      label: 'Spatial Properties',
      type: 'select',
      options: ['euclidean', 'non_euclidean', 'infinite', 'finite_bounded', 'looping', 'fractal', 'subjective', 'layered', 'custom'],
      helpText: 'The geometric and spatial nature of this plane.',
    },
    {
      name: 'native_environment',
      label: 'Native Environment',
      type: 'textarea',
      placeholder: 'Describe the default landscape, atmosphere, and conditions...',
      helpText: 'The baseline environmental conditions that prevail across this plane.',
    },
    {
      name: 'stability',
      label: 'Stability',
      type: 'select',
      options: ['permanent', 'stable', 'fluctuating', 'unstable', 'collapsing', 'forming', 'ephemeral'],
      helpText: 'How structurally stable this plane is over time.',
    },
    {
      name: 'age',
      label: 'Age',
      type: 'text',
      placeholder: 'e.g. primordial, 10,000 years, recent creation',
      helpText: 'How old this plane is, or when it came into existence.',
    },
    {
      name: 'creation_myth',
      label: 'Creation Myth',
      type: 'textarea',
      placeholder: 'How was this plane created? By whom or what?',
      helpText: 'The origin story of this plane—divine creation, magical accident, natural emergence, or unknown.',
    },
    {
      name: 'inhabitants',
      label: 'Inhabitants',
      type: 'textarea',
      placeholder: 'Describe who or what lives in this plane...',
      helpText: 'The beings, entities, and civilizations native to or residing in this plane.',
    },
    {
      name: 'hazards',
      label: 'Hazards',
      type: 'textarea',
      placeholder: 'Describe environmental dangers, hostile entities, reality distortions...',
      helpText: 'Dangers that threaten visitors — environmental hazards, hostile natives, reality distortions, madness effects.',
    },
  ],
  elementTypes: ['material', 'astral', 'elemental', 'shadow', 'ethereal', 'divine', 'demonic', 'fey', 'dream', 'temporal', 'void', 'mirror', 'pocket', 'demiplane', 'custom'],
  prompts: [
    'How are the planes of your world arranged? Is there a clear hierarchy (inner/outer planes), a web of connections, or something more chaotic?',
    'What happens to a mortal body when it crosses into another plane? Can flesh survive in the Elemental Plane of Fire, or does travel require transformation?',
    'Do the planes bleed into each other at weak points? What do these planar crossings look like, and who or what guards them?',
    'How does time flow differently across the planes? Has anyone exploited this for strategic advantage—or been trapped by it?',
    'Are new planes still being created? Can a sufficiently powerful mage or deity forge a demiplane, and what are the consequences?',
  ],
  magicPermeation: null,
  archetypes: [
    {
      id: 'material_plane',
      name: 'Material Plane',
      description: 'The primary physical reality where mortal life exists — the foundation of the planar cosmology.',
      element_type: 'material',
      summary: 'The foundational plane of physical reality',
      fields: {
        plane_type: 'material',
        is_primary_material: true,
        spatial_properties: 'euclidean',
        stability: 'permanent',
        time_flow_rate: 'Standard — all other planes measured relative to this one',
        native_environment: 'An infinite expanse containing stars, planets, and the void between them. Physical laws are consistent and predictable.',
        accessibility: 'The default plane of existence. All portals and planar travel originate from or pass through here.',
      },
    },
    {
      id: 'elemental_realm',
      name: 'Elemental Realm',
      description: 'A plane of pure elemental energy — fire, water, earth, or air in its most primal form.',
      element_type: 'elemental',
      summary: 'A plane of pure elemental force, hostile to mortal life',
      fields: {
        plane_type: 'elemental',
        is_primary_material: false,
        spatial_properties: 'infinite',
        stability: 'stable',
        time_flow_rate: 'Roughly equivalent to the material plane',
        native_environment: 'An infinite expanse dominated by a single element in its purest form. The Plane of Fire is an endless inferno; the Plane of Water, a boundless ocean without surface or floor.',
        hazards: 'Unprotected mortals face instant death from environmental exposure. Elemental storms can reshape vast regions without warning.',
        inhabitants: 'Elemental beings of varying intelligence — from mindless motes to ancient elemental lords of godlike power.',
      },
    },
    {
      id: 'shadow_plane',
      name: 'Shadow Plane',
      description: 'A dark reflection of the material world, drained of color and infused with negative energy.',
      element_type: 'shadow',
      summary: 'A twilight mirror-world where reality frays at the edges',
      fields: {
        plane_type: 'shadow',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Subjective — hours can pass as minutes, or days as moments',
        native_environment: 'A dim, desaturated mirror of the material plane. Familiar landmarks exist but warped — buildings crumble, forests are skeletal, distances shift. Perpetual twilight.',
        hazards: 'Prolonged exposure drains vitality and color from living beings. Shadow creatures hunt by sensing life-force. Navigation is unreliable as geography shifts.',
        accessibility: 'Accessible through deep shadows, mirrors at midnight, or necromantic rituals. The barrier thins near sites of death and despair.',
      },
    },
    {
      id: 'fey_wilds',
      name: 'Fey Wilds',
      description: 'A plane of wild, untamed nature and capricious magic, home to the fey courts.',
      element_type: 'fey',
      summary: 'An enchanted wilderness ruled by the mercurial fey courts',
      fields: {
        plane_type: 'fey',
        is_primary_material: false,
        spatial_properties: 'subjective',
        stability: 'fluctuating',
        time_flow_rate: 'Wildly inconsistent — a night in the Feywild might be a year in the material plane, or vice versa',
        native_environment: 'A hyper-vivid version of the natural world — colors are brighter, emotions more intense, seasons change with the moods of the fey courts. Ancient forests stretch forever.',
        hazards: 'Time dilation can strand travelers for decades. Fey bargains are binding and literally enforced. Consuming fey food may trap you permanently.',
        inhabitants: 'The Seelie and Unseelie courts, nature spirits, talking beasts, trickster sprites, and ancient beings of terrifying beauty.',
      },
    },
    {
      id: 'living_plane',
      name: 'The Living Plane',
      description: 'This plane IS a creature. Its terrain is flesh, its weather is breath, and its earthquakes are heartbeats.',
      element_type: 'custom',
      summary: 'A plane of existence that is itself a living, thinking entity',
      fields: {
        plane_type: 'custom',
        is_primary_material: false,
        spatial_properties: 'non_euclidean',
        stability: 'fluctuating',
        time_flow_rate: 'Tied to the entity\'s biological rhythms — time accelerates when it\'s active, nearly stops when it sleeps',
        native_environment: 'The "ground" is warm and faintly pulsing. Rivers carry a fluid that isn\'t quite water. Mountains rise and fall over decades like slow breathing. The sky is a membrane, and beyond it — another organ.',
        hazards: 'The entity\'s immune system attacks intruders. Antibody-creatures hunt foreign beings. Staying too long risks being absorbed and becoming part of the plane. If the entity dreams, local reality warps to match.',
        inhabitants: 'Symbiotic cultures that have adapted to life inside the entity — they maintain its health in exchange for shelter. Parasitic factions also exist, and the war between symbiote and parasite defines planar politics.',
      },
    },
  ],
  defaultSortField: 'plane_type',
};
