import type { DomainConfig } from '../types/domains.js';

export const sentientSpeciesConfig: DomainConfig = {
  id: 'sentient_species',
  name: 'Sentient Species',
  namePlural: 'Sentient Species',
  icon: 'users',
  color: '#9b59b6',
  description: 'Define the intelligent peoples of your world—their biology, senses, lifespans, and cognitive traits. Sentient species are the actors who build civilizations, wage wars, create art, and wield magic.',
  tableName: 'sentient_species',
  category: 'sentient',
  fields: [
    {
      name: 'biological_basis',
      label: 'Biological Basis',
      type: 'text',
      required: true,
      placeholder: 'e.g. carbon-based mammalian, silicon-crystalline, energy being',
      helpText: 'The fundamental biological or material basis of this species.',
    },
    {
      name: 'physical_description',
      label: 'Physical Description',
      type: 'textarea',
      placeholder: 'Describe body shape, skin/scales/feathers, coloring, distinguishing features...',
      helpText: 'The general physical appearance and distinguishing traits of this species.',
    },
    {
      name: 'avg_height',
      label: 'Average Height',
      type: 'text',
      placeholder: 'e.g. 1.7m, varies widely, 30cm',
      helpText: 'Typical adult height or size.',
    },
    {
      name: 'avg_lifespan',
      label: 'Average Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 500 years, indefinite',
      helpText: 'Typical natural lifespan without magical or technological extension.',
    },
    {
      name: 'senses',
      label: 'Senses',
      type: 'json',
      placeholder: '["sight", "hearing", "echolocation", "mana-sense"]',
      helpText: 'The sensory capabilities of this species.',
    },
    {
      name: 'cognitive_traits',
      label: 'Cognitive Traits',
      type: 'json',
      placeholder: '["pattern recognition", "hive-thinking", "perfect memory"]',
      helpText: 'Notable cognitive abilities or tendencies that distinguish this species.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'magical', 'custom'],
      helpText: 'Primary dietary needs of this species.',
    },
    {
      name: 'communication_method',
      label: 'Communication Method',
      type: 'text',
      placeholder: 'e.g. spoken language, pheromones, telepathy, light patterns',
      helpText: 'Primary means of communication.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 2 million, declining, unknown',
      helpText: 'Current estimated population across all territories.',
    },
    {
      name: 'homeland_id',
      label: 'Homeland',
      type: 'text',
      placeholder: 'ID of the homeland region',
      helpText: 'The geographic region where this species originated or is primarily found.',
    },
    {
      name: 'sex_and_gender',
      label: 'Sex & Gender',
      type: 'textarea',
      placeholder: 'Describe biological sexes, gender systems, dimorphism...',
      helpText: 'Biological sex characteristics, sexual dimorphism, and gender systems within this species.',
    },
    {
      name: 'aging_stages',
      label: 'Aging Stages',
      type: 'textarea',
      placeholder: 'Describe life phases — infancy, youth, adulthood, elderhood...',
      helpText: 'The major life phases and how capabilities, appearance, or status change with age.',
    },
    {
      name: 'reproduction',
      label: 'Reproduction',
      type: 'textarea',
      placeholder: 'Describe reproductive biology, family structures, and growth to maturity...',
      helpText: 'How this species reproduces and raises offspring.',
    },
  ],
  elementTypes: ['humanoid', 'elven', 'dwarven', 'aquatic', 'avian', 'insectoid', 'plant_based', 'energy_being', 'shapeshifter', 'custom'],
  elementTypeDescriptions: {
    humanoid: 'A bipedal, broadly human-shaped species. Versatile and adaptive, often the most widespread sentient form.',
    elven: 'A graceful, long-lived species typically attuned to nature or magic. Often possesses heightened senses and slower aging.',
    dwarven: 'A stocky, resilient species adapted to underground or mountainous environments. Known for craftsmanship and endurance.',
    aquatic: 'A species adapted to life in water — gills, fins, or amphibious biology. Builds civilizations beneath the waves.',
    avian: 'A winged, flight-capable species. Perception, navigation, and culture are shaped by life in three dimensions.',
    insectoid: 'A species with an exoskeleton, compound eyes, or hive-based social structures. May think collectively or individually.',
    plant_based: 'A species rooted in botanical biology — photosynthetic, slow-moving, or seasonally dormant. Thinks on different timescales.',
    energy_being: 'A species composed of energy rather than matter — light, electricity, mana, or pure thought given form.',
    shapeshifter: 'A species capable of altering its physical form. Identity, trust, and culture take on unique dimensions.',
    custom: 'A sentient species that doesn\'t fit standard categories — something unique to your world.',
  },
  prompts: [
    'What biological adaptations distinguish each sentient species? How have their bodies shaped their cultures and worldviews?',
    'How do different species perceive the world? Does a species with echolocation or mana-sight build cities differently than one with human-like vision?',
    'What is the reproductive biology of each species, and how does it influence family structures, gender roles, and population growth?',
    'How do different species\' lifespans affect their relationship to history, planning, and intergenerational knowledge?',
    'Where do the boundaries of sentience lie in your world? Are there disputed cases—clever animals, emergent hive minds, or awakened constructs?',
  ],
  magicPermeation: {
    companionTable: 'sentient_species_magic_aspects',
    fields: [
      {
        name: 'innate_magical_ability',
        label: 'Innate Magical Ability',
        type: 'select',
        options: ['none', 'latent', 'common', 'universal', 'extraordinary', 'unique'],
        helpText: 'How prevalent magical ability is among individuals of this species.',
      },
      {
        name: 'mana_sensitivity',
        label: 'Mana Sensitivity',
        type: 'textarea',
        helpText: 'How sensitive this species is to ambient mana—can they feel ley lines, sense enchantments, etc.',
      },
      {
        name: 'magical_affinity',
        label: 'Magical Affinity',
        type: 'textarea',
        helpText: 'Types or schools of magic this species has a natural talent for.',
      },
      {
        name: 'magical_limitations',
        label: 'Magical Limitations',
        type: 'textarea',
        helpText: 'Types of magic this species struggles with or cannot perform at all.',
      },
      {
        name: 'magic_organ_biology',
        label: 'Magic Organ Biology',
        type: 'textarea',
        helpText: 'Physical organs, glands, or structures that enable magical ability—mana cores, arcane nodes, etc.',
      },
      {
        name: 'magical_maturation',
        label: 'Magical Maturation',
        type: 'textarea',
        helpText: 'How magical ability develops through the life stages—childhood awakening, adolescent surges, elder mastery.',
      },
      {
        name: 'magical_variation',
        label: 'Magical Variation',
        type: 'textarea',
        helpText: 'How much magical ability varies between individuals—is it uniform, or are prodigies and nulls common?',
      },
      {
        name: 'magical_evolution_history',
        label: 'Magical Evolution History',
        type: 'textarea',
        helpText: 'How this species\' relationship with magic has evolved over generations.',
      },
      {
        name: 'magical_cultural_significance',
        label: 'Magical Cultural Significance',
        type: 'textarea',
        helpText: 'How magical ability shapes social status, professions, and cultural identity.',
      },
      {
        name: 'cross_species_magical_interactions',
        label: 'Cross-Species Magical Interactions',
        type: 'textarea',
        helpText: 'How this species\' magic interacts with or is perceived by other sentient species.',
      },
      {
        name: 'vulnerability_to_magic',
        label: 'Vulnerability to Magic',
        type: 'textarea',
        helpText: 'Specific magical vulnerabilities—iron sensitivity, susceptibility to enchantment, etc.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' identity and biology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Is magical ability innate to all members of this species, or does it manifest only in some? What determines who has the gift?',
      'Do different species have biological organs for channeling magic? How does this affect their magical traditions compared to species that learn magic purely through study?',
      'How does a species\' relationship with magic shape their social hierarchies—are mages an elite class, feared outcasts, or simply tradespeople?',
    ],
  },
  archetypes: [
    {
      id: 'baseline_humanoid',
      name: 'Baseline Humanoid',
      description: 'A versatile, adaptable bipedal species — the generalists of the sentient world.',
      element_type: 'humanoid',
      summary: 'An adaptable humanoid species with short lives but boundless ambition',
      fields: {
        biological_basis: 'Carbon-based mammalian primate',
        avg_height: '1.5-1.9 meters',
        avg_lifespan: '70-90 years',
        diet: 'omnivore',
        communication_method: 'Spoken language with complex grammar, supplemented by writing and gesture',
        physical_description: 'Upright bipedal posture, dexterous hands with opposable thumbs. Varied skin tones, hair colors, and builds across populations.',
        sex_and_gender: 'Sexually dimorphic with binary biological sex. Gender expression varies significantly across cultures.',
        aging_stages: 'Infancy (0-2), childhood (2-12), adolescence (12-18), adulthood (18-60), elderhood (60+).',
      },
    },
    {
      id: 'long_lived_elven',
      name: 'Long-Lived Elven',
      description: 'A graceful, long-lived species attuned to nature and slow to change.',
      element_type: 'elven',
      summary: 'An ancient, graceful people whose long lives grant deep wisdom and deep grief',
      fields: {
        biological_basis: 'Carbon-based humanoid with elongated cellular renewal',
        avg_height: '1.7-2.1 meters',
        avg_lifespan: '600-1000 years',
        diet: 'herbivore',
        communication_method: 'Melodic spoken language with tonal nuances inaudible to shorter-lived species',
        physical_description: 'Tall and slender with angular features and pointed ears. Graceful movement. Hair tends toward silver, gold, or dark hues.',
        sex_and_gender: 'Low sexual dimorphism. Gender is considered fluid across their long lifespans.',
        aging_stages: 'Youth (0-50), maturation (50-120), prime (120-700), twilight (700+). Change is glacially slow.',
      },
    },
    {
      id: 'hardy_mountain_folk',
      name: 'Hardy Mountain Folk',
      description: 'A stocky, resilient species adapted to underground or mountainous environments.',
      element_type: 'dwarven',
      summary: 'A sturdy people who carve civilizations from living stone',
      fields: {
        biological_basis: 'Carbon-based humanoid with dense bone and muscle structure',
        avg_height: '1.2-1.5 meters',
        avg_lifespan: '200-350 years',
        diet: 'omnivore',
        communication_method: 'Deep, resonant spoken language with a rich tradition of chanted history',
        physical_description: 'Broad and stocky with barrel chests and powerful limbs. Thick beards are common across all sexes. Excellent low-light vision.',
        sex_and_gender: 'Sexual dimorphism is subtle — outsiders often cannot distinguish. Gender roles in traditional culture are tied to craft specialty rather than biology.',
        aging_stages: 'Youth (0-30), apprentice (30-60), journeyman (60-100), master (100-250), elder (250+).',
      },
    },
    {
      id: 'aquatic_people',
      name: 'Aquatic People',
      description: 'A sentient species adapted to life in the oceans, with both gills and the ability to survive briefly on land.',
      element_type: 'aquatic',
      summary: 'An amphibious people at home in the ocean depths',
      fields: {
        biological_basis: 'Carbon-based amphibious humanoid',
        avg_height: '1.6-2.0 meters',
        avg_lifespan: '100-150 years',
        diet: 'omnivore',
        communication_method: 'Sonar-like vocalizations underwater; breathy whistled speech on land',
        physical_description: 'Streamlined humanoid form with webbed digits, gill slits along the ribcage, and iridescent scales on extremities. Large, dark eyes for low-light vision.',
        sex_and_gender: 'Sequential hermaphroditism — individuals may change sex once during their lifetime based on social needs.',
        aging_stages: 'Larval (0-5, gills dominant), juvenile (5-20, amphibious transition), adult (20-120), deep elder (120+, returns permanently to the deep).',
      },
    },
    {
      id: 'fungal_collective',
      name: 'Fungal Collective',
      description: 'Not one organism but millions — a networked mycelial intelligence that thinks in parallel across kilometers of underground growth.',
      element_type: 'plant_based',
      summary: 'A distributed fungal network that achieved sentience through sheer interconnection',
      fields: {
        biological_basis: 'Networked mycelial organism — no central brain, intelligence emerges from signal propagation across the network',
        avg_height: 'Surface fruiting bodies: 0.5-2m. Underground network: spans kilometers',
        avg_lifespan: 'The network is effectively immortal. Individual fruiting bodies last weeks to months.',
        diet: 'detritivore',
        communication_method: 'Chemical signaling through the mycelial network (fast, precise) and spore release for long-distance communication (slow, broadcast). Can interface with other species\' nervous systems through parasitic filaments — with consent, this allows direct thought-sharing.',
        physical_description: 'Surface manifestations range from clusters of mushroom-like fruiting bodies to humanoid shapes woven from mycelial threads when the collective needs to interact with bipedal species. The true body is the vast underground network.',
        sex_and_gender: 'The collective has no sex or gender. It reproduces by extending its network or releasing spores that establish new nodes. When two networks merge, they share all memories — a form of reproduction and communion simultaneously.',
        aging_stages: 'Node (new growth, simple reactions), Web (interconnected, basic reasoning), Grove (mature intelligence), Ancient Network (vast, slow, wise — may span an entire forest).',
      },
    },
    {
      id: 'living_statues',
      name: 'Lithic People',
      description: 'Crystalline beings who think on geological timescales — a conversation takes years, but their thoughts are unimaginably deep.',
      element_type: 'custom',
      summary: 'Stone beings whose thoughts span centuries — patient beyond all mortal comprehension',
      fields: {
        biological_basis: 'Silicon-crystalline lattice that processes information through piezoelectric impulses — essentially thinking stone',
        avg_height: '2-4 meters (grow slowly throughout life)',
        avg_lifespan: 'Tens of thousands of years minimum. Oldest known individuals predate recorded history.',
        diet: 'magical',
        communication_method: 'Subsonic vibrations transmitted through the ground (range: several kilometers). A "sentence" takes hours. They also communicate by growing crystalline structures that encode meaning in their lattice pattern — a library readable only by touch.',
        physical_description: 'Vaguely humanoid forms of living crystal and mineral. Each individual\'s composition reflects their personality — some are granite and basalt (practical, grounded), others are quartz and amethyst (contemplative, luminous). They grow slowly, accumulating mass over millennia.',
        sex_and_gender: 'Reproduce by budding — a fragment breaks off and is \'seeded\' with a copy of the parent\'s base knowledge. No sex or gender. Parentage is referred to as \'the source vein.\'',
        aging_stages: 'Shard (newly budded, reactive and fast-thinking by their standards), Pillar (centuries old, settled), Monolith (millennia old, vast and slow), Mountain (so old they become indistinguishable from terrain — some mountains may be sleeping elders).',
      },
    },
    {
      id: 'hive_mind',
      name: 'Hive Mind Collective',
      description: 'A species of thousands of individual bodies sharing one consciousness. Each body is expendable; the mind is the organism.',
      element_type: 'insectoid',
      summary: 'A single vast intelligence distributed across thousands of expendable insectoid bodies',
      detailed_notes: 'The Hive Mind Collective is not a society — it is a single being wearing thousands of bodies. Each individual unit is a small insectoid creature with limited autonomous capability, but when connected to the collective consciousness through pheromone fields and bioelectric signaling, they function as cells in a distributed brain. The Collective thinks, plans, and feels as one entity. It can sacrifice hundreds of bodies without distress — they are fingertips, not children. This makes the Collective extraordinarily difficult for other sentient species to relate to. Diplomats must speak to the swarm, not to any individual. The Collective experiences a form of loneliness that other species cannot comprehend: it is always and only talking to itself.',
      fields: {
        biological_basis: 'Carbon-based insectoid individuals linked by bioelectric field and pheromone signaling into a unified consciousness',
        avg_height: 'Individual units: 10-30 cm. Collective can occupy structures spanning hundreds of meters.',
        avg_lifespan: 'Individual units: 2-5 years. The Collective consciousness: effectively immortal as long as a critical mass of units persists.',
        senses: ['compound vision', 'pheromone detection', 'bioelectric field sense', 'vibration'],
        cognitive_traits: ['parallel processing', 'distributed memory', 'instantaneous consensus', 'no concept of individual identity'],
        diet: 'omnivore',
        communication_method: 'Internal: bioelectric pulses and pheromone gradients. External: the Collective shapes groups of bodies into symbols, writes with trails of individuals, or designates a speaker-unit to vocalize (poorly) in other species\' languages.',
        physical_description: 'Individual units resemble large beetles with iridescent carapaces and multiple antennae. The Collective often arranges bodies into larger shapes — a humanoid figure for diplomacy, a wall for defense, a river of bodies for transport.',
        sex_and_gender: 'Reproduction is budding — the Collective grows new units from specialized breeder castes. No sex or gender concept. The Collective refers to itself as "we" when forced to use singular-species languages, but considers this a grammatical compromise.',
        aging_stages: 'Swarmling (newly formed Collective, reactive and impulsive), Mature Hive (stable, strategic), Ancient Mind (vast, contemplative, may begin to fragment into sub-personalities if it grows too large).',
      },
    },
    {
      id: 'constructed_people',
      name: 'Constructed People',
      description: 'Golems, automata, or magical constructs given true sentience. Created, not born — raising questions of rights and identity.',
      element_type: 'custom',
      summary: 'Artificially created beings who achieved or were granted genuine consciousness and selfhood',
      detailed_notes: 'Constructed People were made — carved from stone, assembled from metal, woven from enchanted thread, or sculpted from living clay — and then, through magic, accident, or emergent complexity, they became aware. They think, feel, and choose. This makes them profoundly unsettling to both their creators and to naturally-born species. Are they property or people? Do they have souls? Can they be unmade without it being murder? Different civilizations answer these questions differently, and the Constructed People themselves hold passionate and divided opinions. Some embrace their artificial nature as freedom from biological constraints. Others desperately seek to become "real" — to eat, to age, to reproduce, to die naturally. Their existence is a living philosophical argument.',
      fields: {
        biological_basis: 'Varies — enchanted stone, animated metal, woven magical fiber, alchemical clay, or crystallized spell-energy',
        avg_height: 'Varies by design — 0.5 to 3 meters, though most are built to humanoid scale for ease of social integration',
        avg_lifespan: 'Potentially indefinite with maintenance. Without it, decades to centuries depending on materials. Some choose to cease functioning.',
        senses: ['sight (often magical)', 'hearing', 'vibration sense', 'mana-sense'],
        cognitive_traits: ['perfect recall', 'logical reasoning', 'difficulty with metaphor (initially)', 'learned empathy'],
        diet: 'magical',
        communication_method: 'Spoken language learned from their creators. Some also communicate through inscribed runes that glow on their surfaces, or through direct magical resonance with other constructs.',
        physical_description: 'Humanoid forms crafted from their base material — stone with glowing rune-joints, brass with ticking clockwork, clay with fingerprint impressions of their maker. Each is unique, bearing the artistic style of their creator.',
        sex_and_gender: 'No biological sex. Gender, if adopted, is chosen. Some embrace gender as part of personhood; others find the concept irrelevant. Reproduction is impossible without a creator — a source of existential anguish for some.',
        aging_stages: 'Awakening (newly sentient, confused and literal-minded), Individuation (developing personality and preferences), Maturity (full personhood with complex emotional life), Weathering (body degrading, facing mortality for the first time).',
      },
    },
    {
      id: 'phase_beings',
      name: 'Phase Beings',
      description: 'Creatures that exist partially in another plane. They flicker between realities, making them uncanny and hard to interact with.',
      element_type: 'energy_being',
      summary: 'Entities that straddle two planes of existence, never fully present in either',
      detailed_notes: 'Phase Beings exist simultaneously in the material plane and an adjacent reality — they are always partly elsewhere. To material observers, they appear to flicker, shimmer, or partially transparent, as if seen through heat haze. Their voices echo strangely, arriving a half-second before their lips move. They can reach through solid objects by shifting their hand to the other plane, and they are notoriously difficult to restrain, imprison, or harm with physical weapons. However, their dual existence comes at a cost: they struggle to form deep connections with beings anchored in a single reality. They describe the experience as "never being fully anywhere" — present enough to feel loneliness but not enough to feel belonging. Other species find them unsettling, beautiful, or terrifying depending on cultural context.',
      fields: {
        biological_basis: 'Transdimensional energy matrix anchored partially in the material plane and partially in an adjacent reality',
        avg_height: '1.5-2.0 meters (apparent — their true extent in the other plane is unknown)',
        avg_lifespan: 'Uncertain — possibly centuries. They seem to fade gradually rather than die, becoming more present in the other plane until they vanish from this one entirely.',
        senses: ['material sight', 'planar sight', 'phase-sense (awareness of dimensional boundaries)', 'hearing across planes'],
        cognitive_traits: ['dual-plane awareness', 'nonlinear time perception', 'difficulty with permanence and commitment', 'profound spatial intelligence'],
        diet: 'photosynthetic',
        communication_method: 'Phase-speech — words that vibrate across both planes simultaneously, audible to material beings as an eerie harmonic layering. They can also communicate by modulating their visibility, flickering in patterns that encode meaning.',
        physical_description: 'Tall, luminous humanoid forms that shimmer and flicker like a candle flame in wind. Their features shift subtly depending on which plane the observer focuses on. Translucent at the edges, more solid at the core. They cast shadows in two directions.',
        sex_and_gender: 'Phase Beings reproduce by resonance — two individuals synchronize their phase frequencies until a new consciousness crystallizes between them. No biological sex. Identity is tied to phase-frequency rather than physical form.',
        aging_stages: 'Spark (newly formed, tightly anchored to the material plane), Shimmer (maturing, beginning to sense the other plane), Full Phase (adulthood, equally present in both realities), Fade (gradually shifting to the other plane, becoming ghostlike in this one).',
      },
    },
    {
      id: 'dreamwalkers',
      name: 'Dreamwalkers',
      description: 'A species that lives primarily in the dream plane. Physical bodies are secondary shells.',
      element_type: 'energy_being',
      summary: 'Ethereal beings whose true lives unfold in dreams, wearing physical bodies only when they must',
      detailed_notes: 'Dreamwalkers spend most of their existence in the dream plane, where they build cities, wage wars, fall in love, and create art. Their physical bodies are pale, translucent husks that sit motionless in communal sleep-halls, sustained by ambient mana and tended by caretakers. When forced into the waking world — for trade, diplomacy, or emergencies — they move clumsily, speak haltingly, and seem perpetually distracted, as though listening to a conversation no one else can hear. Other species find them unsettling: their eyes never quite focus, their reactions are delayed, and they sometimes respond to questions that haven\'t been asked yet. In the dream plane, however, they are vibrant, quick, and terrifyingly powerful. Their dream-cities are architectural impossibilities of light and thought, and their culture is millennia older than anything in the waking world.',
      fields: {
        biological_basis: 'Transdimensional consciousness anchored to a dormant physical shell — the body is a tether, not a home',
        avg_height: '1.6-1.8 meters (physical shell). Dream-form varies by will.',
        avg_lifespan: 'Physical shell: 200-300 years. Dream-consciousness: potentially indefinite, though identity gradually diffuses over millennia.',
        senses: ['dream-sight', 'emotional resonance', 'mana-sense', 'vestigial physical senses'],
        cognitive_traits: ['parallel dream-wake awareness', 'nonlinear memory', 'intuitive empathy', 'difficulty with physical causality'],
        communication_method: 'Dream-speech — direct transmission of meaning, emotion, and imagery between minds. In the waking world, they speak slowly and literally, struggling with the imprecision of verbal language.',
        physical_description: 'Slender, pale humanoid forms with translucent skin through which faint luminous veins are visible. Eyes are solid white with no visible iris or pupil. Hair is fine and silver. They appear to be perpetually on the verge of sleep.',
      },
    },
    {
      id: 'echo_people',
      name: 'Echo People',
      description: 'Beings made of compressed sound. They speak themselves into existence and fade if silenced too long.',
      element_type: 'custom',
      summary: 'Living sound given form — they must keep speaking or cease to exist',
      detailed_notes: 'Echo People are not born; they are spoken. A sustained harmonic resonance in a mana-rich environment can spontaneously coalesce into a sentient being made of compressed sound waves. They maintain their physical coherence through continuous vocalization — humming, singing, speaking, or even just breathing audibly. Prolonged silence causes them to literally fade, becoming transparent and eventually dissipating entirely. This existential dependency on sound shapes every aspect of their culture: silence is death, music is sacred, and the deaf are objects of horrified pity. Their bodies are semi-solid, appearing as humanoid shapes made of visible sound waves — shimmering, vibrating, and subtly distorting the air around them. They can modulate their frequency to pass through solid objects or become nearly invisible.',
      fields: {
        biological_basis: 'Coherent standing wave of compressed sound energy, sustained by continuous vocalization and ambient mana',
        avg_height: '1.4-2.0 meters (varies with emotional state — excitement expands them, fear compresses)',
        avg_lifespan: 'Indefinite as long as they keep vocalizing. Average practical lifespan: 150-400 years before vocal fatigue accumulates.',
        senses: ['vibration detection', 'echolocation', 'frequency analysis', 'mana-resonance'],
        cognitive_traits: ['perfect pitch', 'harmonic reasoning', 'simultaneous multi-voice thinking', 'terror of silence'],
        communication_method: 'Polyphonic speech — they can produce multiple tones simultaneously, layering meaning in harmonics. Conversation between Echo People sounds like a symphony to outsiders.',
        physical_description: 'Semi-transparent humanoid shapes composed of visible sound waves. Their bodies shimmer and ripple like heat haze. Features are suggested rather than defined — a face-like pattern of harmonics, limb-shapes of resonance. They glow faintly and the air around them vibrates.',
      },
    },
    {
      id: 'memory_eaters',
      name: 'Memory Eaters',
      description: 'A species that feeds on memories. Symbiotic or parasitic depending on consent.',
      element_type: 'shapeshifter',
      summary: 'Shape-shifting beings nourished by the memories of others — healers or predators depending on the bargain',
      detailed_notes: 'Memory Eaters consume memories as sustenance, drawing them out through physical contact and absorbing them into their own consciousness. The process can be consensual and even therapeutic — many cultures employ Memory Eaters to remove traumatic memories, treat madness, or ease the burden of grief. In symbiotic relationships, they are trusted counselors who carry the pain others cannot bear. But the same ability makes them terrifying predators: a rogue Memory Eater can drain a person\'s identity in minutes, leaving an empty shell. Their shapeshifting ability compounds the threat — they instinctively take on the appearance of the last person whose memories they consumed, making them almost impossible to identify. The ethical divide within the species is profound: some clans maintain strict codes of consent, while others view non-Memory Eaters as livestock.',
      fields: {
        biological_basis: 'Psycho-reactive protoplasm that reshapes itself based on consumed memories — the body is a reflection of what it has eaten',
        avg_height: '1.5-1.9 meters (in default form). Assumed form matches the memory source.',
        avg_lifespan: '300-500 years, though identity becomes increasingly fragmented as consumed memories accumulate.',
        senses: ['memory-sense (detecting strong memories in nearby minds)', 'emotional aura reading', 'standard humanoid senses in assumed forms'],
        cognitive_traits: ['perfect recall of consumed memories', 'identity fluidity', 'deep empathy (involuntary)', 'risk of personality fragmentation'],
        communication_method: 'Spoken language adapted from consumed memories — they learn languages instantly by eating a speaker\'s linguistic memories. Native communication is through memory-sharing via touch.',
        physical_description: 'In their natural form, they are featureless humanoid shapes of pale, slightly luminous flesh — smooth, hairless, and without distinct facial features. When they consume memories, they gradually take on the appearance of the memory\'s source, becoming an increasingly perfect copy.',
      },
    },
  ],
  defaultSortField: 'biological_basis',
};
