import type { DomainConfig } from '../types/domains.js';

export const sentientSpeciesConfig: DomainConfig = {
  id: 'sentient_species',
  name: 'Sentient Species',
  namePlural: 'Sentient Species',
  icon: 'users',
  color: '#9b59b6',
  description: 'Define the intelligent peoples of your world—their biology, senses, lifespans, and cognitive traits. Sentient species are the actors who build civilizations, wage wars, create art, and wield magic.',
  tableName: 'sentient_species',
  category: 'sentient',
  fields: [
    {
      name: 'biological_basis',
      label: 'Biological Basis',
      type: 'text',
      required: true,
      placeholder: 'e.g. carbon-based mammalian, silicon-crystalline, energy being',
      helpText: 'The fundamental biological or material basis of this species.',
    },
    {
      name: 'physical_description',
      label: 'Physical Description',
      type: 'textarea',
      placeholder: 'Describe body shape, skin/scales/feathers, coloring, distinguishing features...',
      helpText: 'The general physical appearance and distinguishing traits of this species.',
    },
    {
      name: 'avg_height',
      label: 'Average Height',
      type: 'text',
      placeholder: 'e.g. 1.7m, varies widely, 30cm',
      helpText: 'Typical adult height or size.',
    },
    {
      name: 'avg_lifespan',
      label: 'Average Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 500 years, indefinite',
      helpText: 'Typical natural lifespan without magical or technological extension.',
    },
    {
      name: 'senses',
      label: 'Senses',
      type: 'json',
      placeholder: '["sight", "hearing", "echolocation", "mana-sense"]',
      helpText: 'The sensory capabilities of this species.',
    },
    {
      name: 'cognitive_traits',
      label: 'Cognitive Traits',
      type: 'json',
      placeholder: '["pattern recognition", "hive-thinking", "perfect memory"]',
      helpText: 'Notable cognitive abilities or tendencies that distinguish this species.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'magical', 'custom'],
      helpText: 'Primary dietary needs of this species.',
    },
    {
      name: 'communication_method',
      label: 'Communication Method',
      type: 'text',
      placeholder: 'e.g. spoken language, pheromones, telepathy, light patterns',
      helpText: 'Primary means of communication.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 2 million, declining, unknown',
      helpText: 'Current estimated population across all territories.',
    },
    {
      name: 'homeland_id',
      label: 'Homeland',
      type: 'text',
      placeholder: 'ID of the homeland region',
      helpText: 'The geographic region where this species originated or is primarily found.',
    },
    {
      name: 'sex_and_gender',
      label: 'Sex & Gender',
      type: 'textarea',
      placeholder: 'Describe biological sexes, gender systems, dimorphism...',
      helpText: 'Biological sex characteristics, sexual dimorphism, and gender systems within this species.',
    },
    {
      name: 'aging_stages',
      label: 'Aging Stages',
      type: 'textarea',
      placeholder: 'Describe life phases — infancy, youth, adulthood, elderhood...',
      helpText: 'The major life phases and how capabilities, appearance, or status change with age.',
    },
    {
      name: 'reproduction',
      label: 'Reproduction',
      type: 'textarea',
      placeholder: 'Describe reproductive biology, family structures, and growth to maturity...',
      helpText: 'How this species reproduces and raises offspring.',
    },
  ],
  elementTypes: ['humanoid', 'elven', 'dwarven', 'aquatic', 'avian', 'insectoid', 'plant_based', 'energy_being', 'shapeshifter', 'custom'],
  prompts: [
    'What biological adaptations distinguish each sentient species? How have their bodies shaped their cultures and worldviews?',
    'How do different species perceive the world? Does a species with echolocation or mana-sight build cities differently than one with human-like vision?',
    'What is the reproductive biology of each species, and how does it influence family structures, gender roles, and population growth?',
    'How do different species\' lifespans affect their relationship to history, planning, and intergenerational knowledge?',
    'Where do the boundaries of sentience lie in your world? Are there disputed cases—clever animals, emergent hive minds, or awakened constructs?',
  ],
  magicPermeation: {
    companionTable: 'sentient_species_magic_aspects',
    fields: [
      {
        name: 'innate_magical_ability',
        label: 'Innate Magical Ability',
        type: 'select',
        options: ['none', 'latent', 'common', 'universal', 'extraordinary', 'unique'],
        helpText: 'How prevalent magical ability is among individuals of this species.',
      },
      {
        name: 'mana_sensitivity',
        label: 'Mana Sensitivity',
        type: 'textarea',
        helpText: 'How sensitive this species is to ambient mana—can they feel ley lines, sense enchantments, etc.',
      },
      {
        name: 'magical_affinity',
        label: 'Magical Affinity',
        type: 'textarea',
        helpText: 'Types or schools of magic this species has a natural talent for.',
      },
      {
        name: 'magical_limitations',
        label: 'Magical Limitations',
        type: 'textarea',
        helpText: 'Types of magic this species struggles with or cannot perform at all.',
      },
      {
        name: 'magic_organ_biology',
        label: 'Magic Organ Biology',
        type: 'textarea',
        helpText: 'Physical organs, glands, or structures that enable magical ability—mana cores, arcane nodes, etc.',
      },
      {
        name: 'magical_maturation',
        label: 'Magical Maturation',
        type: 'textarea',
        helpText: 'How magical ability develops through the life stages—childhood awakening, adolescent surges, elder mastery.',
      },
      {
        name: 'magical_variation',
        label: 'Magical Variation',
        type: 'textarea',
        helpText: 'How much magical ability varies between individuals—is it uniform, or are prodigies and nulls common?',
      },
      {
        name: 'magical_evolution_history',
        label: 'Magical Evolution History',
        type: 'textarea',
        helpText: 'How this species\' relationship with magic has evolved over generations.',
      },
      {
        name: 'magical_cultural_significance',
        label: 'Magical Cultural Significance',
        type: 'textarea',
        helpText: 'How magical ability shapes social status, professions, and cultural identity.',
      },
      {
        name: 'cross_species_magical_interactions',
        label: 'Cross-Species Magical Interactions',
        type: 'textarea',
        helpText: 'How this species\' magic interacts with or is perceived by other sentient species.',
      },
      {
        name: 'vulnerability_to_magic',
        label: 'Vulnerability to Magic',
        type: 'textarea',
        helpText: 'Specific magical vulnerabilities—iron sensitivity, susceptibility to enchantment, etc.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' identity and biology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Is magical ability innate to all members of this species, or does it manifest only in some? What determines who has the gift?',
      'Do different species have biological organs for channeling magic? How does this affect their magical traditions compared to species that learn magic purely through study?',
      'How does a species\' relationship with magic shape their social hierarchies—are mages an elite class, feared outcasts, or simply tradespeople?',
    ],
  },
  defaultSortField: 'biological_basis',
};
