import type { DomainConfig } from '../types/domains.js';

export const sentientSpeciesConfig: DomainConfig = {
  id: 'sentient_species',
  name: 'Sentient Species',
  namePlural: 'Sentient Species',
  icon: 'users',
  color: '#9b59b6',
  description: 'Define the intelligent peoples of your world—their biology, senses, lifespans, and cognitive traits. Sentient species are the actors who build civilizations, wage wars, create art, and wield magic.',
  tableName: 'sentient_species',
  category: 'sentient',
  fields: [
    {
      name: 'biological_basis',
      label: 'Biological Basis',
      type: 'text',
      required: true,
      placeholder: 'e.g. carbon-based mammalian, silicon-crystalline, energy being',
      helpText: 'The fundamental biological or material basis of this species.',
    },
    {
      name: 'physical_description',
      label: 'Physical Description',
      type: 'textarea',
      placeholder: 'Describe body shape, skin/scales/feathers, coloring, distinguishing features...',
      helpText: 'The general physical appearance and distinguishing traits of this species.',
    },
    {
      name: 'avg_height',
      label: 'Average Height',
      type: 'text',
      placeholder: 'e.g. 1.7m, varies widely, 30cm',
      helpText: 'Typical adult height or size.',
    },
    {
      name: 'avg_lifespan',
      label: 'Average Lifespan',
      type: 'text',
      placeholder: 'e.g. 80 years, 500 years, indefinite',
      helpText: 'Typical natural lifespan without magical or technological extension.',
    },
    {
      name: 'senses',
      label: 'Senses',
      type: 'json',
      placeholder: '["sight", "hearing", "echolocation", "mana-sense"]',
      helpText: 'The sensory capabilities of this species.',
    },
    {
      name: 'cognitive_traits',
      label: 'Cognitive Traits',
      type: 'json',
      placeholder: '["pattern recognition", "hive-thinking", "perfect memory"]',
      helpText: 'Notable cognitive abilities or tendencies that distinguish this species.',
    },
    {
      name: 'diet',
      label: 'Diet',
      type: 'select',
      options: ['herbivore', 'carnivore', 'omnivore', 'filter_feeder', 'photosynthetic', 'detritivore', 'magical', 'custom'],
      helpText: 'Primary dietary needs of this species.',
    },
    {
      name: 'communication_method',
      label: 'Communication Method',
      type: 'text',
      placeholder: 'e.g. spoken language, pheromones, telepathy, light patterns',
      helpText: 'Primary means of communication.',
    },
    {
      name: 'population',
      label: 'Population',
      type: 'text',
      placeholder: 'e.g. 2 million, declining, unknown',
      helpText: 'Current estimated population across all territories.',
    },
    {
      name: 'homeland_id',
      label: 'Homeland',
      type: 'text',
      placeholder: 'ID of the homeland region',
      helpText: 'The geographic region where this species originated or is primarily found.',
    },
    {
      name: 'sex_and_gender',
      label: 'Sex & Gender',
      type: 'textarea',
      placeholder: 'Describe biological sexes, gender systems, dimorphism...',
      helpText: 'Biological sex characteristics, sexual dimorphism, and gender systems within this species.',
    },
    {
      name: 'aging_stages',
      label: 'Aging Stages',
      type: 'textarea',
      placeholder: 'Describe life phases — infancy, youth, adulthood, elderhood...',
      helpText: 'The major life phases and how capabilities, appearance, or status change with age.',
    },
    {
      name: 'reproduction',
      label: 'Reproduction',
      type: 'textarea',
      placeholder: 'Describe reproductive biology, family structures, and growth to maturity...',
      helpText: 'How this species reproduces and raises offspring.',
    },
  ],
  elementTypes: ['humanoid', 'elven', 'dwarven', 'aquatic', 'avian', 'insectoid', 'plant_based', 'energy_being', 'shapeshifter', 'custom'],
  prompts: [
    'What biological adaptations distinguish each sentient species? How have their bodies shaped their cultures and worldviews?',
    'How do different species perceive the world? Does a species with echolocation or mana-sight build cities differently than one with human-like vision?',
    'What is the reproductive biology of each species, and how does it influence family structures, gender roles, and population growth?',
    'How do different species\' lifespans affect their relationship to history, planning, and intergenerational knowledge?',
    'Where do the boundaries of sentience lie in your world? Are there disputed cases—clever animals, emergent hive minds, or awakened constructs?',
  ],
  magicPermeation: {
    companionTable: 'sentient_species_magic_aspects',
    fields: [
      {
        name: 'innate_magical_ability',
        label: 'Innate Magical Ability',
        type: 'select',
        options: ['none', 'latent', 'common', 'universal', 'extraordinary', 'unique'],
        helpText: 'How prevalent magical ability is among individuals of this species.',
      },
      {
        name: 'mana_sensitivity',
        label: 'Mana Sensitivity',
        type: 'textarea',
        helpText: 'How sensitive this species is to ambient mana—can they feel ley lines, sense enchantments, etc.',
      },
      {
        name: 'magical_affinity',
        label: 'Magical Affinity',
        type: 'textarea',
        helpText: 'Types or schools of magic this species has a natural talent for.',
      },
      {
        name: 'magical_limitations',
        label: 'Magical Limitations',
        type: 'textarea',
        helpText: 'Types of magic this species struggles with or cannot perform at all.',
      },
      {
        name: 'magic_organ_biology',
        label: 'Magic Organ Biology',
        type: 'textarea',
        helpText: 'Physical organs, glands, or structures that enable magical ability—mana cores, arcane nodes, etc.',
      },
      {
        name: 'magical_maturation',
        label: 'Magical Maturation',
        type: 'textarea',
        helpText: 'How magical ability develops through the life stages—childhood awakening, adolescent surges, elder mastery.',
      },
      {
        name: 'magical_variation',
        label: 'Magical Variation',
        type: 'textarea',
        helpText: 'How much magical ability varies between individuals—is it uniform, or are prodigies and nulls common?',
      },
      {
        name: 'magical_evolution_history',
        label: 'Magical Evolution History',
        type: 'textarea',
        helpText: 'How this species\' relationship with magic has evolved over generations.',
      },
      {
        name: 'magical_cultural_significance',
        label: 'Magical Cultural Significance',
        type: 'textarea',
        helpText: 'How magical ability shapes social status, professions, and cultural identity.',
      },
      {
        name: 'cross_species_magical_interactions',
        label: 'Cross-Species Magical Interactions',
        type: 'textarea',
        helpText: 'How this species\' magic interacts with or is perceived by other sentient species.',
      },
      {
        name: 'vulnerability_to_magic',
        label: 'Vulnerability to Magic',
        type: 'textarea',
        helpText: 'Specific magical vulnerabilities—iron sensitivity, susceptibility to enchantment, etc.',
      },
      {
        name: 'magic_relevance',
        label: 'Magic Relevance',
        type: 'select',
        options: ['none', 'minor', 'moderate', 'major', 'fundamental'],
        helpText: 'How central magic is to this species\' identity and biology.',
      },
      {
        name: 'custom_magic_notes',
        label: 'Custom Magic Notes',
        type: 'textarea',
        placeholder: 'Any additional notes about magical aspects...',
        helpText: 'Free-form notes on magical properties not covered above.',
      },
    ],
    manaSensitivity: 'active',
    planeAware: true,
    prompts: [
      'Is magical ability innate to all members of this species, or does it manifest only in some? What determines who has the gift?',
      'Do different species have biological organs for channeling magic? How does this affect their magical traditions compared to species that learn magic purely through study?',
      'How does a species\' relationship with magic shape their social hierarchies—are mages an elite class, feared outcasts, or simply tradespeople?',
    ],
  },
  archetypes: [
    {
      id: 'baseline_humanoid',
      name: 'Baseline Humanoid',
      description: 'A versatile, adaptable bipedal species — the generalists of the sentient world.',
      element_type: 'humanoid',
      summary: 'An adaptable humanoid species with short lives but boundless ambition',
      fields: {
        biological_basis: 'Carbon-based mammalian primate',
        avg_height: '1.5-1.9 meters',
        avg_lifespan: '70-90 years',
        diet: 'omnivore',
        communication_method: 'Spoken language with complex grammar, supplemented by writing and gesture',
        physical_description: 'Upright bipedal posture, dexterous hands with opposable thumbs. Varied skin tones, hair colors, and builds across populations.',
        sex_and_gender: 'Sexually dimorphic with binary biological sex. Gender expression varies significantly across cultures.',
        aging_stages: 'Infancy (0-2), childhood (2-12), adolescence (12-18), adulthood (18-60), elderhood (60+).',
      },
    },
    {
      id: 'long_lived_elven',
      name: 'Long-Lived Elven',
      description: 'A graceful, long-lived species attuned to nature and slow to change.',
      element_type: 'elven',
      summary: 'An ancient, graceful people whose long lives grant deep wisdom and deep grief',
      fields: {
        biological_basis: 'Carbon-based humanoid with elongated cellular renewal',
        avg_height: '1.7-2.1 meters',
        avg_lifespan: '600-1000 years',
        diet: 'herbivore',
        communication_method: 'Melodic spoken language with tonal nuances inaudible to shorter-lived species',
        physical_description: 'Tall and slender with angular features and pointed ears. Graceful movement. Hair tends toward silver, gold, or dark hues.',
        sex_and_gender: 'Low sexual dimorphism. Gender is considered fluid across their long lifespans.',
        aging_stages: 'Youth (0-50), maturation (50-120), prime (120-700), twilight (700+). Change is glacially slow.',
      },
    },
    {
      id: 'hardy_mountain_folk',
      name: 'Hardy Mountain Folk',
      description: 'A stocky, resilient species adapted to underground or mountainous environments.',
      element_type: 'dwarven',
      summary: 'A sturdy people who carve civilizations from living stone',
      fields: {
        biological_basis: 'Carbon-based humanoid with dense bone and muscle structure',
        avg_height: '1.2-1.5 meters',
        avg_lifespan: '200-350 years',
        diet: 'omnivore',
        communication_method: 'Deep, resonant spoken language with a rich tradition of chanted history',
        physical_description: 'Broad and stocky with barrel chests and powerful limbs. Thick beards are common across all sexes. Excellent low-light vision.',
        sex_and_gender: 'Sexual dimorphism is subtle — outsiders often cannot distinguish. Gender roles in traditional culture are tied to craft specialty rather than biology.',
        aging_stages: 'Youth (0-30), apprentice (30-60), journeyman (60-100), master (100-250), elder (250+).',
      },
    },
    {
      id: 'aquatic_people',
      name: 'Aquatic People',
      description: 'A sentient species adapted to life in the oceans, with both gills and the ability to survive briefly on land.',
      element_type: 'aquatic',
      summary: 'An amphibious people at home in the ocean depths',
      fields: {
        biological_basis: 'Carbon-based amphibious humanoid',
        avg_height: '1.6-2.0 meters',
        avg_lifespan: '100-150 years',
        diet: 'omnivore',
        communication_method: 'Sonar-like vocalizations underwater; breathy whistled speech on land',
        physical_description: 'Streamlined humanoid form with webbed digits, gill slits along the ribcage, and iridescent scales on extremities. Large, dark eyes for low-light vision.',
        sex_and_gender: 'Sequential hermaphroditism — individuals may change sex once during their lifetime based on social needs.',
        aging_stages: 'Larval (0-5, gills dominant), juvenile (5-20, amphibious transition), adult (20-120), deep elder (120+, returns permanently to the deep).',
      },
    },
    {
      id: 'fungal_collective',
      name: 'Fungal Collective',
      description: 'Not one organism but millions — a networked mycelial intelligence that thinks in parallel across kilometers of underground growth.',
      element_type: 'plant_based',
      summary: 'A distributed fungal network that achieved sentience through sheer interconnection',
      fields: {
        biological_basis: 'Networked mycelial organism — no central brain, intelligence emerges from signal propagation across the network',
        avg_height: 'Surface fruiting bodies: 0.5-2m. Underground network: spans kilometers',
        avg_lifespan: 'The network is effectively immortal. Individual fruiting bodies last weeks to months.',
        diet: 'detritivore',
        communication_method: 'Chemical signaling through the mycelial network (fast, precise) and spore release for long-distance communication (slow, broadcast). Can interface with other species\' nervous systems through parasitic filaments — with consent, this allows direct thought-sharing.',
        physical_description: 'Surface manifestations range from clusters of mushroom-like fruiting bodies to humanoid shapes woven from mycelial threads when the collective needs to interact with bipedal species. The true body is the vast underground network.',
        sex_and_gender: 'The collective has no sex or gender. It reproduces by extending its network or releasing spores that establish new nodes. When two networks merge, they share all memories — a form of reproduction and communion simultaneously.',
        aging_stages: 'Node (new growth, simple reactions), Web (interconnected, basic reasoning), Grove (mature intelligence), Ancient Network (vast, slow, wise — may span an entire forest).',
      },
    },
    {
      id: 'living_statues',
      name: 'Lithic People',
      description: 'Crystalline beings who think on geological timescales — a conversation takes years, but their thoughts are unimaginably deep.',
      element_type: 'custom',
      summary: 'Stone beings whose thoughts span centuries — patient beyond all mortal comprehension',
      fields: {
        biological_basis: 'Silicon-crystalline lattice that processes information through piezoelectric impulses — essentially thinking stone',
        avg_height: '2-4 meters (grow slowly throughout life)',
        avg_lifespan: 'Tens of thousands of years minimum. Oldest known individuals predate recorded history.',
        diet: 'magical',
        communication_method: 'Subsonic vibrations transmitted through the ground (range: several kilometers). A "sentence" takes hours. They also communicate by growing crystalline structures that encode meaning in their lattice pattern — a library readable only by touch.',
        physical_description: 'Vaguely humanoid forms of living crystal and mineral. Each individual\'s composition reflects their personality — some are granite and basalt (practical, grounded), others are quartz and amethyst (contemplative, luminous). They grow slowly, accumulating mass over millennia.',
        sex_and_gender: 'Reproduce by budding — a fragment breaks off and is \'seeded\' with a copy of the parent\'s base knowledge. No sex or gender. Parentage is referred to as \'the source vein.\'',
        aging_stages: 'Shard (newly budded, reactive and fast-thinking by their standards), Pillar (centuries old, settled), Monolith (millennia old, vast and slow), Mountain (so old they become indistinguishable from terrain — some mountains may be sleeping elders).',
      },
    },
  ],
  defaultSortField: 'biological_basis',
};
